### ISSUE TITLE
you can currently enter the same key word more then once in the keyword custom f

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#100]
you can currently enter the same key word more then once in the keyword custom field

date recorded in spreadsheet: 17/04/2015 13:55:36

comments from spreadsheet:
If you manually retype in a keyword then you can still resubmitted it to the same compound

**Comment by aekhendry** [comment]
I enter key word 'key' when drawing compound in chemdoodle. Once registered, I can enter keyword 'key' again when customising custom fields in single molecule view. This leads toa duplication of the same key word

**Comment by aekhendry** [comment]
To be honest it half works, i'm not sure how important this is
