### ISSUE TITLE
Plate Maps - plate details form should be readonly when starting to edit a plate

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#1015]
From #806

"If I define a plate size, and save that plate, then amend the size, it isn't re-rendered"

I really can't see a situation where this would be wanted. If you've clicked the wrong size button - start again. Maybe the first form should be readonly when you click "Save plate" and that only clicking "Cancel" can get back to the first form?

**Comment by PaulBarrett79** [comment]
Managed to disable the form using the same condition as Show Plate. May be able to add this restriction just to the plate size, as users may want to amend fields that do not restrict how the plate is constructed.

**Comment by PaulBarrett79** [comment]
Whole-form disabled is now pushed to github.

**Comment by KarenPorter** [comment]
Adding #975 requirement here to consolidate some platemap issues:

Plate Map project type needs the default fields to be read only i.e. not removable as the functionality of adding and editing depends on these 4 fields.

**Comment by PaulBarrett79** [comment]
This is now implemented and ready to test on staging/demo

**Comment by aekhendry** [comment]
Fixed staging testing chrome
