### ISSUE TITLE
Small structures only have a maximum of 1000 results and possible for search for benzene to break elasticsearch

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#1018]
Currently the number of results for a non complex chemical query is limited.

Secondly, searching for a simple benzene ring brings back too many results.

This issue can be addressed by splitting up the results by project when pulling back the structure search so there is less information for elasticsearch to process.

Also reducing the number of shards per index.

**Comment by KarenPorter** [comment]
@strets123 can't remember - did you address this before go live?
