### ISSUE TITLE
Issue when rerunning a saved search the project id can be removed if it is a textsearch

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#1019]
this causes inconsistent results depending on whether that search is already loaded in the page or not

**Comment by KarenPorter** [comment]
to test:

from within a project
run text search
save text search
re-run saved search
(previously - project id was being removed so results were from all projects)
now - only results from relevant project id are returned

**Comment by aekhendry** [comment]
fixed staging/staging chrome
