### ISSUE TITLE
Admin-controllable "down for maintenance" warning banner

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#1022]
We have a placeholder in the header template containing commented code from a recent "system will be down for maintenance". It was activated by "monkey patching" a minified file and adding the extra content.

It should be possible for an admin/superuser to go into the system and switch on this warning, ideally adding a message to be displayed, and specifying a time window during which the message should be displayed.

**Comment by KarenPorter** [comment]
replace admin-controllable approach with documenting existing approach, for pragmatic reasons

**Comment by PaulBarrett79** [comment]
Added a switch via the admin interface to toggle display of an upcoming maintenance warning. The message shown and the start/end times are configurable.

To test:
Log in as an admin user
Go to admin panel
In the list of fields, set Maintenance Warning to "Yes".
Add the message to Maintenance Warning Message
Add the start and end times to their fields Maintenance Warning Start / End

Save this configuration

Leave the admin interface and go back to the main system
The warning message will be displayed at the top of the page.

The warning message will be triggered on page LOCATION CHANGE, so if you perform an action such as switching between projects and search, or trigger a single record modal which changes the URL, the banner will be updated if the Maintenance Warning has been set to yes.

To remove the banner, repeat the admin steps and set the Maintenance Warning to No.

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/staging

**Comment by KarenPorter** [comment]
@PaulBarrett79 
"In the list of fields, set Maintenance Warning to "Yes".

Can't see list of fields
is this in documentation too?

**Comment by KarenPorter** [comment]
*Found in skinning configuration section

**Comment by KarenPorter** [comment]
passed testing
