### ISSUE TITLE
CJS project page view broken when using safari on mac OS

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#1035]
They are reporting that since the update the project page view is displayed oddly (see attached image). They are running this on Safari, OS X Yosemite version 10.10.5. See email from AH for image

**Comment by PaulBarrett79** [comment]
This is very likely due to Safari's (fussy) requirement of the proper webkit prefix for display:flex. I have added all the prefixes to places where this is used. Pushed to Github.

**Comment by PaulBarrett79** [comment]
As far as I am aware this is now fixed - and should be available for testing on staging/demo

**Comment by KarenPorter** [comment]
@aekhendry please test.

**Comment by aekhendry** [comment]
Fixed, hub test safari
