### ISSUE TITLE
Create mass spec service instance according to their specifications

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#1049]
https://docs.google.com/document/d/1xM5Tdl6jeEtjiG-r0L1EzYmmE8lhDL8_yyU6-tJVb_4/edit?usp=sharing

**Comment by strets123** [comment]
Disable add multiple
Remove button on project page - done
Remove button on search page table - done
Remove ‘add supplementary data’ option in add single - Now this add single page no longer exists
Change ‘validate compound’ text on add single page to ‘Submit’ -now done through search page anyway
Make it so the login page looks different to the Hub instance page (I don’t mind how it just needs they just need to be clearly distinct) - You can edit the title and subtitle of the instance so they show on the home page

**Comment by aekhendry** [comment]
Attempting to test but when I give myself the add project permission and click save i get a 403 https://chembiohub.ox.ac.uk/msservice/api/admin/auth/user/8/change/

**Comment by aekhendry** [comment]
Created project through old school admin interface. 

In single molecule view. I click edit. Interger field automatically blanks itself. If i click save it saves this field as blank. Needs to be changed to keep the value.

**Comment by aekhendry** [comment]
I cannot see any of the changes you have described in the MS instance Andy, they mist not have been deployed.

**Comment by aekhendry** [comment]
I can't see any of the points Andy has made above, i don't think they've been deployed

**Comment by aekhendry** [comment]
Done. msservices, chrome
