### ISSUE TITLE
Is it possible to standardise the "amount" custom field i.e. float + unit (10.09

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#105]
Is it possible to standardise the "amount" custom field i.e. float + unit (10.09 mg)

date recorded in spreadsheet: 17/04/2015 14:04:44

**Comment by strets123** [comment]
Can be done as a plugin field

**Comment by PaulBarrett79** [comment]
Part of #585

**Comment by aekhendry** [comment]
Closing as I'm not sure this is relevant anymore
