### ISSUE TITLE
Batch ID's are not working. The batch ID simply increase by one regardless of wh

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#109]
Batch ID's are not working. The batch ID simply increase by one regardless of what compound is drawn in chemdraw

date recorded in spreadsheet: 17/04/2015 14:38:32

**Comment by strets123** [comment]
Part of doing the chemreg assayreg integration

**Comment by aekhendry** [comment]
I need to test this

**Comment by aekhendry** [comment]
I need to discuss this with Andy to confirm what the behaviour should be

**Comment by aekhendry** [comment]
Closing

**Comment by strets123** [comment]
Using a bulk SQL statement will really help with the speed of uploading data and it makes some sense to do this as part of the multiple batch changes.

**Comment by strets123** [comment]
The bulk SQL required is listed in the cbh_chembl_id_generator module (currently unused)

**Comment by strets123** [comment]
This issue has been supplanted by the need for a project-specific batch identifier, incrementing by one for the project, not the batch.
