### ISSUE TITLE
more batch ID problems -

As noted, when drawn in chemdoodle, batch ID's increas

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#110]
more batch ID problems -

As noted, when drawn in chemdoodle, batch ID's increase by one regardless of compound drawn. Further to this:

I draw a new compound in proj A and the compound is given batch ID 20.
I draw a new compound in proj A and the compound is given batch ID 21 
I draw a new compound in proj B and the compound is given batch ID 22

Also:

I have created a user that can can only see one project and when he creates batch id 20, a user in another project he cannot view makes batch 21 with a different compound.

date recorded in spreadsheet: 17/04/2015 14:48:16

comments from spreadsheet:
Increamental batch ids are not yet done

**Comment by PaulBarrett79** [comment]
Is this part of the separate ID service / refactoring?

**Comment by strets123** [comment]
There are 2 sets of refactoring - batch id creation is one and the flow for the validation of data that is added is the other. I am planning on  working on batch ids tomorrow as part of this sprint

**Comment by strets123** [comment]
Duplicate

**Comment by strets123** [comment]
dupe of 109
