### ISSUE TITLE
Sort asc/desc in compound list only sorts that page. This may be addressed by th

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#122]
Sort asc/desc in compound list only sorts that page. This may be addressed by the search functionality,but I can envisage a need for a user to want to look at, say, compounds recently added and they might do that by selecting 'Added on' - desc

date recorded in spreadsheet: 20/04/2015

**Comment by aekhendry** [comment]
To update this, an ability to sort isotab columns is necessary, and it should apply to the whole project not just what is on that page

**Comment by strets123** [comment]
This is an example of something that should have been hidden in the first place

**Comment by strets123** [comment]
Sorting needs to work on ALL pages with compounds on.

Will require elasticsearch integration of the search.

The steps to do this are:

<ol>
<li>Alias the searched for molecule and write that alias to elasticsearch</li>
</ol>

**Comment by strets123** [comment]
Park the decision

**Comment by strets123** [comment]
In the end I have found a way to run this by using the ids query - we now need to work through the frontend for this and refactor

**Comment by strets123** [comment]
We now have sorts on all of the pages, cancelling sorts also work.
