### ISSUE TITLE
Values for keywords, Mol formula, physical form, etc (all the values shown in th

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#123]
Values for keywords, Mol formula, physical form, etc (all the values shown in the Excel download) are not populated. Also some fields have square brackets, the majority don't - so there is probably a difference in how they are processed depending on how the compounds are added.

I assume these values are 'coming soon'.

date recorded in spreadsheet: 20/04/2015 14:55:33

**Comment by strets123** [comment]
need to delete data for consistency

**Comment by strets123** [comment]
comma separated

**Comment by strets123** [comment]
square brackets should now not be there

**Comment by aekhendry** [comment]
Failed testing, brackets still in excel export

**Comment by KarenPorter** [comment]
There are 'red' tasks around this area within the sprint, so I don't think it makes sense not to include this 2 hour effort at the same time .  So a high yellow (orange?).

**Comment by PaulBarrett79** [comment]
Has this been fixed? Needs verification.

Test on staging/sandbox

**Comment by aekhendry** [comment]
Brackets still in export for tags in fields on Sandbox

**Comment by aekhendry** [comment]
i can't replicate this on Hub now, i think it is fixed.
