### ISSUE TITLE
Sdf export of chiral compounds is not drawing the chiral bonds the same way when

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#124]
Sdf export of chiral compounds is not drawing the chiral bonds the same way when reuploaded into the system. In the test project on staging please compare the drawn compound (UOXZH24LXU - batch 10875) which was eported as an SDF and reuploaded as (UOXZH24LXU - batch 10876)

date recorded in spreadsheet: 20/04/2015 14:58:10

**Comment by strets123** [comment]
Please re-test this I think it should be fixed now

**Comment by aekhendry** [comment]
Tested with both real and wrongly drawn chiral compounds both worked.
