### ISSUE TITLE
Added a compound via SMILEs definition (checking for how it handled duplicates) 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#130]
Added a compound via SMILEs definition (checking for how it handled duplicates) and clicked 'Process Ids' to be taken to Validate. Now have only an option to add custom fields - which I may not want to do. I can progress to add custom fields screen then not actually add any.

For discussion - but could be 'add custom fields or complete'?

date recorded in spreadsheet: 20/04/2015 15:39:08

**Comment by aekhendry** [comment]
Negated by refactoring in Sprint 17a
