### ISSUE TITLE
Name and synonyms custom field - I want to add multiple entries so I separated w

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#132]
Name and synonyms custom field - I want to add multiple entries so I separated with commas - but it has been saved as a single value (with commas). I assume there is a character I can add to separate multiple entries - what is it? Some help text would be useful.

date recorded in spreadsheet: 20/04/2015 16:01:05

**Comment by strets123** [comment]
Please change the field type for this to work

**Comment by aekhendry** [comment]
I need to talk to andy to make sure this wont break anything when I do it

**Comment by aekhendry** [comment]
Field type has been changed
