### ISSUE TITLE
I drew this in doodle - C1CC2C3(C1)CCCC3C13C42C2CCCC52C(C24C4CCCC64C(C42C2(C3(C3

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#133]
I drew this in doodle - C1CC2C3(C1)CCCC3C13C42C2CCCC52C(C24C4CCCC64C(C42C2(C3(C3C7(C1CCC7)CCC3)C1CCCC31C2CCC3)C1C2(C4CCC2)CCC1)CCC6)CCC5
and when i went through the rest of the registration, it didn't render the image (left it blank). I then added it via SMILE and when I went through the registration it rendered as I had drawn it.

date recorded in spreadsheet: 20/04/2015 16:08:51

**Comment by aekhendry** [comment]
wont fix
