### ISSUE TITLE
http://stackoverflow.com/questions/23244389/angularjs-abort-all-pending-http-req

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#135]
http://stackoverflow.com/questions/23244389/angularjs-abort-all-pending-http-requests-on-route-change

We currently do not stop the HTTP requests when the URL is changed this can lead to unexpected behaviour

date recorded in spreadsheet: 21/04/2015 01:30:13

**Comment by strets123** [comment]
best way to fix is by doing performance improvements which aren't 1.0

**Comment by aekhendry** [comment]
closing
