### ISSUE TITLE
From Add single compound - click "Save molecule to ChemReg" (without drawing any

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#137]
From Add single compound - click "Save molecule to ChemReg" (without drawing anything at all) - you get in progress bubbles and (eventually) an error count. No warning message, no timeout on save (that I have patience to wait for at any rate).

I think there's quite a delay in general on the error count display. If there is an error does that mean the compound isn't going to be registered? in which case ould be good to message to that effect.

date recorded in spreadsheet: 21/04/2015 11:04:21

**Comment by KarenPorter** [comment]
Clicked 'save molecule to ChemReg' and  - nothing happens visibly to the user.  Should have either an error message or the button disabled until there's 'something' in the doodle box
