### ISSUE TITLE
Should have a concurrent workflow for large files - split file into groups of 10

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#139]
Should have a concurrent workflow for large files - split file into groups of 100 structures and report progress on each.e

date recorded in spreadsheet: 21/04/2015 13:59:53

**Comment by strets123** [comment]
refactoring - other performance improvements

**Comment by KarenPorter** [comment]
@strets123 still outstanding?

**Comment by KarenPorter** [comment]
@strets123  still outstanding? 

There's likely to be another issue covering this.
