### ISSUE TITLE
Concerning uploading multiple compounds by ChemDraw:

It would be better (I beli

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#141]
Concerning uploading multiple compounds by ChemDraw:

It would be better (I believe) to see a list of the compounds found in the file, and to have the ability to edit the information for each compound individually as part of the processing stage.

Currently it is only possible to add information to all or none of the molecules. The fields correspond to properties that are likely to be unique to each different compound uploaded (e.g. chemical name).

Additionally it isn't possible to see which compounds have been detected (to check they are correct) until they have been permanently added to the database, which is quite important.

date recorded in spreadsheet: 23/04/2015 23:30:54

**Comment by strets123** [comment]
refactoring

**Comment by PaulBarrett79** [comment]
Refactoring work for this issue has been completed and deployed to staging/sandbox

**Comment by strets123** [comment]
Can now edit at step 2

**Comment by aekhendry** [comment]
fixed, chrome hub
