### ISSUE TITLE
1. Feature suggestion : would it be possible to have multiple meta data columns

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#142]
1. Feature suggestion : would it be possible to have multiple meta data columns to allow for running a set of compounds against multiple targets and then enter which plates relate to which targets?
2. Fix : when points are removed from the data, if both points are removed and they are at the end of the set the points disappear rather than being greyed out.
3. Feature ; can the graphs auto scale at the bottom as on some occasions compounds increase signal in a dose dependent way and this visual info is lost
4. Fix : Can the update button be placed at the top of graphs?
5. Fix : I like the graphs in the data summary but these have been changes and are harder to interpret than they used to be.
6.Fix: The compound concentrations are in reverse order to our existing template, this will cause confusion and is nice to see the top concentration first as this is the most useful single point to check.
7. Feature: PDF/Image download of heatmap and graphs for ELN

date recorded in spreadsheet: 24/04/2015 12:23:49

**Comment by strets123** [comment]
@KarenPorter  We need to determine if there is any future in crunch by talking to Oleg's team

**Comment by KarenPorter** [comment]
incorporated into #794
