### ISSUE TITLE
When structures drawn have overlaps (eg compounds 140-150 that I added on 24th A

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#143]
When structures drawn have overlaps (eg compounds 140-150 that I added on 24th April) ChemReg does not give you an overlap warning. Also, if you screw up by forgetting to group salts in chemdraw, I couldn't see a way of deleting the entry in order to correct your mistake.

date recorded in spreadsheet: 24/04/2015 15:39:25

**Comment by strets123** [comment]
~Should now be fixed

**Comment by aekhendry** [comment]
Fixed hub chrome
