### ISSUE TITLE
Chemreg understands "-CO2H" in .sdf files to be a formate ester, not a carboxyli

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#144]
Chemreg understands "-CO2H" in .sdf files to be a formate ester, not a carboxylic acid. Reopening sdf file in chemdraw shows CO2H the wrong way round, which may explain why this happens - presumably the software assumes rest of molecule is connected to an O, not C.

date recorded in spreadsheet: 28/04/2015 15:39:37

**Comment by strets123** [comment]
re test

**Comment by aekhendry** [comment]
I think this I fixed but I also tried to replicate this behavior in the CDT instance (which should generate the described issue)  without success without success.  I submitted an SDF as described above and the intended carboxylic acid was generated in both sand box and the CDT instance. Could you double check this for me Andy?

**Comment by KarenPorter** [comment]
@strets123

**Comment by strets123** [comment]
Please test again now

**Comment by aekhendry** [comment]
Fixed marking as done. hub chrome
