### ISSUE TITLE
The capabilities part of the website is a bit useless unfortunately. This isnt o

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#145]
The capabilities part of the website is a bit useless unfortunately. This isnt our fault, its because the site it links to actually contains very little information under each header (I checked a bunch of them). I'm not sure as a resource if it paints the CBH in a good light. You would more then likely be disappointed when using it.

date recorded in spreadsheet: 30/04/2015 09:31:31

**Comment by KarenPorter** [comment]
Moving to Sprint 19A

**Comment by strets123** [comment]
Fixed
