### ISSUE TITLE
Need to be able to export as Chemdraw file. Brian request.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#147]
Need to be able to export as Chemdraw file. Brian request.

date recorded in spreadsheet: 30/04/2015 10:02:33

**Comment by PaulBarrett79** [comment]
ChemDraw XML for each molecule is now generated at validation time. A "Copy CDXML" button has been added as part of the chemsvg directive. This copies CDXML to the clipboard.

**Comment by strets123** [comment]
To be continued when refactoring the list view - currently button loads the molecule too

**Comment by PaulBarrett79** [comment]
It only makes sense to be able to download individual molecules in this format, which you can now do via the copy cdxml button, which has been verified as done. Marking as done.
