### ISSUE TITLE
Custom fields. When submitting a group of compounds the list of possible custom 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#148]
Custom fields. When submitting a group of compounds the list of possible custom fields is the same as when in single compound view. I think there needs to be a distinction between adding custom fields to a group of compounds and adding them to a single compound, as many are not appropriate. This is reflected in the help text for each custom field which refers to compounds as singular. This is confusing when read in the context of adding custom fields to multiple compounds. 

I think this problem ties into feedback in the spreadsheet registered by a CDT student. He wants to be able to see the compounds in a table view before they are registered. If we link this together, we could have a system whereby:

1 submit compound
2 add group custom fields
3 add individual custom fields
4 register compounds

date recorded in spreadsheet: 30/04/2015 10:15:11

**Comment by strets123** [comment]
duplicate

refactoring

**Comment by PaulBarrett79** [comment]
Refactoring work has been applied to this issue

staging/sandbox

**Comment by aekhendry** [comment]
Marking as awaiting deployment, with the new refactoring changes this no longer applies once deployed
