### ISSUE TITLE
The structure images should always take up the maximum amount of available space whenever present. I am having trouble looking at some of these in detail and it will be a common complaint.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#149]
The structure images should always take up the maximum amount of available space whenever present. I am having trouble looking at some of these in detail and it will be a common complaint.

date recorded in spreadsheet: 30/04/2015 10:16:26

**Comment by KarenPorter** [comment]
The image isn't showing up in teh initial list view.  It appears when I 'do something'  - such as scroll or click on the image space.

**Comment by PaulBarrett79** [comment]
This is most important for the single structure summary. At the moment the structure is stretched to fit, making it look slightly janky. If we can use this as a svg and then scale correctly it will be more useful.

**Comment by strets123** [comment]
Now fixed - we set the image to low res and then fetch the high res to replace it

**Comment by KarenPorter** [comment]
I'm not convinced about the user experience this provides. It isn't intuitive that by clicking on the fuzzy image you'll get something better so some users might just close the window down straight away and leave with a negative impression.  Is it possible to auto-load the high res as soon as it is available?

**Comment by PaulBarrett79** [comment]
We could set a loading/spinner to overlay the low res while waiting for the high res version. I should say, though, that having a low res image at first is a common approach to this kind of problem.

**Comment by PaulBarrett79** [comment]
So the issue here is not low vs high res, it is the fact that some level of user interaction is required for the high res to display after load i.e. clicking or scrolling, otherwise the high res is not displayed.. Issue is reported using Firefox on Windows. Could be to do with binary image data on that browser / OS combination?

**Comment by strets123** [comment]
i have re-fixed this again. We now pre-generate all of the images and the sizing looks better now I think

**Comment by PaulBarrett79** [comment]
There is an intermittent issue in Firefox where the modal is attempted to be loaded multiple times, so the reloading of the high res image is out of sync and is not loaded. Can't reliably reproduce but it only happens in firefox.

**Comment by KarenPorter** [comment]
I'm a tad confused.  Andy's comment looks like a fix that would resolve the Firefox issue in any case - as in he is proposing not to use low-res images, but my current test in Firefox still demonstrates that low-res is being returned.  Have I missed a step?

**Comment by PaulBarrett79** [comment]
This has been deployed and needs retesting on Firefox/Windows. I can't now reproduce with Firefox on Linux.

**Comment by KarenPorter** [comment]
Tested - passed on Firefox / Windows
