### ISSUE TITLE
Take an example URL like this

http://staging.chembiohub.ox.ac.uk/sandbox/r/#/pr

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#15]
Take an example URL like this

http://staging.chembiohub.ox.ac.uk/sandbox/r/#/projects/list/damerell-test-project

And change the project name to anything you like

Note how it doesn't complain

date recorded in spreadsheet: 19/03/2015 09:00:09

comments from spreadsheet:
16

**Comment by aekhendry** [comment]
Fix works in principle but redirects back to the project page view. It should really redirect you towards a 404
