### ISSUE TITLE
The mapping phase when submitting excel files is now confusing, It will not auto map stored headers / how is it telling which columns contain the structural information now?

1 Submit

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#150]
Auto mapping for SMILES in excel files no longer works as intended. 

1 Submit excel file and select structure column (SMILES).
2 Can no longer auto map SMILES in custom fields section.
3 In single compound view, SMILES and MOL_WEIGHT from the file is added to the uncurated fields. But it is also present in at the top of the page as (for example MW0 is calcualted by the system. 

In one example, UOXAQ35CHU in SBMCDT / Admin project the calucated MW differs to the uncurated MW

date recorded in spreadsheet: 30/04/2015 10:32:53

**Comment by aekhendry** [comment]
Tested and failed. Nothing seems to have changed?

**Comment by strets123** [comment]
I have now deployed this change fully. Should now push smiles column to ignored
