### ISSUE TITLE
Implement group/ungroup buttons on chemdoodle. See line 850 on https://github.co

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#159]
Implement group/ungroup buttons on chemdoodle. See line 850 on https://github.com/martinp23/elabchem/blob/master/js/chemdoodleweb/src/ChemDoodleWeb-sketcher-unpacked.js

date recorded in spreadsheet: 21/04/2015

**Comment by strets123** [comment]
I have looked into this and decided not to proceed for now as the code works with an old version of chemdoodle

**Comment by KarenPorter** [comment]
If not proceeding it should be in Backlog or closed @strets123

**Comment by strets123** [comment]
Closed as irrelevant, grouping will be done by another method e.g. saved searches or list fields for compound mixtures
