### ISSUE TITLE
There should be an option in single molecule view where you can click on the str

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#165]
There should be an option in single molecule view where you can click on the structure image, and it expands to fill a greater portion of the screen. Currently hard to make out the fine details on large molecules in current viewing window

date recorded in spreadsheet: 01/05/2015 10:49:13

**Comment by strets123** [comment]
Now much wider, not sure we need this

**Comment by KarenPorter** [comment]
1.  Not intuitive how I now launch the compound detail view.
2. It launches without the image visible
3, When I click on the image and it becomes visible - it's still little and stuck in the corner.

**Comment by strets123** [comment]
I can't make it load any quicker, I have changed the layout a bit

**Comment by KarenPorter** [comment]
The larger image looks much nicer.

Not sure about loading the low res though.  Does this save noticeable time?  If no, I'd be inclined to skip it and just load the high res.  It isn't possible to see enough detail in a complex molecule for it to be of any use at all - and then if the user doesn't click on the single page, they might just close down without knowing that they can see more structural detail.

Also - is it possible to load the compound detail page from single click and also from double click events?  I've tried both (think both might be instinctive to users), and the double click seems to sometimes launch 2 windows and sometimes do nothing.  On one occasion it coincided with a browser crash.

**Comment by strets123** [comment]
Now fixed - see other issue

**Comment by strets123** [comment]
There are now 2 bond scales for larger and smaller molecules without compromising on image quality

**Comment by KarenPorter** [comment]
Tested in Chrome and looks good.  Doesn't work for Firefox (and IE10 has more fundamental issues) - which I've raised as a separate new defect.  I'll send this around again for comment but it may have to be an accepted limitation for the moment in this release.  basic issue in Firefox is that the low-res image remains until I click on it, at which point it updates to hi-res.

**Comment by strets123** [comment]
Can't reproduce in FF windows. There is no low res image anymore. Must be caching on your machine

**Comment by KarenPorter** [comment]
I've managed to clear the cache and tested successfully.  Thanks for your patience guys!
