### ISSUE TITLE
Some structures registered in the CDT project are not displaying at all. e.g. UO

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#169]
Some structures registered in the CDT project are not displaying at all. e.g. UOXQK78KMM 

Andy is aware, his comment is below:

There is a different problem for the molecules that wont draw
this is due to structure cleanups the valency appears wrong for that molecule but the inchi software correctly interpretted we will need another cleanup method for this scenario log it as a bug with this url:

CgoKIDI1IDI2ICAwICAwICAwICAwICAwICAwICAwICAwOTk5IFYyMDAwCiAgICAyLjA4NDAgICAtOS4wMDQ2ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgMi4wODQwICAtMTAuODg1NSAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDMuNzEzMyAgLTExLjgyNjYgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICA1LjM0MTIgIC0xMC44ODU1ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgNS4zNDEyICAgLTkuMDA0NiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDMuNzEzMyAgIC04LjA2NDkgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICA3LjEzMDMgIC0xMS40Njc1ICAgIDAuMDAwMCBOICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgNi4xMjM3ICAtMTQuNTY2MCAgICAwLjAwMDAgTyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDYuNTE0MyAgLTE2LjQwNTAgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICA4LjMwMzQgIC0xNi45ODY5ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgNi45MDYyICAtMTguMjQ1MiAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDUuMTE3MCAgLTE3LjY2MzMgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICA3LjUyMDkgIC0xMy4zMDY0ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgOS4zMTAwICAtMTMuODg4NCAgICAwLjAwMDAgTyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDguMjM2NiAgIC05Ljk0NTcgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgICA3LjEzMDMgICAtOC40MjQwICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAgNy43MTIzICAgLTYuNjM0OSAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgIDkuNTUxMiAgIC02LjI0NDMgICAgMC4wMDAwIEMgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIDEwLjEzMzIgICAtNC40NTUxICAgIDAuMDAwMCBOICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAxMS45NzIxICAgLTQuMDY0NSAgICAwLjAwMDAgQyAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgMTIuNDU5NyAgIC0yLjI0NjYgICAgMC4wMDAwIE8gICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIDEzLjMwMjUgICAtNS4zOTM2ICAgIDAuMDAwMCBDICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogICAxMS45MDQwICAgLTYuNjUxOSAgICAwLjAwMDAgRiAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAgIDAKICAgMTQuNTYwOCAgIC02Ljc5MDggICAgMC4wMDAwIEYgICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwICAwCiAgIDE0LjY5OTcgICAtNC4xMzQwICAgIDAuMDAwMCBGICAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMCAgMAogIDEgIDIgIDIgIDAgIDAgIDAgIDAKICAyICAzICAxICAwICAwICAwICAwCiAgMyAgNCAgMiAgMCAgMCAgMCAgMAogIDQgIDUgIDEgIDAgIDAgIDAgIDAKICA0IDE1ICAxICAwICAwICAwICAwCiAgNCAgNyAgMSAgMCAgMCAgMCAgMAogIDUgIDYgIDIgIDAgIDAgIDAgIDAKICA2ICAxICAxICAwICAwICAwICAwCiAgNyAxMyAgMSAgMCAgMCAgMCAgMAogIDggIDkgIDEgIDAgIDAgIDAgIDAKICA4IDEzICAxICAwICAwICAwICAwCiAgOSAxMCAgMSAgMCAgMCAgMCAgMAogIDkgMTEgIDEgIDAgIDAgIDAgIDAKICA5IDEyICAxICAwICAwICAwICAwCiAxMyAxNCAgMiAgMCAgMCAgMCAgMAogMTUgMTYgIDIgIDAgIDAgIDAgIDAKIDE2ICA1ICAxICAwICAwICAwICAwCiAxNiAxNyAgMSAgMCAgMCAgMCAgMAogMTcgMTggIDEgIDAgIDAgIDAgIDAKIDE4IDE5ICAxICAwICAwICAwICAwCiAxOSAyMCAgMSAgMCAgMCAgMCAgMAogMjAgMjEgIDIgIDAgIDAgIDAgIDAKIDIwIDIyICAxICAwICAwICAwICAwCiAyMiAyMyAgMSAgMCAgMCAgMCAgMAogMjIgMjQgIDEgIDAgIDAgIDAgIDAKIDIyIDI1ICAxICAwICAwICAwICAwCk0gIEVORAo

date recorded in spreadsheet: 01/05/2015 11:21:43

**Comment by strets123** [comment]
To be tested with large molecules on the hub server (there will still be errors probably)

**Comment by strets123** [comment]
Tell us how to deploy for these guys - doe we want SSO usernames migrated

**Comment by aekhendry** [comment]
Plan to discuss this in SPRINT

**Comment by strets123** [comment]
Should now be fixed for large molecules also not possible to register invalid valencies

**Comment by aekhendry** [comment]
I can't really remember what this was about and i'm not sure how to test. Will speak to Andy when he is back.

**Comment by aekhendry** [comment]
Closing as no longer relevant since refactoring
