### ISSUE TITLE
HTTP requests are not cancelled when the user presses cancel

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#170]
HTTP requests are not cancelled when the user presses cancel

date recorded in spreadsheet: 06/05/2015 11:04:50

**Comment by strets123** [comment]
http://stackoverflow.com/questions/23244389/angularjs-abort-all-pending-http-requests-on-route-change/29811542#29811542

**Comment by aekhendry** [comment]
No longer relevant
