### ISSUE TITLE
This was a comment from the survey sent out (8/5/15):
"I cannot login on my Mac,

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#174]
This was a comment from the survey sent out (8/5/15):
"I cannot login on my Mac, a forbidden message comes up and suggests that I turn my settings to accepting cookies. My settings are already set to accept cookies though. confused."

date recorded in spreadsheet: 11/05/2015 13:26:10

**Comment by strets123** [comment]
Testing needed on hub instance

**Comment by nroam** [comment]
Tested with Chrome, Firefox and Safari under OS/X 10.10 - no problems logging into chembiohub/hub/login
