### ISSUE TITLE
Export of custom fields in .xml is printing a weird string of information where

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#179]
Export of custom fields in .xml is printing a weird string of information where it should show the symbol for degrees C. e.g. "-80°C Freezer, Room Temp." was entered in custom field. exported as "["-80\u00b0C Freezer"]"

date recorded in spreadsheet: 13/05/2015 13:29:38

**Comment by KarenPorter** [comment]
@strets123 still outstanding?

**Comment by strets123** [comment]
To be deprioritised as special characters will not be allowed in field names
