### ISSUE TITLE
Blinded Excel files no longer able to be uploaded  part 1

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#180]
Blinded Excel files no longer able to be uploaded - part 1 - ensure an excel dataset can be uploaded without structures and a UOX id generated for each item in the dataset.

date recorded in spreadsheet: 13/05/2015 13:30:21

**Comment by KarenPorter** [comment]
I have an exported file of ChemReg compounds, from which I've removed the SMILES values.  I import that file and select 'no structure' - the 'process file' button remains disabled.  Remains disabled if i select a nominated column and then re-select 'no structure', so I can't progress the upload.

**Comment by strets123** [comment]
cant reproduce

**Comment by strets123** [comment]
fixed the issue, see duplicate

**Comment by KarenPorter** [comment]
Tested and passed
