### ISSUE TITLE
Compound representation in system. No longer shows the mol weight in the list of

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#181]
Compound representation in system. No longer shows the mol weight in the list of registered cpds - though there when I exported (single drawn structure)

date recorded in spreadsheet: 13/05/2015 15:35:32

**Comment by strets123** [comment]
Will be fixed for new data - we may need to clean hub instance out...

**Comment by KarenPorter** [comment]
shows molecular weight in all instances i have tested of adding new compounds - single mol, SMILES and file upload
