### ISSUE TITLE
Need:
Ability to manage more than one instance
List of ChemReg instances and the

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#183]
Need:
Ability to manage more than one instance
List of ChemReg instances and their admins (low priority)
Document of workflow access management to all ChemBio nodes - Biog / Crunch/ Reg instances / Assay instances

date recorded in spreadsheet: 14/05/2015 09:07:54

**Comment by aekhendry** [comment]
this may be solved based on discussion regarding CDT migration

**Comment by KarenPorter** [comment]
@aekhendry needs updating

**Comment by aekhendry** [comment]
closing
