### ISSUE TITLE
When you register a group of compounds, the number indicators display the number

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#186]
When you register a group of compounds, the number indicators display the number of compounds that are new, overlap or are duplictaes. It would be nice at this stage to be able to identify what these compound are, as currently there is no way to do this.

date recorded in spreadsheet: 14/05/2015 12:03:53

**Comment by aekhendry** [comment]
Ties into issue 208

**Comment by PaulBarrett79** [comment]
Filtering in the refactoring work for this sprint - users can filter the display table of uploaded compounds by overlaps or duplicates.

Deployed to staging/sandbox

**Comment by KarenPorter** [comment]
tested - passed
