### ISSUE TITLE
Hub instance - May be a repeat of an existing issue (or could be up to 2 new iss

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#187]
Hub instance - May be a repeat of an existing issue (or could be up to 2 new issues I suppose). I dragged a chemdraw file in and clicked process file - it showed the progress bubbles for a long time, and continued to show them after I'd cancelled, when I navigated away and came back, even after I'd uploaded a single compound. Finally went after I'd successfully uploaded another small file (Excel in this instance).

date recorded in spreadsheet: 14/05/2015 12:04:58

**Comment by KarenPorter** [comment]
Left processing bubbles, navigated back a page, when i returned the processing bubbles were no longer there - passed

**Comment by KarenPorter** [comment]
Another test - tried to upload a file with no valid structure (failed- nicely), then uploaded a valid file and I get the processing bubbles - I cancelled, then came back in - bubbles still bubbling (though I can now upload another valid file and have it processed).

**Comment by strets123** [comment]
I have added this to sprint 17 as it is really hard to fix the after cancel issue and is part of the adding data user experience

**Comment by aekhendry** [comment]
I cant seem to replicate this so I think its fixed. Tested on Hub admin project.

**Comment by KarenPorter** [comment]
I can't replicate.
