### ISSUE TITLE
On Hub instance.

the top half of the search results page looks scrappy at certa

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#188]
On Hub instance.

the top half of the search results page looks scrappy at certain sizes. I'm on Firefox. No components change size so they just overlay each other - should be easy to reproduce - just resize the window.

date recorded in spreadsheet: 14/05/2015 12:09:19

**Comment by aekhendry** [comment]
I know this can be fixed by F5 but many wont think to do this when unsupervised. Is there definitely no quick fix for this?

**Comment by strets123** [comment]
I have now made the chemdoodle window responsive and fixed the worst of the layout issues for the fields in the search form. The search form can still be made smaller and the fields lined up better but this would be an enhancement in my world.

**Comment by KarenPorter** [comment]
Much improved - many thanks.
