### ISSUE TITLE
Hub instance.

Logout button takes you to a 404 - page not found

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#189]
Hub instance.

Logout button takes you to a 404 - page not found

date recorded in spreadsheet: 14/05/2015 12:11:11

**Comment by aekhendry** [comment]
Failed Testing - No longer takes you to a 404 page, but does take you here:
https://chembiohub.ox.ac.uk/hub/login
You cannot log back in via this page it, it needs to take you here:
https://chembiohub.ox.ac.uk/hub/webauth

**Comment by strets123** [comment]
Now fixed for webauth instance (deployed only to hub currently)
