### ISSUE TITLE
Hub instance

Got to 'oops, should not have got here...' page by attempting to u

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#192]
Hub instance

Got to 'oops, should not have got here...' page by attempting to upload a file. It was an Excel file of previously exported compounds, with these compounds in:

c1ccccc1
C1Cc2c(C1)cc1c(c2)cccc1
C1CC2CC3CC4CCCC5C4C4C3C3C2C(C1)CC1C3C2C4C(C5)CC3C2C(C1)CCC3
CCCCCCCC
NCOC1CC(N)C([C@H](C1=O)C)C
O[C@@H]1CCC2C([C@H]1C)CC1(CC2)CCCCC1
C[C@@H]1CCC2C([C@H]1C)CCCC2
C[C@@H]1CC[C@@H]([C@@H](C1)C)C
CC1CCC2(CC1)C[C@H](C)C[C@@H](C2)C

Then loaded these SMILES in and demonstrated again (per earlier defect) that they are recorded as new when in fact they are duplicates.

date recorded in spreadsheet: 14/05/2015 12:33:16

**Comment by aekhendry** [comment]
Refactoring, possible duplicate

**Comment by strets123** [comment]
Irrelevant now

**Comment by aekhendry** [comment]
Closing as no longer relevant
