### ISSUE TITLE
Hub instance.
when I register ethane and propane (via SMILES) - mol weight is ca

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#194]
Hub instance.
when I register ethane and propane (via SMILES) - mol weight is calculated. I can't get it to calculate in any other circumstances

date recorded in spreadsheet: 14/05/2015 12:42:43

**Comment by strets123** [comment]
We will delete data with missing properties, this will be fixed on next deploy

**Comment by strets123** [comment]
Will need to clear existing compounds to be sure...

**Comment by KarenPorter** [comment]
Mol weiht is being calculated now in all instances I have tried.
