### ISSUE TITLE
We need to document clearly what we can and cannot accept within a file.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#195]
We need to document clearly what we can and cannot accept within a file. For example, what is our policy on R groups? Can catalysts and intermediate steps be included? Can I submit synthesis routes or will the arrows mess it up? Could do with a discussion and will help manage expectations?

date recorded in spreadsheet: 14/05/2015 12:42:48

**Comment by aekhendry** [comment]
Draft is currently being reviewed by Paul

**Comment by KarenPorter** [comment]
@paulbarrett79  Can you please share draft along with your comments so far?

**Comment by PaulBarrett79** [comment]
I've emailed the document to you

**Comment by KarenPorter** [comment]
Thanks Paul.

@aekhendry Adam - can you please progress this?

**Comment by aekhendry** [comment]
Apologies the email must have got buried at some point. I'll discuss with Paul tomorrow the best way to add this to the current help function.

**Comment by PaulBarrett79** [comment]
I've added some extra documentation to the help page, as supplied by Adam. Now ready for testing on staging/sandbox

**Comment by KarenPorter** [comment]
Might need to be rewritten in light of the new batch upload process in any case.

When it does, please ensure proper capitalisation (eg Excel)
if it is possible to include a screenshot that would help explain now the structure column is mapped.
In general this document could be improved and clarified.  I have some suggested changes in  a Word document (emailed separately).
