### ISSUE TITLE
The old way of adding new user (prior to webauth) is now redundant.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#198]
The old way of adding new user (prior to webauth) is no redundant. i f you try to register a user in the old way, the process fails (get an error) and no user is registered. However an email alerting to a new user is sent to admins.

date recorded in spreadsheet: 14/05/2015 13:58:58

**Comment by KarenPorter** [comment]
1. There is still a https://chembiohub.ox.ac.uk/hub/login page (which shouldn't be there - or at least not with the existing content).

2. When I type in invalid account details it doesn't give any message to me as a user.

**Comment by KarenPorter** [comment]
BTW, I'm not sure that I tested 'the old way of adding new user'

**Comment by strets123** [comment]
login page should now be fixed for webauth instances

**Comment by KarenPorter** [comment]
Tested  - can't get to the previous login page - now directed to webauth
