### ISSUE TITLE
Hub instance.

I registered 2 compounds via SMILES - CC and CCC

then registered

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#200]
Hub instance.

I registered 2 compounds via SMILES - CC and CCC

then registered them again in the same way - and got new IDs. I'll add as low, because we don't have evidence that users will use this route particularly often (if at all), but it may be quite fundamental.

date recorded in spreadsheet: 14/05/2015 12:21:24

**Comment by strets123** [comment]
Something is wrong here, acknowledged

**Comment by strets123** [comment]
refactoring

**Comment by KarenPorter** [comment]
Some commentary?

**Comment by strets123** [comment]
The stats should now be correct - queries and messages changed so it is now all about the project

**Comment by aekhendry** [comment]
Tested on Sandbox using SMILES described above. Fixed. Chrome.
