### ISSUE TITLE
Attach spectra data

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#207]
Could we attach spectra data to compounds?

Student feedback (18/05/15)

**Comment by KarenPorter** [comment]
@aekhendry @PaulBarrett79 I think this is subsumed in #800 (file attachments) - or at least should be considered at the same time.  If we're attaching files to AssayReg, can (or should) we attach specific file types (spectra) to ChemiReg?

**Comment by strets123** [comment]
Needs work to integrate file uploads with ChemiReg

**Comment by PaulBarrett79** [comment]
The spectra in question are in WOrd or PDF format and not too large.

I will change the current AssayReg functionality to allow attachments of this type. We can then analyse how file attachments of any type could work for ChemiReg compound records, as it would probably have to fit into the "things as projects" proposed architecture.

**Comment by PaulBarrett79** [comment]
I have set up the assayreg parts of the app to attach non-image files (including word and pdf). You can also download these when viewing the "details" popup.

Pushed to github, will deploy tomorrow to hubtest

**Comment by PaulBarrett79** [comment]
Deployed to hubtest

**Comment by aekhendry** [comment]
I add single activity, upload a file and click save. Page refreshes but no file is present. It's like nothing happened. no error is thrown. hubtest chrome

**Comment by strets123** [comment]
Issue was with pdf upload which was not supported for this. Note added to add error and document handling when reimplementing in chemireg
