### ISSUE TITLE
Ability to preview compounds before submission.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#208]
Ability to preview compounds before submission.

Student feedback (18/05/15)

**Comment by strets123** [comment]
refactoring

**Comment by strets123** [comment]
The preview UI has some further things that need addressing:

Sorting - see #

**Comment by strets123** [comment]
Now complete. We will not do any more filters on this due to the way filters need to be implemented being a bit different to on the search page. We have filters for the errors and also sorts which is most important
