### ISSUE TITLE
I think the compound search page needs a few changes.

After you have clicked "S

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#21]
I think the compound search page needs a few changes.

After you have clicked "Search" you have to scroll past the search interface to get to the results. I'd recommend either having the search results on a separate page or move the search interface to the side or make it hidden with something like an accordion.

date recorded in spreadsheet: 19/03/2015 10:40:15

**Comment by strets123** [comment]
Re layout of search page is now done (finally) Please also test in responsive design view

**Comment by aekhendry** [comment]
Looks OK in chrome (exception of issue 647). Note that in responsive design view its not so good visually, it doesn't fit completely on the screen and buttons jump around. In single molecule view a button is in the middle of the custom fields.

**Comment by strets123** [comment]
OK, please test again now

**Comment by KarenPorter** [comment]
There a very big blank space after the results and before the end of the frame that the results are shown in.  It seems to get bigger too as you change search criteria and reapply them.

UOXID and Upload ID boxes aren't the same height (in responsive mode)

Clicking away from Project list box doesn't close the list unless I click into another select box (same with Functional Group and Filter by project data values).

Size of ChemDoodle box appears illogical - bigger when the overall window is small and small when the window is bigger.

**Comment by KarenPorter** [comment]
Not sure how this has ended up in the Backlog list - needs response from developer - I'm moving to Code review for comment.

**Comment by strets123** [comment]
OK to be continued to fix all responsive issues

**Comment by strets123** [comment]
Fixed the responsive design issues here and also made sure page does not jerk after search

**Comment by aekhendry** [comment]
fixed chrome tagnew
