### ISSUE TITLE
Clarity of group or individual compound allocation of custom field information

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#214]
When you submit a group of compounds, you are presented with an option to add custom fields during the file submission process. It is not clear whether these custom fields will apply to all compounds, or how you can apply custom fields individually. i think this issue can be tied in with preview of compounds before submission.

**Comment by strets123** [comment]
refactoring

**Comment by PaulBarrett79** [comment]
This issue has been dealt with in work completed during this sprint. The table view now allows editing of individual records and "fill down" similar to Excel.

staging/sandbox

**Comment by KarenPorter** [comment]
I can't edit any cells - either in Firefox or Chrome.

**Comment by strets123** [comment]
I would like to demote this issue to be "yellow" as in we will make it work if we have time this sprint

**Comment by KarenPorter** [comment]
I'm still not clear whether the ability to edit records within the table view is in scope / done as Paul commented above?  I haven't seen it in the file upload - and think it was out of scope there - we agreed that data could be bulk edited before submission.  Does that mean it will be possible to edit cells in the search results table or not?

**Comment by strets123** [comment]
This was changed and simplified when chemreg upload was changed
