### ISSUE TITLE
Mapping phase of custom fields during .sdf and .xml file uploads

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#215]
Mapping phaseof custom fields during .sdf and .xml file uploads is currently very broken and doesnt make much sense

**Comment by strets123** [comment]
refactoring

**Comment by PaulBarrett79** [comment]
Refeactoring work may have rendered this bug obsolete - please verify on staging/sandbox

**Comment by KarenPorter** [comment]
Closing - files now mapped very differently.
