### ISSUE TITLE
Browsability - ability to look through the data at a glance and filter it

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#216]
ChemReg outstanding issue as identified in 18/05/15 meeting

For filtering and browsability there are 2 stages: 

1) All custom fields in the table view will have a filter or sort  dropdown
2) There will be a place to include and to exclude items
3) On click outside the dropdown (closing it) if you have not clicked update there will be a notification telling you there are unapplied changes to the filter
4) The filters will be OR within a field and AND between fields

For phase 2 (yellow in this sprint)

1) The values in the dropdowns will be filtered down to encompass the filters that have already been applied ie make the filters
2) There will be another tab in the dropdown for range filters
3) Project profile

**Comment by KarenPorter** [comment]
Create a faceted view for search of custom fields / tags

**Comment by strets123** [comment]
This might be one for you to work on. Suggest a tag cloud approach or a github style label list with sections for each of the fields in a sidebar on the search page. If you do front end I can integrate. Leave a space for tag count, I can add that to the search results

**Comment by PaulBarrett79** [comment]
I'll tackle this today

**Comment by PaulBarrett79** [comment]
This may be affected by potential custom fields refactoring work.

**Comment by PaulBarrett79** [comment]
This won't be done until refactoring has been done and tested - moving to sprint 18

**Comment by strets123** [comment]
Will be covered partly by the dropdowns on the project page at the top of the compound list

**Comment by KarenPorter** [comment]
Not sure what outcome to expect - what changes will this now encompass?

**Comment by PaulBarrett79** [comment]
For changing filter parameters - on any change, form & results should lock the screen until new search results are applied

**Comment by PaulBarrett79** [comment]
Column filters and search form custom field selection are now always in sync through additiona or removal of custom field selections.. Columns pick up preselected filters from search form on load.

**Comment by PaulBarrett79** [comment]
Still to do from Phase 1
2) There will be a place to include and to exclude items
3) On click outside the dropdown (closing it) if you have not clicked update there will be a notification telling you there are unapplied changes to the filter
4) The filters will be OR within a field and AND between fields

**Comment by PaulBarrett79** [comment]
remaining
# front end ticks and filter indicator in button (grey/black)
# Make the filter linked up properly with the download URL
# Apply button for the ui select
# Get rid of projects and uox ids from dropdown
# Make the dropdown in dropdown styled correctly

**Comment by PaulBarrett79** [comment]
"front end ticks and filter indicator in button (grey/black)" has been completed and committed

**Comment by PaulBarrett79** [comment]
"Get rid of projects and uox ids from dropdown" has been completed

**Comment by PaulBarrett79** [comment]
"Make the dropdown in dropdown styled correctly" translates as "stop the typeahead options from overlaying the input box you're typing in" and has been completed

**Comment by PaulBarrett79** [comment]
With respect to the AND / OR filtering, the one change that needs to be made to keep us in line with the comments in issue #355 and to keep it simple, is to change the between column filter to be an AND by default. Currently this is an OR.

**Comment by PaulBarrett79** [comment]
I have made this search default change and marked #355 as such.

**Comment by KarenPorter** [comment]
All delivered in Release 1.0
