### ISSUE TITLE
List Views (display of compounds in projNewect view)

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#217]
ChemReg outstanding issue as identified in 18/05/15 meeting

**Comment by PaulBarrett79** [comment]
Andy has implemented handsontable to become the new list view across the application

**Comment by KarenPorter** [comment]
Accept the list view with its current functionality for this sprint.  I will add a new request for the feedback received from Tom Merritt - I anticipate this is a request others will echo.
