### ISSUE TITLE
User activity log in ChemReg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#218]
ChemReg outstanding issue as identified in 18/05/15 meeting

**Comment by KarenPorter** [comment]
Specifically, requirement is to retain and be able to reference specific searches by user, so they can refer to them in future

**Comment by PaulBarrett79** [comment]
Stage 1: Added a /users page which lists the users registered on the system

**Comment by PaulBarrett79** [comment]
Stage 2: Created page stubs for per-user activity pages  - these will show which projects they belong to as well as multiple batch uploads they have performed with times and will ultimately link to the search page to show details of each.

**Comment by KarenPorter** [comment]
Details of specific searches will need to be visible only to that user.

**Comment by KarenPorter** [comment]
2 further issues in testing:

I can see batches that Adam has uploaded against the Sobey project, even though I don't have access to that project.

The search criterion doesn't seem to be applied when I click on a specific batch - search results are all compounds.  For example, I click on my batch upload from this morning - I know that was a batch of 178 compounds but search results are ~900 compounds.

**Comment by PaulBarrett79** [comment]
Identified and fixed the project restriction issue - not on test yet

**Comment by PaulBarrett79** [comment]
Identified and fixed multiple batch ID issue - not on test yet. Pushing these to central repo

**Comment by PaulBarrett79** [comment]
Pushed to git - ready for code review

**Comment by PaulBarrett79** [comment]
Deployed to hub instance

**Comment by strets123** [comment]
performance enhancement needed to remove the big blob field from the batch data

**Comment by KarenPorter** [comment]
I don't see any change in search results. Still returns all compounds rather than the user batch. (though I think I can't see projects I'm not authorised to see)

**Comment by PaulBarrett79** [comment]
I have committed the code, deployed it to hub but the deployment is not reflecting the up to date code.

**Comment by PaulBarrett79** [comment]
This is now deployed and present on hub instance. Ready for re-testing

**Comment by KarenPorter** [comment]
Passed testing
