### ISSUE TITLE
items can be logged without a structure in chemreg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#219]
For the storage of basic lab maintenance data sets i.e. antibody / peptide / plasmid libraries.

**Comment by strets123** [comment]
Things can be logged without a structure

Project can be set up not to show structures so they dont take up space

**Comment by KarenPorter** [comment]
Done, but needs an update to the list view before it's possible to test.

**Comment by strets123** [comment]
List view now updated I think. Do you mean more updates for structure-free projects?

**Comment by KarenPorter** [comment]
tested - passed
