### ISSUE TITLE
ChemBio Assay User list

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#221]
We need a list of assays commonly used by key groups across all relevant university departments.

**Comment by strets123** [comment]
The approaches we can use are 
Asking people
Searching researchgate
Searching pubmed/ chembl/ pubchem

Search terms could be assay technologies and formats from the bao drop down in pubchem upload sheet from Scripps.

**Comment by aekhendry** [comment]
duplicate of 230
