### ISSUE TITLE
Search by username is missing

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#225]

**Comment by strets123** [comment]
I think what you really man here is search by full name or email in the web auth context. Also username field needs to show this.

**Comment by strets123** [comment]
And we need auto complete searching LDAP

**Comment by aekhendry** [comment]
Hi Andy, yes that what I mean, so say I could search for compounds in a project paul had submitted for example

**Comment by strets123** [comment]
Fixed

**Comment by aekhendry** [comment]
tested on hub.
