### ISSUE TITLE
large sdf upload issue

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#227]
Just uploaded a large (3.5 K) SDF file to hub instance. After the mapping phase I clicked save and it processed the file and after some time  looked to have timed out. The loading bar dissapeared and nothing happened. I clicked save again and this time after a long wait I got to the next page but it had registered the file twice i.e. the compounds had been duplicated.

**Comment by aekhendry** [comment]
https://wiki.nci.nih.gov/display/NCIDTPdata/Compound+Sets;jsessionid=8B785541E971A58AAF751242AE8E960B 

DiV set V file found here

**Comment by strets123** [comment]
refactoring

**Comment by PaulBarrett79** [comment]
Is this still a reproducible issue with the work that has been carried out?

staging/sandbox

**Comment by KarenPorter** [comment]
@aekhendry - can you retry with a large file please - or send me an example and I will test.

**Comment by KarenPorter** [comment]
Not addressed yet

**Comment by strets123** [comment]
Marked down to size 1 for now as we will handle large files with an error message

**Comment by strets123** [comment]
There are now 4 possible file errors:
Incorrect format/extension
No headers found
No data found
Catch all other error

**Comment by KarenPorter** [comment]
Tested - passed.

We will need to process larger files but a hard stop on 1000 records for the moment is better than the crash that previously occurred.
