### ISSUE TITLE
Text on login page doesn't make total sense. What will you find in an email?

Simply click the butto

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#231]
Text on login page doesn't make total sense. What will you find in an email?

Simply click the button below to log in via webauth. You will find these in an email from info@chembiohub.ox.ac.uk. If you haven’t heard from us – drop us a line and we will create an account for you.

**Comment by PaulBarrett79** [comment]
The reference to "these" needed to be moved to part of the app only visible if the system is not under webauth..

Committed to github
