### ISSUE TITLE
Images aren't visible in the compound list until after I've 'done something'.  Not comprehensively t

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#232]
Images aren't visible in the compound list until after I've 'done something'.  Not comprehensively tested but they seem to appear after a click or scroll.

**Comment by strets123** [comment]
I think this was an issue both with our original tablke plugin and the new one. The images now appear immediately or after a consistent load delay

**Comment by KarenPorter** [comment]
Tested - passed
