### ISSUE TITLE
Are we keeping rotatable bonds field in the compound list?  I thought from the discussion with DTC s

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#233]
Are we keeping rotatable bonds field in the compound list?  I thought from the discussion with DTC students that this wasn't relevant to most?

**Comment by aekhendry** [comment]
No we need to get rid of it

**Comment by strets123** [comment]
fixed

**Comment by KarenPorter** [comment]
Tested  -passed
