### ISSUE TITLE
Test of iScienceSearch http://isciencesearch.com/iss.  Passing through search terms likely to be use

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#234]
Test of iScienceSearch http://isciencesearch.com/iss.  Passing through search terms likely to be used in ChemReg to test results.  Determine if there'd be any value in further testing / integration.

**Comment by aekhendry** [comment]
not sure what this is or how important it is

**Comment by strets123** [comment]
We have already added pubchem and chembl searches, this covers what we need to do on this I think, closing
