### ISSUE TITLE
Upload a file of compounds then export the result. Fields which were blank in the imported file now have a value of 'nan' - which would be meaningless to users. Need to remain blank or be given an agreed default value.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#238]
Upload a file of compounds then export the result. Fields which were blank in the imported file now have a value of 'nan' - which would be meaningless to users.  Need to remain blank or be given an agreed default value.

**Comment by strets123** [comment]
Re test

**Comment by KarenPorter** [comment]
@strets123 - This is in 'Under Investigation' but I think it is done.  Can you confirm please?

**Comment by PaulBarrett79** [comment]
This has been completed. Verified on staging/sandbox

**Comment by KarenPorter** [comment]
close - processing now different.
