### ISSUE TITLE
Return search results (for everything in the Merritt project - so no structures), then click on the 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#239]
Return search results (for everything in the Merritt project - so no structures), then click on the UOxID to see what's editable - locks the browser and cannot be recovered.  I need to kill the application.

**Comment by strets123** [comment]
Cant reproduce

**Comment by KarenPorter** [comment]
I haven't been able to reproduce either so happy t close this and create a new one should it reoccur.
