### ISSUE TITLE
Partial process of an uploaded file - progress bubbles for maybe 5 seconds then they stopped so I pr

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#241]
Partial process of an uploaded file - progress bubbles for maybe 5 seconds then they stopped so I pressed the process button again - it processed 208 records instead of the 178 records in the file.

**Comment by strets123** [comment]
refactroring

**Comment by PaulBarrett79** [comment]
Is this still a reproducible issue with the work that has been carried out?

staging/sandbox

**Comment by KarenPorter** [comment]
CAn no longer reproduce. Closing defect.
