### ISSUE TITLE
Loading a file to the new Wood Group project - progress bubbles for a couple of seconds then stopped

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#242]
Loading a file to the new Wood Group project - progress bubbles for a couple of seconds then stopped, so I cancelled.  When I then look at the compound list there are 60 compounds registered.  Surely if i cancel the transaction should be rolled back?  There is a strange pattern of batches registered - The numbers don't seem to make sense and the entries are a mixture of records with and without the custom fields I am attempting to add for each record.  I have a copy of the upload and download files - or download another and it should be clear what's odd.

**Comment by strets123** [comment]
refactoring

**Comment by PaulBarrett79** [comment]
Upload failures and numbers are now dealt with in a much better - needs validating that this is still an issue or not.

staging/sandbox

**Comment by KarenPorter** [comment]
Refactored - can no longer reproduce. Closing issue.
