### ISSUE TITLE
List view for ChemReg Playground doesn't show anything for the first 2 pages - information only show

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#246]
List view for ChemReg Playground doesn't show anything for the first 2 pages - information only shows up on P3 - P6 (again nothing on p7-8).

**Comment by aekhendry** [comment]
This appears to be fixed?

**Comment by strets123** [comment]
fixed, see dupes

**Comment by KarenPorter** [comment]
Tested and passed
