### ISSUE TITLE
I think on the previous list view it showed how many compounds were in the project - that would be u

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#247]
I think on the previous list view it showed how many compounds were in the project - that would be useful to get back.

**Comment by aekhendry** [comment]
Which list view are we referring to here? I'm assuming the project overall view?

**Comment by KarenPorter** [comment]
Any and all - Project view or search view.  User can extrapolate to the nearest 10 how many compounds are available in that view (by multiplying the number of tabs by 10).  The previous list view said there were 178 compounds available- very useful to know in search results and also in project view.  Now I only know there are 18 tabs of results, so somewhere between 171 - 180 compounds.

**Comment by strets123** [comment]
Now shows count
