### ISSUE TITLE
Seems to be consistent that the first time of processing my Tom Merritt input file, it stops process

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#248]
Seems to be consistent that the first time of processing my Tom Merritt input file, it stops processing after 30 records.  The 31st record is the first one to contain a date in the relevant input field - that might be significant.

Then when it reprocesses the input file it doesn't process any of the custom fields.

**Comment by aekhendry** [comment]
Did this get fixed already?

**Comment by strets123** [comment]
try testing, I think so

**Comment by KarenPorter** [comment]
I can get files that aren't accepted - with date values and with special characters.  Issue is not so much that it isn't processed but that the user isn't informed.

hard to get all the steps written down here but I can show you easily enough.

**Comment by strets123** [comment]
refactoring of file processing

**Comment by PaulBarrett79** [comment]
This bug has been superceded by work done during this sprint and is no longer applicable.

Verified on staging/sandbox

**Comment by KarenPorter** [comment]
No longer happening. Close.
