### ISSUE TITLE
Not sure how the 'Supplier' option is supposed to work in the compound detail form.  It shows a list

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#253]
Not sure how the 'Supplier' option is supposed to work in the compound detail form.  It shows a list of all the suppliers - doesn't apply one if I select it, doesn't apply remaining one if I delete all other options.

**Comment by aekhendry** [comment]
Can you tell me which project you found this in? I just tried this and I'm not sure what you mean

**Comment by KarenPorter** [comment]
Look in Read only search demos list, select any compound and look at the detail form.  Toggle edit form and you will see a list of lots of suppliers as tags.  How (as an ignorant user) am I supposed to interact with this?  I tried selecting one and I tried deleting all of the options bar one - but the original supplier value isn't updated.

If I haven't explained this well enough do let me know - I can demo easier.

**Comment by aekhendry** [comment]
I think this is linked to refactoring, reallocate if im wrong

**Comment by PaulBarrett79** [comment]
There is a permissions issue here - I am a superuser on hub, and if I try to edit the supplier field I can see in my debug window that I get a 401 (Unauthorized) error

I shouldn't get this because I am a superuser.

**Comment by strets123** [comment]
We currently have no way of turning string field into a list or visa versa

**Comment by strets123** [comment]
List views are now fixed in chemreg, marking as done
