### ISSUE TITLE
Bringing up of compound detail form isn't intuitive.  Single click then wait appears to be the requi

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#254]
Bringing up of compound detail form isn't intuitive.  Single click then wait appears to be the required behaviour, but as a user I am inclined to double-click (or even triple-click when nothing appears to happen).

I think this can result in 2 windows appearing too - so I edit something in the first one, close it and it doesn't look as though it has closed (when in fact I'm now looking at a second window)

**Comment by strets123** [comment]
Now faster and no 2 window problem. Also the data is lost unless the user clicks update and the update mode is always off by default

**Comment by aekhendry** [comment]
Tested on hub in admin

**Comment by KarenPorter** [comment]
2 things (and I'd be happy for these to be represented by new issues or carried on in this one  -at least to provide me with a response).

Can double-click be interpreted in the same way as single click - ie to launch the modal window? I think both are likely behaviours by users.

When I add a label (eg in alternative name), it is lost if I mouse click in another field - only retained if I tab or enter.  Can it also be retained if I click in another field (or even select update and close)?

**Comment by strets123** [comment]
Regarding double click, I do not agree and much of the interaction design community is with me on this, see here:

http://ux.stackexchange.com/a/7402

What we are missing is a pointer effect on the image.

**Comment by strets123** [comment]
On the tagging fields, while I agree in principle, unfortunately this is really hard to do with the different levels of abstraction we have in place. The field is able to add new values to a drop-down. There has to be concious effort by the user in order to permit this.

**Comment by PaulBarrett79** [comment]
http://ux.stackexchange.com/questions/7400/should-double-click-be-avoided-in-web-applications

**Comment by PaulBarrett79** [comment]
I agree that a link-style pointer for images would work here and make the interface more intuitive.

**Comment by PaulBarrett79** [comment]
I have opened a separate issue for mouse pointer in list/gallery views

**Comment by aekhendry** [comment]
can this issue now be closed?

**Comment by KarenPorter** [comment]
I can't add more than one keyword in compound detail form - surely multiple keywords would be the norm?

**Comment by strets123** [comment]
Which project is this on? Keywords works fine for me
