### ISSUE TITLE
I can't interact with a URL in the list view.  Ideally I'd like to simply click on hyperlinked text 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#255]
I can't interact with a URL in the list view.  Ideally I'd like to simply click on hyperlinked text ('link'), but if not then clicking on the URL.  And if not that then the ability to copy the link so I can at least put it in a browser myself.

**Comment by strets123** [comment]
links shortened and made into hyperlinks, target="_blank" so they open in a new tab

**Comment by KarenPorter** [comment]
Passed testing  -works beautifully!
