### ISSUE TITLE
Search results are not as expected.  When no filter - the first result (in Woods group 2.0) is for P

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#259]
Search results are not as expected.  When no filter - the first result (in Woods group 2.0) is for PARAFORMALDEHYDE. So I added that tag in the filter  - it returns no results.

Instead, if I add a tag for SIGMA as a supplier - filters appropriately (I assume  - at least I get a subset of results)

**Comment by strets123** [comment]
wontfix for now see 263

**Comment by aekhendry** [comment]
Not convinced these are issues that will be addressed, if You push them back again then get rid of them

**Comment by strets123** [comment]
yes got rid
