### ISSUE TITLE
Choice field does not select the right items

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#261]

**Comment by strets123** [comment]
When I try to edit a choice field with a value already assigned then the value is not properly found

**Comment by strets123** [comment]
This issue could only be seen when using the "Choice field allowing create" or Choice field option in the admin. It resulted in 2 bugs - sometimes it listed all the available options on click of edit mode, other times it would select fluka (sigma) instead of sigma

**Comment by aekhendry** [comment]
Could I have this demo'd to me as I'm not sure i understand

**Comment by aekhendry** [comment]
Tested on hub
