### ISSUE TITLE
As I tab through the list or gallery view of search results, every time it loads a new tab of search

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#266]
As I tab through the list or gallery view of search results, every time it loads a new tab of search results it also loads the search results page and goes back to the top of the page - so I have to scroll down to look at the new search results.  Can the results page stay as previously and just the table be updated please?

**Comment by PaulBarrett79** [comment]
List & Gallery view now scroll to the results when you have been paginating through results.

**Comment by PaulBarrett79** [comment]
Checked in to github

**Comment by PaulBarrett79** [comment]
deployed to hub instance

**Comment by KarenPorter** [comment]
Need to see this demo'ed - I still get exactly the same behaviour.

**Comment by PaulBarrett79** [comment]
I have committed the code, deployed it to hub but the deployment is not reflecting the up to date code.

**Comment by PaulBarrett79** [comment]
Present on hub ready for testing

**Comment by aekhendry** [comment]
tested in hub
