### ISSUE TITLE
When there isn't an image in the gallery view, could we have a stronger 'no image' message?  The ima

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#267]
When there isn't an image in the gallery view, could we have a stronger 'no image' message?  The image shown now reminds me more of an 'image not found' message - so looks a bit broken in my opinion.  Trivial priority.

**Comment by aekhendry** [comment]
I actually dont think this is trivial, people dont use things that look broken.

**Comment by PaulBarrett79** [comment]
Added a "No structure" placeholder image where no image is found (list and gallery view)

**Comment by PaulBarrett79** [comment]
Pushed to github

**Comment by PaulBarrett79** [comment]
This needs to be altered to handle a blank image earlier in the process.

**Comment by PaulBarrett79** [comment]
Fix pushed to github

**Comment by strets123** [comment]
The grunt build did not work for this so I have added an extra item to the gruntfile to deal with images

**Comment by aekhendry** [comment]
Tested, looks much better
