### ISSUE TITLE
Can automap be made a little less rigorous - specifically not case sensitive?  I caught myself out w

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#269]
Can automap be made a little less rigorous - specifically not case sensitive?  I caught myself out with a couple of fields I copied wrongly.  

Fairly trivial so not worth any great effort.

**Comment by strets123** [comment]
See the other issues related to update of custom field definitions in a project. We need to rethink certain things about how this works with use cases in mind.

**Comment by strets123** [comment]
Automap - tbf for 1.0 with non case sensitive

**Comment by strets123** [comment]
Have now added ability to automap. Need to think of what the message should be to say data has been autopmapped

**Comment by KarenPorter** [comment]
I think it's ok as it is - indicating automap on relevant columns.

tested, passed
