### ISSUE TITLE
On behalf of Tom Merritt:

(I think this should be one feature request but happy to be told it shoul

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#271]
On behalf of Tom Merritt:

(I think this should be one feature request but happy to be told it should be 2)

Add ability to change the default number of entries in list view (as we had previously)
Add ability to change the order of columns in the list view - so the fields of interest are closest to the left and redundant ones can be left off entirely.

**Comment by strets123** [comment]
Possible everywhere except in the upload view

**Comment by strets123** [comment]
Long estimate due to needing to persiste the order of columns after page reload

**Comment by KarenPorter** [comment]
@strets123 I think this is superseded with current functionality? please clarify if there is outstanding effort needed and put in backlog.

**Comment by strets123** [comment]
Project owners can now reorder a project  - closing
