### ISSUE TITLE
Batch uploads list per user doesn't have the project name truncated - so the list does that untidy j

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#272]
Batch uploads list per user doesn't have the project name truncated - so the list does that untidy jumbled up thing that has been fixed elsewhere wherever projects are listed.  Can the name be truncated here too please

**Comment by PaulBarrett79** [comment]
Might change this to use the new list/table view but will truncate these names for now

**Comment by PaulBarrett79** [comment]
Project name item truncated at 20 characters.

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox. Verified that fix has been applied.

**Comment by KarenPorter** [comment]
tested - passed
