### ISSUE TITLE
Supported / tested browser list.

I've tried IE10 - I can't move beyond the project list page - when

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#273]
Supported / tested browser list.

I've tried IE10 - I can't move beyond the project list page - when I click a project title or the add compound link - nothing happens.  Nothing happens from menu options either.

In Firefox I have an issue where in the compound detail page I only get the low-res image until I click on it and it then resolves to hi-res.  I don't have that sames problem in Chrome.

We need a statement as to which browsers we support , any settings that need to be changed and any constraints a specific browser (and OS combination) supports.

**Comment by strets123** [comment]
How did you install IE 10? IE 11 works OK

**Comment by aekhendry** [comment]
working for IE 11
