### ISSUE TITLE
CDXML copy link removed (regression)

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#276]
Due to changes to the list view and image display of single moecule, the copy CDXML link has been removed.

**Comment by PaulBarrett79** [comment]
Adding to sprint 16

**Comment by PaulBarrett79** [comment]
Re-added link into header of single compound modal

**Comment by KarenPorter** [comment]
Needs to be tested by adding compounds with structures and checking hte cdXML link on those

**Comment by KarenPorter** [comment]
I still can't see the link  - added 4 compounds with structures and there's no CDXML link on the single compound window that I can see.

**Comment by PaulBarrett79** [comment]
I have committed the code, deployed it to hub but the deployment is not reflecting the up to date code.

**Comment by PaulBarrett79** [comment]
This is now present on hub ready for testing

**Comment by KarenPorter** [comment]
Passed test
