### ISSUE TITLE
The list view of registered compounds is initially too small - I added 4 compounds (via SMILEs strin

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#278]
The list view of registered compounds is initially too small - I added 4 compounds (via SMILEs strings) but could only see one in the batch upload finish page.  Flipping to Gallery view then back to list fixed it but needs to be the right size to begin with.

**Comment by strets123** [comment]
refactoring of backend

**Comment by PaulBarrett79** [comment]
This only happens when the compound list being loaded doesn't contain structure images. That is a s reproducible as I can make this.

**Comment by PaulBarrett79** [comment]
There has been some work done on the table component which means that this may have been fixed

**Comment by PaulBarrett79** [comment]
After refactoring work, I can no longer reproduce this. List is always loaded with the correct viewport sizing.

Needs verifying after latest deploy

**Comment by PaulBarrett79** [comment]
Verify on latest deployment staging/sandbox

**Comment by KarenPorter** [comment]
Different table view now so no longer an issue
