### ISSUE TITLE
Search criteria remembered from previous visit to the page, but not applied - so what I selected las

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#279]
Search criteria remembered from previous visit to the page, but not applied - so what I selected last time is checked / unchecked at the top but all results are returned, not with that filter applied.

**Comment by strets123** [comment]
form retains previous data

**Comment by PaulBarrett79** [comment]
examining now

**Comment by PaulBarrett79** [comment]
examining now

**Comment by PaulBarrett79** [comment]
This does not happen with date field selection - date is cleared. This may just be limited to certain fields.

**Comment by PaulBarrett79** [comment]
This bug was limited to the project list selection. Re-visiting the search page (via a link) now correctly re-initisalises the search.

**Comment by PaulBarrett79** [comment]
Pushed to github, awaiting deployment

**Comment by aekhendry** [comment]
Tested
