### ISSUE TITLE
Search doesn't bring back all relevant results..  

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#282]
Search.

Searched for sucrose (by tag - Formula|C12H22O11) - got back my 2 records.  Added another criterion (Amount|100 TABLETS) and got back records with 100 tablets, my 2 sucrose records *plus* a sucrose entry Adam created - which I assume is in a project I don't have access to.  When I click on that entry, the modal window doesn't appear - so security kicks in there).

**Comment by KarenPorter** [comment]
https://chembiohub.ox.ac.uk/hub/#/search?project__project_key__in=wood-group,wood-group-20&search_custom_fields__kv_any=Formula|C12H22O11,Amount|100%20TABLETS

**Comment by KarenPorter** [comment]
accidentally closed - meant to add the search URL

**Comment by strets123** [comment]
One of the records is stopping the modal from loading and there MAY be a perms issue?

**Comment by strets123** [comment]
I will be changing the wording of the search to make clear this is an "any" search not an "all" search. The search is entirely consistent and the data comes from the 2 wood group projects both of which you have access to

**Comment by strets123** [comment]
Also opened issue to show project on list view

**Comment by KarenPorter** [comment]
This is in Awaiting Deployment and as such maybe I'm not seeing the latest search functionality on Hub (but the wording has changed so I think I am).  

As a user this does not appear to me to be entirely consistent.  To explain further:
the projects I have selected are Wood Group and Wood Group 2.0.  I search for Formula C12H22O11 and get back 2 entries - both added by me.  I add a second custom field selection (I've tried a couple and they produce the same effect).  In this case - I added amount of 100 tablets.  I now get 9 entries returned - the original 2 sucrose records, 6 records with amount of 100 tablets and a third sucrose record (it has an amount of 1 kilo).  

That third sucrose record should be returned in the first search.

**Comment by KarenPorter** [comment]
If this is user error please discuss.

**Comment by strets123** [comment]
I was not aware that there was a lack of isolation in the SQL statements generated by the framework - all that was missing was some brackets to change the meaning of the OR in my code. Very well spotted!

**Comment by KarenPorter** [comment]
Could be new but I'm not sure:

Search in Wood group and wood group2.0 for Sucrose (name) and get 6 results, all of which look like their formula is C12H22O11.  Search on that formula in same projects and I only get 2 results.  So is the formula actually the same in all records (ie no trailing spaces or anything non-printable?

**Comment by KarenPorter** [comment]
has something changed here?  There's no new comment.  What should I expect to happen differently?

**Comment by strets123** [comment]
Currently there is an ANY query against the custom fields ie. 
(col1=x OR col1=z) OR (col2=Y)
Really  it needs to be

(col1=x OR col1=z) AND (col2=Y)

But I would like to move this to the next sprint as it is difficult to do with the current implementation

**Comment by strets123** [comment]
The bug you reported is fixed however

**Comment by strets123** [comment]
The reported bug is fixed

**Comment by aekhendry** [comment]
This links to an issue I just raised that can help in the meantime (422)

**Comment by KarenPorter** [comment]
Original defect raised here has now been resolved, and Adam has created a new issue for the Boolean issue.  Closing this one out as passed in that case.
