### ISSUE TITLE
Date parsing for Excel uploads

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#283]

**Comment by strets123** [comment]
Dates can now be entered either as text format (achieved in Excel by putting an apostrophe before) OR as excel date format. A wide variety of formats will be accepted although there will probably be confusion if you use text format and write the date in the British English order.

The SDF import and XLS export should now also work properly

**Comment by strets123** [comment]
There is a related issue in that chemreg playground data sometimes the pop up does not work. This should be solved by having only correctly formatted dates in the date field

**Comment by strets123** [comment]
Integer, percentage and decimal field validation has also been added.

**Comment by aekhendry** [comment]
Tested on hub
