### ISSUE TITLE
Save and Email a search - new feature

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#286]
Andy has suggested an ability to save a search, and email it to another user. This may work in an amazon "basket" like way.

**Comment by strets123** [comment]
Quick win

**Comment by PaulBarrett79** [comment]
Also add copy/paste link so they can add it to their own emails.

**Comment by PaulBarrett79** [comment]
The save a search part of this ticket is being explored as a new piece of functionality.

**Comment by PaulBarrett79** [comment]
- [ ] User Experience overview of this functionality
- [ ] Brief mockup of how the search interface will look with saved search functionality
- [ ] Build front end elements and user interaction pathway
- [ ] Provision back end/DB saving and retrieval of searches (as part of User model?)
- [ ] Stretch - email a saved search

**Comment by PaulBarrett79** [comment]
I have added a document to S:\OxChemBioHubDB\Project Documents\Requirements Capturing\ChemiReg\saved search ux.docx

**Comment by PaulBarrett79** [comment]
Users can now save a search and see a list of their searches.

to save:
Go to Search Compounds page
Perform a search
Click the Saved Searches drop down button at top right of page
Click Save Search
Enter a title in the "Save Search As" box
Click Save
The modal will close and your search is saved.

to see saved searches:
Either go to Projects page (searches listed on the RHS
Or go to Search Compounds Page
Click Saved Searches
Click My Saved Searches
Modal window displays searches

TO use a saved search, in the list click "Use this search". You are forwarded to the search page with your parameters added.

Pushed to github for code review.

**Comment by KarenPorter** [comment]
save search - name should be mandatory.

Project page doesn't update - says I have none when I do.

**Comment by PaulBarrett79** [comment]
Made alias mandatory

Project box was intended to be for sharing search to other users in specified projects, we will have to revisit this based on permissions model and the fact that these are compound batches now. Removed the box from the form for now as it is not required.

These changes pushed to github. I have still to work out why list does not update. It does show immediately in the modal window via search page dropdown. Page refresh seems to fix this on project list page, think there is an object somewhere which needs refreshing, or it doesn't load in time.

**Comment by PaulBarrett79** [comment]
Project list page -  saved search list needed $scope.$apply to add loaded searches.

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to hubtest

**Comment by strets123** [comment]
removing label

**Comment by aekhendry** [comment]
I can add a new saved search, and access it via the project page or search page. 

However I am getting very inconsistent behaviour when adding additional projects to the search parameter box in the search form.  I keep getting no entries returned on adding a new project. 

Fomr project page -> serach compounds -> search page (all entries for all projects shown) -> Enter a project i know contains entries -> no entries returned

Refreshing the page occasionally returns the entries, but is again inconsistent. I can't seem to find a pattern to trigger it but it is occuring enough to be a serious concern.

If this issue is un related, push back to testing and I'll create a new card.

**Comment by PaulBarrett79** [comment]
@aekhendry This is unrelated to this card, your first sentence here as far as I can tell signs off this issue. Please make a new card for this project addition bug.

**Comment by aekhendry** [comment]
Signed off chrome hub test
