### ISSUE TITLE
Ability to view more then 20 entries in list view at one time

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#287]
It would be useful to be able to select to view more then 20 entries in table view. I see this working a lot like pubmed. Paul has said it shouldn't be difficult to impliment

**Comment by strets123** [comment]
Currently we have different default number of items dependent on the view type, how will this be handled?

**Comment by PaulBarrett79** [comment]
Added a mechanism to select number of records per page - works for list and gallery  but produces an unusual number for gallery - will raise a separate issue for this, as this issue describes table view only.

**Comment by PaulBarrett79** [comment]
pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to hub instance

**Comment by aekhendry** [comment]
tested on hub
