### ISSUE TITLE
Project not shown in list view or on single compound view

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#289]

**Comment by PaulBarrett79** [comment]
Added to single molecule modal

**Comment by PaulBarrett79** [comment]
Added to list view

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox, verified fix has been deployed

**Comment by KarenPorter** [comment]
Where it appears in the single molecule modal window it is clickable - takes the parent window back to the projects list page (no project selected).  I don't think it should be clickable - and if it is that isn't necessarily the behaviour I'd expect - happy to discuss if there's a logic there I'm missing.

**Comment by PaulBarrett79** [comment]
Yes I suppose it doesn't make such sense to link to the project from there. It can just be static text.

**Comment by PaulBarrett79** [comment]
Removed link from project display in single molecule modal

Pushed to github

Deployed to staging/sandbox, verified fix is deployed

**Comment by KarenPorter** [comment]
tested, fixed.
