### ISSUE TITLE
File submission mapping phase bug.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#293]
I submit excel file containing structure to admin project on hub
I select SMILES as structure column and submit.
Progress to mapping phase.
In my excel file, i have two column headings that describe alternative names for each compound.
I move both of these field headings under the predetermined 'custom identifier heading'. Note that both heading are accepted into this field.
I click submit
Only one of the headinf idenifiers is saved to each compound e.g. UOXGB76ERN

My expected outcome was to see both identifiers listed like tis in the field at the end: "indentifiera, identifierB. "
I appreciate that logically what happened make sense, but it wont to a user who doesnt know the system. 
There needs to be a warning that this can happen, or the user should not be allowed to put more then one heading under each new column.

**Comment by aekhendry** [comment]
This also happens for SDF. A short explainiation is that you cannot map more then one field heading from a file to a custom field during the file upload mapping phase. Only the first field heading mapped is saved. I have also tested that this is true when mapped to custom fields that are set to be tag based. the easy fix would be to only permit one heading per custom field, but this may lead to user problems in the future.

**Comment by strets123** [comment]
Now set the dragable area to only allow one item. We will work with lists as comma separated eventually

**Comment by aekhendry** [comment]
tested on hub
