### ISSUE TITLE
SMILES error message

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#294]
Entered SMILES and this was shown "5, when counting from the top.8, when counting from the top.9 when counting from the top."

I believe it should read as  "5, 8, and 9 when counting from the top."

Hub instance admin project

smiles submitted:

c1ccccc1
C1Cc2c(C1)cc1c(c2)cccc1
C1CC2CC3CC4CCCC5C4C4C3C3C2C(C1)CC1C3C2C4C(C5)CC3C2C(C1)CCC3
CCCCCCCC
NCOC1CC(N)C(C@HC)C
O[C@@H]1CCC2C([C@H]1C)CC1(CC2)CCCCC1
C[C@@H]1CCC2C([C@H]1C)CCCC2
C[C@@H]1CCC@@HC
CC1CCC2(CC1)CC@HCC@@HC

**Comment by strets123** [comment]
fixed

**Comment by aekhendry** [comment]
tested on hub
