### ISSUE TITLE
When a SMILES string is longer then the text box you insert it into, when it moves onto the next line it is not lcear that this is part of the same string

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#296]
If you eneter a long SMILES string into the submission box it will spill over onto the next line. If you past multiple long SMILES it is currently hard to determine where a new string starts or ends. Maybe if a string spills over into subsequent lines it could be indented?

**Comment by strets123** [comment]
Added code editor to ensure smiles line numbers match up properly

**Comment by aekhendry** [comment]
tested on hub
