### ISSUE TITLE
Really long compounds are currently displayed in list view with a red line

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#297]
Really long compounds are currently displayed in list view with a red line. i s this behaviour intended? It just looks a bit strange but i understand its purpose. When you exand the view to single molecule it does give you what i would consider to be the correct image. See UOXKS52ZRL in admin on hub for an example

**Comment by strets123** [comment]
Why are we putting this as a bug for this sprint? It is just the way image generation works
