### ISSUE TITLE
Navigating the carousel in the help page in ChemReg (hub) is broken

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#298]
Using carosel gives you a 404 https://chembiohub.ox.ac.uk/hub/#/404

**Comment by PaulBarrett79** [comment]
Needs changing to angular-ui carousel rather than vanilla bootstrap

**Comment by PaulBarrett79** [comment]
Converted to use angular ui-bootstrap carousel. Pushed to github.

**Comment by PaulBarrett79** [comment]
Deployed to hub instance

**Comment by aekhendry** [comment]
tested on hub
