### ISSUE TITLE
Search results duplicated. I excluded all bar the Wood Group 2.0 project, no other search parameters

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#302]
Search results duplicated. I excluded all bar the Wood Group 2.0 project, no other search parameters.  The same IDs appear twice - at least those which have a structure.  They seem to appear in order 1 - 5 then 5 -1.

This is the search URL -  https://chembiohub.ox.ac.uk/hub/#/search?page=1&compoundBatchesPerPage=10&project__project_key__in=wood-group-20&doScroll=true#search-bottom

**Comment by PaulBarrett79** [comment]
This is an odd one.

**Comment by PaulBarrett79** [comment]
Duplicates are as a result of multiple records from different multiple batches- need to be able to differentiate these, which will involve adding a column to the list view.

**Comment by PaulBarrett79** [comment]
Added config to allow this column to be displayed. Pushed to github.

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox

**Comment by aekhendry** [comment]
I can no longer replicate the described behavior so I'm labeling as fixed. Tested on sandbox / chrome
