### ISSUE TITLE
Duplicate custom field value.

In Chemreg Playground, there are 2 tags of 'Powder' for physical form

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#305]
Duplicate custom field value.

In Chemreg Playground, there are 2 tags of 'Powder' for physical form - they look the same so I'm not sure how the difference has arisen.  Could be cosmetic or could be important if there are records with each type of label and therefore search results are incomplete when a user only selects one.  I'll make priority medium on the basis of potential incomplete search results - happy to have it downgraded if this isn't the case.

**Comment by strets123** [comment]
should not be possible now I think, re test with new data

**Comment by aekhendry** [comment]
Fixed chrome hub
