### ISSUE TITLE
List view component initially not tall enough.

This feels like one already raised (and fixed?).

Up

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#307]
List view component initially not tall enough.

This feels like one already raised (and fixed?).

Uploaded a chemdraw file with 2 molecules in it - the list view on the finish page was only tall enough to see one and I had to scroll to see the second.  Flipping to Gallery view and back - it was now tall enough to see both compounds.  Loaded the same file a second time and the finish page included a list view showing both compounds.

**Comment by aekhendry** [comment]
fixed tested on hub
