### ISSUE TITLE
Functional Group list box isn't wide enough.

It isn't possible to read enough of the text in the fu

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#308]
Functional Group list box isn't wide enough.

It isn't possible to read enough of the text in the functional group list box to distinguish all of the options from each other.

**Comment by PaulBarrett79** [comment]
This has been fixed when we altered the angular-schema-form-ui-select library to make the form layout better. You can now read these fields correctly. ALreday deployed to staging/sandbox

**Comment by KarenPorter** [comment]
tested - fixed
