### ISSUE TITLE
Cursor should be a pointer for images in list and gallery view

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#311]
Hovering over a structure image in list and gallery view shows the standard arrow cursor. Should be a pointer (link) cursor as it opens the sinlge structure modal.

**Comment by PaulBarrett79** [comment]
Cursor in list and gallery view is now a link pointer. Committed to github.

**Comment by PaulBarrett79** [comment]
Now deployed to hub instance

**Comment by KarenPorter** [comment]
tested, passed
