### ISSUE TITLE
Purity can be set to 0

### ISSUE THREAD

**Issue by nroam** [thesgc/chembiohub_helpdesk#313]
A purity value of 0 is not physically possible.

**Comment by KarenPorter** [comment]
When I set the purity in the single compound window to 0  I get an error message message saying "0 is less than the allowed minimum of 0.1"  however the message isn't updated if I change it to -1, -2 etc (still says "0 is less than...).

**Comment by PaulBarrett79** [comment]
Can't replicate on staging/sandbox, which are later versions - possibly fixed or a config error on Sydney's version? You definitely can't set purity to be 0 any more.

**Comment by PaulBarrett79** [comment]
Hub instance does not allow negative values

**Comment by PaulBarrett79** [comment]
staging sandbox instance does not allow negative values

**Comment by PaulBarrett79** [comment]
Validation message now shows "Value less than" instead of "[first erroring number used] less than" on staging/sandbox instance

**Comment by aekhendry** [comment]
tested on sandbox
