### ISSUE TITLE
Custom Identifier

### ISSUE THREAD

**Issue by nroam** [thesgc/chembiohub_helpdesk#314]
It is not clear to the end user what 'Custom Identifier' means. It either needs to be renamed or there should be a help capability that makes it clear what the purpose is and perhaps give and example.

**Comment by PaulBarrett79** [comment]
This particular field is a project-specific custom field but the principle extends to all custom fields - there needs to be better help integration for all of these.

Renaming "Custom Identifier" is not a task which will be performed here as it is confined to one instance and can be renamed by an admin. I will open a new issue for better help/infobox support

**Comment by PaulBarrett79** [comment]
Opened #360 to deal with the wider issue here.
