### ISSUE TITLE
Date box is too hard to populate historical values

### ISSUE THREAD

**Issue by nroam** [thesgc/chembiohub_helpdesk#315]
Trying to add a compound I made in 2004 is a pain - I must go through each month to get to 2004. It should be possible to click on the year and move this back to 2004 quickly.

**Comment by PaulBarrett79** [comment]
This is a config change on the pickadate library - should be a simple fix

**Comment by PaulBarrett79** [comment]
Updated the version of angular-schema-form-datepicker and changed config of date fields to allow month/year selection. Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to hub instance

**Comment by KarenPorter** [comment]
year and month values aren't completely visible in the box - font size is too big.

**Comment by PaulBarrett79** [comment]
Font size is not too big - rather the padding on the select box is too much. (this has been determined by the creator of third party library)

Added an override for the app, committed to github

**Comment by KarenPorter** [comment]
Has it been applied to Hub?  not seeing any different.

**Comment by PaulBarrett79** [comment]
.It has been applied - you should either show me or take a screengrab (you can add these to issues through the github interface rather than waffle)

**Comment by KarenPorter** [comment]
I'm now seeing the revised date picker and text is all visible.  Passed testing
