### ISSUE TITLE
Tabbing between fields does not show drop down

### ISSUE THREAD

**Issue by nroam** [thesgc/chembiohub_helpdesk#317]
When tabbing between fields in single reg mode, it is not obvious that there is a drop down to select from. You must click to see this possibility. Can an icon on the far right of the field be shown to indicate there is a drop down?

**Comment by PaulBarrett79** [comment]
This is to do with the tab behaviour of the "angular schema form ui select " library we are using - dropdown is triggered on mouse click but not tabbing to the field. Don't  know how trivial it will be to change this behaviour. Adding some sort of info box or indicator might be the best way to do this.

**Comment by PaulBarrett79** [comment]
Usability is mixed with these components - tabbing/keyboard events work well with some but not with others.

**Comment by strets123** [comment]
Could you specify an example of a user interface where tabbing to open a dropdown works well?

http://plnkr.co/edit/HiABwudoJjQMRGN65PoD?p=preview

It's possible to to but of the examples I have seen lead the user to accidentally select an item if they click tab again.

By far the biggest improvement possible for these would I believe come from a combination of a much faster response for the typeahead and an icon as you have suggested.

**Comment by nroam** [comment]
I'd rather you spent time putting the icon in than trying to kludge a tab-fix.

**Comment by strets123** [comment]
OK, clear and helpful, thanks.

Regarding the ID field would we perhaps be better using a multiline like we do in the "Add" section?

As I come to think of it this would be more helpful for pasting IDs  in from Excel. Would only need a height of 3 lines.

**Comment by PaulBarrett79** [comment]
Might try an "onfocus" which displays a info message when mousing to the area - "Type ahead or press down to see options for this field" or similar

**Comment by strets123** [comment]
I think there is a way to set the deault placeholder - we can make the description go below the field. Any idea how to add the icons?

**Comment by PaulBarrett79** [comment]
Think we can inject html to be included - we can use the info-box directive we have then

**Comment by PaulBarrett79** [comment]
A really simple and effective way to do this could also be to have the placeholder say "Choose..." inferring that there are choices available for that field

**Comment by PaulBarrett79** [comment]
(and put the description inside a info-box directive inside our version of the uiselect template)

**Comment by PaulBarrett79** [comment]
Tried to make this so you could inject your help directive of choice but couldn't get it to work - taking too long. I have hardcoded an infobox directive into our version, Could become a proper dependency in future?

UI select boxes now have "Choose..." as the placeholder and an info box which holds the old placeholder descriptive sentence. This should make it more obvious to tabbing users that choices are available.

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox

**Comment by PaulBarrett79** [comment]
After some fiddling, now on staging/sandbox

**Comment by KarenPorter** [comment]
Better, but there is a limitation to this UX.  Tabbing to a select box requires that the user tab twice before the drop down can be activated with enter key, so there appears to be an inconsistency of action needed (tab once to add info to a text field, tab twice to select a value from a selection).  Having said that - if not a trivial fix I think this is something users could easily live with.

**Comment by KarenPorter** [comment]
(on Firefox - not tested on other browsers)

**Comment by strets123** [comment]
If you do tab once then the UX will be more broken than tab twice - see my
earlier example URL in this thread. It will cause accidental selections.

**Comment by PaulBarrett79** [comment]
As Andy says, we risk ruining other aspects of UX and potentially even giving ourselves more bugs by trying to fine-tune this more - also any further work wouldn't be in our codebase, it would be "fixing" an imported module. I propose we leave this as it is.
