### ISSUE TITLE
Excel export columns

### ISSUE THREAD

**Issue by nroam** [thesgc/chembiohub_helpdesk#320]
The column widths and justification in the excel export of compounds is diabolical and entirely user-unfriendly:

1) As a minimum, widths must be at least that of the column title
2) As a maximum, column widths must be no more than the maximum width of any record in that column

**Comment by PaulBarrett79** [comment]
The export library we are using does not allow autosizing of columns. I would love it if it did but the simple fact is that it doesn't.

All we can do is guess the size of the columns. We could set a more sensible default width for columns, possibly based on character length of the header text.

**Comment by aekhendry** [comment]
Not sure if there's much we can do here, close if you think its a deadend

**Comment by strets123** [comment]
Disagree. This is less easy than we would hope but with a little maths can be fixed.

We get the string length of the column via pandas and the string length of the header and take the max of those 2

df[col1]str.len().max()

If that is greater than the maximum we have in mind (e.g. 100 chars) then we use the maximum

The width value in Excel is specified in characters approximately.

http://xlsxwriter.readthedocs.org/en/latest/worksheet.html

**Comment by strets123** [comment]
see #391 too

**Comment by KarenPorter** [comment]
elegant solution proposed

**Comment by strets123** [comment]
Column widths are now regularised

**Comment by KarenPorter** [comment]
Still seems a bit random - Amount, BatchID and Known drug are all wide in Excel but contain values with a small number of characters. Chemical Names, SMILES and Std InChi fields are all fairly narrow with values overspilling quite considerably.

I appreciate there are limitations to what can be done - is this the best we can hope for with the information available? @strets123

**Comment by strets123** [comment]
I have tweaked this again, the random element has been removed and the max width set even higher and the min width lower

**Comment by KarenPorter** [comment]
I'm getting no data rows in the export - though agree the header widths do look better (hard to tell without the data though).

Failed test

**Comment by strets123** [comment]
Yes - new issue somewhere with the export

**Comment by strets123** [comment]
Please try again now, should be all fixed. Data order is 

* UOx ID	SMILES	Added By	Std InChi	Mol Weight	alogp
* Then project defined fields
* Then upload-defined fields

**Comment by KarenPorter** [comment]
Needs quick discussion - _although column widths are much better (no issue with those) I don't understand the data order, which doesn't seem to reflect the order indicated above.  

Example is download of a search of batch id 727.  there are a load of empty columns at the front that look like they belong to an inventory project, but the data all relates to the Test Project.

**Comment by KarenPorter** [comment]
@strets123 @aekhendry any remaining issue with excel export should be documented and estimated in backlog please.

**Comment by strets123** [comment]
I have now fixed this as part of the Scarab work
