### ISSUE TITLE
References to custom fields across app

### ISSUE THREAD

**Issue by nroam** [thesgc/chembiohub_helpdesk#321]
References to 'custom fields' (e.g. in Search) are MEANINGLESS to end users. This is internal chembiohub jargon and we should not assume that end users understand what this means.

Please remove/reword globally.

**Comment by PaulBarrett79** [comment]
Maybe these should be renamed "User fields"? If we have no distinction between autogenerated fields and user-added fields, users will think that generated fields can be changed which is not the case. It is important to keep these sets of field distinct.

**Comment by nroam** [comment]
Does the user know what a field is? Is this too much jargon even then? (I am being devil's-advocate deliberately )

I would have thought that fields that are not editable have a grey background to signify the fact.

**Comment by PaulBarrett79** [comment]
That might be a good compromise.

**Comment by strets123** [comment]
I would advocate that across the app we keep to 3 definitions:

Compound information

Batch Information

Upload Information


Any reference to Batch should be about the batch of a compound

**Comment by KarenPorter** [comment]
Does this proposed effort include relabeling of the Compound detail form with its 'curated' and 'uncurated' groups of metadata.  No users would know what that means either.

**Comment by PaulBarrett79** [comment]
Yes it does. I will replace "Custom Fields" with "Project Data" as custom field sets are assigned on a project to project basis. I will replace Uncurated with "Supplementary Data" which is the best description of this that I can think of that indicates that this not officially part of what is required by the project.

If these are wildly unsuitable please let me know.

**Comment by strets123** [comment]
Good suggestions Paul, lets go with those for now.

**Comment by PaulBarrett79** [comment]
This is waiting to be pushed to github until inventory code can be assessed

**Comment by PaulBarrett79** [comment]
Custom field references now pushed. Awaiting sandbox deployment

**Comment by PaulBarrett79** [comment]
Should all be deployed to sandbox

**Comment by aekhendry** [comment]
'Custom field value' can be seen on search page above the 'custom field' search box in search. Needs to be changed to new definition i.e. 'project data values'

**Comment by PaulBarrett79** [comment]
This should be on sandbox now - please retest

**Comment by aekhendry** [comment]
Tested, staging, chrome
