### ISSUE TITLE
SDF exports should be marked as being sourced from ChemBio Hub ChemReg

### ISSUE THREAD

**Issue by nroam** [thesgc/chembiohub_helpdesk#322]

**Comment by PaulBarrett79** [comment]
SD files now show a "Generated by ChemReg" message with the website URL

Pushed to github.

**Comment by KarenPorter** [comment]
I can see the indicator when I view the file in Notepad.  Brian, do you expect to be able to see this by other means - I'm not sure how you interrogate the source currently?

**Comment by nroam** [comment]
Only in the header of the SDF itself. So this sounds done.

**Comment by KarenPorter** [comment]
Thanks, I'll close it.
