### ISSUE TITLE
SMILEs field automapped to Ignore Columns area.

In the Sydney instance I upload a file and define t

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#323]
SMILEs field automapped to Ignore Columns area.

In the Sydney instance I upload a file and define the SMILEs column.  When I get into the Map page, the SMILES field is in the Ignore Columns area.  The first time I did the upload I didn't even spot where it was and processed the file without SMILES.  Obviously I can drag it back and map it correctly but this is wrong behaviour.

**Comment by PaulBarrett79** [comment]
Validation and mapping steps are being refactored - may affect any fixes I provide

**Comment by PaulBarrett79** [comment]
This functionality has now been superceded by other work done during this sprint- no longer applicable.

Verified on staging/sandbox

**Comment by KarenPorter** [comment]
Close - now not applicable.
