### ISSUE TITLE
When there is a single result returned in search, it says '1 results' - should be '1 result'.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#324]
When there is a single result returned in search, it says '1 results' - should be '1 result'.

**Comment by PaulBarrett79** [comment]
Added a ng-pluralize field for this display (correctly pluralizes now)

**Comment by PaulBarrett79** [comment]
pushed to github

**Comment by PaulBarrett79** [comment]
deploying to staging/sandbox

**Comment by KarenPorter** [comment]
Tested - passed
