### ISSUE TITLE
Exact search following a substructure search does not work

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#327]
I draw a molecule in search. 
I click search substructure and search.
It works
I click exact match and search same structure (I do not edit drawing in anyway)
I get previous substructure search results.
This happens even if i refresh the page. i have to navigate away and come back to reset the page back to nothing
If I search exact match first (before substructure search) then it works
tested on hub, chrome and firefox

**Comment by PaulBarrett79** [comment]
Substructure search not clearing between searches. Added a function which does that. Pushed to github.

**Comment by PaulBarrett79** [comment]
Deployed to sandbox

**Comment by aekhendry** [comment]
tested on sandbox / chrome
