### ISSUE TITLE
Explorer browser issue - font changes

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#328]
Note font has changed when using explorer (up to date). Also note thate for custom fields that are tag related, the helper text is a different colour to the helper text in non tag related custom fields.

**Comment by aekhendry** [comment]
tested on hub

**Comment by PaulBarrett79** [comment]
Converted the Nexa font from OTF to EOF/WOFF/SVG. Essentially this means that a version suitable for every browser will be used where appropriate.

Pushed to github

**Comment by PaulBarrett79** [comment]
Converted the OTF font to EOF/WOFF/SVG so that the correct version is used in the appropriate browser. IE doesn't like OTF files.

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox

**Comment by aekhendry** [comment]
Tested on sandbox / explorer
