### ISSUE TITLE
Explorer browser issue - search by custom field values crashes is extremely slow and can crash browser

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#329]
search by custom field values crashes is extremely slow and can crash browser. this is much worse then seen in other browsers so far. Tested on latest explorer version

**Comment by aekhendry** [comment]
tested on hub

**Comment by PaulBarrett79** [comment]
This is related to #330 which is a candidate for sprint 18

**Comment by strets123** [comment]
Please re test

**Comment by aekhendry** [comment]
Can't seem to replicate this so closing it
