### ISSUE TITLE
Need to show/explain how AlogP e.t.c. is calculated (and what it means)

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#33]
Need to show/explain how AlogP e.t.c. is calculated (and what it means)

date recorded in spreadsheet: 24/03/2015

comments from spreadsheet:
PB - I have added a placeholder on the compound list which launches a popup containing a glossary of terms. This can be added to and updated in the same way as the system messages

**Comment by KarenPorter** [comment]
@aekhendry Now 10 months old.  Does the system effectively explain AlogP?  if not, how should this be added? Get issue appropriately recorded into backlog or closed.

**Comment by strets123** [comment]
Removed these fields now, future requests for molecular properties will be on an ad hoc basis with plugins
