### ISSUE TITLE
search by custom field tags is too slow to load tags in drop down

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#330]
hub instance

**Comment by PaulBarrett79** [comment]
Custom field search may be changed so that individual fields are split out or the user looks up the type of field first. Performance may also be browser/OS dependent. In any case, this will be dependent on refactoring so is a candidate for sprint 18

**Comment by KarenPorter** [comment]
This has no effort assigned and in code review - does that mean it has been done?  i'M LOOKING ON STAGING AND STILL BEHAVES AS PREVIOUSLY (oops).

**Comment by PaulBarrett79** [comment]
Performance work we did on this has been committed and deployed to sandbox since the last comment.

**Comment by aekhendry** [comment]
Much quicker, works fine for me on chrome. I'm considering this fixed.

**Comment by strets123** [comment]
Not currently fixed in the edit compound view
