### ISSUE TITLE
Safari custom field date custom field is broken

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#332]
When Using safari, the custom field function where you can edit a date is broken in single molecule view (an empty box appears). It works fine when using a similar function in search

**Comment by aekhendry** [comment]
cant test elsewhere as cannot submit compounds on safari!

**Comment by PaulBarrett79** [comment]
Needs verifying on Mac Safari

**Comment by nroam** [comment]
Custom field date is working fine. But fonts for year/month dropdown are ENORMOUS.

Tested on OS/X 10.10 + Safari

**Comment by PaulBarrett79** [comment]
I can probably shrink those with an override. It's the 3rd party library's fault though!

**Comment by PaulBarrett79** [comment]
Date custom field works correctly on Mac OS/X Safari and the font sizes are now less massive.
Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox - verified on the Mac test box over VNC

**Comment by PaulBarrett79** [comment]
Broken in one specific place - this is probably due to data formatting for that location

**Comment by strets123** [comment]
Moving back to backlog for further work

**Comment by KarenPorter** [comment]
@strets123 still outstanding?

**Comment by aekhendry** [comment]
Need to check this

**Comment by KarenPorter** [comment]
@aekhendry please update / test as appropriate

**Comment by aekhendry** [comment]
No longer an issue. Closing
