### ISSUE TITLE
Safari bug - cannot submit compounds to safari! The submission home page is missing links to compound submission page

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#333]
Safari bug - cannot submit compounds to safari! The submission home page is missing links to compound submission page.
Tested on Hub - windows

**Comment by PaulBarrett79** [comment]
Needs verifying on Mac Safari

**Comment by aekhendry** [comment]
could not verify on mac safari

**Comment by aekhendry** [comment]
Does this mean we should close the issue?

**Comment by aekhendry** [comment]
We are not supporting safari on Windows
