### ISSUE TITLE
Firefox slow

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#339]

**Comment by strets123** [comment]
Adding some performance tricks to improve this

**Comment by KarenPorter** [comment]
Some commentary?  Why is this now in the awaiting testing column - It's still very slow?

**Comment by strets123** [comment]
Please try again, looks fine on my firefox and has sped up due to elasticsearch indexing

**Comment by aekhendry** [comment]
I've tested and firefox is working fine. Staging, firefox / chrome
