### ISSUE TITLE
It is not clear to the user that they can't update a record. In the read-only project search results

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#342]
It is not clear to the user that they can't update a record. In the read-only project search results I can launch the single compound window, toggle edit mode, type an updated value in a field, and click Update Batch Custom Fields button - which then does nothing.  So the security is properly in place but the user is led to believe they have capability which they don't.  Can the toggle edit mode button be disabled based on user's permission level?

**Comment by KarenPorter** [comment]
What's the approach to resolution?

**Comment by KarenPorter** [comment]
Failed test - user can no longer edit the project data that they have edit-permissions on.

**Comment by strets123** [comment]
Fix deployed

**Comment by KarenPorter** [comment]
Passed test.  User with read-only access has greyed out add compounds button on project page and greyed out toggle edit mode button in compound detail page.
