### ISSUE TITLE
Web Page Up date

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#345]
The CBH website could use an overhaul to better advertise / display the applications  that are now accessible.

**Comment by KarenPorter** [comment]
Partly addressed within Release 1.0. To be tested, then determine if there are further changes needed (which could be a new issue to define detail). @aekhendry

**Comment by aekhendry** [comment]
I'm closing this as changes have been made. I'll open new issues based on those changes
