### ISSUE TITLE
Deploy Hub instance ChemReg changes to other instances

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#347]
The CDT in particular need to have their instance updated to the current version, webauth included. Last time we spoke we were going to integrate their project into the Hub instance.

**Comment by aekhendry** [comment]
Once this is done, there are a lot of issues in awaiting deployment from Sprint 15 that should be able to be closed.

**Comment by KarenPorter** [comment]
CDT are the first group to have Release 1.0 deployed.  Adam - are there other issues which can now be closed as your earlier comment @aekhendry?

**Comment by strets123** [comment]
CDT in progress
