### ISSUE TITLE
Search results page input fields are all over the place  - not left aligned, not centre aligned, lab

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#348]
Search results page input fields are all over the place  - not left aligned, not centre aligned, labels wrap, not right aligned.  Needs a basic tidy up.

Plus any tweaks to labels and positioning. - From and To aren't particularly meaningful, if there's one result it says '1 results"

**Comment by PaulBarrett79** [comment]
angular schema form ui select corrected, form now picks up all specified styling classes , and labels are now altered. Added to github

**Comment by PaulBarrett79** [comment]
Deploying to hub

**Comment by KarenPorter** [comment]
passed testing
