### ISSUE TITLE
Managing RHS of Waffle Board

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#356]
For debate:

Now that we have a process of deploying to sandbox for testing I think we can tweak the issue board processing.  When a card is moved out of "Awaiting Testing", it should be labeled as 'Failed QA / testing" and move to 'Under Investigation (minority of the time), or (most often) moved to 'Awaiting Deployment'. 

Developer then moves to 'Done' when it has been deployed to the live environment (Hub or Syd or wherever most applicable for specific users).  

This leaves the opportunity to match the move to Done with a release strategy and note-creation.

Thoughts? @aekhendry @PaulBarrett79 @strets123

**Comment by aekhendry** [comment]
I agree, I'm happy to go ahead and do this

**Comment by aekhendry** [comment]
This would mean however that we would have to account for deploying to other instances when time lining our sprint. Just something to keep in mind. It would certainly encourage us to deploy more regularly

**Comment by PaulBarrett79** [comment]
This would also help with tagged releases - I'm happy for this to be the process.
