### ISSUE TITLE
Search and sessions backend

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#357]
We have experienced some slowdown due to storing sessions in the database. Therefore we need to move to an in-memory session engine.

Redis is the obvious choice and works well... But we also need to store and search ephemeral data when people add a file and potentially do text search.

The best of breed approach is to use redis and elasticsearch.

The "keep the tools we use to a minimum" approach is to use MongoDB for everything apart from our chembl database.

This will keep lines of code and dependencies to a minimum. Chembl also use MondoDB for caching which we may need to at some point.

At this moment I am erriing towards MongoDB just to keep lines of code and dependencies down as discussed.

I have also looked at using Solr for the search part as Chembl are using this but it is not easy to use it with our flexible schemas.

Any thoughts @nroam @KarenPorter @PaulBarrett79 @ddamerell53

**Comment by strets123** [comment]
Having researched python mongoDB support a bit more it would seem there was a version change to the default library for accessing via python and a lot of things have not kept up - including session support. Essentially those who use Mongo for django tend to use very large libraries and run the whole system through mongodb.

Also the JSON schema support for mongo is shaky with the library being maintained by a single person.

Therefore,  back to my original plan of elasticsearch and redis sessions. We can also use redis for our message queue and cache so not an issue.

The dependencies being added will therefore be:

https://elasticsearch-py.readthedocs.org/en/master/ - officially supported
https://github.com/llonchj/django-tastypie-elasticsearch - small and relatively easy to maintain
https://github.com/martinrusev/django-redis-sessions  - active and many contributors

**Comment by ddamerell53** [comment]
Switching the session cache to Redis sounds like a great idea and should
solve the issue of slowness caused by your custom RDBMS solution.

Why do you need elasticsearch?

**Comment by strets123** [comment]
I attempted previously to run the custom field search in postgres and hstore. This mostly works but there are a few issues:
*  I have to use like with widcards to search lists which is slow
*  Building a dropdown of the available values for filtering is possible but does a table scan and requires custom SQL or python functions to sort the data whereas with ES aggregations the data comes out in an ideal format pre-sorted.
* I could potentially switch to postgres JSON fields but the python support is still being built
* I could also use gist indexes in postgres but again I think it will come out complicated.

For the new interface I am supporting search on data that has not yet been committed to the database - not structure search but tag search. I also want a standard search box across all fields.

Elasticsearch allows in-memory indexing of this data so I figure it is easiest to use elasticsearch. I know this sort of thing can be done in redis but it would mean building my own query language to an extent and each new type of query we "might" support would require extra code. This way I can serve all content from elasticsearch and speed everything up - for structure searches the results can be pushed to elasticsearch as a where in query.

For Elasticsearech I can use the query string or the json object sytax to query so I have a lot of choice

**Comment by strets123** [comment]
I should note that we also tried doing this sort of thing in HDF in our crunch project but this is not good for large text fields and unicode

**Comment by strets123** [comment]
Done
