### ISSUE TITLE
No error message if i have an invalid value in a custom field in single molecule entry.

For example

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#359]
No error message if i have an invalid value in a custom field in single molecule entry.

For example, I enter text into the%purity field.  It is highlighted in red and clearly marked as wrong.  i can however click the 'save molecule to ChemReg' button - it does nothing.  Should either be disabled whilst there's an invalid value in at least one entry field or show an error message on click 'Please fix the fields highlighted before proceeding'.

**Comment by aekhendry** [comment]
This can be left until users are actually updating there stuff in the system regularly

**Comment by aekhendry** [comment]
I think this is now good enough. closing
