### ISSUE TITLE
Better help/infobox support for custom fields

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#360]
As noted in #314, there needs to be better templated help support for custom fields.

**Comment by PaulBarrett79** [comment]
I've split the info box code into it's own repository, this may help with integrating it with angular-schema-form which is being used to generate the custom field form items.

**Comment by strets123** [comment]
The solution currently only covers the dropdown fields.

**Comment by KarenPorter** [comment]
@PaulBarrett79 please comment and move to backlog (with estimate?) or close.

**Comment by KarenPorter** [comment]
@PaulBarrett79 please comment and move to backlog (with estimate?) or close.
