### ISSUE TITLE
Amend 'Cancel' button text and functionality on Search page.  

Text should be 'Reset' and it should

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#361]
Amend 'Cancel' button text and functionality on Search page.  

Text should be 'Reset' and it should have the effect of clearing out all existing parameters and rerunning that search.

**Comment by PaulBarrett79** [comment]
Renamed button to Reset

**Comment by PaulBarrett79** [comment]
Reset button now clears the form and also clears previous search results. Pushed to github.

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox

**Comment by PaulBarrett79** [comment]
Why has this been returned?

**Comment by KarenPorter** [comment]
Failed testing:

default search all (when landing on page - 11410

Added filter (added-from 1/6/15) - now 521 results and <new action> results jump to the bottom of the page.

Click reset - now 11410 results and page goes to bottom

Now added from and to dates - 0 results (correctly) and not search bottom

Click Reset - same URL - 0 results

Remove 3 projects from list/ various other actions - basically cannot get Reset function to run, so I switch to Projects page and back to search

Searched for 3 specific UOX ids and got (correctly) 9 results
remove project from list and got (correctly) 0 results

Click reset - 0 results, no change to URL.

SUMMARY: Looks like reset works once only (major issue) and the behaviour of whether or not it scrolls to the bottom is not consistent (minor issue).

**Comment by KarenPorter** [comment]
@paulbarrett79 - now commented.

**Comment by PaulBarrett79** [comment]
Altered the code slightly so that the call to reload the page now reloads from an empty URL and clears the controller cache. So Reset now resets properly every time.

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox

**Comment by KarenPorter** [comment]
Passed testing
