### ISSUE TITLE
Info box directive should be in it's own repo

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#362]
The angular directive providing us with info-box help icons should be in its own repo so we can reliably use it in other modules and maybe even use it in pull requests for other modules...

**Comment by PaulBarrett79** [comment]
https://github.com/PaulBarrett79/angular-info-box

The repo itself is a work in progress but allows us to use it outside chemreg and even put it in pull requests to other repos.

pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox

**Comment by KarenPorter** [comment]
How do I test this Paul? @paulbarrett79

**Comment by PaulBarrett79** [comment]
Well... you can't. I thought that's why we had the "Dev Specific" tag. There is no noticeable difference in the front end - it's simply a change of mechanic in the back end.

The best you could do is verify that the boxes still work as expected - this will at least confirm that there are no regressions,

**Comment by aekhendry** [comment]
Done Paul's suggested tests, everything is working fine. Tested sandbox, chrome
