### ISSUE TITLE
failure to login on mac safari

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#364]
A user has been unable to login on mac safari.

The defect report was about the following message I would always receive when logging in. Even when accepting cookies from all websites and restarting my browser logging in failed. I didn’t really understand the help section. Could you let me know your thoughts on this? I am using a MacBook.

The email has been forwarded onto andy and paul

**Comment by aekhendry** [comment]
Have asked student to clear cookies and try again, I'm waiting on responce

**Comment by KarenPorter** [comment]
In which case, this should be 'Under Investigation' rather than 'Awaiting testing' surely Adam @aekhendry?

**Comment by aekhendry** [comment]
OK. Still waiting on his response.

**Comment by aekhendry** [comment]
He tried again and it worked without even having to clear cookies. Not sure what was happening there
