### ISSUE TITLE
Screen cast update following upload reenginerring

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#365]
Some of the screen cast are now irrelevant following Andy's changes and need updating

**Comment by KarenPorter** [comment]
Think this is done as part of Release 1.0 - placing in Awaiting Testing for now to confirm

**Comment by PaulBarrett79** [comment]
Moving to awaiting testing

**Comment by aekhendry** [comment]
I'm moving this back for these reasons, feel free to disagree:
1. The videos are currently too quick
2. When they loop over it is not immediately obvious that you are watching the same thing again.  I recommend a 2 second shot of a static 'title page' at the start of each video describing what your about to show.
In video 1 you submit a file and map one of the custom fields. From what I can see this custom field has not been mapped correctly when you open it up in single molecule view.

**Comment by PaulBarrett79** [comment]
I have to balance file size with amount we can show in one of these "videos". They are each 2.5 Mb and there are 3 of them - if I increase the time for each, I increase the load on the page.

I agree with adding a screen to the start which explains what each video is. I can then remove the overlay at the bottom.

**Comment by PaulBarrett79** [comment]
I've made a few changes.
1. Got rid of the carousel and replaced it with a library called Gifffer which allows gifs to be started and stopped. All gifs are now visible and guaranteed start from the beginning.
2. Added intros of 2 seconds to each gif. This also serves to label each gif now that they are all displayed side by side.

**Comment by PaulBarrett79** [comment]
Pushed to github

**Comment by aekhendry** [comment]
Tested, looks beautiful. Staging Chrome
