### ISSUE TITLE
Compound added on 16/6 has no value in 'added by' field - not sure how this is possible.

It does ha

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#367]
Compound added on 16/6 has no value in 'added by' field - not sure how this is possible.

It does have custom field values though, where other rows in the search results have 'added by' value filled but have no custom field values - could be coincidence.

Used this search: http://staging.chembiohub.ox.ac.uk/sandbox/#/search?project__project_key__in=adam-hendry,amy-varney-test-project,anthony-test,damerell-test-project,james-wickens-test-project,karen-malaria,marsden-test-project,martin-peeks-test-project,test-project&related_molregno__chembl__chembl_id__in=UOXCA60AQH,UOXKJ20WUU,UOXZC17EHC

**Comment by strets123** [comment]
Added by needs to be a proper profile link and therefore be rebuillt anyway

**Comment by KarenPorter** [comment]
Would be necessary to fix if we're to have ' added by' as a search parameter.

**Comment by strets123** [comment]
Fixed for new data and much of old data
