### ISSUE TITLE
project view page

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#368]
On Hub, there is a maximum amount of projects view able and I can't see projects added beyond this limit. This means I can't see whether people are using new projects I make for them, and so needs to be changed. 

This problem will probably only affect admin as most users wont see that many projects. Maybe the option of a drop down menu of projects could solve this problem

**Comment by strets123** [comment]
Need to add pagination after 1 line of projects

**Comment by strets123** [comment]
Also needed on user list page

**Comment by PaulBarrett79** [comment]
Added "show all" on project list page. You see the first 4. If there are more you can show them by clicking a button. Need to change the sort order so that the most recently modified projects are displayed first (probably the ones of most interest)

**Comment by PaulBarrett79** [comment]
Note: I didn't add "pagination" as that interferes with pagination on the list of compounds for that project.

**Comment by PaulBarrett79** [comment]
Need to remove the restriction of 20 projects and reverse the order of display (should be most recently modified first)

**Comment by PaulBarrett79** [comment]
Deployed to sandbox

**Comment by aekhendry** [comment]
Tested on Staging, chrome. Show all option works fine,  but as far as i can see maximum amount of project shown is still 20
