### ISSUE TITLE
Columns view is broken - adding new columns; cannot resize column widths Cannot 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#37]
Columns view is broken - adding new columns; cannot resize column widths Cannot copy from table

date recorded in spreadsheet: 24/03/2015

comments from spreadsheet:
PB - Where would you be copying this to? Excel? Well then export it to excel. The table provided by NG grid is not great, I will explore the config options to see what is customisable WRT these concerns.

**Comment by aekhendry** [comment]
fixed with new table view
