### ISSUE TITLE
Number of rows marked as to be saved is greater than number of records uploaded (in Chrome).  On san

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#371]
Number of rows marked as to be saved is greater than number of records uploaded (in Chrome).  On sandbox.

I uploaded a file with 118 records (all without structures), but table heading says there are 119 results to be saved.  Same file in Firefox shows the numbers matching.

**Comment by strets123** [comment]
Lots more testing on this

**Comment by KarenPorter** [comment]
Make sure I reproduce this before you spend lots of time on it - I raised this when I was feeling very crook so would want to check for user error.

**Comment by strets123** [comment]
OK please reproduce, marking as yellow as not reproduced

**Comment by KarenPorter** [comment]
Can't reproduce - mark as user error and done.  Will create a new one if I ever get similar issue.
