### ISSUE TITLE
Search results for a batch of compounds just uploaded doesn't show custom field values.  Fields are 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#375]
Search results for a batch of compounds just uploaded doesn't show custom field values.  Fields are blank, though downloading shows the input values to have been loaded to uncurated fields rather than the mapped ones specified in the upload process.In Chrome, on sandbox.

**Comment by KarenPorter** [comment]
Correction - in Firefox.  Not a new defect - I wasn't able to map the custom fields (raised as separate issues) so logical that they are not mapped!  User error.
