### ISSUE TITLE
Duplicate records not being found in input file / new compounds not being identified in Add Compound

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#377]
Duplicate records not being found in input file / new compounds not being identified in Add Compound page.  Sandbox / Firefox.

I uploaded a file containing compounds which had been previously added to the project (Karen Test).

There were 2 pairs of records which were identical (ie duplicates) and had previously been added, 2 additional records which had previously been added but having a different compound id (SMILES were the same), and 4 records which were new to that project.  Summary info said 0 unique compounds, 0 new to ChemReg, 0 overlaps and no duplicates.

**Comment by strets123** [comment]
Think this was the one where you didn't map the file...

**Comment by KarenPorter** [comment]
User error.
