### ISSUE TITLE
Info text for new to ChemReg could be misleading (especially where there are 0 new compounds.  I thi

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#378]
Info text for new to ChemReg could be misleading (especially where there are 0 new compounds.  I think 'This is the number of compounds in your input file which ChemReg has not previously registered.  We check all of the projects you have access to to get this total.  If the number is zero it means all of your compounds already exist in ChemReg'.  Any better?

**Comment by strets123** [comment]
Ensure that compounds are only new to project you are adding to

**Comment by strets123** [comment]
Next deploy - we have added different terminology and filtered to the specific project

**Comment by KarenPorter** [comment]
All text has been reviewed and altered as required.
