### ISSUE TITLE
Sometimes not possible to see the options in the drop down of actions for the last row in the list o

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#380]
Sometimes not possible to see the options in the drop down of actions for the last row in the list of compounds being processed.  Sometimes just one option visible (so can see 'new batch' but not 'ignore').

Depends on previous action but fairly easy to reproduce IMO - Chrome.

**Comment by KarenPorter** [comment]
Looks like it has been fixed - check with Paul

**Comment by KarenPorter** [comment]
Passed testing
