### ISSUE TITLE
Duplicate horizontal scroll bars in table in AddCompounds.

I have a screen shot. 
This is my URL ht

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#381]
Duplicate horizontal scroll bars in table in AddCompounds.

I have a screen shot. 
This is my URL http://staging.chembiohub.ox.ac.uk/sandbox/#/projects/karen-test/addcompounds/?mb_id=611&warningsFilter=warnings.duplicate&page=1&sorts=%5B%7B%22properties.action%22:%7B%22order%22:%22asc%22,%22missing%22:%22_last%22%7D%7D%5D

**Comment by KarenPorter** [comment]
Andy has fixed - ready to test

**Comment by KarenPorter** [comment]
can no longer reproduce - passed
