### ISSUE TITLE
Need to be able to map input field to new custom field.  OR direct user to their administrator "Have

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#382]
Need to be able to map input field to new custom field.  OR direct user to their administrator "Have fields that you can't map into this project?  Contact ..."

This is in the new Add Compound functionality -

**Comment by KarenPorter** [comment]
Add an (i) to the unmapped field to explain any unmapped values will be written anyway.  User should contact administrator if they want the field to be applied to the whole project.

**Comment by strets123** [comment]
OK reasonable first solution

**Comment by strets123** [comment]
Added info boxes

**Comment by aekhendry** [comment]
This has been done so I'm moving it across. Tested on staging, chrome
