### ISSUE TITLE
The compound table is quite long - so not obvious to get to horizontal scroll when I am moving along

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#384]
The compound table is quite long - so not obvious to get to horizontal scroll when I am moving along mapping the various fields.  I need to be in full screen to see headings and scroll bar at the same time.  In Firefox, new Add Compound page.

**Comment by KarenPorter** [comment]
I swear when I first did this there was no horizontal scroll bar at the top (it's been a long week) - since there is, that alleviates the problem quite considerably.  Not so obvious in Chrome as in Firefox.

**Comment by strets123** [comment]
Scrollbar styling is possible for chrome, do we want curly edges like firefox?

**Comment by PaulBarrett79** [comment]
The described issue is no longer an issue due to scrollbar at the top of the table.

Marking as awaiting testing

**Comment by KarenPorter** [comment]
tested- passed
