### ISSUE TITLE
Mapping the chemical structure field unmaps any other fields I've already assigned  - doesn't seem l

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#388]
Mapping the chemical structure field unmaps any other fields I've already assigned  - doesn't seem logical.

In the specific example, I map COMPOUND_ID to Compound ID, then map SMILES to SMILES for chemical structures - which unmaps the compound id.

Might be an issue if I'm mapping from left to right and don't notice when I get to the structural identifier column that the preceding fields are no longer mapped- especially if I then go straigh to save the records - I've failed to map a bunch of data potentially

**Comment by strets123** [comment]
Tests performed -
<ol>
<li> Mapping a struture column and unmapping </li>
<li> Mapping a struture column and mapping another column then unmapping structure </li>

</ol>

**Comment by KarenPorter** [comment]
tested - passed
