### ISSUE TITLE
I don't think 'SMILES for chemical structures' is as simple as we can get it.  Not obvious what it's

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#389]
I don't think 'SMILES for chemical structures' is as simple as we can get it.  Not obvious what it's doing, particularly when each project is likely to have a SMILES column.  Would 'Chemical structure (SMILES)' be clearer?

**Comment by KarenPorter** [comment]
Action Adam / Karen to suggest alternatives - maybe try out on users?

**Comment by strets123** [comment]
I am a big fan of tools that use abbreviations in a grammatically correct way. In this case the abbreviation SMILES means 

Simplified molecular-input line-entry system 

therefore whatever we come up with should make sense if read with the words that SMILES represents

**Comment by aekhendry** [comment]
I have looked at what a couple of other sites do regarding this:

ChEMBL: Please enter a list of SMILES separated by newlines
PubChem: Enter SMILES or InChi
ChemSpider: http://www.chemspider.com/Search.aspx

Grammatically correrct usage of SMILES is not consistent. The difficulty lies in whether you are referring to a list of SMILES's or a single SMILES. In my opinion, most people don't have a clue what SMILES stand for,  therefore I would stick with the ChEMBL example (which is similar to what we already have).
