### ISSUE TITLE
Column headers misaligned.  I have a long column header text which has now gone out of alignment wit

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#390]
Column headers misaligned.  I have a long column header text which has now gone out of alignment with the other header values.

**Comment by strets123** [comment]
Needs to be really long to break it - this kind of thing should be a yellow

**Comment by KarenPorter** [comment]
or limit the maximum column header?

**Comment by PaulBarrett79** [comment]
This may no longer be an issue since we have changed the column headers to fix IE functionality. Needs verification.

Test on staging/sandbox

**Comment by aekhendry** [comment]
Header now just cuts off if too long, but does not mess up the table as reported before. The only way to stop this is to restrict the length of the allowed column headings field
