### ISSUE TITLE
Excel download has a set of columns that don't immediately make sense.

A lot of the columns are one

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#391]
Excel download has a set of columns that don't immediately make sense.

A lot of the columns are ones that the user of a particular project wouldn't recognise.

**Comment by KarenPorter** [comment]
What is proposed here?  I thought in discussion that there wasn't much could be done about the redundant columns (for a particular result set)?

**Comment by strets123** [comment]
OK so a future task would be to allow selection and moving of columns in the table view and use the same exclusions in the export. For now what we could potentially do is show only curated fields on the first tab and then all fields on the second tab. Downgrading to yellow

**Comment by aekhendry** [comment]
Done
