### ISSUE TITLE
Info boxes are not relevant / complete.  There are a lot of placeholder texts rather than appropriat

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#393]
Info boxes are not relevant / complete.  There are a lot of placeholder texts rather than appropriate text.

**Comment by KarenPorter** [comment]
Action Karen or Adam - at least to devise the text - will save developers' time.

**Comment by KarenPorter** [comment]
Can you please confirm new info text in a file format for review @paulbarrett79?

**Comment by KarenPorter** [comment]
Can you please confirm new info text in a file format for review @paulbarrett79?

**Comment by aekhendry** [comment]
New text has been added.

**Comment by aekhendry** [comment]
New Text has been added. staging /chrome
