### ISSUE TITLE
Top menu can be made to re-appear so you get a double menu when using firefox

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#394]
It happens on top of the table view

**Comment by KarenPorter** [comment]
Can't reproduce so closing.

**Comment by KarenPorter** [comment]
was something specifically done to resolve this?

**Comment by strets123** [comment]
Yes the original menu now has a height of 0 so you dont see it but it still performs its function in making the widths calculate properly

**Comment by aekhendry** [comment]
I can't reproduce so I'm considering this fixed
