### ISSUE TITLE
1 week of ducmenting our code between the release for DTC and the release for Hub

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#396]

**Comment by KarenPorter** [comment]
I'm not sure in reviewing all of the items for 1.0 which are needed for DTC and which can be done afterwards - so when will the DTC version be ready (assuming that's a 0.9)?

**Comment by strets123** [comment]
It is not about that. The idea is that there will be zero functional changes in this week. The code will be up for DTC and maybe hub but it will be a silent soft launch for hub. Then you send the email 1 week later and also do the big fanfare at the symposium. Point is to allow time only for load testing and documentation. @ddamerell53 suggested this.

**Comment by strets123** [comment]
Will include refactoring away the camel case serialization across the app by searching the relevant fields

**Comment by aekhendry** [comment]
done
