### ISSUE TITLE
Nofication for filters that are not applied

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#397]
If the user has changed the filters using the dropdown menus or the serch interface then there should be a notification to remind them to apply the filter unless they click on apply filter inside the dropdown.

**Comment by KarenPorter** [comment]
Don't understand this one.  Is this in the list view? Which hasn't been applied to the search page yet.

**Comment by strets123** [comment]
By making chemreg reachable from assayreg search we will have instant search

**Comment by PaulBarrett79** [comment]
Same as custom field search

**Comment by PaulBarrett79** [comment]
Fixed by table top fix

**Comment by strets123** [comment]
Currently irrelevant due to way filters now work
