### ISSUE TITLE
dropdown inside table gets cut off at the bottom of the table

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#400]

**Comment by strets123** [comment]
Gap now added at the bottom of the table to allow dropdown to work. On mapping a field the table now rebuilds properly

**Comment by KarenPorter** [comment]
passed testing

**Comment by strets123** [comment]
Also now fixed for mapping dropdowns

**Comment by strets123** [comment]
Also now fixed for mapping dropdowns even if there is only one item added

**Comment by KarenPorter** [comment]
tested - passed
