### ISSUE TITLE
A slash is required after the url to log on to hub

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#401]

**Comment by strets123** [comment]
We need to change the server setup to evade this problem

**Comment by KarenPorter** [comment]
Is there a link check utility Adam or I could use to test to help check robustness across the app?


And on that subject - what is our 404? Are we going to add something nice?  https://www.youtube.com/watch?v=eHrcRqu_Es4  

something chem-error related?
http://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0CCgQtwIwAQ&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D8TPnns-5UxA&ei=zVSVVaeUMsrQ7Ab495X4Ag&usg=AFQjCNG11ZGRzR8ib2vPodZgZK0eSBcwMw&sig2=EYgqH0_6bPJSXjenNbbxeA

Or other ideas - http://www.creativebloq.com/web-design/best-404-pages-812505

Scope stretch - yellow if included at all (and if it is limited to an hour or two).

**Comment by strets123** [comment]
fixed for hub, integrated with general config script so will be rolled out as we deploy to other servers

**Comment by strets123** [comment]
Link checking doesn't work for javascript apps - you have to write end to end tests to simulate clicks

**Comment by aekhendry** [comment]
Tested on sandbox, chrome. This is now fixed, no slash is required. However if you now add a slash to the end of the URL, the page loses some formatting and looks strange. I don't think this is something that we need to fix, but felt I should alert you to it as it is odd behavior. Move to awaiting deployment if you wont do anything further.
