### ISSUE TITLE
Small defects (<1) suggested for 1.0 inclusion

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#403]
Add suggestions - typos, small function changes, labels.  Each in a new comment so they can be appraised and commented on separately.

**Comment by KarenPorter** [comment]
Add Compounds - drag and drop your files here - add an (i) to inform users what file types are acceptable.

**Comment by KarenPorter** [comment]
Warning message for invalid file type needs rewording.  Currently says:
File cannot be processed even though the format apears valid, if you have questions please contact the chembiohub team.

are there 2 errors?  for file extensions we can't process and for those we can but where the contents are uninterpretable?
Suggested: 1. We can process file extension types - .xls,

2. We can't process the contents of this file.  Take a look at our help section to see examples of what we can (and can't process).  If you still have an issue please contact the ChemBio Hub team for help.

**Comment by KarenPorter** [comment]
Compound details form has 2 headings for Custom Fields and for Uncurated fields - these are going to be meaningless to users I would suggest. Do we need to separate them in this way? could we just have a list of fields and values without losing anything if there are no headings?

**Comment by KarenPorter** [comment]
Add a Help entry  for 'why do some of the projects I can see have the 'add compounds' button greyed out?'

**Comment by strets123** [comment]
I have tidied up the invalid file messages as part of another ticket

**Comment by PaulBarrett79** [comment]
Added "Add Compounds - drag and drop your files here" info box

Also went through all the recently added info boxes and specified the message list to lookup from

**Comment by PaulBarrett79** [comment]
Added a Help entry  for 'why do some of the projects I can see have the 'add compounds' button greyed out?' - now located in a new FAQ section of the help page.

**Comment by PaulBarrett79** [comment]
Suggestion - might have to have navigation links at the top of the help page to alert people of the different sections

**Comment by KarenPorter** [comment]
Can I review the list of infobox texts please?  Easier than looking at each I in isolation.

**Comment by PaulBarrett79** [comment]
infobox tests currently under review

**Comment by strets123** [comment]
@karenporter where are we with this?
