### ISSUE TITLE
Bug with elasticsearch indexer

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#404]
Cant index

**Comment by strets123** [comment]
Now able to index

**Comment by aekhendry** [comment]
Not sure how to test this?

**Comment by PaulBarrett79** [comment]
Steps to test:

Go to admin panel
Click Projects
Select all projects
In the action dropdown (bottom left corner) select reindex all compounds

Result of this should eventually be a message top of the page informing the user

Very large datasets may need indexing via command line - speak to Paul or Andy about getting this done. May have to add a cron job to re-index periodically throughout the day.
