### ISSUE TITLE
chemdraw reaction

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#405]

**Comment by strets123** [comment]
Make it possible to upload and map reaction data

**Comment by strets123** [comment]
When talking about this point out that it would work even better if the data were displayed in a horizontal table under each compound (like the grid view) but we haven't got there yet.

The mapping options would be on the right - we could do a mockup if you like.

The second thing to discuss is that we have not yet added a facility for annotating an "upload".

This could be used as a place to store ELN data for a reaction.

You can set up a project with relevant fields and then be able to search for reactants in that project

**Comment by strets123** [comment]
Now working - will identify which are products and which are reactants properly

**Comment by KarenPorter** [comment]
tested - passed
