### ISSUE TITLE
In Addcompounds - SMILES in input file automaps to SMILES for chemical structures.

Trivial - this c

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#408]
In Addcompounds - SMILES in input file automaps to SMILES for chemical structures.

Trivial - this causes a lengthening of that column heading which then goes out of alignment with the other headings shown

More concerning - the first time I unmap then attempt to remap, the appropriate target field isn't available.  It appears in the list on the second attempt.

**Comment by strets123** [comment]
should now be fixed

**Comment by KarenPorter** [comment]
tested - passed
