### ISSUE TITLE
on occasions Add Compounds results table isn't long enough and no vertical scrolling.  In one exampl

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#412]
on occasions Add Compounds results table isn't long enough and no vertical scrolling.  In one example I filtered on duplicates and got >10 results, but what was visible in the table was ~7 (the first time).  Subsequent repeat of actions - table was long enough.

**Comment by strets123** [comment]
Please try to reproduce this, I believe now the images are always fetched before render which alleviates this issue.

**Comment by aekhendry** [comment]
I have seen this issue as well, although I can also not get it to repeat consistently. Not sure how to proceed?

**Comment by strets123** [comment]
This is quite rare now and not particularly urgent, we can fix by setting the images in the backend so lets do alongside the scarab work on backend plugins

**Comment by strets123** [comment]
Should now be fixed

**Comment by aekhendry** [comment]
Cannot replicate issue. MARKING AS FIXED
