### ISSUE TITLE
Info data column not  repopulated between mappings.  For example, I map a random column to SMILES an

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#413]
Info data column not  repopulated between mappings.  For example, I map a random column to SMILES and get relevant message (SMILES not processable), then I unmap but info message remains until I map another column to SMILES.

**Comment by strets123** [comment]
Now resetting mapping is done by unchecking the checkbox and this functionality works for that use case. I have removed the reset button as it is superfluous.

**Comment by KarenPorter** [comment]
Tested - passed
