### ISSUE TITLE
When I have a long compound detail form in view, scrolling via mouse wheel randomly alternates betwe

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#414]
When I have a long compound detail form in view, scrolling via mouse wheel randomly alternates between the compound form and the search page behind.

**Comment by strets123** [comment]
This is an incredibly picky bug. The alternation is not random - it scrolls the modal until it can scroll no more. Locking the background scroll is annoying IMHO.

**Comment by PaulBarrett79** [comment]
I agree with Andy here.

**Comment by aekhendry** [comment]
assigned to Karen as relevant

**Comment by KarenPorter** [comment]
I appreciate that is the behaviour it is supposed to have  - previously it was not consistent and would alternate onto scrolling the background page when it hadn't reached the top / bottom of the foreground page - then produced a growing vertical scroll bar below the foreground page.

It is now behaving consistently in my testing - which previously it was not.  Passed.
