### ISSUE TITLE
Selective reset sort does not work

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#415]

**Comment by strets123** [comment]
Fixed this

**Comment by aekhendry** [comment]
Not sure what you have fixed here, so can't test it

**Comment by KarenPorter** [comment]
@strets123 Can you respond please?

**Comment by strets123** [comment]
Should be possible to unsort a field by clicking    the link (checkbox gets removed)

**Comment by KarenPorter** [comment]
tested - passed
