### ISSUE TITLE
(i) info icon next to Paste your SMILES or Inchis here doesn't respond

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#417]
(i) info icon next to Paste your SMILES or Inchis here doesn't respond

**Comment by PaulBarrett79** [comment]
This was also a problem for a couple of other info buttons.

I traced the issue to the refactoring of info-box recently - the way the box was rendered had changed to be more dynamic but activating the popup was inconsistent. I put the initialisation code in a $timeout function so it is only initialised when the whole page had finished rendering

Committed to github, awaiting deployment to sandbox

**Comment by PaulBarrett79** [comment]
Deployed to sandbox

**Comment by KarenPorter** [comment]
tested - passed (subject to other outstanding issue to tidy up the message content).
