### ISSUE TITLE
new behaviour (bug).  Now shows 'No Compounds found' message on project list and search results list

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#420]
new behaviour (bug).  Now shows 'No Compounds found' message on project list and search results list - even though there are results shown as well.  Also, I'm pretty sure the search results page previously scrollled to the start of search results and now it stays at the top of the page.

**Comment by PaulBarrett79** [comment]
Removed this message for instances where results are present.

**Comment by PaulBarrett79** [comment]
Think the fix is still waiting for deployment

**Comment by PaulBarrett79** [comment]
Deployed to sandbox

**Comment by KarenPorter** [comment]
There's a second issue in the original text (should have been a separate issue in retrospect - my apologies).  Search results did scroll to start of results and now stays at teh top of the page, which I think is retrograde.

**Comment by KarenPorter** [comment]
superseded by integrating ChemReg into AssayReg effort
