### ISSUE TITLE
Bug.

Select an action drop down (no need to change the action), then select another action field an

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#421]
Bug.

Select an action drop down (no need to change the action), then select another action field and page jumps around - goes to the top then back down <near to> where you were previously . Chrome definitely, awaiting another deployment so I can check Firefox.

I'm making it medium - not a functional thing but would be a poorly perceived thing.

**Comment by strets123** [comment]
This is now fixed for these particular dropdowns but not fixed for the mapping dropdowns

**Comment by aekhendry** [comment]
Karen is referring to batch upload here

**Comment by aekhendry** [comment]
Tested on staging / chrome. Works as intended so considered fixed
