### ISSUE TITLE
Add an information point on search by tags

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#422]

**Comment by aekhendry** [comment]
We need to let users know that searching by multiple tags currently operates as an 'or' search function. I'm pretty sure most people will expect it to be 'and'. This is fine for now but some clarity would help here.

**Comment by PaulBarrett79** [comment]
Agreed, I've added a mechanism to allow using our info-box inside ui-select so I'll set that up.

**Comment by PaulBarrett79** [comment]
Message configured within the schema form setup.

Committed to github, waiting deployment to sandbox

**Comment by PaulBarrett79** [comment]
Deployed to sandbox

**Comment by KarenPorter** [comment]
Pinging this back to under investigation status - the text will need to be changed in line with revised functionality.

**Comment by PaulBarrett79** [comment]
Changed the wording to demonstrate OR between the same custom field, with AND across different custom fields.

**Comment by PaulBarrett79** [comment]
Waiting to be pushed to github until inventory work can be verified and tested

**Comment by PaulBarrett79** [comment]
Waiting deployment to sandbox
