### ISSUE TITLE
Adding custom fields containing single quotes creates problems when searching

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#423]
Custom tags containing single quotes creates problems when used as a search parameter. Once you search for a tag (e.g. [my'tag]) After clicking search the tag is split in two (e.g. [my] [tag]). this obviously yields no search results. Single quotes are sure to crop up from time to time, we will need to address this

**Comment by PaulBarrett79** [comment]
These should definitely be escaped

**Comment by strets123** [comment]
There are a number of special cases with this tag search. Longer strings
will also currently fail but should arguably be dealt with differently
anyway. Apostrophes may work OK when we switch to elastic search for this.

**Comment by KarenPorter** [comment]
@strets123 still outstanding now we have elasticsearch?

**Comment by strets123** [comment]
Now fixed due to new whitespaceanalyser

**Comment by KarenPorter** [comment]
tested and passed
