### ISSUE TITLE
Auto mapping of fields during file submission bug

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#424]
Automapping appears to work when submitting on staging. Column headings are green and are correct. However when you submit the file all data is registered as uncatagorised. Tested in two projects (tag field test / admin) on Chrome.

**Comment by strets123** [comment]
should now be fixed. Also, the SMILES field no longer dissapears randomly

**Comment by KarenPorter** [comment]
Not behaving as expected.  When I have any fully matching column headings (other than SMILES) I get the file error message- change headings so that they don't automap and I can then manually map them successfully.

**Comment by strets123** [comment]
Now fixed, small typo in code

**Comment by aekhendry** [comment]
Tested on staging, chrome
