### ISSUE TITLE
Start over button on file upload is annoying

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#425]
A small thing. If working quickly the start over button during file upload on staging is frustrating. It is exactly where you would expect the submit button to be and a few times i have clicked it before i could stop myself. I recommend swapping the positions of the start over and submit button, and making the submit button green.

**Comment by PaulBarrett79** [comment]
Agreed.
I've swapped the positions and changed the Save button to success class (green)

**Comment by PaulBarrett79** [comment]
Committed to github, awaiting deployment to staging

**Comment by PaulBarrett79** [comment]
Deployed to sandbox

**Comment by KarenPorter** [comment]
tested - passed.
