### ISSUE TITLE
When I upload 10 compounds, the first 3 processed have a MW with umpteen decimal places (about 10?),

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#426]
When I upload 10 compounds, the first 3 processed have a MW with umpteen decimal places (about 10?), the next are all to 2 decimal places.  There are duplicates within the compound list and they all overlap with compounds already in the project.

The next time I process the same 10 compounds, they all have only 2 decimal places, so this is a first-time process bug.

**Comment by PaulBarrett79** [comment]
I've altered the handsontable to force molecular weight to be displayed to 2 decimal places. Pushed to github.

**Comment by aekhendry** [comment]
Fixed. Staging / chrome
