### ISSUE TITLE
Can add duplicate custom field values for search - then it breaks the ability to add any more tags.


### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#429]
Can add duplicate custom field values for search - then it breaks the ability to add any more tags.

In Firefox.
To replicate -

TEST 1:   Add tag Amount 100g.  Add tag Amount 100ML. Add tag Amount 100g. Try to add tag Amount 100 tablets - doesn't show.  Delete second tag Amount100g - now tag Amount 100 tablets shows up.

TEST 2: Add tag Amount 100g.  Add tag Amount 100ML. Add tag Amount 100g. Try to add tag Amount 100 tablets - doesn't show.  Run search - it searches for 4 criteria (100g, 100ML, 100g, 100 tablets), so brings back the right results.

Plus, the custom field values are cleared out when I run this search.

**Comment by aekhendry** [comment]
closing
