### ISSUE TITLE
Correct case for InChI app-wide

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#430]
InChI has inconsistent casing - across the site

**Comment by PaulBarrett79** [comment]
All instances corrected within the code and system messages. If there are any more, these are very likely due to instance specific configs.

Pushed to github

**Comment by aekhendry** [comment]
'Paste your SMILES or Standard InChIs here' incorrect capilatisation of InChI in associated information box. on file upload page

**Comment by aekhendry** [comment]
fixed, staging, chrome
