### ISSUE TITLE
.XML export exporting all possible custom fields

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#432]
.XML export exporting all possible custom fields. This needs to export only custom fields containing data.

**Comment by KarenPorter** [comment]
@aekhendry have you tested this recently?  I think the way of processing exports has changed so we no longer have all poss custom fields in the file?  Can you please confirm if this is still an issue and annotate it appropriately - placing in backlog if it still needs action.

**Comment by aekhendry** [comment]
Closing as other cards cover relevant information
