### ISSUE TITLE
Adding new tag values doesn't work as it should.

In project Researcher profiles, I used a schema wi

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#434]
Adding new tag values doesn't work as it should.

In project Researcher profiles, I used a schema with 4 custom fields defined as "tags field allowing create".

I edited a researcher entry and added 4 new tag values.  I could see these associated with the entry in the compound detail window in view mode.  When I toggled to edit, they were not in the relevant field.  

I then logged out and back in - the researcher entry no longer had these values associated with it in view mode.  In edit mode - these values were now available to select and associate with the record.

**Comment by strets123** [comment]
Yes, understood, this dropdown is not as "live" as it should be in a number of ways.

**Comment by aekhendry** [comment]
no longer relevant
