### ISSUE TITLE
one situation: Show only blanks/ show only non-blanks filter doesn't affect search results shown whe

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#437]
one situation: Show only blanks/ show only non-blanks filter doesn't affect search results shown when applied to Custom identifier field - all records are still shown.

another situation: Show only blanks filter successfully applied, then switch to show only non-blanks - that is ignored.  Also, no means of taking that filter off. 
There is generally a lack of robustness around this functionality.

**Comment by strets123** [comment]
Now fixed - filters are toggled by clicking them. There is also an "apply" button

**Comment by aekhendry** [comment]
Fixed. Tested on staging, chrome
