### ISSUE TITLE
Functional Requirement - Inv.
User can mark a compound as deleted. 
Delete is validated in some way 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#440]
Functional Requirement - Inv.
User can mark a compound as deleted. 
Delete is validated in some way (allowing user to change her mind for at least a period of time).
Deleted compounds are not visible in search results of inventory project list.
Admin can remove delete indicator from a compound on request.

**Comment by KarenPorter** [comment]
Will be easier following refactoring of compound data

**Comment by strets123** [comment]
Now working, the toggle archive buttons are in the filter dropdown on the restore or archive column.

**Comment by strets123** [comment]
Item does not disapear immediately but the button changes as a form of confirmation

**Comment by KarenPorter** [comment]
Changed in delivery compared to spec - improved approach delivered.

User marks as compound(s) as deleted. Deleted compounds are not shown in search results - UNTIL user selects edit mode and selects appropriate filter on Archive/Restore column, where they can restore a previously archived compound.

No need for Admin-specific action but deliberately made a bit obscure to users don't inadvertently archive an item.

Passed testing.

See Item #491 for the suggested additional requirement to add FAQ information to assist the user with this functionality.
