### ISSUE TITLE
Functional Requirement - Inv.
User can edit cells in results table - in particular update multiple r

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#441]
Functional Requirement - Inv.
User can edit cells in results table - in particular update multiple records with revised keyword values. May be done by changing one specific cell (via modal compound page) and then allowing that to be copied or dragged over adjoining cells.

**Comment by PaulBarrett79** [comment]
User must click "Edit Mode" before editing can start.
User has to click "Save" or "Clear/Reset" in order to exit edit mode, mirroring single compound modal edit functionality.
Left-drag/right-drag only allowed for blanking cells.
Down-drag allowed for filling in blanks or values.

**Comment by PaulBarrett79** [comment]
This was dependent on scrolling issues being resolved - scroll plugin was blocking edits from taking place. We have decided on a workaround for this.

**Comment by PaulBarrett79** [comment]
Workaround of non-scrolling editable table now pushed to Github (thanks Andy)

A number of valuable lessons learned from this issue.
1) Extremely difficult / impossible to use anything other than handsontable's own scrolling if any custom code has been applied
2) We will have to revisit how the filters are applied to the header - having a custom div which is used as the header causes a lot of issues and is difficult to adapt or code for
3) Sometimes - just sometimes - you have to cut your losses to get things done.

**Comment by strets123** [comment]
Drag down is now supported. I have removed unnecessary fields too.

**Comment by strets123** [comment]
Still working on undo and permissions check

**Comment by KarenPorter** [comment]
1  Weird treatment of dates in pop up window

2 Can't drag list fields / multi select fields

**Comment by PaulBarrett79** [comment]
Point 1 - popup in a popup. I'll change the min height of the field if it is a date field.

**Comment by PaulBarrett79** [comment]
Increased the min height for the edit popup for all edits. Ideally I need to find a way for the cell to trigger the date selector popup directly - very difficult given the schemaform system we are using, whereby the field could be any data type until the modal is rendered.

**Comment by PaulBarrett79** [comment]
Pushed to github

**Comment by strets123** [comment]
Please test edit and undo

Project permissions to be completed
