### ISSUE TITLE
Functional Requirement - Inv.
Administrator can label projects as compound registration or inventory

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#442]
Functional Requirement - Inv.
Administrator can label projects as compound registration or inventory management project type (with scope to add other project types in future)

Based on project type, default fields are added - specifically compound reg has structure field, which inv management does not.

Based on project type, labels and messages are displayed as appropriate

**Comment by PaulBarrett79** [comment]
I have implemented a Project Type. Project Types can be created through the admin interface and assigned to Projects.

There still needs to be a visual cue as to which type is which on project list.

Also we need to determine which elements should be controlled by Project Type - which fields should be hidden, which options to show etc.

**Comment by KarenPorter** [comment]
Outstanding:  visual indicators, 
need to define what in a project type is configurable. 
Paul - organise meeting where we fully define project type configuration requirements.

**Comment by PaulBarrett79** [comment]
This has now been clarified.

**Comment by PaulBarrett79** [comment]
Now going through the system to see where references to compounds are and making them either "compound or item" where the user is not within a project specific are (help, user areas etc) or display the correct term if within a project where it can be ascertained. (project list, addition of records etc)

**Comment by PaulBarrett79** [comment]
Hiding items:
Structure column on table where project is a non-chemical project;
Structure image on single molecule (item) view;
Structure specific rows in validation section when records are being added;

**Comment by strets123** [comment]
Need to get rid of the compound stats from the add items page

**Comment by strets123** [comment]
On add compounds page need to remove the chemical stats

**Comment by PaulBarrett79** [comment]
Chemical stats on add compounds are now conditional based up a project being configured to show compounds.

**Comment by PaulBarrett79** [comment]
Pushed to github

**Comment by KarenPorter** [comment]
1.  Need to hide Info, structure and InChI key columns for Inventory project type.

2. The number not processed and the info icon associated with that are very far apart now.  Maybe make the data summary box narrower (or move number not processed right or (i) left)?

**Comment by PaulBarrett79** [comment]
Both of these addressed. Appropriate columns hidden in inventory mode, and single summary box for inventory mode is narrower and more central.

Pushed to github

**Comment by strets123** [comment]
Fixed the last couple of fields when edit mode not ion for mol weight
