### ISSUE TITLE
Functional Requirement - Inv, Reg and Assay
User can use a custom field to hold a link reference to 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#444]
Functional Requirement - Inv, Reg and Assay
User can use a custom field to hold a link reference to relevant data (eg Mass Spec).

**Comment by PaulBarrett79** [comment]
link to FIB - for sharing and internal referencing. This is more compounds management. Linking to chemistry portal/sharepoint type thing.

**Comment by strets123** [comment]
Now have update single working with a dynamic template for the modal.

Please help me:

1. Get the edit pencil button in the top corner
1. Any consistency errors in the modal
1. Make a new scrollbar outside of the directive
1. Make the search and project list pages full width for the table

**Comment by strets123** [comment]
Links now work but only for local files

**Comment by KarenPorter** [comment]
Same comment to @nroam as #445 and request for direction for this sprint.

**Comment by KarenPorter** [comment]
Passed testing
