### ISSUE TITLE
Functional Requirement - Inv, Reg and Assay
User can add an image to a custom field so that it is vi

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#445]
Functional Requirement - Inv, Reg and Assay
User can add an image to a custom field so that it is visible within the project list view, compound detail and search results.

**Comment by strets123** [comment]
The approach to this will determine timings.

**Comment by strets123** [comment]
Best to do it one group at a time and get it working with their server links to images.

**Comment by strets123** [comment]
A good case study would be Tracy Marr perhaps?

**Comment by PaulBarrett79** [comment]
Will this be editable? i.e. what will the interface look like to replace an image when editing?

**Comment by strets123** [comment]
In the first instance this would be for images stored on another server and accesible via a server link i.e. s:\images/myimage.jpg

**Comment by strets123** [comment]
Only possible for remotely hosted files

**Comment by strets123** [comment]
@nroam Any comments or alternative options?

**Comment by nroam** [comment]
Suggest we host for now, with a fairly stringent filesize cap (100k?).  Expectation is that the Uni will sort out DropBox soon at the very least. Agree that dept-based systems are too heterogeneous and politcal to be used.

**Comment by KarenPorter** [comment]
In the meantime, this has been delivered into test as url link, which works for now.  Question for Brian @nroam - are you happy to sign off functionality as delivered and for us to make this change in a subsequent sprint?  Specifically when we have a user group who will benefit.

**Comment by PaulBarrett79** [comment]
We could set up a job to optimise existing images without reducing quality using grunt/imagemin as part of the deployment process?

**Comment by KarenPorter** [comment]
Passed testing as-is.  Will raise a new functional requirement for future release.
