### ISSUE TITLE
Functional Requirement - Inv, Reg and Assay.
User can rearrange results columns.

Requirement to be 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#446]
Functional Requirement - Inv, Reg and Assay.
User can rearrange results columns.

Requirement to be fully informed by technical feasibility/ease but could be a remembered order applied for that user each time they interact within a given project - between projects?  Also needs user feedback as to need for flexibility versus persistence of setting.

**Comment by strets123** [comment]
Not fixing in this sprint as it is possible to prioritise columns in the admin and this task is better done as part of a more comprehensive overhaul. Also, too difficult with the current way the code works, will take too long and not be smart to do now.

**Comment by KarenPorter** [comment]
Accepted
