### ISSUE TITLE
Clicking in the Custom Field values box on search, but not typing anything - what is presented as ca

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#448]
Clicking in the Custom Field values box on search, but not typing anything - what is presented as candidate autocomplete values starts with Project and Upload values which shouldn't be in the list.

**Comment by strets123** [comment]
This should now be fixed

**Comment by aekhendry** [comment]
Tested on staging, Chrome. Could not replicate described behavior so considered as fixed
