### ISSUE TITLE
Bug with upload / automap.

If I upload a 2 column file - one labelled SMILES and one labelled XXXX,

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#450]
Bug with upload / automap.

If I upload a 2 column file - one labelled SMILES and one labelled XXXX, the SMILES column automaps to the appropriate field and I can manually map the other column to Compound ID. If I upload the same file but label the second column as Compound ID - I get the error message and the file is not processed.

Secondarily the error message contains 2 typos - should be "appears" and "ChemBio Hub"

**Comment by strets123** [comment]
Now fixed and the messages edited

**Comment by aekhendry** [comment]
Not fixed, same behavior observed

**Comment by strets123** [comment]
OK, now fixed

**Comment by aekhendry** [comment]
Fixed, tested on staging as described above
