### ISSUE TITLE
Now that the project list is constrained to 4 projects, I select a different project to see those re

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#452]
Now that the project list is constrained to 4 projects, I select a different project to see those results and now want to add more compounds to it.  However there's no way that I can see to do that.  (I know that I can show more projects and then select the "add compound" button but as an inexperienced user I'd probably have forgotten that).  So I think the fix is to  add another 'Add compound' button to the project detail area - in the project header banner for instance (after the project name)?

**Comment by strets123** [comment]
Now added add button

**Comment by aekhendry** [comment]
Tested and works, sandbox, chrome
