### ISSUE TITLE
Zoom on browser generates strange behavior in tables

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#453]
If I zoom out on chrome (ctrl + scroll), the table reorders so that more than one custom field is displayed per column. I.e. one on top of another. It takes the last custom field and puts it underneath the first.

**Comment by strets123** [comment]
Please re-test this with the new table header

**Comment by aekhendry** [comment]
Fixed for new table header, tagnew, chrome
