### ISSUE TITLE
table grid disappears on the RHS when there are lots of custom fields in the search results view.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#456]
table grid disappears on the RHS when there are lots of custom fields in the search results view.

**Comment by strets123** [comment]
Initial fix will be to make the project list a single project in the search page

**Comment by aekhendry** [comment]
Whilst there are no blank areas, the table is still broken. I upload data and it is not being presented in the table. I notice the table is not in line with the above header text. i dont know if this is related but it gives the appearence of not having loaded properly and being broken
