### ISSUE TITLE
Default behaviour of selecting all projects in search results causes issues in managing all of the c

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#457]
Default behaviour of selecting all projects in search results causes issues in managing all of the custom field columns (and other unwanted behaviour).

Therefore make the default that no projects are selected (or one if there is only one that the user has access to) - assume user will typically select one in which to search.  Maybe produce warning if user selects multiple and there are therefore loads of custom fields to display (nice to have).

**Comment by aekhendry** [comment]
This has been temporarily addressed by allowing to search through only one project at a time.
