### ISSUE TITLE
Avoid reload of search page

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#459]

**Comment by strets123** [comment]
Search form reloads when searching for something which is quite distracting

**Comment by strets123** [comment]
Re-factoring  required - tasks are:

* Build a new search controller
* Ensure that scope is inherited 
* Ensure that page reloads happen at the bottom of the page
* Also look at tidying up the table headers so they don't always reload

**Comment by aekhendry** [comment]
No longer relevant / Done
