### ISSUE TITLE
Discrepancies between what is shown in compound grid on Project page and what is downloaded:

For Te

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#462]
Discrepancies between what is shown in compound grid on Project page and what is downloaded:

For Test Project Delete:
In grid but not in Excel - Date Added, Project, structure
In Excel but not in grid - std InChI, aLogP, SMILES, Known drug, med chem friendly, mol formula

Also, Batch ID is in both but doesn't match.

**Comment by aekhendry** [comment]
done
