### ISSUE TITLE
Updates needed on Help page.

The sample searches are mostly instance / user specific.  I'm not sure

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#465]
Updates needed on Help page.

The sample searches are mostly instance / user specific.  I'm not sure what examples we could provide that would be generically useful - should we remove this?

The text for file submission needs updating (assumes previous mapping approach.  For Excel, I suggest:

 ChemReg can accept Excel .XLSX files (newer Office versions)
Column headers must be in the top row, and all data must be organised in the relevant columns underneath. Figures and/or images cannot currently be accepted, although URLs are acceptable.

On submission of an Excel file, a column may contain structural information (e.g. SMILES). If there is a column labelled as SMILES this will be automatically mapped, otherwise the user will need to select the appropriate column name.  This will ensure a compound structure is drawn in the system following submission.

An Excel file may be submitted containing no structural information. In this case, the application will assign each record with a unique ID as normal but with no structure information.

**Comment by aekhendry** [comment]
done
