### ISSUE TITLE
Number of decimal points on some MW custom field entries was very long.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#468]
Number of decimal points on some MW custom field entries was very long.

**Comment by aekhendry** [comment]
entires include - UOXKF54MCG
UOXVD13YQF

**Comment by KarenPorter** [comment]
Could be coincidence - or might be relevant but the ones with more digits after the dec point are towards the bottom of each page (10/page).

**Comment by aekhendry** [comment]
fixed
