### ISSUE TITLE
Overlap/duplicate and new to chemreg indicators need clarification

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#470]
Overlap/duplicate and new to chemreg indicators need clarification. Currently they are difficult to understand which means what, particularly when distinguishing between overlapping compounds and duplicate compounds.

**Comment by PaulBarrett79** [comment]
Does the fix in #664 adequately deal with this?

**Comment by PaulBarrett79** [comment]
pushed to github

**Comment by aekhendry** [comment]
Yes 664 deals with this. As it's live on hub, marking as done
