### ISSUE TITLE
Browser selection affecting ability to upload compounds

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#476]
Student submitted file to IE and file could been seen in system, but the table and information below did not appear, nothing happened. Summerised below -

Uploading structure worked on IE version 11
Didn't work on Mozilla 39.0

In a separate issue, student submitted SD file to chrome (windows 7) and experienced similar behavior. Worked when uploaded to internet explorer. 

This behavior is weird, I will test on it further soon and update.

**Comment by strets123** [comment]
Please re test

**Comment by aekhendry** [comment]
I have recently done browser testing and not replicated any of these issues. Closing
