### ISSUE TITLE
Assay Reg Ideas (andy)

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#480]

**Comment by strets123** [comment]
* A set of template buttons at the top of the custom field config page in admin
* Unit and range
* Validation on upload

**Comment by strets123** [comment]
There could be 3 index views of the data allowing it to be viewed in different ways,,,

1. The current view by batch with bioactivities listed in a single cell
1. A view of the standardised bioactivities and other experiement data with compound and batch data alongside row by row
1. A view which builds a field per bioactivity on each compound which would allow comparision - the user would select a list of assays and end up with a comparision matrix

**Comment by strets123** [comment]
Backend database for results reg could potentially be the same as for chemreg

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by PaulBarrett79** [comment]
AssayReg follows this pattern - done
