### ISSUE TITLE
Search page rework.

Search page needs some redevelopment:

add ability to select multiple projects


### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#481]
Search page rework.

Search page needs some redevelopment:

add ability to select multiple projects

move structural search type to underneath chemdoodle widget (minimally)
OR hide ChemDoodle (or separate tab?) unless user selects a new 'Search by substructure' option which makes draw window visible (in pop-up?)

add 'added by' search option
add 'project type' search option
add 'download template' option (documented in another issue)
add grey banner (above results table) cf project list page - can be used to list projects included in search
add 'save search' option

**Comment by aekhendry** [comment]
done
