### ISSUE TITLE
just my opinion - edit mode signalling could be more obvious in search results page.  I appreciate t

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#489]
just my opinion - edit mode signalling could be more obvious in search results page.  I appreciate the button is greyed, and each cell has a pencil icon but my inclination would be to perhaps make the button a different colour or/and add text to hammer home the message.

**Comment by aekhendry** [comment]
I believe this is still relevant

**Comment by PaulBarrett79** [comment]
This was remarked upon by Katherine England when I visited her so there is justification in making it more obvious

**Comment by strets123** [comment]
OK, we should work on this. Specifically what we could do is make the table look less like handsontable when not in edit mode, also for everything apart from lists you should just edit in the cell perhaps but would need to integrate the handsontable editor functions for dropdowns etc. Could be worthwhile to make it feel really finished.

**Comment by KarenPorter** [comment]
This is now better.  Closing.
