### ISSUE TITLE
Add an FAQ for archiving and restoring items / compounds.

Suggest:

Can I archive items in my proje

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#491]
Add an FAQ for archiving and restoring items / compounds.

Suggest:

Can I archive items in my project which are no longer relevant or were added in error?

Yes.  To archive an item or items, on the Search Results page, select the Edit button at the top of the results grid.  The first column will now contain an Archive/Restore button. Click this on any items you wish to archive.

Can I restore previously archived items in my project?

Yes.  To restore an item or items, on the Search Results page, select the Edit button at the top of the results grid.  Now select the filter option in the first column header to "show only archived".  Click on any items you wish to restore.

**Comment by aekhendry** [comment]
Can be added to my help page suggests I've just sent to Paul

**Comment by KarenPorter** [comment]
@aekhendry still outstanding?

**Comment by aekhendry** [comment]
covered in another card, closing
