### ISSUE TITLE
Edit mode must only be selectable if only one project is selected

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#493]

**Comment by strets123** [comment]
There was an issue whereby data could be copied between projects to fields that do not exist in another project

**Comment by KarenPorter** [comment]
Is this perhaps not deployed?  Not seeing edit functionality constrained as described.

**Comment by KarenPorter** [comment]
Think this was a deployment issue - behaviour has now changed.

Passed the major functional test.

One issue remaining - the (i) which appears (I  assume to explain why edit is not selectable) is not clickable - because the button is not selectable.

**Comment by strets123** [comment]
The (i) issue was browser specific for Mozilla.


Changed it to have a general (I) about edit mode and a title attribute on the disabled button saying why it is disabled.

Should now also redirect if you specify editMode in the URL when it is not allowed.

In addition I have added the permissions check

**Comment by KarenPorter** [comment]
Passed testing.

**Comment by KarenPorter** [comment]
@strets123  -what was the effort needed for this task?
