### ISSUE TITLE
Functional requirement: in advance of a University-provided Dropbox utility, provide storage for fil

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#494]
Functional requirement: in advance of a University-provided Dropbox utility, provide storage for files (including images) associated with a project.  Will need constraints on individual file size and maximum storage provision per project in order to be manageable.  Actual figures for each tbd.

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
In progress via other issues
