### ISSUE TITLE
List of features for the new assay reg api

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#497]
===DataPoint API===

- [ ]  Whether each field for each row is editable for each value in the response based on the user and projects at this time (lists of booleans per field)
- [ ] The schema  in schemafrom format (better to update it each time data is requested). The autocomplete function names could be included.
- [ ] The schema in handsontable format
- [ ] The last updated date- for use when updating data
- [ ] The filter and sort forms as JSON (Make a modal for this with an accordian per field that opens up based on the field you click on in the header - that way we can simplify and have one form only)

- [ ] The applied filters and sorts would remain stored in the URL

This information should be split into separate "views" which are defined at the project type level.
Assume that each "view" may or may not have its own controller. By using dynamic controller names and controllareAs, it is possible to use class based inheritance with controllers.

The project API should provide:

- [ ] endpoints for the datapoint views that are available for that project
- [ ] Name of the listview controller, template and controllerAs for each of those possible listviews
- [ ] Eventually name of the add compounds controller and template

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by PaulBarrett79** [comment]
Requirements here deplrecated or implemented - marking as done
