### ISSUE TITLE
Date field

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#504]
Can we remove the time seen when data is imputed into a date field? Even if this was working I don't see much of a use for it.

**Comment by PaulBarrett79** [comment]
Is this still an issue? Marking as ready for testing by way of a review

**Comment by aekhendry** [comment]
Yes still an issue. The time stamp does not work, reports as 00:00:00 whenever you enter data. Can this either be removed or fixed?

**Comment by KarenPorter** [comment]
@PaulBarrett79

**Comment by PaulBarrett79** [comment]
@aekhendry can you please give steps to reproduce this? I can't see any date locations that do this.

**Comment by aekhendry** [comment]
Fixed, closing. chrome hub
