### ISSUE TITLE
Project type logic needs tightening up for a read-only project.  

I have a read-only Chemical proje

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#508]
Project type logic needs tightening up for a read-only project.  

I have a read-only Chemical project which has greyed out buttons for add compound and add compounds - this should be just the add compounds button (other is not valid for a chemical project).  Similarly at the top of the project list table.

Needs to be checked for what happens with a read-only inventory project type.

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by PaulBarrett79** [comment]
Addition links are dependent on the user being an editor. Marking as ready for testing for review

**Comment by KarenPorter** [comment]
Signed off.  Behaviour has now changed following refactoring of project list page
