### ISSUE TITLE
UI changes for assayreg

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#510]

**Comment by strets123** [comment]
[ ] - Make overview page into a tree of fieldsets
[ ] - Create data list page showing data in each of its levels separately (with hightlighted fields)
[ ] -

**Comment by strets123** [comment]
In order to add permissions to the existing objects that are on the staging/test server, run the code that is in environment.py in method after_all - add permissions and reindex elasticsearch

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
Do this all via ChemiReg
