### ISSUE TITLE
Search should be able to pull out all records associated with the search term

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#512]
Feedback from Tom Merritt -

Search should be able to pull out all records associated with the search term, rather then forcing the user to pick one from the list of auto complete options.

For example, if you type 'sds' into the wood project, you get 7 autocompleted options. you must select one and then click search. tom would prefer to be able to pull out all of the auto complete options, i.e. rather then pick one to search for, press enter and pull out all possible options.

**Comment by strets123** [comment]
This behaviour should now work for assayreg

**Comment by KarenPorter** [comment]
tested and passed
