### ISSUE TITLE
Branding conversation

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#513]
We need to discuss how we refer to 'the system' as a whole. We now have a package of three apps (chemreg, assayreg and inventory manager). are we referring to these as 'the ChemBio Hub', or do we have another name in mind? We need to do this soon as Brian will need this to take on the road.

**Comment by KarenPorter** [comment]
Initial workshop on branding and web-site revamp requirements.  The effort to make the web-site changes will be captured in a separate issue.
