### ISSUE TITLE
Create further developer documentation and host on readthedocs

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#515]
Even though most classes are documented this is not hosted anywhere and there are not enough documentation pages.

Docs should cover:

*  Installation
*  Data Model
*  Project Structure
*  Models and APIs
*  Creating Plugins

**Comment by KarenPorter** [comment]
Plus:

how to use app
how to modify app

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by KarenPorter** [comment]
Done (as part of documentation task)
