### ISSUE TITLE
Sub-project edit window buttons aren't entirely logical. Options are to cancel or save changes.  "Ca

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#518]
Sub-project edit window buttons aren't entirely logical. Options are to cancel or save changes.  "Cancel" saves the changes and closes the window; "Save Changes" saves the changes and doesn't close the window.  "Cancel" should discard the changes and close the window; "Save Changes" should commit the changes and close the window.

**Comment by strets123** [comment]
Now closes the window

**Comment by aekhendry** [comment]
Tested on test. Works at all stages, i.e. add assay, add activity etc.
