### ISSUE TITLE
When in Add Assay mode, the sub-project actions drop down is still visible / active.  These actions 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#520]
When in Add Assay mode, the sub-project actions drop down is still visible / active.  These actions aren't logical in this context - in effect the mode should be add assay (commit or cancel) before an action at sub-project level can be taken.

This action needs to be a bit more 'modal' - finish Assay-level action before allowing sub-project action - and the window should reflect that more obviously.

**Comment by aekhendry** [comment]
Done
