### ISSUE TITLE
Just a little concerned - the assay Analysing newly synthesized compound activity at cRaf1 by Alpha 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#521]
Just a little concerned - the assay Analysing newly synthesized compound activity at cRaf1 by Alpha screen assay had 13 activities yesterday (I'm pretty sure) and now has 10.  Can someone confirm they've deleted the others?

**Comment by strets123** [comment]
YES, i deleted all of the data to ensure consistency with the change to the format. We will have upload soon so we can test properly.

**Comment by aekhendry** [comment]
I'm closing this as Andy has answered it.
