### ISSUE TITLE
Proposed small change to data model for classifying data and how it relates to the combination of templates used to produce it on assayreg.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#523]
Data is pulled from AssayReg in the data structure defined below:

Data Point Classification:
This is the index of all of the data points (nodes of data) on the system. Although the data is in the form of a tree, it is stored in a flat format
Each form that is associated with a project will have its own tree of data within that project
If the tree of data produced by a form looks like this then 
<pre>

        l0 project_X 
        ├── l1 subproject_A
        │   ├── l2 assay_A
        │   │   ├── l3 bioactivity_V
        │   │   ├── l3 bioactivity_W
        │   │   └── l3 bioactivity_X
        │   └── l2 assay_B
        │       └── l4 bioactivity_Y
        └── l1 subproject_B
</pre>
For each leaf node in the tree there will be one data point classification object
<pre>
        l0 project_X                        
        ├── l1 subproject_A
        │   ├── l2 assay_A
        │   │   ├── l3 bioactivity_V
        │   │   ├── l3 bioactivity_W
        │   │   └── l3 bioactivity_X
        │   └── l2 assay_B
        │       └── l4 bioactivity_Y
        └── l1 subproject_B
</pre>
<pre>
{"l0" : "uri for project_X's data point"}
{"l0" : "uri for project_X's data point", "l1": "uri for subproject_A" }
{"l0" : "uri for project_X's data point", "l1": "uri for subproject_A" , "l2": "uri for assay_A" }
{"l0" : "uri for project_X's data point", "l1": "uri for subproject_A" , "l2": "uri for assay_A" , "l3": "bioactivity_V"}
{"l0" : "uri for project_X's data point", "l1": "uri for subproject_A" , "l2": "uri for assay_A" , "l3": "bioactivity_W"}
{"l0" : "uri for project_X's data point", "l1": "uri for subproject_A" , "l2": "uri for assay_A" , "l3": "bioactivity_X"}
{"l0" : "uri for project_X's data point", "l1": "uri for subproject_A" , "l2": "uri for assay_B" }
{"l0" : "uri for project_X's data point", "l1": "uri for subproject_A" , "l2": "uri for assay_A" , "l3": "bioactivity_Y"}
{"l0" : "uri for project_X's data point", "l1": "uri for subproject_B" }
</pre>

This structure works well for search as it allows us to access all fields for all levels in a flat structure.

Up to now these data point classifications have been related to a full template combination that are configured for a particular project.

This means that the first item might have the same template combination id as the second item but not the same ID as the last item.

Clearly though, the provenance of the first item could be either from the template combination used to make the second item in the list or that used to make the last item.

This was something I did not notice at the time of creating the database structure because I was concentrating on presenting the data by template combination rather than grouping it up by project and subproject.

In order to make the system properly capable of supporting different template combinations for one project we have a few options for the way that we link a piece of data to the allowed templates for the "child" data that can be added to that piece of data

Option 1) Make the administrator create each permutation explicitely in the admin interface so that the form config table is structured the same as the data point classification table
Option 2) Get rid of the explicit link in the datapointclassification table and instead use a natural key based on the sub form ids
Option 3) Don't worry about this edge case where the database does not precisely match up and allow the user interface to select forms when needed
Option 4) Define an explicit tree-based configuration in django admin using parent-child relationships
Option 5) Retain the current admin interface for forms and denote that the objects produced are legacy objects that need to be kept in sync with "new" objects. The "new" objects will have the following structure:

<pre>
{"l0" : "uri for project config json"}
{"l0" : "uri for project config json", "l1": "uri for subproject config json" }
{"l0" : "uri for project config json", "l1": "uri for subproject config json" , "l2": "uri for assay_A config json" }
{"l0" : "uri for project config json", "l1": "uri for subproject config json" , "l2": "uri for assay_A config json"  "l3": "uri for assay_A's bioactivity config json"}
{"l0" : "uri for project config json", "l1": "uri for subproject config json" , "l2": "uri for assay_B config json" }
{"l0" : "uri for project config json", "l1": "uri for subproject config json" , "l2": "uri for assay_B config json" }
{"l0" : "uri for project config json", "l1": "uri for subproject config json" , "l2": "uri for assay_B config json"  "l3": "uri for assay_B's bioactivity config json"}
</pre>

There is a difference between the schema schema (used for the formbuilder form) and the schema produced by that formbuilder. The schema schema will allow lists of fields to be created. The schema it produces will just allow key-values.

Option 5 supports using the data form system that we have created in the assayreg front end to also support building the forms in the first place. This will reduce the total amount of code in the application in the long term. 

Option 6 would be to merge the best bits of option 5 and 1. That is keep the current object structure but hide the complexity in the admin user interface.

Option 4) This means 2 different ways of defining a tree - one for configuration and one for data. It would work great if we had a Javascipt tree-base user interface for doing administration, but we are limited by django admin.

Option 3 is the smallest amount of changes to the current code but will require some hacky additions that will be hard to back out of later.

Option 2 could work quite neatly but will not give us a database structure that is consistent between configuration and data. This will make the system less learnable.

Option 1 works apart from the complexity for the data curator. Option 5 looks perfect as it reduces the complexity of the system in the long term.

What does option 1 mean for data curator:
===========================================
Curator will need to explicitely define each permutation of forms that can be used on the system in a flat, tree-like table similar to above. This is difficult. It is also not clear how this will be migrated if we later chose to build a different user interface.

What Option 1  mean for front end developer?
==========================================
All the places where data is linked to its form config ID will carry on working.

All the places where the interface needs to select a next level config ID in order to add something, these needed to change anyway so we can have a dropdown for the template that you want to use.

What about option 5?
==========================================
Because the table used for the configuration and the data will be the same the overall complexiy of the system in the long term will be reduced and this has the advantages of option 1 while not further complicating the setup of fields.

For the front end developer there are more changes needed to make option 5 work correctly. Hence I will do extra work to keep the project on track. The overall structure of the objects returned by the API will be the same, we are just moving them around.

What does it mean for this sprint?
==================================
Ensuring that this works properly will take an extra day on top of what was planned for this task as it took a while to work out what was wrong.
Therfore I propose postponing the editable table user interface for now and providing only file upload or simple forms in this sprint.

**Comment by strets123** [comment]
This fix is now deployed to test - users can pick a template for their assay

**Comment by aekhendry** [comment]
If this is how we create projects using the data form configs then i would say this is tested well and works. Could you confirm this is what testing here refers to Andy?

**Comment by strets123** [comment]
Marked as done
