### ISSUE TITLE
Chemreg re-enabled

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#526]
Please test for FUNCTIONALITY ONLY, not UX on staging/test - just want to see that everything still works including the admin for chemreg and the json save function in admin,

We will need to make the dropdowns filter down to avoid interference with assayreg

Note that the project list is shown twice. This is pending us converting it into a dashboard which would give you access to your Assays, Activities, Compounds or Inventory items and show a stat for how many of each there were.

**Comment by aekhendry** [comment]
Is this still relevant?

**Comment by aekhendry** [comment]
Everything works with one exception out lined in issue 611. As such I'm closing this issue. AssayReg, tagnew
