### ISSUE TITLE
Asked to define assays in the sub project - which I can only select one.  Then when I add an assay I

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#529]
Asked to define assays in the sub project - which I can only select one.  Then when I add an assay I can choose a template of any type - shouldn't they be restricted to the assay type I've defined?

**Comment by strets123** [comment]
???? Please clarify @KarenPorter

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
AssayReg issue, better dealt with under ChemiReg
