### ISSUE TITLE
When you've duplicated an activity (but not submitted or cancelled), should it be possible to add a 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#530]
When you've duplicated an activity (but not submitted or cancelled), should it be possible to add a single activity (button isn't disabled)?  Also, when I do select Add Single Activity in that circumstance then the assay selection list appears way below the button.

**Comment by aekhendry** [comment]
Done

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
AssayReg issue, better dealt with under ChemiReg
