### ISSUE TITLE
Front-end observations /suggestions for tweaks:

At the Project level - replace the 2 buttons with s

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#531]
Front-end observations /suggestions for tweaks:

At the Project level - replace the 2 buttons with single drop-down (to be consistent with sub-project and assay) containing View Details and Edit options (I assume we don't want to make it too easy to duplicate a project definition?)

At each level make the title a link that pops up the More Information window.

Put the word Project (at the project level) in the same format as Sub-Project, Assay and Activities.

Round the dynamic search box at activity level (to match other rounding).

**Comment by aekhendry** [comment]
No longer relevant
