### ISSUE TITLE
Installation methods improvement

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#532]
Current submodule based installation is confusing. Here are some reccomendations having discussed the project with my former boss Marius...

**Comment by strets123** [comment]
There should only be one master branch and this should be what is deployed.

We can use pip to manage the submodules or better still merge them all into one git repository.

Throughout his 20+ years experience of digital projects, good project structure and refactoring has had much more of an impact on success than automated tests have.

**Comment by strets123** [comment]
With these principles in mind I have looked at ways in which we can achieve the goal of making the project easier to install. 

We are currently only using 2 tables from the chembl schema in chemreg so it would be better not to use the chembl codebase. This will simplify the install of chemreg and assayreg.

We can then provide a quickstart folder that would have all the things needed to get going quickly using anaconda

Where we do need the chembl schema I have found a way to install the whole database quickly in an isolated environment. For each deposition we can have a clean database which can then be sent on to chembl for integration. This will allow us to keep our code separate from chembl's code and allow them to continue with their existing process. 

After all they currently receive data in both database dumps and in csv/sdf and we dont want to really help them with the SQL integration part as that problem is already solved at their end.

**Comment by KarenPorter** [comment]
Add blog post re ChEMBL installation script

**Comment by strets123** [comment]
Building ChemBio Hub with Conda

Step 1:

Create a virtual machine - Ubuntu 64 bit server

Step 2:

Install anaconda

    wget https://3230d63b5fc54e62148e-c95ac804525aac4b6dba79b00b39d1d3.ssl.cf1.rackcdn.com/Anaconda2-2.4.0-Linux-x86_64.sh
    bash Anaconda2-2.4.0-Linux-x86_64.sh
Step 3:

**Comment by strets123** [comment]
Now that the system level dependencies are installed, we install the code:

    git clone https://github.com/thesgc/chembiohub_ws
    cd chembiohub_ws/
    git submodule init && git submodule update

**Comment by strets123** [comment]
Remaining in the activated environment, next create a directory for the postgresql data to be in and a directory for the connection socket
mkdir ~/postgresdata
mkdir ~/postgressocket
initdb -D ~/postgresdata

**Comment by strets123** [comment]
Now make supervisor start (as sudoable user)

#Make a link

    sudo ln -s /srv/chembiohub/chembiohub_ws/conf/supervisor/* /etc/supervisor/conf.d/
    sudo supervisorctl reread
    sudo supervisorctl reload

**Comment by strets123** [comment]
Remaining in the activated environment, next create a directory for the postgresql data to be in and a directory for the connection socket

    mkdir ~/postgresdata
    mkdir ~/postgressocket
    initdb -D ~/postgresdata
    createdb -h /home/chembiohub/postgressocket/ chembiohub_db
    psql -h /home/chembiohub/postgressocket/ chembiohub_db -c 'create extension if not exists hstore; create extension if not exists rdkit;'

**Comment by strets123** [comment]
Now set up apache, as the sudoable user:

sudo ln -s /srv/chembiohub/chembiohub_ws/conf/apache.conf /etc/apache2/sites-available/chembiohub.conf
sudo a2dissite 000-default
sudo a2ensite chembiohub

**Comment by strets123** [comment]
During this sprint I have been able to do the following:

- [x ] Create a full installation script for ubuntu including ability to built frontend from source
- [x ] Create a full install script for centos not including ability to built frontend from source
- [x] Test the centos install script on a local VM
- [x] Test the ubuntu install script on staging

The install script was developed in two stages. The first required a set location for the code and was limited to one installation per VM. This was done in order to enable testing of the new version of RDKit.

The second install script has yet to be merged to master but has been tested locally. This enables multiple installs of the system on a server.
Postgres data is stored in the /var/postgresdata directory of the anaconda environment. Unix sockets and randomised ports are used. 

Installation of new instances is massively simplified via this new method, we just now need to decide whether it is simple enough for general consumption.

**Comment by aekhendry** [comment]
Not sure how I can test this?

**Comment by strets123** [comment]
Let's just park this until we are coming up to the conference at which point a sprint for install methods will be appropriate.
