### ISSUE TITLE
Thoughts for October

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#533]
Current feedback requirements:
•	Compartmentalisation of project i.e. some columns hidden / editable, others are not. Depending on your permissions.
•	Search – Auto complete option should not be only search item returned. i.e. you search ‘plates’ should bring back all entries that contain the search term ‘plates’. 
•	System generated data should either be hidden from regular view or at least be on the far right of the table. Feedback from tom McAllister:
“Being able to adjust the order of the columns would be useful but this probably ties in with creating the project in the first place. Since the window only shows 10 or so columns at once having the most important columns first would make sense to see the most relevant information. Stuff like UOx ID, Batch ID and Upload ID aren't going to be useful for what we do very often, whereas the name and properties of the sample (e.g. concentration, storage location, volume etc.) would be useful things to be able to see at a glance. Or perhaps width adjustable/hide-able columns; since I've got columns of DNA/RNA sequences the entries are just long text strings which take up a lot of space but that we don't necessarily want to see all the time.”
•	Ability to draw new structures into system (like we had before)
•	The table view can be buggy. It often doesn’t line up properly with the header text. 
•	Is there a limit to the number of columns table view can handle? Currently seems to be breaking when presented with too much.
•	Can we raise the cap on number of entries add at a time?
•	Internet explorer functionality currently broken. Table headers are all out of whack.
•	Ability to sort / organise projects in project overview.
•	Give Adam the ability to archive projects
•	Update admin interface for users – when are we going to allow people to make new projects and add their own custom fields?
•	Default table view for inv projects should be 50 per page
•	Ability for Adam to see when people last logged in / edited a project
Website TLC

**Comment by aekhendry** [comment]
Website TLC

**Comment by strets123** [comment]
For the website, my 2p's worth...

It seems to me that regardless of whether this "is a technology project" or not the majority of the pitch for new funding is about technology. Therfore the research equipment and symposium stuff should now be relegated and the data section brought to the top.

chemreg page should say Upload. Store. Search. Info on the chemreg page should be shortened and now include stats on how many groups are using it and some quotes.

Walkthrough gifs should potentially be added.

**Comment by aekhendry** [comment]
No Longer relevant
