### ISSUE TITLE
Production data migration

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#535]
Due to the changes to the database structure we need to do a test of the migration routine and ensure that the system still works and the data is not corrupted.

**Comment by strets123** [comment]
We have done the preliminary tests for this with the following findings:

Bug in chemnreg search page needs fixing
The issue I thought we hd with django admin is fixed when we upgrade django so we will be able to delete projects (with some small changes)

**Comment by PaulBarrett79** [comment]
Not happening until people are happy with assayreg

**Comment by strets123** [comment]
So far I have created the data migration scripts and tested them on the dataset in the tagnew instance. This is to add images as blobs to the database and also add a created by field to existing data in a better way to enable search.

**Comment by strets123** [comment]
Now migrated the data and put it all on the tagnew instance

**Comment by KarenPorter** [comment]
All the migrated projects show project type of Assay - I don't think that is the case (at least based on project names).

Burton Inventory has 2060 compounds and no assay data.

Project button options aren't intuitive.  By clicking project name I go to assay reg (no data) - same with assay button.  I need to click chem, then view/add compounds to get to my chemical list - too deeply buried.

**Comment by strets123** [comment]
Agreed but the plan is for Adam to set all of the users to have assayreg disabled then it will point to chemreg. You can change this in the admin using the "member" group

**Comment by strets123** [comment]
@aekhendry

**Comment by strets123** [comment]
- [x] maintenance mode activated
- [ ] code backed up and re pulled
- [ ] db backed up and migrated
- [ ] indexes rebuilt
