### ISSUE TITLE
Deposit AssayReg data in multiple repositories

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#538]
The proposed effort for October is to produce capability to deposit assay data in multiple repositories.

**Comment by KarenPorter** [comment]
October effort may constitute developing a plan for deposition rather than doing the deposition sructure

Using API to deposit to PubChem
tracking progress and notifying user of status

**Comment by KarenPorter** [comment]
What has been done?  How does that change manifest itself in testing / revised behaviour?

Where's the documentation?

**Comment by PaulBarrett79** [comment]
This is waiting for the ability to map chembl fields on the staging/tagnew instance to be enabled.

Manifested as a link on the search page within the results table. This launches a popup with ChEMBL compatible json which can be copied and pasted into ChEMBL. This is documented in the help page.

**Comment by PaulBarrett79** [comment]
Users can now view ChEMBL json via the search page. Any results with a "View Deposition Preview" link have ChEMBL data mapped. This launches a popup containing ChEMBL json. Available on staging/tagnew

**Comment by aekhendry** [comment]
Tested on staging tagnew
