### ISSUE TITLE
Meeting with ORA and OERC

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#539]

**Comment by strets123** [comment]
Looking at the ORA documentation it would seem that they reccomend putting the data in multiple formats but don't actually specify formats at the outset.

Could be worth seeing if there can be a reduction in the upfront curation cost if the data is already formatted a certain way.

**Comment by strets123** [comment]
Approach to ORA deposition will be:

Deposit as PubChem Spreadsheet and PubChem XML

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
Meeting not needed - closing
