### ISSUE TITLE
The labeling of the x-axis of IC50 curves is unclear. The axis is labelled "Micr

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#54]
The labeling of the x-axis of IC50 curves is unclear. The axis is labelled "Micromolar concentration" and the tick marks on the graph are numbered "0.1, 0.316, 1, 3.16". Based on the data I put in, I think the point labeled 3.16 should in fact be 1 X10^3.16, is that the case?

I would prefer the axis to show log10 of the molar concentrations, which I think would be more inline with what is normally used.

It would also be nice if the IC50 value was displayed underneath the IC50 curve (but that is definitely a luxury rather than a necessity).

date recorded in spreadsheet: 30/03/2015 14:26:24

**Comment by KarenPorter** [comment]
@strets123 still outstanding?

**Comment by strets123** [comment]
No interest in fixing this

**Comment by KarenPorter** [comment]
incorporated in #794
