### ISSUE TITLE
ChemReg working with IE

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#540]
including working in compatibility mode.

Define issue - what is broken?

select option for delivering

**Comment by PaulBarrett79** [comment]
ChemReg / AssayReg IE issues

IE8 - neither app loads correctly - AngularJS needs adapting to be able to work correctly with this scenario.
Error generated: Object does not support property or method addEventListener

Officially Angular has dropped IE8 support for the version we are using

https://docs.angularjs.org/guide/ie

There are tips online for achieving IE8 support
http://tales.itnobody.com/2014/04/angular-ui-router-ie8-nested-states.html
http://henriquat.re/appendix/angularjs-and-ie8/necessary-changes-for-ie8-compatibility.html




IE9
Chemreg - Page loads. Headers do not scroll on tables. Filters not shown correctly. Other functionality seems unaffected.
AssayReg - Page Loads, tables display correctly.

Putting in workarounds for IE8 in ChemReg architecture is likely to be more expensive than migrating ChemReg to AssayReg architecture
Benefits:
Better/easier IE8 compatibility
Better searching and filtering using elastic UI library - filtering widgets potentially will work more dynamically based on the experience we have had with AssayReg implementation

**Comment by PaulBarrett79** [comment]
Fixes to do to get round these:
replace header div on tables with td
Remove doublescroll
Add gutter CSS for emphasised bottom scroll bar
Store image in elasticsearch as data64 - enables us to avoid too much data coming to front end / extra calls
Examine whether page being reloaded twice in IE - possible perf issues
FlowFile IE shim - similar to flow js, maybe needs adding into the angular version

**Comment by aekhendry** [comment]
Tested on IE 10, table view now seems to be displaying correctly for both chem and inv projects. Also tested in IE10 compatability mode with same results

**Comment by aekhendry** [comment]
Tested on sandbox

**Comment by strets123** [comment]
Does the file upload work?

**Comment by aekhendry** [comment]
Yes
