### ISSUE TITLE
Move system generated columns to the right for ChemReg

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#541]
other than UOxID.

**Comment by KarenPorter** [comment]
This is in Awaiting Testing column with no update to comments - indicating what's been done, where it can be tested, replication and test steps.

**Comment by KarenPorter** [comment]
Moving to code review - I have no idea where / how to test this.  System generated columns still on left in new project

**Comment by PaulBarrett79** [comment]
I've corrected this on ChemReg - deployed to staging/sandbox
I've also applied to AssayReg - waiting deployment at time of writing.

**Comment by PaulBarrett79** [comment]
System generated columns (added by, generated mol weight etc) will appear after any project fields or supplementary fields i.e. on the right of the table. User will see project field columns after image, UOX ID, Project cells.

**Comment by PaulBarrett79** [comment]
This is now applied to AssayReg and deployed to staging/tagnew.

Filters now open in a popup window, and system generated columns are on the RHS of the table

**Comment by aekhendry** [comment]
Tested on tagnew, chrome
