### ISSUE TITLE
Reference registered compound from ChemReg in AssayReg

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#542]

**Comment by strets123** [comment]
The field in the activity must be labelled as UOx id. This will then show the image of the structure.

Currently no links, just an image. There was previously a bug stopping this showing on the data overview page, now fixed. 

Compound must be in the same project and the project must have compounds enabled

**Comment by KarenPorter** [comment]
Still not an ideal user experience.

When user wants to add a compound in a single activity they need to be able to reference relevant compounds - so having Uox IDs in drop down (ideally with images).  And having a link to compound info window or relevant search results.  What effort would that take?

**Comment by strets123** [comment]
The task that was carried over from the last sprint was a basic integration so you can see the image. In the next sprint we do a full integration.

**Comment by strets123** [comment]
Marking as done in order to add a new ticket for Nov 2
