### ISSUE TITLE
CAS number field breaks file upload

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#546]
If you use 'CAS Number' as a field heading it breaks file upload. In preview all compounds in file are present, but on pressing submit only a subset are actually registered. Hub / chrome

**Comment by aekhendry** [comment]
Still not working. All values with a value under the CAS Number field heading are not being saved

**Comment by PaulBarrett79** [comment]
Related to an assayreg fix

**Comment by strets123** [comment]
Please test again after production upgrade

**Comment by aekhendry** [comment]
Fixed, Hub chrome
