### ISSUE TITLE
Instructions for error log should be present

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#548]
There should be detailed instructions about how to access the error logs for assayreg (and all apps)

**Comment by KarenPorter** [comment]
And the error logging itself should be guaranteed to be robust

**Comment by aekhendry** [comment]
How do we plan on doing this? Via help when logged in / via our website?

**Comment by strets123** [comment]
Once the next deployment to hub happens we will have an error reporting system such that any front end errors are pushed to to logging server. Back end errors will be recorded to file AND pushed to the logging server.

**Comment by strets123** [comment]
OK so we now have front end errors being pushed and back end errors being properly captured in the supervisor log. Now need to redirect supervisor log to a file as part of the production install.

**Comment by strets123** [comment]
Back end supervisor logging is now possible, need to continue testing this out

**Comment by strets123** [comment]
Errors logging needs to be fixed up before we can do this task

**Comment by strets123** [comment]
#769 covers this
