### ISSUE TITLE
Instructions for reindexing elasticsearch produce an error

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#549]
Steps:

ssh to staging
go to the elasticsearch indexes location
delete indexes
restart elasticsearch
sudo su chembiohub
set the correct source
python manage.py shell
from cbh_datastore_ws.resources import reindex_datapoint_classifications
reindex_datapoint_classifications()

After performing these steps as instructed, an error trace is shown:

189
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-df700151da9b> in <module>()
----> 1 reindex_datapoint_classifications()

/var/www/automated_reg_installs/test/chembiohub_ws/src/cbh_datastore_ws/cbh_datastore_ws/resources.pyc in reindex_datapoint_classifications()
   1256     for chunk in chunked:
   1257 
-> 1258         index_filter_dict({"id__in": chunk})
   1259 
   1260 

/var/www/automated_reg_installs/test/chembiohub_ws/src/cbh_datastore_ws/cbh_datastore_ws/resources.pyc in index_filter_dict(filter_dict)
   1278     dpcs = res.Meta.queryset.filter(**filter_dict)
   1279     print dpcs.count()
-> 1280     bundle.data["objects"] = [res.full_dehydrate(res.build_bundle(obj=dpc, request=request)) for dpc in dpcs]
   1281     resp = res.create_response(request, bundle)
   1282     elasticsearch_client.index_datapoint_classification(resp.content, refresh=False)

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/resources.pyc in full_dehydrate(self, bundle, for_list)
    850                 field_object.resource_name = self._meta.resource_name
    851 
--> 852             bundle.data[field_name] = field_object.dehydrate(bundle, for_list=for_list)
    853 
    854             # Check for an optional method to do further dehydration.

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/fields.pyc in dehydrate(self, bundle, for_list)
    730         self.fk_resource = self.get_related_resource(foreign_obj)
    731         fk_bundle = Bundle(obj=foreign_obj, request=bundle.request)
--> 732         return self.dehydrate_related(fk_bundle, self.fk_resource, for_list=for_list)
    733 
    734     def hydrate(self, bundle):

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/fields.pyc in dehydrate_related(self, bundle, related_resource, for_list)
    568                 objects_saved=bundle.objects_saved
    569             )
--> 570             return related_resource.full_dehydrate(bundle)
    571 
    572     def resource_from_uri(self, fk_resource, uri, request=None, related_obj=None, related_name=None):

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/resources.pyc in full_dehydrate(self, bundle, for_list)
    850                 field_object.resource_name = self._meta.resource_name
    851 
--> 852             bundle.data[field_name] = field_object.dehydrate(bundle, for_list=for_list)
    853 
    854             # Check for an optional method to do further dehydration.

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/fields.pyc in dehydrate(self, bundle, for_list)
    730         self.fk_resource = self.get_related_resource(foreign_obj)
    731         fk_bundle = Bundle(obj=foreign_obj, request=bundle.request)
--> 732         return self.dehydrate_related(fk_bundle, self.fk_resource, for_list=for_list)
    733 
    734     def hydrate(self, bundle):

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/fields.pyc in dehydrate_related(self, bundle, related_resource, for_list)
    568                 objects_saved=bundle.objects_saved
    569             )
--> 570             return related_resource.full_dehydrate(bundle)
    571 
    572     def resource_from_uri(self, fk_resource, uri, request=None, related_obj=None, related_name=None):

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/resources.pyc in full_dehydrate(self, bundle, for_list)
    850                 field_object.resource_name = self._meta.resource_name
    851 
--> 852             bundle.data[field_name] = field_object.dehydrate(bundle, for_list=for_list)
    853 
    854             # Check for an optional method to do further dehydration.

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/fields.pyc in dehydrate(self, bundle, for_list)
    821             m2m_bundle = Bundle(obj=m2m, request=bundle.request)
    822             self.m2m_resources.append(m2m_resource)
--> 823             m2m_dehydrated.append(self.dehydrate_related(m2m_bundle, m2m_resource, for_list=for_list))
    824 
    825         return m2m_dehydrated

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/fields.pyc in dehydrate_related(self, bundle, related_resource, for_list)
    568                 objects_saved=bundle.objects_saved
    569             )
--> 570             return related_resource.full_dehydrate(bundle)
    571 
    572     def resource_from_uri(self, fk_resource, uri, request=None, related_obj=None, related_name=None):

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/resources.pyc in full_dehydrate(self, bundle, for_list)
    850                 field_object.resource_name = self._meta.resource_name
    851 
--> 852             bundle.data[field_name] = field_object.dehydrate(bundle, for_list=for_list)
    853 
    854             # Check for an optional method to do further dehydration.

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/fields.pyc in dehydrate(self, bundle, for_list)
    730         self.fk_resource = self.get_related_resource(foreign_obj)
    731         fk_bundle = Bundle(obj=foreign_obj, request=bundle.request)
--> 732         return self.dehydrate_related(fk_bundle, self.fk_resource, for_list=for_list)
    733 
    734     def hydrate(self, bundle):

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/fields.pyc in dehydrate_related(self, bundle, related_resource, for_list)
    568                 objects_saved=bundle.objects_saved
    569             )
--> 570             return related_resource.full_dehydrate(bundle)
    571 
    572     def resource_from_uri(self, fk_resource, uri, request=None, related_obj=None, related_name=None):

/home/chembiohub/anaconda/envs/test/lib/python2.7/site-packages/django_tastypie-0.12.0-py2.7.egg/tastypie/resources.pyc in full_dehydrate(self, bundle, for_list)
    856 
    857             if method:
--> 858                 bundle.data[field_name] = method(bundle)
    859 
    860         bundle = self.dehydrate(bundle)

/var/www/automated_reg_installs/test/chembiohub_ws/src/cbh_datastore_ws/cbh_datastore_ws/resources.pyc in dehydrate_edit_form(self, bundle)
    282     def dehydrate_edit_form(self, bundle):
    283         '''          '''
--> 284         return {"form" : [self.get_field_values(bundle)[1]]}
    285 
    286     def dehydrate_edit_schema(self, bundle):

/var/www/automated_reg_installs/test/chembiohub_ws/src/cbh_datastore_ws/cbh_datastore_ws/resources.pyc in get_field_values(self, bundle)
    220     def get_field_values(self,  bundle):
    221         obj = bundle.obj
--> 222         data =  deepcopy(obj.FIELD_TYPE_CHOICES[obj.field_type]["data"])
    223 
    224         data["title"] = obj.name

KeyError: u'related'

These instructions should rebuild elasticsearch indexes without issue

**Comment by PaulBarrett79** [comment]
Refactoring work done by Andrew means this should no longer be an issue

**Comment by KarenPorter** [comment]
One for Paul to test?

**Comment by PaulBarrett79** [comment]
I have followed the re-indexing instructions provided on staging/test and the commands no longer produce an error and rebuild indexes correctly.

Ready for deployment.
