### ISSUE TITLE
Excel downloads via URL involving elasticsearch parameters are not allowed

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#550]
Following the examples from ChemReg and the AssayReg template download, to try and create an excel export of datapoints from search results.

If I put the appropriate elasticsearch data in the URL, I get a 400 response (operation not permitted). This is for both post and get requests

If I use an AJAX query, the export works and examining chrome devtools shows that binary data is returned. However, it is not possible to stream binary data from an AJAX request as a file.

The assayreg backend needs modification to allow a URL request to take place, consistent with template download mechanism.

**Comment by PaulBarrett79** [comment]
Searches are now saved on the server side with an ID - easier to reference searches which have been carried out. Excel downloads of filtered results are now possible.

**Comment by KarenPorter** [comment]
I've downloaded search results - though I have some questions.  See separate issue raised which queries some of the behaviours I'm seeing.

also, how do I reference a saved search?

**Comment by strets123** [comment]
for refrencing a saved search see #572

**Comment by KarenPorter** [comment]
Need data volumes to test more rigorously, though looks good from what I've seen so far.

**Comment by aekhendry** [comment]
Cant upload a large file as i think the server times out due to it taking way to long to load a file

**Comment by aekhendry** [comment]
Takes too long to upload a large file and i think it times out. i cant test this until file upload is fixed

**Comment by PaulBarrett79** [comment]
Upload comments are irrelevant here. This is a ticket for downloading a file which works correctly.

**Comment by PaulBarrett79** [comment]
Upload comments are irrelevant here - the bug on the card was to do with file downloads/export, being caused by elasticsearch parameters which we have now got around. File upload issues are in #579. This issue is fixed.

**Comment by aekhendry** [comment]
Tested marked as fixed

**Comment by aekhendry** [comment]
Fixed
