### ISSUE TITLE
Assay Reg load time far too long

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#552]
Uploading large files of data into assay reg currently takes far too long. Andy is aware of this.

**Comment by PaulBarrett79** [comment]
Andy has done a great deal of performance improvements so should be acceptably fast now

**Comment by strets123** [comment]
There was actually a special issue to do with wide files as well as all the other performance fixes that I have done. This was causing column records to be saved as many times as you had previously uploaded the file. I willl deploy the fixes tomorrow.
