### ISSUE TITLE
Search Assays functionality defects (on test): what is populated in the select boxes for search isn'

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#555]
Search Assays functionality defects (on test): what is populated in the select boxes for search isn't complete.  Projects, sub-projects and assays is not comprehensive are each missing data.  

There are also blank lines - may reflect the fact that these fields aren't mandated when created? Need fixed

Results has a column headed study - should be sub-project

**Comment by strets123** [comment]
Please re-test this

**Comment by aekhendry** [comment]
Tested on tag new chrome. i think this is working, i cant replicate the described behaviour
