### ISSUE TITLE
Add single assay - where names of fields are long the label goes over 2 lines, then knocks the rows 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#563]
Add single assay - where names of fields are long the label goes over 2 lines, then knocks the rows of fields out of alignment and odd-looking things result.

**Comment by PaulBarrett79** [comment]
Label fields need truncating in same way as project lists - schemaform reconfiguration / bootstrap decorator. Or trim names on backend before applied to schemaform.

**Comment by aekhendry** [comment]
This is almost fixed. It no longer puts the table out of whack as the heading is no truncated correctly. However the white space either side of a very long heading is very large and widens the table a great deal unnecessarily.

**Comment by aekhendry** [comment]
assay reg tag new

**Comment by aekhendry** [comment]
Fixed. chrome hub
