### ISSUE TITLE
Upload a Tree of data

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#564]
In order to process the SGC's datasets it would be easier if the data could be converted into a tree i.e. register your Assay, Activities and Replicates all at once

**Comment by strets123** [comment]
Data could be visualised using handsontable and generating merged cells, there is a simple function to do this.

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
AssayReg issue, better dealt with under ChemiReg
