### ISSUE TITLE
Project type of assay (all lower case) is treated as a chemical project type  (at a guess it doesn't

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#566]
Project type of assay (all lower case) is treated as a chemical project type  (at a guess it doesn't pass the test of type = Assay).

See projects list where SGC Assay deposition data project is blue and has chemical symbol (though hover shows 'assay project')

**Comment by PaulBarrett79** [comment]
Configuration issue

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
AssayReg issue, better dealt with under ChemiReg as data will be in same place. Assay data will be against a compound abtch
