### ISSUE TITLE
The view activity details window showing search results has long header fields which extend way beyo

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#567]
The view activity details window showing search results has long header fields which extend way beyond the right window margin.

Select any search result from: http://staging.chembiohub.ox.ac.uk/test/#/search-assays?textsearch=gsk`

**Comment by PaulBarrett79** [comment]
Needs break-word to restrain within popup

**Comment by aekhendry** [comment]
This is a replication of a previous reported issue
