### ISSUE TITLE
the view activity details window needs a close (X) at the top as well as the button at the bottom - 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#568]
the view activity details window needs a close (X) at the top as well as the button at the bottom - it can become quite a long window quite easily and currently you need to scroll to the bottom.

**Comment by PaulBarrett79** [comment]
Added close button to the top of all modal windows via template. 

Within AssayReg, go to Search Activities
Click View Activity Details
The modal displayed has a Close button (x) in the top right hand corner.

Pushed to github, awaiting test deployment.

**Comment by PaulBarrett79** [comment]
Deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
Prob different issue but raising here where experienced - look at the activity details for Marsden project - each alternate row of data extends beyond the window in which it is framed.

the (X) close works as expected and is helpful / intuitive

**Comment by PaulBarrett79** [comment]
Table extending past window issue is recorded in #641.

Moving back to awaiting testing.

**Comment by KarenPorter** [comment]
In which case, pending being able to test #641, signing off this issue.

**Comment by KarenPorter** [comment]
closing issue
