### ISSUE TITLE
Search Assay  -User (select user) drop-down doesn't work.  There's nothing in the drop down and noth

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#571]
Search Assay  -User (select user) drop-down doesn't work.  There's nothing in the drop down and nothing can be typed in the field.

Poor user experience.

**Comment by strets123** [comment]
fixed user box on http://staging.chembiohub.ox.ac.uk/tagnew/

**Comment by KarenPorter** [comment]
Didn't work the first time I tried.  All activities seem to be recorded against andy so results aren't as expected.

**Comment by KarenPorter** [comment]
Reported sa fixed - Karen to test

**Comment by KarenPorter** [comment]
tested - passed
