### ISSUE TITLE
Difficult to understand how the chunks of downloaded data from search results are grouped together.


### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#573]
Difficult to understand how the chunks of downloaded data from search results are grouped together.

Partly our data but I don't think it will be obvious to users what's being shown in whichorder.

I've searched for activities from 1st Sept until 1st Oct, in project SGC Data Deposition, sub project Alpha Screen probe Data - 160 records.  By selecting various 'blank' assays I can see that these are in 3 assays (one with 112 records, one with 36 and one with 12 records).  

There are 105 fields in one of these activities but the number of columns downloaded is 215.  They appear *nearly* duplicated - which would make sense if there were 2 very similar assay definitions - but there are 3.  So how are the columns generated?  And how are the records grouped?  Different assays appear to be interspersed with each other (tricky to tell with no values in the assay field).

**Comment by KarenPorter** [comment]
Also, in the downloaded file there's a column headed 'study' _ assume this should be sub-project?

**Comment by KarenPorter** [comment]
Proposed fix -only allow download of search results when they are all part of a single assay/ subproject/ project combo (otherwise hover over tells use why disabled).

**Comment by PaulBarrett79** [comment]
Putting back in the backlog for now

**Comment by strets123** [comment]
AssayReg issue - better dealt with under ChemiReg
