### ISSUE TITLE
Odd search parameter options:

Sub-project "J31 characterisation" doesn't appear in the drop down li

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#574]
Odd search parameter options:

Sub-project "J31 characterisation" doesn't appear in the drop down list (search on assay "Thermal shift of compound J31 Vs protein MCL-3" to see 20 results with that combination of assay and sub-project).

Assay "Compound X" doesn't appear in the drop down list (search on sub-project "Alpha screen testing results" for 5 results with this combination - and now the assay is in the drop down, where it wasn't previously).

when I clear projects selection and I have other selections in sub-project and assays, they are still applied but I can't see the selection criteria - selections in relevant dropd downs no longer highlighted.

**Comment by strets123** [comment]
Please re-test all of this with fresh data on http://staging.chembiohub.ox.ac.uk/tagnew/

Logic is now changed, specifically:

Top search bar only searches the titles of projects, assays etc

Autocomplete on the search page for assays, subprojects etc searches all fields of the relevant thing

Activity User and activity date do not filter available projects list but each level of project, subproject, assay filters the next level

All fields across the activity, subproject and project are filtered by the free text search.

There are now little icons to tell you in the top search bar what type of thing you are going to

When clicking on a top search bar item the URL and UI update accordingly.

**Comment by KarenPorter** [comment]
tested - accepted
