### ISSUE TITLE
I don't think Advanced Search is working at all. The values in the Field Name drop down aren't field

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#575]
I don't think Advanced Search is working at all. The values in the Field Name drop down aren't field names.  Run Search doesn't apply any additional search parameters.

**Comment by strets123** [comment]
Taken off for now, we will re-add if we have time in this sprint

**Comment by KarenPorter** [comment]
accepted - returning to Backlog.

**Comment by PaulBarrett79** [comment]
Tied to #585 - duplicate

**Comment by aekhendry** [comment]
As it's a duplicate, i'm marking as done
