### ISSUE TITLE
Bookmarkable search links on assayreg

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#576]

**Comment by strets123** [comment]
All search parameters on assayreg should now work consistently and change the URL as you edit the form.

**Comment by KarenPorter** [comment]
Can't see this issue in the Waffle board for some reason?

Not a complete user solution- as it stands they have to know that they can bookmark / cut and share URL.  Better experience would be to have a button to 'save and share search'.

**Comment by KarenPorter** [comment]
Now appeared on Waffle

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by aekhendry** [comment]
closing as no longer relevant
