### ISSUE TITLE
search testing 28/10 (am):

the drop down of locations to search for a value isn't consistently ther

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#577]
search testing 28/10 (am):

the drop down of locations to search for a value isn't consistently there.  From within the project page - I searched for a value '222' - drop down is there, then changed to 'test' - no drop down.

text in the search field isn't cleared out when moving around within AssayReg.  Suspect this is by design but would like to know that explicitly.

results table heading says '1 Results' when there's a single result

results table doesn't show (in the example I'm testing) the ic50 value.  Users will want to see assay results at a glance.

activity created by user - the first time I tested this nothing dropped down.  Subsequent testing - drop down appears (including a user '-1').  

All activities are tagged with Andy as a user.  If I search with karen selected I get zero results (and I have created activities this morning.

If I have the activity created by user drop down visible, it doesn't go when i click into activity date from or activity date to fields.  Does go when i click a drop down box or elsewhere on the page.

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
I believe this issue is completed as part of December's custom field changes
