### ISSUE TITLE
AH feedback on assay reg file upload

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#579]
[X] When you upload a file with muliple tabs it is too easy to submit the wrong tab. Can we have a warning pop up saying 'you are about to upload x assay defs from tab x'
[X] pressing cancel once a file has been uploaded seems to cause a crash (error 500)
{X}Cant upload file, click save get immediate 500 error. Doesnt even think about it - computer says no.

**Comment by KarenPorter** [comment]
in addition (from KP):

the text in the mapping window is confusing / technical - is this really needed for end users?

the mapping field functionality is not robust.  Pick a field may or may not drop down, seemingly arbitrarily.  It may generate a second 'pick a field' entry in the drop-down.

the red/green icons are too subtle - hard for user to see where their data are wrong.  No indication what to do about it.  No warning when you click 'save this sheet' that it can't process it.

**Comment by aekhendry** [comment]
•	Upload file. I do not map fields, none of the fields are automapped to the assay def. None of the fields in the assay def are mandatory. I click submit. Page refreshes. After a very long loading time (with no loading bar present), page loads fully with appropriate number of rows containing no information. Logically this makes sense but no warnings or guidance were present. I would assume this was broken if unfamiliar with the system.
•	A better ‘no image available’ image is required. The same as ChemReg will do.
•	Added SDF file to assay reg project compound upload. The table following clicking save in the search page had no table headers at all. 
•	Added SDF / excel file to assay reg project compound upload. I cannot map fields, no table header is available.  Following submission, I open compound up into single molecule view. I’m interested in where the fields I see attached to this compound come from? In ChemReg this makes sense as the project uploaded to is a static set of fields. This is not the case with Assay Reg which has multiple fields. Depending on the subproject, assay def and activities. Clarification needed.
•	Added SDF file to assay reg project compound upload. Following submission, I open compound up into single molecule view. The Batch update button appears to not be working. Nothing happens when I click it. I would expect it to update all the other compounds in this upload batch with the same new info I just added.
•	Added SDF file to assay reg project compound upload. Following submission, some compounds molecular weight has an unnecessarily large amount of decimals. E.g. UOXCA72JJM in Test 1 project.
•	On project view, click search on the project button itself. Drop down shows search option for compounds only. 
o	Text in the drop down is right aligned, needs to be moved left
o	Text on the button itself is ambiguious. If all you can do is search compounds via here, then remove the drop down and word the button better to reflect its function.
o	Same goes for the Add+ button opposite
•	What is the purpose of “project type”, when creating a new project? It would be far simpler to make all projects “compound” by default. 
•	Will we be integrating ChemReg project structures fully with assay reg, or will they be expected to upload their compounds twice? Im not a fan of the latter, that’s poor usability to me and highlights an inability to link our systems. The same goes the other way, if you register compounds to a project you should be able to nominate a ChemReg (or multiple projects) you wish to deposit to as well. 
•	In compound search if I search for a compound that does not exist in the project it locks the page and goes into an infinite loop (at least it looks that way). Note that this also happens if I search with or without specifying a project
•	I think It would be a good idea to enable a sort of faceted structure search. For example you would be search for a substructure. Then from that list you could search for another substructure (or even an additional text field). Being able to see how many of a subset possess a particular feature is useful. 
•	Added by / Added after isn’t working as it should. It seems to only work for compounds I’ve registered today. I’ll test this next week to see if I can replicate this behaviour using the compounds I’ve just submitted vs new ones.

**Comment by aekhendry** [comment]
•	UOx ID submission is broken. File will not upload if UOx ID’s are included in file. I can submit if I remove UOx ID’s, meaning the header itself is not breaking the project.

**Comment by aekhendry** [comment]
upload of Assay def file was WAY too long with no loading bar to indicate it had not broken

**Comment by PaulBarrett79** [comment]
Need time to assess which of these things are fixed and which are not, then estimate time of those not fixed.

**Comment by PaulBarrett79** [comment]
Time given is time for the estimation task.

**Comment by PaulBarrett79** [comment]
Are these all split out now? Can this be closed?

**Comment by aekhendry** [comment]
Closing as all issues have been split into separate ones on the board. i'm sure I did this already?
