### ISSUE TITLE
There are 2 new activities in Paul Test project (with blank and 444 UoXids) which Adam created - but

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#580]
There are 2 new activities in Paul Test project (with blank and 444 UoXids) which Adam created - but they are recorded as Karen.  This is critical that users are recorded accurately.

**Comment by KarenPorter** [comment]
@strets123 - are you happy that this can't recur?  This was so long ago it's probably a test instance we no longer use, would be very difficult to test in any case to try to get it to recur.

**Comment by KarenPorter** [comment]
If confirmed to be the case - let's close this.

**Comment by strets123** [comment]
Yes, there was a specific bug in the code that I fixed while doing something else
