### ISSUE TITLE
User documentation - help page & FAQ

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#581]

**Comment by PaulBarrett79** [comment]
Documentation added to Help page within AssayReg. Gives descriptions of how to use key functionality within the app.

Still waiting for the opportunity to take screengrabs of search page for some of the images, but text is completed.

Pushed to github, awaiting deployment to tagnew.

**Comment by PaulBarrett79** [comment]
Deployed to staging/tagnew

http://staging.chembiohub.ox.ac.uk/tagnew/#/help

**Comment by KarenPorter** [comment]
Suggestions made (on printout copy)

**Comment by PaulBarrett79** [comment]
Karen's suggestions have been applied, awaiting deployment.

**Comment by PaulBarrett79** [comment]
Suggestions applied, awaiting deployment to staging/tagnew

**Comment by PaulBarrett79** [comment]
Deployed to staging/tagnew

**Comment by aekhendry** [comment]
This look good to me, I'm moving it across
