### ISSUE TITLE
ChemReg paper discussion

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#582]
Publication, of some sort, for ChemReg, AssayReg or both.

1) What is our target audience?
2) Do we write multiple modular papers for coverage, or an all-encomapssing paper for impact?
3) Where do we want to publish?
4) Is there a particular angle or story this should tell?

**Comment by PaulBarrett79** [comment]
Here is an example paper - the Chromohub utility that SGC Toronto wrote for examining phylogenetic trees

http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3928521/

To give an idea of what an academic paper for similar apps can look.

**Comment by aekhendry** [comment]
How do you want to proceed with this Paul? We had this discussion (loosely), can this issue be closed? I think just opening up the paper generically as an issue would be suitable?

**Comment by aekhendry** [comment]
I will be looking at this this week

**Comment by strets123** [comment]
OK, here are some notes on what Chembl have done over the years...

Web services paper published in nucleaic acids research
http://nar.oxfordjournals.org/content/43/W1/W612

Data paper with technical details published in nature scientific data (This is what we need to do for the SGC dataset)
http://www.nature.com/articles/sdata201532

Technical paper in bioinformatics
http://bioinformatics.oxfordjournals.org/content/30/2/298

**Comment by aekhendry** [comment]
This is on going. The first draft is now written and awaiting feedback

**Comment by aekhendry** [comment]
Second draft now out for review

**Comment by KarenPorter** [comment]
therefore closing
