### ISSUE TITLE
Create a set of tutorials for data management in cheminformatics/chemical biology

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#583]
This would be a great way to promote our project and would be a more authentic and less "marketing" way to approach groups at other universities - we say we will run a workshop for them.

We can use the building of this course as a way to maintain engagement with the Chembl team - get them blogging about it and contributing etc.

I can also approach the 250+ data carpentry instructors around the world who would hopefully recommend good research groups to approach.

**Comment by aekhendry** [comment]
I'm working on this as part of a lecture I'll be giving in Dec
