### ISSUE TITLE
3 day's work prepping for and documenting what comes out of our meetings with PubChem and ChEMBL

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#588]

**Comment by PaulBarrett79** [comment]
And attending meetings themselves.

**Comment by PaulBarrett79** [comment]
I created a document for our PubChem meeting containing my notes at the time. S:\OxChemBioDB\Meeting Notes\PubChem Conversation Notes.txt

**Comment by KarenPorter** [comment]
If there are any PubChem ideas which should be reflected in our issues backlog can you please create those too. @paulbarrett79

**Comment by PaulBarrett79** [comment]
ChEMBL meeting notes at:
S:\OxChemBioDB\Meeting Notes\ChEMBL Conversation Notes.txt
