### ISSUE TITLE
Search bug - hang over from previous search stops new search from working as desired

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#589]
I click search in project view. I type hello. hello appears in the drop down as the name of both an assay and a subproject. I click the assay option. Takes me to search page, data is displayed correctly. I click on search page search bar at the top of the screen. I type hello. This time i select the sub project. It takes me to the results, but the assay part of the search query remains, and therefore misrepresents what should have been displayed (i.e. a search query pertaining to the sub-project 'hello', not also including the assay 'hello')

**Comment by aekhendry** [comment]
tag new chrome

**Comment by strets123** [comment]
Now fixed for next deploy

**Comment by aekhendry** [comment]
Fixed tested on TagNew Chrome
