### ISSUE TITLE
Permissions model changes on ChemReg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#591]
• Compartmentalisation of project is necessary i.e. some columns are hidden / editable, others are not depending on your permissions.

**Comment by PaulBarrett79** [comment]
Requires field group, implemented as part of #585

**Comment by aekhendry** [comment]
Changed our mind, will do this on its own

**Comment by strets123** [comment]
Tasks are as follows:

- [x] Implement tickbox field in the model for a field to do this and expose in django admin
- [ ] Make this work for custom field config on chemreg
- [ ] Add extra information when indexing a compound
- [ ] Add appropriate exclude fields statement to

**Comment by strets123** [comment]
Looking at the above tasks it became clear that the code for being certain that a particular user was definately not able to search through a given field was going to take a long time to implement and test and could put at risk some stable apis.

**Comment by strets123** [comment]
Therefore it was decided to use a different strategy and to index each compound twice - once for each permission level. 

This has the advantage of simplifying the implementation and building upon what is already there. The trade off is slightly more resource usage but this will not be a problem for a long time if ever on the size of datasets we are typically dealing with.

**Comment by strets123** [comment]
The new task list is therefore:

-[x] Implement tickbox field in the model for a field to do this and expose in django admin
-[x] Add a field "viewer_version" in the index and add a new viewer version of the document to the index as it is created 
-[x] make the above into a hook on the data that is being indexed
-[x] Add an extra check when retrieving data to use the new field

**Comment by strets123** [comment]
Currently deployed to hubtest is a cosmetic fix that does hide the appropriate columns from the user. However, missing from that is the full backend implementation so the fields in the project data fields dropdown will still be visible at this time.

In order to confirm that this part works...

Create a new user who is a viewer of a project
mark a field on that project as restricted
login as the new user
you will not see the field in the table view but will see it in the other views

**Comment by strets123** [comment]
I also looked into the permissions API on elasticsearch but this would necessitate almost creating a role per user on our system which is too many roles and too much configuration management in my opinion. Easier to just index the data twice. We can revisit if there is a real data size issue

**Comment by KarenPorter** [comment]
Tested - passed as implemented
