### ISSUE TITLE
Draw structures into chemReg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#593]
• Ability to draw new structures into system (like we had before)

**Comment by PaulBarrett79** [comment]
Part of feature field - #585

**Comment by strets123** [comment]
Now ready to add fore chemreg but back end will need some work - how are we doing it? Will SDF be submitted like an sdf file and a temporary datastore created?

**Comment by PaulBarrett79** [comment]
Yes, SDF submission - as close to the multi upload process as possible to reuse existing, working code and minimise duplication of effort.

[ ] - Analyse old single-upload/sketch page to see what is still useable (if anything). Could also analyse single-molecule view popup to see if anything from there can be repurposed
[ ] - Set up using project fields within page for submission (possible reuse of single molecule edit mode components)
[ ] - Addition of supplementary fields
[ ] - Validation?
[ ] - Connection to back end via web service
[ ] - Integration into existing molecule save architecture
[ ] - Return messages to front end - errors warnings etc
[ ] - Redirection flow

**Comment by PaulBarrett79** [comment]
I have to add some more links to the system to actually get to this page.

Also add an extra link to the "would you like to add more compounds" that allows re-entry to this page.

**Comment by PaulBarrett79** [comment]
Pushed to github

Steps to reproduce:
Log in, get to project list
For a project with show compounds set to true, click the Draw Compound link
On the resulting page, add project fields, supplementary fields as directed/necessary
Draw your structure. When you have finished, click Validate Compound
For a valid structure, you will see either a green message (valid/no overlap), a blue message (valid/overlap), or a red message (invalid structure or valency error)
If your structure is invalid, make changes to make it valid then re-press Valaidate Compound
If your structure is valid, a "Save Strcutre button will appear. Click this to save your structure.

You are then forwarded to the search page in the saem way as when you add compounds via file.

**Comment by PaulBarrett79** [comment]
Deployed to chembiohub.ox.ac.uk/hubtest

**Comment by PaulBarrett79** [comment]
Found a bug with integer/decimal project field types - now fixed on hubtest.

Steps to test remain the same.

**Comment by KarenPorter** [comment]
When I add a new structure the search results page I land on has a broken ChemDoodle toolbar (not like that when I arrive directly).

From results page I can't link directly back to 'add another single structure'

When I add a compound and am taken to the search results, there's a filter on the relevant multiple batch id to show just this result which is great, but ten non-intuitive tat I need to expand the search form and remove the batch id in order to see the compounds in this project.   No functional error here but not optimal UX imo.

**Comment by KarenPorter** [comment]
I don't see how to add Project Fields along with the compound.  There's no button, only for supplementary fields.  Need to be able to test the bug Paul has identified and reported fixed.

**Comment by KarenPorter** [comment]
Nothing happens when i click the link here - If you want to add more than one compound at a time via SD or Excel, please use this form

**Comment by PaulBarrett79** [comment]
To address these concerns:

- Search form is hidden when saving your drawn molecule - easier to see the single item and the "compound saved below" message together
- Fixed "SD or Excel" cross-link
- Project Fields section is now hidden if no fields have been configured for that project
- Added a Drawn Another Structure link to the search page when you have drawn a structure

Available for testing on hubtest

**Comment by strets123** [comment]
Note that I have now fixed the remaining crosslinks from the search page and deployed to hubtest

**Comment by aekhendry** [comment]
Works, looks good. Checked links that I could find as well. HubTest Chrome
