### ISSUE TITLE
Table in ChemReg looks buggy following file upload

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#594]
• The table view can be buggy. It often doesn’t line up properly with the header text. Is there a limit to the number of columns table view can handle? Currently seems to be breaking when presented with too much.

**Comment by PaulBarrett79** [comment]
Finished - please retest

**Comment by aekhendry** [comment]
I'm getting some really strange behaviour on this one. Testing on tag new chemreg I upload a file that i know give poor table behaviour in hub (emailed to devs). File previews ok but cuts off about a half of the columns. Weirdly I can scroll across as thought the missing columns are there. At some point (cant tell when) the missing columns reappear with data. I scroll across but note that the table headings do not remain static and so quickly the headings are out of sync with the data.

**Comment by PaulBarrett79** [comment]
Numerical cells containing "~ 22 kDa"

**Comment by PaulBarrett79** [comment]
Think this may be to do with handsontable needing a fully visible div at the time of loading - all the data is there in the background, it is just not rendered.

Looking at a way of pinning search form and header to a fixed position and letting the table be unconstrained - gives the user the impression that the table is scrolling but it is in fact the page itself.

**Comment by PaulBarrett79** [comment]
This may be solved by re-adding the double scroll plugin. We originally removed it becuase of all the tab;e header/filter functionality - which we've since changed for IE compatibility.

Testing the file on Andrew's system looks good so far for the speciment file which Adam sent through and was causing issue.

**Comment by PaulBarrett79** [comment]
This has indeed fixed the issue for the given file (and other files with a large number of columns).

Add compounds
Upload excel files with a large number of columns (> 20)
All columns are displayed correctly and table is scrollable.

Deployed to staging/tagnew

**Comment by aekhendry** [comment]
Fixed. tested on tag new chrome
