### ISSUE TITLE
Raise cap on number of entries in a file upload - ChemReg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#595]
• Can we raise the cap on number of entries add at a time?

**Comment by PaulBarrett79** [comment]
We can raise this for inventory projects but not chem projects - up to 5000 is probably possible.

**Comment by PaulBarrett79** [comment]
Raised cap for excel uploads if the project is of type inventory

Add compounds
Upload excel file with more than 1000 but fewer than 5000 records
Upload should proceed without error.

Deployed to staging/sandbox

**Comment by aekhendry** [comment]
Does not appear to be fixed, I get an error when uploading a file that has over 1000 entries in an inv project. 

"File cannot be processed even though the format appears valid. If you have questions please contact the ChemBio Hub team."

I have sent the testing file to devs.

Sandbox, chrome.

**Comment by PaulBarrett79** [comment]
Apologies, had only pushed this to assayreg.

Now applied to chemreg

Deployed to staging/sandbox

**Comment by aekhendry** [comment]
I get a 502 error when trying to upload the "all" tab in the previous file I sent you. Around 4500 entries in the example. Worked for 2000 entries. Chrome sandbox

**Comment by PaulBarrett79** [comment]
In that case the system can only handle 2000 entries before timing out. So that's what we can only raise the limit to. The limit was there to stop the system timing out past the point of no return.

**Comment by aekhendry** [comment]
OK in which case i'll try with 3000 and see what happens.

**Comment by aekhendry** [comment]
Times out on 3000 as well. Retried with 2000 and works fine. in which case could you set the max as 2000 please.

**Comment by PaulBarrett79** [comment]
Will do.

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox (chemreg instance)

Will display "file too large" warning for excel files containing more than 2000 records.

**Comment by aekhendry** [comment]
Didnt get that warning im afraid, i got: File cannot be processed even though the format appears valid. If you have questions please contact the ChemBio Hub team.

**Comment by PaulBarrett79** [comment]
Added a message entry to messagefactory.js, there wasn't one for the case where there are too many entries.

Add compounds
Upload excel file with more than 2000 records
Upload will be prevented and a suitable error message will be displayed explaining there are too many records and the user should consider splitting file.

Pushed to github for both ChemReg and AssayReg.

**Comment by PaulBarrett79** [comment]
This is still awaiting a deployment

**Comment by PaulBarrett79** [comment]
Deployed to staging/tagnew

**Comment by aekhendry** [comment]
I'm still seeing the same : File cannot be processed even though the format appears valid. If you have questions please contact the ChemBio Hub team. Sending example file again. tagnew chrome

**Comment by PaulBarrett79** [comment]
Moving back to testing - there has been a subsequent deployment which means this is now testable and verifiable

**Comment by aekhendry** [comment]
fIXED TAG NEW
