### ISSUE TITLE
ChemReg: ability to sort project page projects in a meaningful way

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#596]
• Ability to sort / organise projects in project overview.

**Comment by PaulBarrett79** [comment]
Add simple search bar?

**Comment by aekhendry** [comment]
Not sure why this is in testing?

**Comment by aekhendry** [comment]
Not sure why this is in testing, moved back to code review

**Comment by strets123** [comment]
We want you to tell us if a simple search bar will satisfy your requirements

**Comment by aekhendry** [comment]
Yes that will be fine

**Comment by strets123** [comment]
Also need to add more relevant links and make the links more visible e.g.

My Assays
My Compounds
Project Compounds
Add Compounds

etc.

**Comment by PaulBarrett79** [comment]
In order to accomplish this, I think we need to remove the idea of 4 columns of project boxes. These need to be rows, either in a table or full width boxes, to show the functionality and options to the user better.

**Comment by PaulBarrett79** [comment]
I've rearranged this page so that every project is a single row. Since we no longer have the preview window on the project page, this can be a big scrollable list. Happy to accept feedback on how this is laid out etc. Pushed to github.

**Comment by PaulBarrett79** [comment]
I note that there are some other suggestions to do with wording, I will try and integrate these.

**Comment by PaulBarrett79** [comment]
As directed by Adam, I have added a simple search bar to make this page more navigable.

Go to project list
Enter text in the box next to Find
The project list will be narrowed down to items with a match to the search text. This includes the project type, so typing "chem" will show chemical projects.

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
Got it now but I was confused as to which search box to use - change text on the 'Find' box to something like "Filter by project name".

Other than that I'm happy but needs Adam to confirm his requirements are met.

**Comment by PaulBarrett79** [comment]
I've changed the label text and also added a help button to explain how the box filters. Happy to revise the wording of either of these further.

Pushed to github

**Comment by strets123** [comment]
deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
I don't understand how filtering the project list for 'config' returns project 'Tag test attempt 2' along with 'Tag test config' as expected.

**Comment by PaulBarrett79** [comment]
It may be that 'config' is in the project key - this would trigger a hit. It may be possible to ignore the project key when performing the search _ I will investigate.

**Comment by strets123** [comment]
Search on just name

**Comment by PaulBarrett79** [comment]
Limited search to name only.

Go to project list page
Type search term in the Filter Project List box
Projects displayed which have this search term present in the project name.

Pushed to GitHub

**Comment by PaulBarrett79** [comment]
Available for testing on hubtest

**Comment by aekhendry** [comment]
Looks good, making as done. hubtest chrome

**Comment by strets123** [comment]
DEployed
