### ISSUE TITLE
no table headers when uploading compounds - assay reg tagnew

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#604]
• Added SDF file to assay reg project compound upload. The table following clicking save in the search page had no table headers at all.

**Comment by PaulBarrett79** [comment]
This is fixed on AssayReg staging/tagnew - please retest.

If it still fails please send us the SPECIFIC files which caused the bug.

**Comment by PaulBarrett79** [comment]
Work done: < 1 hour

**Comment by aekhendry** [comment]
Fixed, tested on tagnew
