### ISSUE TITLE
Where do customfields come from in compounds registered to assay reg - tag new?

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#605]
• Added SDF / excel file to assay reg project compound upload. I cannot map fields, no table header is available.  Following submission, I open compound up into single molecule view. I’m interested in where the fields I see attached to this compound come from? In ChemReg this makes sense as the project uploaded to is a static set of fields. This is not the case with Assay Reg which has multiple fields. Depending on the subproject, assay def and activities. Clarification needed.

**Comment by PaulBarrett79** [comment]
Add compounds needs verifying with IE fixes.

**Comment by aekhendry** [comment]
Closing as no longer relevant
