### ISSUE TITLE
Batch update button not working - assay reg tag new

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#606]
• Added SDF file to assay reg project compound upload. Following submission, I open compound up into single molecule view. The Batch update button appears to not be working. Nothing happens when I click it. I would expect it to update all the other compounds in this upload batch with the same new info I just added.

**Comment by strets123** [comment]
Fixed hub - when it says update batch it is updating the batch, not applying an update to all molecules in the upload

**Comment by aekhendry** [comment]
Please change the wording of the Button to 'Update'. i dont think it needs any more then that

**Comment by strets123** [comment]
pushed to github

**Comment by aekhendry** [comment]
Can't test fully until 804 has been resolved

**Comment by aekhendry** [comment]
Fixed chrome hubtest
