### ISSUE TITLE
too many decimals on MW for compounds registered to assay reg tagnew

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#607]
• Added SDF file to assay reg project compound upload. Following submission, some compounds molecular weight has an unnecessarily large amount of decimals. E.g. UOXCA72JJM in Test 1 project.

**Comment by PaulBarrett79** [comment]
Is data being textified before visualisation? Needs handling if not recognised as a decimal number.

**Comment by PaulBarrett79** [comment]
Moving back to backlog

**Comment by aekhendry** [comment]
closing as i cannot replicate this
