### ISSUE TITLE
Improvements to project view on assay reg tagnew

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#608]
• On project view, click search on the project button itself. Drop down shows search option for compounds only. 

o   Text in the drop down is right aligned, needs to be moved left
o   Text on the button itself is ambiguious. If all you can do is search compounds via here, then remove the drop down and word the button better to reflect its function.
o   Same goes for the Add+ button opposite

**Comment by PaulBarrett79** [comment]
I have changed the functionality of these button to Chem and Assay.

**Comment by aekhendry** [comment]
Looks good, marking as fixed. AssayReg tag new

**Comment by aekhendry** [comment]
Looks good, marking as fixed. Chrome TagNew
