### ISSUE TITLE
[Not an immediate blocker, but VERY irritating]: It MUST be possible to copy/pas

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#61]
[Not an immediate blocker, but VERY irritating]: It MUST be possible to copy/paste IDs e.t.c. from the summary tables for the project. Right now, it’s not possible to mark ANYTHING from the table. Is this a ‘feature’ of the js library you are using? If so, it is a big blocker. A response of ‘just export to Excel’ is not valid – that’s too much effort. We must make things easy for the user if we want good adoption.

date recorded in spreadsheet: 31/03/2015 13:42:40

comments from spreadsheet:
PS - need to analyse how much time this would take to replace ui-grid with a "better" angular grid (or our own solution). Currently this would be a low priority or feature request - it WILL be addressed in a future version however.

**Comment by aekhendry** [comment]
Fixed with new table
