### ISSUE TITLE
Clarification on users uploading compound to chemreg and assay reg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#610]
• Will we be integrating ChemReg project structures fully with assay reg, or will they be expected to upload their compounds twice? Im not a fan of the latter, that’s poor usability to me and highlights an inability to link our systems. The same goes the other way, if you register compounds to a project you should be able to nominate a ChemReg (or multiple projects) you wish to deposit to as well.

**Comment by PaulBarrett79** [comment]
Linked to #585

**Comment by strets123** [comment]
We will do assay registration in chemireg as the changes to assayreg required are too big and ChemiReg does nearly everything already
