### ISSUE TITLE
compound search bug in assay reg tagnew

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#611]
• In compound search if I search for a compound that does not exist in the project it locks the page and goes into an infinite loop (at least it looks that way). Note that this also happens if I search with or without specifying a project

**Comment by strets123** [comment]
I believe this is now fixed. I have not yet created a way to see the images on existing compounds but you should see that it works foir new compounds that you register.

**Comment by aekhendry** [comment]
Original described bug has been fixed. Tested tagnew chrome
