### ISSUE TITLE
Filed name in activities values bug assay reg tag new

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#615]
• I upload a file containing activities. There are two fields (Field 1, Field 2), each containing 10 rows of text data. In Field 1, one of the ‘results’ matches the field name (one of the Field 1 activities in the cell is called ‘Field 1’). I click save. I get some very strange behaviour and the data displayed is in the wrong order and columns to that in the original file.

**Comment by PaulBarrett79** [comment]
Pandas bug.

**Comment by aekhendry** [comment]
Fixed, tagnew chrome

**Comment by strets123** [comment]
Marking as done but not sure what changed
