### ISSUE TITLE
Some structures cannot be uploaded to ChemReg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#618]
ChemReg file upload breaks when presented with some specific structures. The file cannot be recognised. As a temporary measure, Paul has allowed it so that the file can be uploaded but the error causing structures are ignored. Compounds containing distance bonds and / or certain small Ion molecules seem to set it off.

Examples are on the server.

S:\OxChemBioDB\Broken Compound examples

**Comment by PaulBarrett79** [comment]
Workaround is to allow upload without a structure. Maybe report that there was an RDKit error when registering?

Again, has this been fixed in a newer version of RDKit? Write up examples for RDKit mailing list.

**Comment by PaulBarrett79** [comment]
Re. Newer version of RDKit: There is one available. The version we are running is from 1/3/2014. The stable version available is 1/3/2015.

It requests to downgrade numpy - this is the output while attempting upgrade with conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-1.56.0               |           py27_1         7.2 MB
    numpy-1.9.3                |           py27_0         5.7 MB
    rdkit-2015.03.1            |       np19py27_0        16.1 MB
    ------------------------------------------------------------
                                           Total:        28.9 MB

The following packages will be UPDATED:

    boost: 1.55.0-py27_2        --> 1.56.0-py27_1       
    rdkit: 2014.03.1-np18py27_2 --> 2015.03.1-np19py27_0

The following packages will be DOWNGRADED:

    numpy: 1.10.1-py27_0        --> 1.9.3-py27_0  :

**Comment by PaulBarrett79** [comment]
Our current anaconda config specifies numpy=1.8.2=py27_0

**Comment by PaulBarrett79** [comment]
RDKit upgrade successfully registers troublesome 8 membered ring.

**Comment by strets123** [comment]
Great, we can address any install issues related to the numpy version in
the next sprint.

**Comment by PaulBarrett79** [comment]
I have modified the backend code so that structures which cannot be parsed, such as with distance bonds etc, basically become blinded compounds so that at least all the metadata can be added.

Load an SDF file containing issue-causing compounds
File will load and display in the preview with metadata shown.
Ignore is selected by default BUT you are now able to override this and select New Batch to add as a blinded compound.
Clicking save when these steps are followed saves the molecule.

**Comment by PaulBarrett79** [comment]
Pushed to github

**Comment by PaulBarrett79** [comment]
Some molecules are unprocessable by either RDKit or PyBel/OpenBabel . In the case of these, we need to retrieve the metadata from the ctab text via regular expression.

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox

**Comment by aekhendry** [comment]
Failed, Paul and Andy are investigating. Number of compounds in preview to not much the actual number being saved. This behaviour is definietly from the new code as this does not happen in hub. Also, while it worked for a while it is now not uploading previously reported problem compounds. It simply reports uploading 0 entries despite providing an upload number

**Comment by PaulBarrett79** [comment]
Myself and Andrew assessed this and found the counts to be correct. We have however made a change which was stopping some structures being uploaded.

Upload counts should now be correct. Uploads now work consistently.

This is available to test on staging/sandbox

**Comment by aekhendry** [comment]
This is fixed. Tried uploading all broken compounds. They are ignored if broken. Selecting 'add new batch' will register their metadata but not their structure as described. One issue was reported that is being dealt with separately, see issue 657.
