### ISSUE TITLE
8 sided ring file upload bug - ChemReg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#619]
I upload a file containing a single 8 sided ring with one or more double bonds. The file will preview, but clicking save causes an infinite loop that freezes the screen. ChemReg on Hub

**Comment by PaulBarrett79** [comment]
RDKit bug. Is this fixed in a recent version of rdkit?

**Comment by strets123** [comment]
Outcome of sprint 1 = estimate or fix

**Comment by PaulBarrett79** [comment]
Conda install newer rdkit?

**Comment by PaulBarrett79** [comment]
Newer RDKit verdsion deals with this substructure with no issue.

**Comment by PaulBarrett79** [comment]
Pushed to github.

**Comment by PaulBarrett79** [comment]
RDKit upgrade potentially breaks the deployment and other functionality, on hold for now

**Comment by PaulBarrett79** [comment]
Moving to next sprint to give us enough time to check that no core functionality is broken by upgrading RDKit

**Comment by PaulBarrett79** [comment]
To throw a spanner in the works, there has been today another RDKit release. Do we risk moving to this instead?

**Comment by PaulBarrett79** [comment]
RDKit 2015.09.2 release deals with the 8 membered ring correctly locally while using ChemReg functionality within AssayReg.

We now have to evaluate whether this breaks a deployment or not.

**Comment by PaulBarrett79** [comment]
Doesn't break deployment or any other functionality, fixes 8 sided ring bug.

Deployed to staging/chembiohub

**Comment by aekhendry** [comment]
Tested on Chembiohub, chrome

**Comment by strets123** [comment]
deployed
