### ISSUE TITLE
Dunn school orders system

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#620]
We have been given an opportunity to create the Dunn school order system. Can we make a decision on how realistic it is we will engage with them?

**Comment by aekhendry** [comment]
Requirements can be found here:

https://docs.google.com/document/d/1cTDXQchs3U-xbpF2tbjRrAwdNOse0-eg2dZd5FenrQo/edit

**Comment by PaulBarrett79** [comment]
Schedule in a discussion about what is expected and the effort involved.

**Comment by strets123** [comment]
Research done and document produced

**Comment by strets123** [comment]
Paul and I have both reviewed this document and we are happy that the costs provided are accurate.

**Comment by aekhendry** [comment]
There is a separate issue raised dealing with the next steps of this
