### ISSUE TITLE
Analyse compound search capabilities on ChemReg (ref Anderson feedback)

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#621]
When I searched for the first entry (diphenyldichlorosilane) but used methyl groups instead of phenyls (i.e. free sites on a single carbon atom adjacent to the silicon), it did not pick up diphenyldichlorosilane, and it probably ought to. I mention this as it might be that the search engine cannot cope with aliphatic / saturated vs aromatic / unsaturated in a free sites search.

**Comment by PaulBarrett79** [comment]
Needs 1 day to research a solution

**Comment by PaulBarrett79** [comment]
Putting this back to next sprint

**Comment by aekhendry** [comment]
I have a meeting with Anderson next week, it would be good to give an update on this

**Comment by strets123** [comment]
Analyse SMARTS vs SMILES, new RDKit Version, and chemdoodle (query mode in chemdoodle 7)

**Comment by strets123** [comment]
I have now added a fix that ensures any terminal carbon atom apart from those in ethane which is very short, get queried as a generic carbon atom. This means the substructure matching picks up the diphenyldichlorosilane molecule requested by Ed. The proof can be seen at this URL: http://staging.chembiohub.ox.ac.uk/chembiohub/#/search?archived=false&with_substructure=Molecule%20from%20ChemDoodle%20Web%20Components%0A%0Ahttp:%252F%252Fwww.ichemlabs.com%0A%20%205%20%204%20%200%20%200%20%200%20%200%20%20%20%20%20%20%20%20%20%20%20%20999%20V2000%0A%20%20%20%200.0000%20%20%20%200.2500%20%20%20%200.0000%20Si%20%200%20%200%20%200%20%200%20%200%20%200%0A%20%20%20%200.8660%20%20%20%200.7500%20%20%20%200.0000%20Cl%20%200%20%200%20%200%20%200%20%200%20%200%0A%20%20%20-0.8660%20%20%20%200.7500%20%20%20%200.0000%20C%20%20%200%20%200%20%200%20%200%20%200%20%200%0A%20%20%20-0.0000%20%20%20-0.7500%20%20%20%200.0000%20C%20%20%200%20%200%20%200%20%200%20%200%20%200%0A%20%20%20%200.8660%20%20%20-0.2500%20%20%20%200.0000%20Cl%20%200%20%200%20%200%20%200%20%200%20%200%0A%20%201%20%2021%20%200%20%20%20%20%200%20%200%0A%20%201%20%2031%20%200%20%20%20%20%200%20%200%0A%20%201%20%2041%20%200%20%20%20%20%200%20%200%0A%20%201%20%2051%20%200%20%20%20%20%200%20%200%0AM%20%20END&doScroll=true

**Comment by strets123** [comment]
There were however some other bugs when I played with substructure searching - the buttons don't select properly, if you delete wour molecule you get a different result AND, certain combinations of keypress such as in the popups on periodic table dont always work.

**Comment by strets123** [comment]
Recommend  installing chemdoodle 7 via the CDN and using a different code structure that I have developed today while investigating.

To integrate all of these changes will take a day. To do this and make adding single compounds possible will take 1.5 days.

**Comment by aekhendry** [comment]
I am marking this issues as fixed, your comments (Andy) have been moved to a relavnt outstanding issue (514)

**Comment by strets123** [comment]
Closing for now
