### ISSUE TITLE
A robust way to link in image files

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#622]
The ability to link in files, particularly image files, is something that would be of a huge benifit to the system

**Comment by PaulBarrett79** [comment]
@aekhendry How do you see a bulk image upload working?

**Comment by KarenPorter** [comment]
@PaulBarrett79 I think this is now addressed in 800?  please confirm and close if appropriate or update with outstanding proposal for work needed.

**Comment by aekhendry** [comment]
closing as covered in 800
