### ISSUE TITLE
Archive functionality in ChemReg is not good enough

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#623]
It works. But if you have a archive 2 or more entries it is very tedious. There should be a way to flag all the ones you want to remove and then archive them all at once.

**Comment by PaulBarrett79** [comment]
Enable fill down for archive column

**Comment by PaulBarrett79** [comment]
Fill down now enabled for archive button column.

Highlight the cell you want to drag down from, drag the bottom right hand corner of the cell down. Selected cells will reflect the cell you have dragged from and will still be independently clickable.

Pushed to github, awaiting deployment to staging.

**Comment by PaulBarrett79** [comment]
Time taken:3 hours

**Comment by aekhendry** [comment]
Where has this been deployed to?

**Comment by strets123** [comment]
Tagnew, see the compound search view when only 1 project is selected and you have editor rights

**Comment by aekhendry** [comment]
It works. I click and drag down and it changes the tag from archive to restore accordingly. However after doing this if I click on the bottom most entry that is now to be archived, the page jumps to the bottom and nothing happens. In other words I cannot continue to drag and drop after doing it the first time. This is important as i may want to do this process for a large number of entries. Tested TagNew chrome.

**Comment by PaulBarrett79** [comment]
Something funny going on with subsequent actions after one drag has been performed. One single drag seems to work fine.

**Comment by PaulBarrett79** [comment]
This glitch is fixed by upgrading to Handsontable version 0.20.0 (from 0.15)

Verifying that this does not break any other existing functionality.

**Comment by PaulBarrett79** [comment]
Existing functionality not affected - pushing to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/sandbox

**Comment by aekhendry** [comment]
Tested on sandbox, still works and additional bug is no longer present

**Comment by strets123** [comment]
marked as done but new issue for handsontable upgrade
