### ISSUE TITLE
Make assayreg and chemreg enable and disable at the user level

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#625]

**Comment by strets123** [comment]
This is now deployed to tagnew. In order to deactivate a particular user from chemreg 

remove superuser permissions
add the permission called

_can_see | Apps which the user can see | ChemReg Disabled

or do the converse permission in order to disbale assayreg.

Things that have been disabled are:

the links on the project list page

the links in the top search bar

There may be other things to cut out that I have not thought of

**Comment by aekhendry** [comment]
I need to test this alongside Karen, Will wait till tomorrow (12/11/15)

**Comment by aekhendry** [comment]
Works, Looks good! Tag New assayreg
