### ISSUE TITLE
2) Instant search without having to click search with a search bar at the top of the table like on assayreg (content at bottom should change and URL should change without having to click search)

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#626]

**Comment by strets123** [comment]
This does not cover custom fields search or toolbar search, they are dealt with later

**Comment by strets123** [comment]
Completed most of the code changes needed for this but was bigger than I thought as there were things that needed tidying up on the way. We now have a search page that does not refresh itself when you press search.

**Comment by strets123** [comment]
Now deployed to tagnew. You can search using any of the fields that are present in the chemreg search page. In order to structure search you must click the button.

**Comment by aekhendry** [comment]
Works. The page does jump around alot as I'm typing the text in, but it's very quick. Is there any quick way to stop this? If not I'll report it as a seperate issue and mark this as done, as overall the functionality is excellent

**Comment by aekhendry** [comment]
Fixed, very nice. TagNew Chrome
