### ISSUE TITLE
assay reg tables

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#628]
Assay Reg Tables need a scroll bar (for left/right scrolling) at the top as well as the bottom. Otherwise i cannot see the column headings and scroll across at the same time.

**Comment by strets123** [comment]
Please take a look at google sheets and say  if the gutter scrollbar in google sheets is suitable. This is easier to make work across the site

**Comment by aekhendry** [comment]
It's better then what we have now so yes. Ideally you want to be able to scroll X or Y and always be able to see the field headings. Google sheets allows you to freeze the headings to allow you to do this. Perhaps this is too much to ask of our system?

**Comment by strets123** [comment]
Mothballed
