### ISSUE TITLE
Title field needs to be compulsary for all custom field configurations, including assay def and activity

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#629]
Other then the obvious benifits for having titles for a groups of activities, I have also found that without one you cannot effectively search for them. So for example I have two assays with two different sets of sctivites. One of these sets of activities has a title, the other does not. when searching through advanced search, I will only be able to find the activities with a title. I thin this should perhaps go beyond including it in the custom field config and prompt the user on file upload. This would ensure compliance.

**Comment by strets123** [comment]
Rejected for 
November as best done when the admin UI is re done

**Comment by strets123** [comment]
Fixign by moving Assay data to ChemiReg
