### ISSUE TITLE
Inchi upload issue

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#63]
This potssasium salt was processed differently dependent on if it came via chemdraw or via molfile. See 2 inchis below

InChI=1S/C19H21N3O3.K/c23-18(12-15-4-2-1-3-5-15)22-10-8-21(9-11-22)14-17-13-16(19(24)25)6-7-20-17;/h1-7,13H,8-12,14H2,(H,24,25);

InChI=1S/C19H21N3O3.K.H/c23-18(12-15-4-2-1-3-5-15)22-10-8-21(9-11-22)14-17-13-16(19(24)25)6-7-20-17;;/h1-7,13H,8-12,14H2,(H,24,25);;

date recorded in spreadsheet: 02/04/2015 15:36:07

**Comment by PaulBarrett79** [comment]
Is this still the case?

**Comment by KarenPorter** [comment]
@strets123 still outstanding?

**Comment by strets123** [comment]
Inchi upload does not work, also check above inchi

**Comment by strets123** [comment]
Marking as wont fix for now as chemdraw upload is sort of deprecated
