### ISSUE TITLE
Mapping icons need to be clearer in assay reg file upload

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#633]
Currently when submitting a file to assayreg it is hard to see which fields are mapped based on the colour of the icon. I would suggest making the arrows in the Icon white and the back ground either red or green based on whether they are mapped or not. Im marking this for this Sprint as i beleieve this should be very quick, change if this is not the case

**Comment by strets123** [comment]
Closing as we are mothballing this functionality
