### ISSUE TITLE
Large file upload (1000 row) breaks assayreg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#635]
I uploaded a file containing 1000 rows and i got a 502 error. It did once upload the file, but it registered 6000 entries instead of 1000 and the data was in the wrong columns. Since then i have not been able to repeat this, the file just wont load. (File has been sent to Andy - try it in Marsden project tm activities.) note that a file of 100 rows goes in fine. AssayReg

**Comment by aekhendry** [comment]
Fixed tag new

**Comment by strets123** [comment]
Timeouts were added up to 3 mins
