### ISSUE TITLE
File export in AssayReg changes order of columns

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#639]
When I export activities from project overview page, the columns are ordered alphabetically. They need to be displayed in the same order as they appear in the browser

**Comment by aekhendry** [comment]
Brian feedback

**Comment by KarenPorter** [comment]
@strets123 still outstanding?

**Comment by strets123** [comment]
Marking as uncommitted due to deprecation of assyreg
