### ISSUE TITLE
The project overview page for assay reg needs to be tidied up to improve clarity

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#640]
A better system is required to organise what we see. Currently it is visually very confusing. I think at each level the ability to collapse or expand the data would be useful. Titles should be mandatory for each level.

**Comment by aekhendry** [comment]
Brian feedback

**Comment by strets123** [comment]
Assayreg to be mothballed, ChemiReg search page much simpler
