### ISSUE TITLE
Table looks wrong when clicking view activity in search

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#641]
I'm searching marsden project - TM and then click view activities. Table is all out of whack. I'm sure this is related to the length of the sequence information in one of the fields.

**Comment by PaulBarrett79** [comment]
Added styling to the table to force "break-word" on long strings like sequences.

Search for Marsden project
Click first View Activities record
Modal window has table completely confined within the modal box.

Pushed to github

**Comment by strets123** [comment]
deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
passed.
