### ISSUE TITLE
Table headers add more filters and mapping messages when selecting from the Action dropdown

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#643]
Load file
In the preview table click the Action dropdown in any row.
Make any selection or click away
Table header displays multiple filters and mapping messages

**Comment by PaulBarrett79** [comment]
Condition for looking for a button as the last child of the column header does not work for the mapping/preview tables as the mapping message is the last child. Changed to check for existence of button.

Pushed to Github

**Comment by PaulBarrett79** [comment]
Deployed to staging/tagnew (assayreg) and also staging/sandbox (chemreg)

**Comment by PaulBarrett79** [comment]
Steps to reproduce:

Go to any chemical project and select Add Compounds
Add either a valid file or a list of SMILES
In the preview table, click one of the table filters in the column header then close the popup.
The problem manifested itself as showing 2 filter buttons and any associated messages (Unmapped etc) would also display twice.

Issue is fixed because opening and closing the filter popup no longer replicates the filter button or header messages.

**Comment by KarenPorter** [comment]
Tested and passed (this strict test for behaviour) in tagnew.

However, failed because the SMILES I added are all not -processable.  I added the simplest molecules - cc, ccc and cccc.  I am unaware of when this was introduced or what it relates to - probably not associated with this resolution - please confirm and raise a new ticket if appropriate.

**Comment by PaulBarrett79** [comment]
Unprocessable molcules are now available to process as blinded compounds (to allow addition of records with metadata) in line with Adam's requests for this sprint. We may need to revisit whether this becomes the case for SMILES which have no metadata by definition - this is best up for discussion.

This as far as I can tell does not affect this issue directly so I will raise a new card.

**Comment by PaulBarrett79** [comment]
Since this has already been marked as passing for this issue, moving back to awaiting testing.

**Comment by PaulBarrett79** [comment]
Added card #682 to record this question
