### ISSUE TITLE
Side scrollbar required at top of table in all case where new table format has been deployed

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#648]
Side scroll bar must be at the top, its really irritating having to go to the bottom of the table, scroll across, then scroll back up again to see the top half of the tables data. This is irritating enough to be considered important for November sprints.

**Comment by PaulBarrett79** [comment]
Added a method to add double scrollbar to the data overview tables.

Go to data overview
View a table with columns which scroll horizontally
Scrollbar should be visible and usable from the top of the table.

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
'Background Information' assay in JW project is an example where the filled portion of the scrollbar is different top and bottom - actually can only use the bottom scroll to get to RHS of table.

**Comment by PaulBarrett79** [comment]
Tech explanation - I had put the ID for the doubleScroll plugin to act on onto the containing div rather than the table itself.

Scrollbars are now of even size and position, and there is no indent on the top scrollbar any more.

Saved to github, awaiting deployment to staging

**Comment by strets123** [comment]
deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
The filled portion of the scrollbars is now the same top and bottom but the top one doesn't move the frame at all now.

**Comment by PaulBarrett79** [comment]
This has been fixed and is available for testing on hubtest

**Comment by strets123** [comment]
Also now deployed to hub

**Comment by aekhendry** [comment]
Works, but on hub side scroll bar is not being rendered properly, you only get half the thickness of the bar and it is positioned below the headers of the table. On hubtest it looks fine

**Comment by strets123** [comment]
Please test again on hub, should now all work fine

**Comment by aekhendry** [comment]
fixed, looks good. Hub chrome
