### ISSUE TITLE
AssayReg Upload bug - data saves but is not there

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#649]
I've uploaded some large files (column wise) into the wilding project on tagNew. At first i thought they had not saved as after clicking save, the page refreshed and no values were shown. However when i went to upload a file again, the values appear. This happens before I even upload a file again, I just click add multiple submissions, select the file type and they appear. Once there, they stay there until i refresh the page and perform the same steps again.

**Comment by KarenPorter** [comment]
@aekhendry.  Is this still an issue?  Not sure why / how long it has been in Under Investigation but if it is in this category it should be assigned to someone - hence I've assigned you

**Comment by aekhendry** [comment]
closing as can't replicate
