### ISSUE TITLE
Export in AssayReg search requires improvement.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#651]
The current search results are not actually that useful. If i search for something that is a parttical match in lots of different fields it is not easy at all to see which of the results pulled back are the one I was looking for. Currently you have to click and open each activity one by one. Also if you search for an assay or several assays with the same (or very similar) assay definitions, it should really return the results as you would see them in the project overview.

**Comment by aekhendry** [comment]
Brian feedback

**Comment by strets123** [comment]
No longer relevant
