### ISSUE TITLE
User search in chemreg

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#652]

**Comment by strets123** [comment]
User search is now available, suggest that we add navigation links for my activities and my chemicals

**Comment by KarenPorter** [comment]
This is now a bit confused Andy.  Are you suggesting an issue to 'Add navigation links for my activities and my chemicals from AssayReg'?  In which case title needs to reflect this as 'User search in chemreg' doesn't imply what you are suggesting. @strets123

**Comment by strets123** [comment]
OK what I mean is that the state of the search form where you have added your name as the user should be accessible via a link on the project list page. This is an easy fix and would improve navigation on the system. You are right that this is not part of this issue so needs its own issue.

**Comment by strets123** [comment]
Let's start by testing that searching for compounds created by a user works in chemreg

**Comment by KarenPorter** [comment]
I've done that bit - it passes.  I was confused about why this was in the backlog list.  I'll forward it to awaiting deployment and raise a new issue.
