### ISSUE TITLE
UOX id search in chemreg not picking up blinded compounds

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#653]

**Comment by strets123** [comment]
Now fixed and awaiting test uox validation will cover all available uox ids that have not been archived - both blinded compounds and those with structures

**Comment by PaulBarrett79** [comment]
This has been deployed to staging/sandbox

**Comment by aekhendry** [comment]
No this is fine for the time being

**Comment by aekhendry** [comment]
Fixed tagnew chrome
