### ISSUE TITLE
Archived data being included in chemreg custom fields autocomplete

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#654]

**Comment by strets123** [comment]
autocomplete should now include all items that you have access to apart from archived items. Note that filtering down to the pre-selected items in search is not yet supported

**Comment by aekhendry** [comment]
I Have access to everything, I need to test this alongside Karen who I can give limited access

**Comment by aekhendry** [comment]
Tested on tag new
