### ISSUE TITLE
Add navigation links for my activities and my chemicals from AssayReg

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#656]
From the project list, add a quick link to 'my recent activities' and 'my chemicals'

**Comment by PaulBarrett79** [comment]
Added a working link for Chemicals/Inventory - user can click the link within the project list for a given project

Trying to work out how to do this for Assay as the project/l0 uri is unavailable from the project page, which is what the assay search page is expecting.

**Comment by PaulBarrett79** [comment]
I've added a links to search for "things I've added to this AssayReg project" and "things I've added to this ChemReg project".

Pushed to github.

**Comment by PaulBarrett79** [comment]
Deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
...but shows up now that what you can't see (in one step) is 'the compounds in this project'.  You can get to it from My Data then removing the userid filter but there isn't a compound overview (cf Assay Data / Data Overview)

**Comment by PaulBarrett79** [comment]
You can but it is labelled somewhat badly - the View / Add Single performs this.

Maybe two separate links, even if they go to the same place?

**Comment by KarenPorter** [comment]
label is definitely confusing in that there is no specific functionality to 'add single compounds' via that link - from results page you can only go to the /addcompounds page and add a file or SMILE / InChi, which is the same as clicking from list page through add multiple compounds.

I would suggest mirroring assay data options with:  View all compounds, My data, and Add compounds options in that order.

**Comment by strets123** [comment]
OK, changes to wording and order (search my data)

**Comment by PaulBarrett79** [comment]
Changed wording as directed.

Pushed to GitHub

**Comment by PaulBarrett79** [comment]
Available for testing on hubtest

**Comment by aekhendry** [comment]
Fixed, hub chrome
