### ISSUE TITLE
Saving when attempting to submit only ignored compounds locks the system up

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#657]
I Submit a file with a broken compound. In preview, I do not change the apply fucntion from ignore to save. i click Save, the system locks up and I get a 500 error. You should not be allowed to click save unless one of the compounds being previewed is not being ignored.

**Comment by aekhendry** [comment]
Tested on Sandbox, chrome

**Comment by PaulBarrett79** [comment]
Investigating

**Comment by PaulBarrett79** [comment]
Button now disabled when there are no compounds marked to upload i.e. no new batches.

Upload compounds
select all to be ignored
Save button now disabled.

Deployed to staging/sandbox

**Comment by PaulBarrett79** [comment]
Note this is an additional task added after Adam's testing.

**Comment by aekhendry** [comment]
Works, sandbox Chrome
