### ISSUE TITLE
On all browsers on mac, table data is not being displayed correctly in ChemReg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#658]
On Mac browsers (Safari, Firefox and Chrome), the new table is not displaying all of the available data on hub. The CJS compound project has four field headings at the end of the table - CAS, MW, Formula and Mol ID. The headings are there, but the data below them is not. The table actually ends completely before these heading, the gridlines are not present either. Not that these issues cannot be replicated in any of the browsers on Windows

**Comment by aekhendry** [comment]
Tested on Hub, Safari, Firefox and Chrome on OSX (all up to date).

**Comment by PaulBarrett79** [comment]
Due to Handsontable needing upgrade. Covered by issue #699.

**Comment by PaulBarrett79** [comment]
And in turn covered by #694

**Comment by strets123** [comment]
Should now all be fixed

**Comment by aekhendry** [comment]
Tested and fixed. Chrome/safari/firefox mac osx
