### ISSUE TITLE
Show / hide the compound search interface

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#659]

**Comment by strets123** [comment]
Added a show/hide button to allow user to page through results more easily and to give them a way to see their newly added compounds without an irrelevant search form

**Comment by KarenPorter** [comment]
on behalf of strets123 - 
button is available.  Logic added to open & close view search form.  Hides when navigating direct from project list.

Ready to test.

**Comment by KarenPorter** [comment]
Some issues identified in test with Andy and me reviewing behaviour. 

Also, feels odd to be able to edit and add at the same time - I can select both and have the table in edit mode while I add a new record.

**Comment by KarenPorter** [comment]
button says 'show search from' rather than 'show search form'

**Comment by strets123** [comment]
fixed
