### ISSUE TITLE
Add enable/disable archive mode on chemreg search page

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#660]
As part of the search form their is now a switch for archive mode. In addition there is an extra button in the table header to disable archive mode when it is on

**Comment by KarenPorter** [comment]
this sounds like it's a 'done' - is it in the right column?  Showing under backlog still @strets123

**Comment by aekhendry** [comment]
I can't see this? You may have to show me. looking on tag new

**Comment by aekhendry** [comment]
Fixed tag new chrome
