### ISSUE TITLE
Numbers on uploaded data display look buggy

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#661]
Whenever you up load a file into the system you typical get data at the top that tells you how many are overlaps, unique etc. If these number exceed two digits then they often are not displayed correctly. When the most atheistically attractive feature on the page looks broken it does not sit well with new users. Could we please reformat this so that it is presented correctly, preferably before i start showing it to DPAG. I would sugget replacing the circles with rectangles, this should make life easier.

Chrome Hub, Although i believe it is consistent across all our instances.

**Comment by strets123** [comment]
duplicate
