### ISSUE TITLE
The numbers on the file upload data display could be presented better

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#662]
Whenever you up load a file into the system you typical get data at the top that tells you how many are overlaps, unique etc. If these number exceed two digits then they often are not displayed correctly. When the most atheistically attractive feature on the page looks broken it does not sit well with new users. Could we please reformat this so that it is presented correctly, preferably before i start showing it to DPAG. I would sugget replacing the circles with rectangles, this should make life easier.

Chrome Hub, Although i believe it is consistent across all our instances.

**Comment by strets123** [comment]
duplicate

**Comment by PaulBarrett79** [comment]
I've changed these from circles to lozenges and lowered the font size - these will comfortably accommodate 4 digit numbers (this is within the parameters of what the system will allow)

**Comment by PaulBarrett79** [comment]
pushed to github

**Comment by aekhendry** [comment]
Fixed, working on Hub marking as done
