### ISSUE TITLE
Explanation of automatically ignoring broken compounds on file upload.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#664]
When you upload a file with a broken compound it is uploaded but automatically set to ignore. A better system needs to be in place explaining this and potentially directing you to the compounds in question. Similarly, if you upload compounds that are all set to ignore you cannot click save. This also needs to be explained

**Comment by strets123** [comment]
Please learn to spell

**Comment by PaulBarrett79** [comment]
Added a message informing why the Save button has been disabled if all records are marked as ignore

**Comment by PaulBarrett79** [comment]
Added a button "What do the different statuses mean?" at the top of the upload preview table, next to the Remove Filter buttons,  which launches a popup containing the explanations for both the Info and Action columns. 

I am happy to change the wording for any of these explanations to something more suitable.

**Comment by PaulBarrett79** [comment]
pushed to github

**Comment by aekhendry** [comment]
There is a typo in the what do different statuses mean text: the structural position will be ignored but a record will 

Duplicated values text change: This data has been added previously with the exact same fields and values to this project.

New text change: The data has not been added to any project you have access to previously.

Is it possible to have a (if you have any further questions please contact us here: link) like thing at the bottom of the box?

**Comment by PaulBarrett79** [comment]
Changes made - pushed to github

**Comment by PaulBarrett79** [comment]
I have also added the email link as requested

**Comment by strets123** [comment]
deployed to staging/chembiohub

**Comment by aekhendry** [comment]
Looks good, marking as fixed. Chembiohub chrome

**Comment by strets123** [comment]
deployed
