### ISSUE TITLE
Decide on the administrator user experience - roles and functionality analysis

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#670]

**Comment by strets123** [comment]
Gap analysis of what a user needs to be able to administer

**Comment by strets123** [comment]
Creation of a custom field config from a file is supported by assayreg function already.

Adding users will be supported by invite, but you also have the option of someone wanting to join a project

**Comment by PaulBarrett79** [comment]
I have prepared a document of aspects to consider, along with some mockups as illustration, at:

S:/OxChemBioDB/Project Documents/UI Mockups/Admin UX/

I would like to add to this document but this is what I was able to prepare in the time allowed. This will at least be a focal point for discussion, which was the aim of this research.

**Comment by KarenPorter** [comment]
Meeting arranged to discuss on 15/12/15

**Comment by aekhendry** [comment]
Meeting held, A plan is being drafted

**Comment by strets123** [comment]
Closing, work is done
