### ISSUE TITLE
Finish off required fields when adding a single item

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#673]
needs validation on assayreg and inv reg

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
Needs completion - validation needs to work as per the project add form

**Comment by PaulBarrett79** [comment]
Validation on the forms for adding single items and editing items via the modal should now work correctly.

Pushed to github.

**Comment by KarenPorter** [comment]
testable for single items

**Comment by KarenPorter** [comment]
1.  When I first clicked add single inventory item, the search results page appeared but the add single part of the form wasn't exposed.  I can't reproduce.

2. when I first get into the add single part of the form there is nothing to indicate which fields are mandatory.  

3.  I can also launch this part of the form with the message You have required fields missing or incorrect data - please correct these and try again. - again, with no indication of what the required fields are.

4. In modal window, when I delete mandatory values and get warning message - i can  cancel edit but the warning message persists.

**Comment by PaulBarrett79** [comment]
Changing the allocated time to reflect this as estimated to be 3 hours effort. This is probably configuration on the schema form setup for this form.

**Comment by PaulBarrett79** [comment]
1. Can't reproduce. Form always shown when I click the link.

**Comment by PaulBarrett79** [comment]
2. Added mandatory field indicator

**Comment by PaulBarrett79** [comment]
point 3 - message now clears when form is cleared

**Comment by PaulBarrett79** [comment]
1.5 hours spent so far

**Comment by PaulBarrett79** [comment]
4 . Warning message now hidden when editing cancelled

**Comment by PaulBarrett79** [comment]
Pushed to github

**Comment by PaulBarrett79** [comment]
Available for testing on staging/staging

**Comment by KarenPorter** [comment]
2.  No mandatory field indicator visible (chem project)

4. Hiding and showing of message still isn't consistent.  No message about mandatory fields when I check structure - surely these should be indicated at the same time?

When I clear the form, it deletes the structure I've drawn but stores it - so when I don't draw anything else but just add project field data, the record created stores those project field values AND the original structure I drew.

Clear form doesn't remove the message from underneath doodle or related to project fields

**Comment by KarenPorter** [comment]
When I add a blank record to an inventory project with no mandatory fields a record is written - need check for minimal data (at least one field has something)

When I add a value to the last blank mandatory field, the warning message should be removed at that point.

**Comment by PaulBarrett79** [comment]
"When I add a blank record to an inventory project with no mandatory fields a record is written - need check for minimal data (at least one field has something)"

...is a philosphical question around user behaviour and assumed expected outcomes - if there are no mandatory fields and a user adds a record with no data, does the system need to intervene? the project is configured to allow this through having no mandatory fields, and still creates a unique record to which data can be added later

I'll make a separate card for this.

**Comment by PaulBarrett79** [comment]
"When I add a value to the last blank mandatory field, the warning message should be removed at that point."

Added a form.$valid check on whether the message displays or not, rather than dependent on the error message

**Comment by PaulBarrett79** [comment]
"No mandatory field indicator visible (chem project)"
Have altered the form - madatory fields now indicated

"Hiding and showing of message still isn't consistent.  No message about mandatory fields when I check structure - surely these should be indicated at the same time?"
Included form validation when validating single compound

**Comment by PaulBarrett79** [comment]
"When I clear the form, it deletes the structure I've drawn but stores it - so when I don't draw anything else but just add project field data, the record created stores those project field values AND the original structure I drew."

Have put in a condition when clearing the form to clear the molecule if this is not a cloned molecule.

**Comment by PaulBarrett79** [comment]
That's all these issues addressed - pushing to github.

**Comment by PaulBarrett79** [comment]
Available to test on staging/staging

**Comment by KarenPorter** [comment]
@strets123 Andy - do you have any insight into why code on staging has now changed?  Paul has pulled very recent changes in but other things are included and now, for instance, search results bring back nothing (with no filters on anything).

**Comment by PaulBarrett79** [comment]
The lack of search results was a result of needing an elasticsearch re-index

**Comment by KarenPorter** [comment]
"Clear form doesn't remove the message from underneath doodle or related to project fields"

It now does- mostly.  Except when message is 'It looks like you have drawn an invalid structure - please check and click Validate Compound again if you make any changes.'

**Comment by strets123** [comment]
I have fixed the issue from the above comment and deployed to demo

**Comment by KarenPorter** [comment]
I added a second required field to Hendry Compounds project for testing - making Owner required (choice allowing create).  I then saved a new record without assigning a value to that mandatory field.

**Comment by KarenPorter** [comment]
When I add a file on addsingle page it is ignored.

**Comment by KarenPorter** [comment]
Owner field drop down does not include the values defined for that field in the project definition - shows what I think are all of the existing current values for that field.  To confirm this, I use search in the project (Hendry Compounds) and select 'not blank' values - no results are returned.

**Comment by strets123** [comment]
I will check this, I think that this field is working as designed but that the not blanks filter is now broken

**Comment by strets123** [comment]
I have now fixed the nonblanks filter

**Comment by KarenPorter** [comment]
The not-blanks filter works as expected.

But the other defects raised above are still there:

I added a second required field to Hendry Compounds project for testing - making Owner required (choice allowing create).  I then saved a new record without assigning a value to that mandatory field.

AND

Owner field drop down does not include the values defined for that field in the project definition - shows what I think are all of the existing current values for that field.

**Comment by strets123** [comment]
raised issue #1017 as the pick from list validation is not a quick job

**Comment by strets123** [comment]
Required fields now work for choice fields. For tags allowing create fields this does not work because of an issue with the underlying angular framework #1020

**Comment by KarenPorter** [comment]
Remaining issues raised an new defects, therefore passing this issue.
