### ISSUE TITLE
Simple tool to help recommend groupings of fields within a custom field config

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#674]
Need some sort of field profiles system so a user can pin a set of fields they want to see first.

**Comment by aekhendry** [comment]
Jing Yu's primer/plasmid data base had this functionality, could be worth talking to him.

**Comment by KarenPorter** [comment]
@strets123 still outstanding?  I think this'll be deprecated at this point as low priority.

**Comment by KarenPorter** [comment]
very low - closing
