### ISSUE TITLE
Search doesn't include searching the project name.  Should it?  

Now we have very many projects I c

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#675]
Search doesn't include searching the project name.  Should it?  

Now we have very many projects I can see I might just want to look at the compounds associated with a specific project so i type that project name in the search box but get no results.  Is this the right user experience?

**Comment by aekhendry** [comment]
I believe this is a fair assumption Andy.

**Comment by aekhendry** [comment]
This has now been solved. hub chrome
