### ISSUE TITLE
Search compound has data in "compound batch created by" field consisting of name concatenated with S

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#677]
Search compound has data in "compound batch created by" field consisting of name concatenated with SSO id, rather than just name.  It searches correctly so just cosmetic.

**Comment by strets123** [comment]
fixed to be committed

**Comment by strets123** [comment]
fixed

**Comment by KarenPorter** [comment]
Order of names is still a bit odd (Paul Barrett, followed by all others in alphabetical order).

**Comment by strets123** [comment]
deployed to staging/chembiohub

**Comment by KarenPorter** [comment]
no change in issue - don't think this has been addressed.

**Comment by strets123** [comment]
Lets put lower case on sort

**Comment by PaulBarrett79** [comment]
Added a lower() to the uiselect config which is generating this list. It is now alphabetically ordered whether in upper or lower case.

Pushed to GitHub

**Comment by strets123** [comment]
On hubtest

**Comment by aekhendry** [comment]
I'm not sure this has been fixed? I'm seeing their single sign on user name in some of the CDT entries as opposed to their actual name. Have I misunderstood what this fix is for?

**Comment by PaulBarrett79** [comment]
Are you testing this on hubtest?

**Comment by aekhendry** [comment]
Ignore my previous comment, it was not relevant as I misunderstood the core issue i was testing. the original issue is fixed. Hubtest, chrome

**Comment by strets123** [comment]
Done
