### ISSUE TITLE
Search compounds is slow (now that there are over 100000 records).  what can we expect in future - i

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#678]
Search compounds is slow (now that there are over 100000 records).  what can we expect in future - is it going to progressively slow down as additional compounds are added?

**Comment by strets123** [comment]
Please test again after elasticsearch performance changes. Substructure search of very common structures will still be a bit slow but other searches work fine just as on ChEMBL. Searching for a benzene ring is not a realistic test!

**Comment by aekhendry** [comment]
I have looked at this and am happy with the performance (Bearing Andy's comments in mind), what do you think Karen?

**Comment by KarenPorter** [comment]
acceptable performance time achieved now.
