### ISSUE TITLE
Migrate the data from the CDT instance to Hub.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#681]
Migrate the data from the CDT instance to Hub.

**Comment by strets123** [comment]
Task for this sprint was to have a plan and be ready to migrate the data.

I have made one attempt at the migration and have fixed the issues that arose - image sizes and name display.

I have a script to do the migration which is run at the console and contains the names and temporary passwords and so is not shared here.

**Comment by KarenPorter** [comment]
Not ready to test?  How does a second person confirm data has been migrated successfully where appropriate /possible?

**Comment by strets123** [comment]
Adam should be aware of the task that has been passed on to him for this

**Comment by aekhendry** [comment]
I'm working on this now

**Comment by aekhendry** [comment]
Task completed
