### ISSUE TITLE
Should unprocessable SMILES in list be allowed to be added with empty metadata

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#682]
Unprocessable molcules are now available to process as blinded compounds (to allow addition of records with metadata) in line with Adam's requests for this sprint. We may need to revisit whether this becomes the case for SMILES which have no metadata by definition - this is best up for discussion.

**Comment by PaulBarrett79** [comment]
This question raised itself in a manifestation during fixing of bug #643 

"However, failed because the SMILES I added are all not -processable.  I added the simplest molecules - cc, ccc and cccc.  I am unaware of when this was introduced or what it relates to - probably not associated with this resolution - please confirm and raise a new ticket if appropriate."

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by strets123** [comment]
Logical behaviours to be defined for smiles upload, single molecule addition and file upload.

File upload to be tested following changes made for scarab integration, particularly custom field validation in SDF

**Comment by strets123** [comment]
need to tidy up this processing of smiles

**Comment by strets123** [comment]
As metadata can now easily be edited, I think this is OK
