### ISSUE TITLE
On hub - structure search returns different results before and after structure search.

Search for p

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#684]
On hub - structure search returns different results before and after structure search.

Search for project Jones compounds - 608 results.  Add some structure or other and run structure search  - smaller number of results.  Clear structure and run structure search - 511 results.  

No need even to run the structure search with something in it - get the same results if you just start to draw a structure then clear it and run structure search.  I realise this may be related to ChemDoodle and some artefact of what it leaves in the search parameter, but if it can't be resolved it should at least be noted somewhere - FAQ?

 https://chembiohub.ox.ac.uk/hub/#/search?archived=false&project__project_key__in=jones-compounds&with_substructure=Molecule%20from%20ChemDoodle%20Web%20Components%0A%0Ahttp:%252F%252Fwww.ichemlabs.com%0A%20%201%20%200%20%200%20%200%20%200%20%200%20%20%20%20%20%20%20%20%20%20%20%20999%20V2000%0A%20%20%20%200.0000%20%20%20%200.0000%20%20%20%200.0000%20C%20%20%200%20%200%20%200%20%200%20%200%20%200%0AM%20%20END&doScroll=true

**Comment by aekhendry** [comment]
I've retested this and found the same behaviour. You must click reset and then reselect the project you were searching through to get the full list of compounds back. My solution to this if possible is that clicking clear on the doodle app resets the page with the same project parameters in place.

**Comment by strets123** [comment]
Move to testing once the chemdoodle fix is deployed

**Comment by strets123** [comment]
hubtest - ready for testing

**Comment by aekhendry** [comment]
I beleieve this is now fixed. hub test chrome
