### ISSUE TITLE
Review help text on Hub

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#685]

**Comment by aekhendry** [comment]
Passed on to Paul to put on hub

**Comment by KarenPorter** [comment]
I've tweaked the text slightly.

**Comment by strets123** [comment]
Can be put in to repo

**Comment by PaulBarrett79** [comment]
I have readded the amended help text onto the help page.

Available to test on hubtest

**Comment by aekhendry** [comment]
Looks good, marking as fixed

**Comment by strets123** [comment]
Leave open to remind us to redo help pages once ChemiReg changes are done

**Comment by aekhendry** [comment]
Add an FAQ for archiving and restoring items / compounds.

Suggest:

Can I archive items in my project which are no longer relevant or were added in error?

Yes.  To archive an item or items, on the Search Results page, select the Edit button at the top of the results grid.  The first column will now contain an Archive/Restore button. Click this on any items you wish to archive.

Can I restore previously archived items in my project?

Yes.  To restore an item or items, on the Search Results page, select the Edit button at the top of the results grid.  Now select the filter option in the first column header to "show only archived".  Click on any items you wish to restore.

**Comment by PaulBarrett79** [comment]
Extra text added, pushed to github.

**Comment by PaulBarrett79** [comment]
Deployed to hubtest

**Comment by aekhendry** [comment]
Looks good chrome hubtest
