### ISSUE TITLE
Double table header bug

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#686]
I click add single on schofield plasmid project XXX. I see a table of entries. i scroll down to the bottom of the page, I scroll back up and the header has been duplicated. this does not seem to happen for chemical inventories, only inv reg projects.

**Comment by aekhendry** [comment]
hub chrome

**Comment by strets123** [comment]
Downgrading as hard to fix and  not important enough. Moving to December

**Comment by aekhendry** [comment]
Done

**Comment by strets123** [comment]
Closed - deployed
