### ISSUE TITLE
Some fields dissapear when I click add single or edit

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#687]
I've just noticed that when I wanted to add a single entry to schofiled plasmids XXX, I filled out of the options, clicked save and all my data was saved. However, looking at the entry in the table I can see two blank field headings that were not presented to me during the data input stage. they are No. aas + tag and No. aas - tag. Something about these fields makes them dissapear so data cannot be entered manually into the system. Note that I have checked and they have not been saved as interger only or something like that. i'm guessing it's to do with the characters used

**Comment by strets123** [comment]
I think this is due to the dots

**Comment by aekhendry** [comment]
I think this is due to the use of the .  It seems to be restricted to Chem/InvReg. Assay reg does not seem to have this issue. I'm moving back to backlog. it is no lon ger red as i can manage it quite easily. Hub Chrome.

**Comment by aekhendry** [comment]
Try as I might, this issue refuses to move into the backlog..

**Comment by aekhendry** [comment]
Is this issue relevant to the admin work we will be doing in the December sprint? In some way we need to make users who create their own projects aware of this or fix it.

**Comment by strets123** [comment]
Dots not allowed in field names via admin section - closing
