### ISSUE TITLE
Need to handle incidents where users has access to assay reg when they shouldn't better

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#688]
Just a thought. If you have access to assay reg when it has no data configs attached to it and click save, you can get an infinite loading bar. Can we stop this from happening and instead inform the user why they cannot proceed? I appreciate there is a way to solve this by resticting their access but it would tighten the system up some what if mistakes are made

**Comment by PaulBarrett79** [comment]
Disabled the Save button if no data configs are loaded for a project. Also changing the message to explain that the project needs to be set up correctly (i.e. have data configs added) if there is no way of adding data.

**Comment by PaulBarrett79** [comment]
Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to staging/chembiohub

**Comment by aekhendry** [comment]
First part works, I'm not sure about the second part - explanation of settings up project properly. I don't know how to trigger this? If you set up a project with no custom field config then It breaks the instance (you get a blank screen on log in). Have I misunderstood this?

**Comment by strets123** [comment]
Deprecated because menu item has been removed for projects without assayreg added. Please test staging/chembiohub

**Comment by aekhendry** [comment]
This is no longer an issue due to recent changes on hub. closing
