### ISSUE TITLE
Presentation when restricted to chem reg

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#689]
Presentation when restricted to chem reg could be improved. At the moment the button to add compounds is stuck out on the right and say chem even if its an inv project. This could be improved as currently this looked visually better in the previous version. Also, we seem to have lost different colors depending on what type of project it is?

Hub  Chrome

**Comment by strets123** [comment]
This issue should have been fixed by the change to the project list page

**Comment by KarenPorter** [comment]
awaiting @aekhendry sign off

**Comment by aekhendry** [comment]
my data link: chemage to 'Search my data' or 'look up my data' Currently I don't know what to expect when I click on that link.

Inv reg project does not have a separate colour. I think it should. 

Inv reg project still says things like 'add compound'. Can we change this to add item

**Comment by strets123** [comment]
Could add Search  my data

Check logic for colour change and add item wording and do quick change if possible

Do not agree on space between things

**Comment by PaulBarrett79** [comment]
All of the colour change checks are now based on the "show compounds" property of the project type. Show compounds = blue.  Not show compounds  = pink.

Search My Data wording change added.

Pushed to GitHub.

**Comment by PaulBarrett79** [comment]
Available for testing on hubtest

**Comment by aekhendry** [comment]
Looks good, marking as done. Hub chrome
