### ISSUE TITLE
Ignore function when uploading compounds is not working as it should

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#690]
First the drop down will not disspear. Secondly when I do select ignore and click save, it does not ignore the compound on upload

**Comment by aekhendry** [comment]
hub chrome

**Comment by strets123** [comment]
Is this also a problem on cdt?

**Comment by strets123** [comment]
Adam has confirmed as fixed and deployed to hub. Need to do the handsontable upgrade to finish these items properly
