### ISSUE TITLE
view 50 compounds per page option is not working

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#691]
Hub Chrome

**Comment by strets123** [comment]
Refactor needed of the code which manages this part

**Comment by KarenPorter** [comment]
This is also reflected in another issue I believe.  

Proposal is to make 50 the default regardless of project type or whether there are compound structures shown in the table.

**Comment by strets123** [comment]
I have now fixed this issue and deployed to tagnew

**Comment by aekhendry** [comment]
Fixed tag new chrome
