### ISSUE TITLE
Add upload multiple on inv search page

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#693]
Currently there is only a button to add single, I'd like to see an add multiple button here too

**Comment by KarenPorter** [comment]
@aekhendry - I think you have what you requested here now?  If so, can be closed.

**Comment by strets123** [comment]
Assigning to Paul to work on this when single add is done for compounds

**Comment by strets123** [comment]
Fix is deployed to hubtest, I have also fixed the add single inventory item button on the project list page

**Comment by aekhendry** [comment]
Looks good. HubTest, chrome
