### ISSUE TITLE
Handsontable version upgrade

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#694]
Need to make tha handsontable version upgrade work without breaking the dropdown on the addcompounds page. This currently only works properly if version 16.1 is used however #603 (fill down) requires us to use version 20

**Comment by PaulBarrett79** [comment]
I have made a number of changes to how we are using and setting up handsontable to iron out a few things. There was code that I think was there from when we had our "fake header" appended div .

With version 20.2:

Handsontable now loads and works consistently. 
All data is always displayed. 
Edit mode still works. 
Drag-fill works consistently.
Dropdown cells work correctly and no longer hang.
Table can scroll with the header consistently.
Vertical scroling no longer triggers extra scrollbars
Any scrolling no longer triggers non-display of data

Pushed to github.

**Comment by strets123** [comment]
now pushed to hub

**Comment by KarenPorter** [comment]
I get a sliver of the top horizontal scrollbar - needs to be either the full height or not there at all.

**Comment by strets123** [comment]
OK, what is currently on hub is the best we can do. No gap when using google chrome, other browsers there is a little gap above scrollbar but scrollbar there and works. Wontfix any more this sprint

**Comment by aekhendry** [comment]
Fixed, chrome hub
