### ISSUE TITLE
Uploading some compound files to CDT instance ignores all compounds when only one is broken.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#698]
See email I have sent for full explanation and example files.

'Hi Guys,

I’m finding this file (Problem file 1) is ignoring all compounds, when only the compound in row 9 (Problem file one single example) cannot be processed by the system. I have also attached the problem compound separately. There is a second file (Problem file 2) that I suspect also has the same problem, but I have yet to prove it to be the case. 

I’m confused as to how my testing did not pick this up, I tried with files much larger then this that possessed compound known to be problematic and it did not ignore all compounds like this.  

Can we look at this asap as I’m worried about the implications this has for other uploaders.

Adam'

**Comment by strets123** [comment]
Please test on hubtest

**Comment by aekhendry** [comment]
This is now fixed. chrome hub test

**Comment by strets123** [comment]
deployed
