### ISSUE TITLE
Search activity icon is missing from top bar - mac safari bug

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#700]
hub mac osX

**Comment by PaulBarrett79** [comment]
Glyphicon (font based icon) not being picked up correctly. No obvious fix for Safari. 

We shouldn't really be using these anyway for accessibility reasons - tempted to convert all the headers to proper image icons.

**Comment by PaulBarrett79** [comment]
Converted all the header glyphicons to images. This really is cross browser.

Pushed to github

**Comment by PaulBarrett79** [comment]
Available for testing on hubtest

**Comment by aekhendry** [comment]
fixed. Hubtest mac os safari
