### ISSUE TITLE
Image analysis with Zegami

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#701]
Zegami.com is the open source software developed at Oxford for visualising images.

By integrating it we can get people on board who have images

**Comment by aekhendry** [comment]
I would prefer to focus on Pivot tables and graph generation. These are things that people have voiced an opinion on where as no one has seen Zegami yet. I'm worried it's a feature that looks good but need to assess whether people will use it.

**Comment by strets123** [comment]
I think we should explore the idea of doing another innovation seed fund proposal for this one.

**Comment by KarenPorter** [comment]
@strets123 still outstanding?  I think we shou,d close out of our backlog - useful but not realistic to get scheduled in the time remaining

**Comment by aekhendry** [comment]
Closing as we have other priorities in the next 6 months
