### ISSUE TITLE
Assay reg and Chem Reg export to excel and SDF is broken

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#702]
I get this error message when trying to export from the new search page: https://chembiohub.ox.ac.uk/hub/api/cbh_compound_batches/?project__project_key__in=cjs-compound-inventory&textsearch=adamarchived=falseformat=xls&limit=10000

I have not seen this before, despite previous testing

**Comment by strets123** [comment]
links should now be fixed

**Comment by aekhendry** [comment]
Export to SDF working, Export to Excel is not

**Comment by aekhendry** [comment]
Tested tagnew chrome
