### ISSUE TITLE
Symbols i.e. $%^ are allowed in the table search but do not provide any results on clicking enter.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#707]
Symbols i.e. $%^ are allowed in the table search but do not provide any results on clicking enter. Is there a reason we cannot search for symbols? If this is too difficult, I would recomend that adding a symbol produces a warning, or provides a blank table immediately to inform the user something is wrong.

**Comment by KarenPorter** [comment]
@strets123 still outstanding?

**Comment by aekhendry** [comment]
no closing
