### ISSUE TITLE
setting up pypi and sorting out the remote repos

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#708]

**Comment by strets123** [comment]
Working on setting up pypi in order to make install easier

For test puproses used a new organisation

mkdir 
cd renamebranch/
git clone https://github.com/strets123tests/cbh_chembl_ws_extension.git
cd cbh_chembl_ws_extension/
git branch 0.9.0_unstable
git checkout 0.9.0_unstable
git push origin 0.9.0_unstable
#maybe need this lets test
git push origin :master
git branch -d master

**Comment by strets123** [comment]
To be syncced

[ ] - git://github.com/strets123/cbh_chembl_ws_extension.git
[ ] - git://github.com/strets123/cbh_chembl_model_extension.git
[ ] - git://github.com:strets123/chembl_core_model.git

**Comment by aekhendry** [comment]
Please discuss or mark as done as appropriate

**Comment by aekhendry** [comment]
All ticked off and not discussed so closing
