### ISSUE TITLE
Data validation on Hub is not as it should be during file upload

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#709]
Files that used to go into Hub are now getting an error message - File cannot be processed even though the format appears valid. If you have questions please contact the ChemBio Hub team.

This was previously fixed by Paul who made a number of changes to SDF file uploads. Also affects large excel files (300 rows). My guess is that something has not been deployed on hub correctly.

**Comment by strets123** [comment]
fixed hub chrome

**Comment by aekhendry** [comment]
Tested and appears to be fixed. Chrome, hub
