### ISSUE TITLE
Change to how we control assayReg access on projects

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#710]
Currently whether a user sees a project as assay reg or just ChemReg/InvReg is controlled at the user permissions level. I can see advantages to this, but I think It also makes sense to to control this at the Project creation level. I do believe that we need both methods of control (the one in place now and my proposed method).

Control at the project level makes much more sense for projects that will never be used for AssayReg. Looking forward, any admin user will be extremely confused by the fact that they have access to assayreg stuff when in their mind they should not. This will also allow for assay reg projects to be highlighted in a separate colour (green) and is a much more intuitive experience for the user. 

The current method is still relevant for people who want to open up access to their assayreg project to users who need to see the compounds only. This extra level of control is useful and is definitely worth keeping. 

Any thoughts?

**Comment by aekhendry** [comment]
I believe this issue is linked to the admin update as this is where it's going to confuse users the most.

**Comment by strets123** [comment]
Access will be controlled by having different project types in Chemireg and cross-refferences between them
