### ISSUE TITLE
The link to 'try the system here: chembiohub.ox.ac.uk/assayreg/login on the assayreg page of the web

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#711]
The link to 'try the system here: chembiohub.ox.ac.uk/assayreg/login on the assayreg page of the website is broken  - URL is http://staging.chembiohub.ox.ac.uk/test/login

The other 2 application pages direct to chembiohub.ox.ac.uk/hub/webauth.

Also, the button at the top of each of these pages to 'try it out' launches a new tab.  This should be the same from the link lower down on each page - which currently navigates to the app in the same window in each case.

**Comment by PaulBarrett79** [comment]
I have amended the link to point to hub/login.

All AssayReg links to try out the system from this page now point to the working hub instance.

Link works on both staging and live.

**Comment by aekhendry** [comment]
All working on live. Marking as done
