### ISSUE TITLE
Searching for an incorrect structure I get a message 'Loading selected items failed' message.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#712]
Searching for an incorrect structure I get a message 'Loading selected items failed' message.

**Comment by aekhendry** [comment]
Can you define incorrect? I'm not sure how to replicate this. Also what project you were searching in please.

**Comment by KarenPorter** [comment]
@aekhendry In search structure - just draw any nonsense structure and hit 'run structure search'.  not related to any project.  It's about how invalid structures are handled.

**Comment by aekhendry** [comment]
Yes tested this and is still a bug. hubtest chrome

**Comment by PaulBarrett79** [comment]
Possible dupe of #833

**Comment by KarenPorter** [comment]
Resolved by refactoring.
