### ISSUE TITLE
New staging version says 'Click a project title to see more details....'  but project title isn't cl

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#718]
New staging version says 'Click a project title to see more details....'  but project title isn't clickable.

http://staging.chembiohub.ox.ac.uk/chembiohub/#/projects/list

However, the Project list heading is clickable - but directs to where you are so redundant.

**Comment by KarenPorter** [comment]
@strets123 still outstanding - needs tidying.

**Comment by strets123** [comment]
Fixed

**Comment by aekhendry** [comment]
Fixed, hubtest chrome
