### ISSUE TITLE
data overview page has buttons for Add single project and Add multiple project- these should refer t

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#720]
data overview page has buttons for Add single project and Add multiple project- these should refer to activities.  Also the Activities label currently reads Projects.

Sub-project title value doesn't show up on overview in relevant place for project Test 1, though it does for Test 2 - weird.

where title field is shown (on project and assay), it doesn't wrap where there's a long word (see project Test 1 for example - would be very unlikely to happen in production but good catch all the same).

**Comment by KarenPorter** [comment]
I understand that the first of these is a configuration artefact - the structure of sub-project / assay / activity is defined in the project config, therefore this behaviour is as a result of the L3 being defined as project rather than activity..

others remain as issues though.

**Comment by KarenPorter** [comment]
@strets123 still outstanding but prob redundant as functionality is moved to ChemiReg?

**Comment by KarenPorter** [comment]
redundant - close
