### ISSUE TITLE
Click the info icon next to filter project list box on list page and view the information.  Then cli

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#723]
Click the info icon next to filter project list box on list page and view the information.  Then click back - info box remains

**Comment by KarenPorter** [comment]
same with the info next to 'click a project title to see more detail...'

**Comment by strets123** [comment]
Can't reproduce, which browser?

**Comment by aekhendry** [comment]
I can't replicate, I'm closing. chrome, fire fox and ex10 hub
