### ISSUE TITLE
Not possible to see the activity details in assayreg in the same way as you can from Search results.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#724]
Not possible to see the activity details in assayreg in the same way as you can from Search results. You can obviously download the data but not just see all relevant information related to a single activity - bit of a functional hole.  please add ability to pop up modal activity window

**Comment by aekhendry** [comment]
To extend this, I don't know if Assay Reg search results are actually useful / meaningful. Currently exporting the data to excel is the only way to visualise this data in its original form. I think we need to think really carefully about what we should see on this page and what the user will expect. I'll be getting more feedback on this over the next few weeks, but I think it is worth discussing.

**Comment by strets123** [comment]
Would be handled by search improvements to ChemiReg
