### ISSUE TITLE
Login system for Lara's external users via her portal

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#727]
This can be as simple as a link, but i would like to get back to her with exactly how we plan to handle this by Tuesday nexteek

**Comment by strets123** [comment]
Simply add the login url to the portal, as agreed with Adam, Lara will invite users via chemreg

**Comment by aekhendry** [comment]
I'm waiting on a reply to make sure this is what she wants, I'll move the card appropriately when she responds.

**Comment by aekhendry** [comment]
Weve done our end of this. I'm closing
