### ISSUE TITLE
Mychembl integration

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#730]
Integrate with mychembl, send to chembl and discuss publication options

**Comment by KarenPorter** [comment]
Moved to Under Investigation as planned for today 17/12

**Comment by strets123** [comment]
@KarenPorter  Please respond to my email about this. What date can we give ChEMBL to say that we will do a sprint with them by?

**Comment by KarenPorter** [comment]
@strets123 I assume this can now be marked as done?  Please forward me email so I can confirm.

**Comment by KarenPorter** [comment]
Now with ChEMBL for testing,  therefore this issue can be marked as done.  Subsequent effort may arise as a result of testing.  A separate issue is likely to be needed to capture effort for supporting ChEMBL curation activities.

**Comment by strets123** [comment]
Closed for now
