### ISSUE TITLE
Monitor the status of the ntp daemon

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#735]
Ntp is critical to be enabled to avoid the kind of clock drift error seen on the production server with webauth

**Comment by nroam** [comment]
We believe this issue was due to clock skew on the underlying server due to a misconfiguration in BIOS on my part.

This is now addressed and it is highly unlikely this issue will repeat itself. So long as the step-tickers and ntp.conf are set to use ntp[0-3].ox.ac.uk, all should be good.
