### ISSUE TITLE
Update wiki to tell those changing the kerberos tokens what the procedure is

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#736]
As soon as a kerberos ticket is re-issued by central Oxford IT, it deprecates the existing one. Therefore a note has been added to the wiki to this effect.

**Comment by strets123** [comment]
http://wiki.sgc.ox.ac.uk/wiki_sysadmin/index.php?title=Webauth,_SSO_and_LDAP

**Comment by aekhendry** [comment]
Not sure how to test this? Link is asking for authentication i don;t have.

**Comment by strets123** [comment]
Marking as done because I did this, come and look if you wish
