### ISSUE TITLE
Centos issue with GREP

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#739]
I have pushed a fix for the name of the grep process.

This may cause issues in production - we must ensure our paths are correct on ubuntu

**Comment by strets123** [comment]
please test on hubtest to see that all SDF uploads function correctly. If they do this change has worked.

**Comment by aekhendry** [comment]
SDF upload is working. Hubtest chrome

**Comment by KarenPorter** [comment]
Is this reflected in documentation? @strets123
