### ISSUE TITLE
Inchi issue with VM

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#740]
Inchi is not installed properly on the VM

Run this to correct the issue

su chembiohub
sudo yum install unzip
source activate 0
cd $CONDA_ENV_PATH/var
wget http://www.iupac.org/fileadmin/user_upload/publications/e-resources/inchi/1.03/INCHI-1-BIN.zip
 unzip INCHI-1-BIN.zip
 gunzip INCHI-1-BIN/linux/64bit/inchi-1.gz
 chmod +x INCHI-1-BIN/linux/64bit/inchi-1

**Comment by strets123** [comment]
Hi David - run a pull and apply this fix

**Comment by KarenPorter** [comment]
Andy - are these steps included in the updated installation instructions?

**Comment by strets123** [comment]
yes, part of the script
