### ISSUE TITLE
Elasticsearch new version sort issue

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#741]
Sorting of data in ChemiReg currently requires a separate index to be present, separate to the one that is used for the rest of the custom fields.

This is memory inefficient. It is much better to concentrate all of the indexing on one document structure.

Therefore I propose moving the sorting to be an inline script:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_script_based_sorting

This task can be done in preparation for a larger refactor of the way the custom fields are stored.

**Comment by strets123** [comment]
Moving back to backlog - we need to find a way to fix this for the angular plugin elasticsearch search

**Comment by KarenPorter** [comment]
@strets123 still an issue?

**Comment by strets123** [comment]
It makes some sense to do this at the same time as the changes for images as the images can then be stored as inline JSON

**Comment by strets123** [comment]
As it turns out it is possible to force everything to be indexed as a string. This would mean all projects with the same fieldname can be searched with the same query and we only require 1 or 2 indexed fields.

We can quickly find if a string is a float or number by using:

data.replace(".", "", 1).isdigit()

This will be a much faster check.

If we find that there is a number then we simply zero-pad it and add or remove decimal places up to 5.

This will allow numeric sort to still work in the context of a column of mixed data just as it does in Excel

Furthermore, date range queries will also work fine so long as we put the date in a standard YYYY-MM-DD format

**Comment by strets123** [comment]
Nested sorts with a sort filter are actually possible in elasticsearch! 

https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-sorting.html

**Comment by strets123** [comment]
This has been implemented but not deployed yet as need to do some upgrades and then run it on the staging server

**Comment by strets123** [comment]
Now deployed on staging server

**Comment by KarenPorter** [comment]
how can we test this?

**Comment by KarenPorter** [comment]
Needs 100K results to ensure valid test

**Comment by PaulBarrett79** [comment]
Volume of data test - for Andy to estimate

**Comment by strets123** [comment]
1-2 hours but potentially 3-6 hours of waiting

**Comment by strets123** [comment]
The data volume test is now in place on staging/staging. The projects have been indexed in full but the data is 2 weeks out of date

Chemical search is not enabled currently

**Comment by KarenPorter** [comment]
Bit of an oddity (may be a new issue needs to be raised re error handling?): I created a multi-sort / filter search, then added a structure search (not enabled), ran and got no results.  When I take the substructure filter off I get whirling, then error message (sorry there was an error...), then the results I expect from the query just run.

**Comment by KarenPorter** [comment]
I think we need a backlog item for extraneous columns returned from a search which is not based on Project name but with restricted number of projects returned.  Currently it isn't ideal behaviour to have a number of columns returned which are not relevant to the projects included in the results.

**Comment by KarenPorter** [comment]
No other issues identified, so passed when these 2 comments above are reviewed.

**Comment by strets123** [comment]
OK demo substructure search is now disabled and staging is enabled

**Comment by KarenPorter** [comment]
passed - need to capture defect with specific structure and large number of projects.  @strets123 please raise that issue in backlog and then this item can be moved to Done

**Comment by strets123** [comment]
see issue #1018 now raised

**Comment by KarenPorter** [comment]
can be moved to Done in that case
