### ISSUE TITLE
Write copy for emails to users

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#743]
Hi Adam,

We are going to require standard email formats for the following situations:

Password reset

Invite a user

Site Maintenance

**Comment by KarenPorter** [comment]
Shouldn't be possible to have issues all the way through to Awaiting Testing without any comments in them to say what has been done.  I assume this is here because the emails have been drafted?

**Comment by aekhendry** [comment]
Andy is asking me to draft some emails, I'll do this tomorrow

**Comment by aekhendry** [comment]
Done
