### ISSUE TITLE
Add documentation for the setup and development process using our VM

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#744]
It is clear that all of the setup tasks and refresh tasks when coding need to be documented.

E.G.

Grunt build#
collectstatic
and other management commands
git best practise for the project

**Comment by KarenPorter** [comment]
@strets123 still outstanding - to be incorporated when doing any work on installation.

**Comment by KarenPorter** [comment]
Subsumed in current documentation task. closing.
