### ISSUE TITLE
Security bug in latest version

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#747]
David has identified a security bug whereby compound information can be requested without a session id.

This is not present on the production system so will need to find out what the

**Comment by strets123** [comment]
I have fixed this issue and pushed to github. fix will go live with next release

**Comment by aekhendry** [comment]
Not sure how to test this?

**Comment by strets123** [comment]
@paulbarrett79 can you test this - copy a curl url like this and verify you get a 401 if you remove all cookie tokens
#
      curl "http://chembiohub.ox.ac.uk/hub/api/cbh_compound_batches/get_list_elasticsearch/?archived=false&created__gte=2015-12-08&creator_uri=&doScroll=true&flexmatch=&limit=50&offset=0&project__project_key__in=&related_molregno__chembl__chembl_id__in=&search_custom_fields__kv_any=&similar_to=" -H "Accept-Encoding: gzip, deflate, sdch" -H "Accept-Language: en-GB,en-US;q=0.8,en;q=0.6" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36" -H "Accept: application/json, text/plain, */*" -H "Referer: http://chembiohub.ox.ac.uk/hub/"   --compressed

**Comment by PaulBarrett79** [comment]
Using that curl command, I get a 301 (page moved)

Using the location the URL has moved to, I get:

{"errorMessage": "no_logged_in", "traceback": "Traceback (most recent call last):\n\n  File \"/home/chembiohub/anaconda2/envs/hub/lib/python2.7/site-packages/tastypie/resources.py\", line 202, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"./cbh_chembl_ws_extension/compounds.py\", line 1483, in get_list_elasticsearch\n    pids = self._meta.authorization.project_ids(request)\n\n  File \"./cbh_core_ws/authorization.py\", line 187, in project_ids\n    self.login_checks( request, None)\n\n  File \"./cbh_core_ws/authorization.py\", line 158, in login_checks\n    raise Unauthorized(\"no_logged_in\")\n\nUnauthorized: no_logged_in\n"}

which basically picks up the fact that I am not logged in. Done in browser and via command line.

Test passed - moving to awaiting deployment
