### ISSUE TITLE
Excel file upload to hubtest not working

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#750]
I upload a file. I click save and it takes me to the submitted screen but the compounds and data are not showing.

Chrome, hubtest

**Comment by strets123** [comment]
I believe this has been fixed, tested hub chrome

**Comment by aekhendry** [comment]
Sorry still not working. hubtest chrome

**Comment by aekhendry** [comment]
I tried again with the file I sent you

**Comment by strets123** [comment]
you will have to show me this, works fine for me

**Comment by aekhendry** [comment]
Fixed, hubtest chrome

**Comment by strets123** [comment]
deployed
