### ISSUE TITLE
URLs for css were wrong in development and production

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#754]
Login page css was missing in dev environment. Now fixed. Also does not rely on hacks to get css working in the prod environment

**Comment by KarenPorter** [comment]
How did this manifest and what has now changed?  Need more info to allow testing.

**Comment by strets123** [comment]
It is only a dev issue.

The fact that someone took our vagrant box and used it is proof enough.

**Comment by PaulBarrett79** [comment]
Can verify this is no longer an issue in dev environment.

Confirm closed.
