### ISSUE TITLE
Default name required for external log in

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#756]
Currently the email sent out when inviting a new person to a project uses the name provided by the person inviting provided by webauth. However if this person did not login via webauth, their name wont be know and this messes up the emails text. 

A possible solution is that on sign up, when resetting your password you are also asked your name as a mandatory field. 

Alternatively, currently when inviting some one you have the option to add their name. We could make this mandatory. 

The former option is better for a number of reasons (easier for the person inviting who may not know full name, avoids mistakes, new user can add their preferred name variation etc). But the latter option I'm sure is quicker.

**Comment by KarenPorter** [comment]
@aekhendry still outstanding?

**Comment by aekhendry** [comment]
closing
