### ISSUE TITLE
Issue with instance variables on python compound API

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#759]
There is a global instance variable which is used for structure search. When this is set it can break the upload. This may have been what caused the issues Adam had

**Comment by strets123** [comment]
Now fixed, hub and hubtest

**Comment by aekhendry** [comment]
Not sure exactly which behaviour this has corrected?

**Comment by strets123** [comment]
The issue where I had to reset after a structure search had been done by someone

**Comment by aekhendry** [comment]
Ah thank you. Fixed, Hub Chrome
