### ISSUE TITLE
Issue with new SDF parser

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#760]
The regex SDF parser can break globally if the SDF file is not terminated properly with an array index out of bounds. Needs to be done with a single regex then this can't happen.

**Comment by KarenPorter** [comment]
Moving to under investigation as planned for today 17/12

**Comment by strets123** [comment]
Not yet done, moving back to backlog

**Comment by aekhendry** [comment]
Fixed, hub test chrome
