### ISSUE TITLE
Generate an assay registration schema form based upon the scripps pubchem templa

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#77]
Generate an assay registration schema form based upon the scripps pubchem template mixed with the chembl schema.

date recorded in spreadsheet: 09/04/2015 17:10:41

**Comment by KarenPorter** [comment]
Adam - I believe this may be done (but not demonstrated)? @aekhendry

**Comment by aekhendry** [comment]
Closing

**Comment by aekhendry** [comment]
Out of date so closing
