### ISSUE TITLE
External user sees the 'Send an Invitation' option, and can bring up the modal window (though not se

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#770]
External user sees the 'Send an Invitation' option, and can bring up the modal window (though not select and projects).

Would be neater to disable the option or change the text in the window to say user can't because they don't have admin access to any projects.

**Comment by KarenPorter** [comment]
low priority but let's weigh that up with effort to fix - and do it if trivial or close as not being addressed.

**Comment by KarenPorter** [comment]
closing.
