### ISSUE TITLE
Tags have strange behaviour

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#771]
On hub, there is a project called tag test. i open an entry with no tags into single molecule view, i add a new tag and click save. notice that now in the table the other cells I had not edited now show all of their possible tag options.

**Comment by KarenPorter** [comment]
I can't reproduce (though I haven't tried very hard tbh).  is this still an issue @aekhendry ?

**Comment by aekhendry** [comment]
Fixed hub chrome

**Comment by aekhendry** [comment]
fixed hub chrome
