### ISSUE TITLE
Exported an xls from a set of results with 0 records - 1000 records were downloaded.  Project was Ch

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#772]
Exported an xls from a set of results with 0 records - 1000 records were downloaded.  Project was ChemReg Playground, on Hub

**Comment by KarenPorter** [comment]
Can't reproduce because of existing no exception error - review along with that issue

**Comment by KarenPorter** [comment]
Should the 3 issues 789, 818 and 821 be addressed together?  and 772

**Comment by KarenPorter** [comment]
Resolved.  Closing
