### ISSUE TITLE
Project data values' field behaves inconsistently in Hub.  Type 'Bottle name' and no option appear i

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#773]
Project data values' field behaves inconsistently in Hub.  Type 'Bottle name' and no option appear in ddl, but backspace briefly and options do appear.  

Not sure about this element of search in any case - what are users to make of it?  Non-intuitive label then there's the data value pairs that I just don't think people are used to seeing.

Needs discussion.

**Comment by KarenPorter** [comment]
redundant now. Closing
