### ISSUE TITLE
Can't send invitation on renamed projects.  

There is a bug manifest in existing data - namely rena

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#774]
Can't send invitation on renamed projects.  

There is a bug manifest in existing data - namely renamed projects.  It means that when inviting new external users the invitation fails because the permission objects can't be created as referring to original project ketys and names in permission definition.

Low priority as not affecting any production users  (they are only accessing clean projects), but should be addressed as part of a group of issues related to Django upgrade and admin refactoring.

**Comment by strets123** [comment]
"Traceback (most recent call last): File "/home/chembiohub/anaconda2/envs/hub/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper response = callback(request, *args, **kwargs) File "/home/chembiohub/anaconda2/envs/hub/lib/python2.7/site-packages/tastypie/resources.py", line 433, in dispatch_list return self.dispatch('list', request, **kwargs) File "/home/chembiohub/anaconda2/envs/hub/lib/python2.7/site-packages/tastypie/resources.py", line 465, in dispatch response = method(request, **kwargs) File "/home/chembiohub/anaconda2/envs/hub/lib/python2.7/site-packages/tastypie/resources.py", line 1349, in post_list return self.create_response(request, updated_bundle, response_class=http.HttpCreated, location=location) File "./cbh_core_ws/resources.py", line 572, in create_response p.make_viewer(new_user) File "./cbh_core_model/models.py", line 115, in make_viewer group_or_user, "viewer") File "./cbh_core_model/models.py", line 107, in _add_instance_permissions_to_user_or_group self.get_instance_permission_by_codename(codename)) File "./cbh_core_model/models.py", line 98, in get_instance_permission_by_codename codename=codename, content_type_id=self.get_contenttype_for_instance().id) File "./cbh_core_model/models.py", line 87, in get_contenttype_for_instance app_label=self.get_project_key(), model=self) File "/home/chembiohub/anaconda2/envs/hub/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/home/chembiohub/anaconda2/envs/hub/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get self.model._meta.object_name) DoesNotExist: ContentType matching query does not exist. "

**Comment by strets123** [comment]
pdate  django_content_type, cbh_core_model_project set django_content_type.name=cbh_core_model_project.name,django_content_type.model=cbh_core_model_project.name  where cbh_core_model_project.id = to_number(django_content_type.app_label,'9999') 
and ((django_content_type.id > 145 and django_content_type.id < 252) or (django_content_type.id > 266 and django_content_type.id < 282) or django_content_type.id in (283,284,286,287)) and  django_content_type.name != cbh_core_model_project.name;


Shows the renamed projects - need to write a script to sort this out as part of removing need for name field too

**Comment by KarenPorter** [comment]
@strets123 any progress on this?

**Comment by strets123** [comment]
Should now be fixed for all existing data on hub

**Comment by KarenPorter** [comment]
IS this testable on hubtest though?

I've created and renamed a project but don't see the 'invite users' options.  logged on as 'karen' in hubtest and with webauth on hub.

**Comment by strets123** [comment]
No, not testable on hubtest

**Comment by KarenPorter** [comment]
passed
