### ISSUE TITLE
Create new fab deploy script

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#775]
Script will have a local settings file with:

server, folder, environment folder as a yaml

**Comment by KarenPorter** [comment]
Awaiting testing by Paul (after instructions have been created).

**Comment by PaulBarrett79** [comment]
I have a new deployment script which deploys to hubtest.

I have managed to deploy to this instance with no errors and all of the generated information (python deployment processes, collectstatic etc) progresses as it should.

If I do subsequent deployments, they do not update content, or don't clear a cache or similar. For example, a change I made to how the project list detects whether it should allow an "add single compound" link are not shown. I know that the change to the ng-chem repo has been picked up and transferred via collectstatic. But the change is not reflected on the hubtest instance. I verified this by adding a text-only (non-programmatic) change which should have shown up regardless.

**Comment by strets123** [comment]
This could well be something to do with cache control headers. These should be set to cache only css and js files but I have a feeling they also cache html.

This kind of caching wont necessarily be removed by crtl f5. The line is somewhere in the includes or main apache conf for hub

**Comment by PaulBarrett79** [comment]
Changes showed up ~30 mins later - not a massive problem and not stopping us deploying.

Marking as done
