### ISSUE TITLE
Edit table bug triggered by specific parameters

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#776]
On Hub, i search in a project using user name search field and project name search field. I click edit table. The table disappears. Chrome

**Comment by KarenPorter** [comment]
@aekhendry Adam - This looks like it has been resolved, please retest and update / mark as fixed as appropriate.

**Comment by aekhendry** [comment]
fixed, chrome hub

**Comment by aekhendry** [comment]
fixed hub chrome
