### ISSUE TITLE
Some cdt compounds can't be registered in our system

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#777]
chrome hub. see email for files and info. So all CDT compounds are now on hub, with the exception of these compounds that were in some of the files I had to upload today. YaoYao's are interesting. In some cases you have identical compounds registered, and only one will not be recognised. Note that the larger YaoYao file is included so you can see this for yourself. The smaller file is only the compounds that could not be uploaded. Please do not upload the whole file to the CDT project as some of the compounds in it have already been successfully registered.

**Comment by strets123** [comment]
I am going to look at these files in Chemdraw this morning

**Comment by strets123** [comment]
The work around for this issue, just as they do on ChEMBL is to register all organometallic complexes with NO bonds between the metal Ion and the complexing agents.

This means, as with ChEMBL, all chirality information is lost.

Here is an example of one of Yao Yao's compounds.

Note that Yao Yao also made the mistake of registering a PF6- ion with 2 negative charges on it when there should be 2 pf6- ions as per wilfred's ruthenium complex.

You can correct the offending complexes in chemdraw and then ensure they are regrouped properly and then upload them.

**Comment by aekhendry** [comment]
Done and implimented according to andy's suggestions. Hub chrome
