### ISSUE TITLE
error in hubtest when I export 0 search results.
There are 0 records in the project.

TypeError at /

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#778]
error in hubtest when I export 0 search results.
There are 0 records in the project.

TypeError at /hubtest/api/cbh_compound_batches/
expected string or buffer
Request Method:	GET
Request URL:	https://chembiohub.ox.ac.uk/hubtest/api/cbh_compound_batches/?creator_uri=/hubtest/api/users/56&project__project_key__in=plasmid-test-fields&archived=false&format=xlsx&limit=10000
Django Version:	1.7.10
Exception Type:	TypeError
Exception Value:	
expected string or buffer
Exception Location:	/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/json/decoder.py in decode, line 366
Python Executable:	/home/chembiohub/anaconda2/envs/hubtest/bin/uwsgi
Python Version:	2.7.10
Python Path:	
['.',
 '',
 '/home/chembiohub/anaconda2/envs/hubtest/lib/python27.zip',
 '/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7',
 '/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/plat-linux2',
 '/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/lib-tk',
 '/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/lib-old',
 '/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/lib-dynload',
 '/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages/cairocffi-0.6-py2.7.egg',
 '/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg',
 '/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages']
Server time:	Wed, 16 Dec 2015 05:29:29 -0600
Traceback Switch to copy-and-paste view

/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                    response = wrapped_callback(request, *callback_args, **callback_kwargs) ...
▶ Local vars
/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages/django/views/decorators/csrf.py in wrapped_view
        return view_func(*args, **kwargs) ...
▶ Local vars
/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages/tastypie/resources.py in wrapper
                return self._handle_500(request, e) ...
▶ Local vars
/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages/tastypie/resources.py in _handle_500
            return self.error_response(request, data, response_class=response_class) ...
▶ Local vars
/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages/tastypie/resources.py in error_response
            serialized = self.serialize(request, errors, desired_format) ...
▶ Local vars
/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages/tastypie/resources.py in serialize
        return self._meta.serializer.serialize(data, format, options) ...
▶ Local vars
/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/site-packages/tastypie/serializers.py in serialize
        serialized = getattr(self, "to_%s" % desired_format)(bundle, options) ...
▶ Local vars
./cbh_chembl_ws_extension/serializers.py in to_xlsx
        exp_json = json.loads(data.get('export', [])) ...
▶ Local vars
/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/json/__init__.py in loads
        return _default_decoder.decode(s) ...
▶ Local vars
/home/chembiohub/anaconda2/envs/hubtest/lib/python2.7/json/decoder.py in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ...
▶ Local vars
Request information

GET
Variable	Value
limit	
u'10000'
archived	
u'false'
format	
u'xlsx'
creator_uri	
u'/hubtest/api/users/56'
project__project_key__in	
u'plasmid-test-fields'
POST
No POST data
FILES
No FILES data
COOKIES
Variable	Value
hubcsrftoken	
'iaMW0dAosQlSpLzo2ik6ckqIOWQNY0Rk'
ccShowCookieIcon	
'no'
dontShowCookieNotice	
'TRUE'
_ga	
'GA1.4.1814829304.1448456433'
it-services_cookiecontrol	
'yes'
hubtest_sessionid	
'gsr9vvn4kx9dd1ov9t4y7lv9o19gse6a'
_gat	
'1'
hubtestcsrftoken	
'cSCl22jbBC28GAmtbK8jjgWuLkUgtXTM'
META
Variable	Value
wsgi.multiprocess	
False
HTTP_X_FORWARDED_SERVER	
'chembiohub.ox.ac.uk'
HTTP_REFERER	
'https://chembiohub.ox.ac.uk/hubtest/'
HTTP_X_FORWARDED_HOST	
'chembiohub.ox.ac.uk'
uwsgi.version	
'2.0.11.2'
SCRIPT_NAME	
u''
REQUEST_METHOD	
'GET'
UWSGI_ROUTER	
'http'
SERVER_PROTOCOL	
'HTTP/1.1'
QUERY_STRING	
'creator_uri=/hubtest/api/users/56&project__project_key__in=plasmid-test-fields&archived=false&format=xlsx&limit=10000'
HTTP_USER_AGENT	
'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.80 Safari/537.36'
HTTP_CONNECTION	
'Keep-Alive'
HTTP_COOKIE	
'dontShowCookieNotice=TRUE; ccShowCookieIcon=no; it-services_cookiecontrol=yes; hubcsrftoken=iaMW0dAosQlSpLzo2ik6ckqIOWQNY0Rk; _ga=GA1.3.1473125177.1448466165; _gat=1; hubtestcsrftoken=cSCl22jbBC28GAmtbK8jjgWuLkUgtXTM; _ga=GA1.4.1814829304.1448456433; hubtest_sessionid=gsr9vvn4kx9dd1ov9t4y7lv9o19gse6a'
SERVER_NAME	
'chembiohub'
REMOTE_ADDR	
'127.0.0.1'
wsgi.url_scheme	
'https'
SERVER_PORT	
'45096'
uwsgi.node	
'chembiohub'
HTTP_X_FORWARDED_PROTO	
'https'
wsgi.input	
<uwsgi._Input object at 0x7fdc3b985d20>
HTTP_HOST	
'chembiohub.ox.ac.uk'
wsgi.multithread	
False
HTTP_UPGRADE_INSECURE_REQUESTS	
'1'
REQUEST_URI	
'/hubtest/api/cbh_compound_batches/?creator_uri=/hubtest/api/users/56&project__project_key__in=plasmid-test-fields&archived=false&format=xlsx&limit=10000'
HTTP_ACCEPT	
'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
wsgi.version	
(1, 0)
HTTP_X_FORWARDED_FOR	
'176.250.23.129'
wsgi.errors	
<open file 'wsgi_errors', mode 'w' at 0x7fdc3edbbed0>
REMOTE_PORT	
'27882'
HTTP_ACCEPT_LANGUAGE	
'en-GB,en-US;q=0.8,en;q=0.6'
wsgi.run_once	
False
wsgi.file_wrapper	
''
CSRF_COOKIE	
u'cSCl22jbBC28GAmtbK8jjgWuLkUgtXTM'
HTTP_ACCEPT_ENCODING	
'gzip, deflate, sdch'
PATH_INFO	
u'/hubtest/api/cbh_compound_batches/'
Settings
Using settings module deployment.settings.default
Setting	Value
USE_L10N	
True
USE_THOUSAND_SEPARATOR	
False
CSRF_COOKIE_SECURE	
False
DEBUG_SQL	
'INFO'
LANGUAGE_CODE	
'en-us'
ROOT_URLCONF	
'deployment.urls'
MANAGERS	
(('Andrew Stretton', 'andrew.stretton@sgc.ox.ac.uk'),)
BASE_DIR	
'.'
TEST_NON_SERIALIZED_APPS	
[]
DEFAULT_CHARSET	
'utf-8'
SESSION_SERIALIZER	
'django.contrib.sessions.serializers.JSONSerializer'
STATIC_ROOT	
'./deployment/static'
OPEN_BABEL_EXECUTABLE	
'/home/chembiohub/openbabel-2.3.2/build/bin/babel'
ALLOWED_HOSTS	
['staging.chembiohub.ox.ac.uk', 'chembiohub.ox.ac.uk']
COMPOUND_MOLS_TABLE	
'compound_mols'
MESSAGE_STORAGE	
'django.contrib.messages.storage.fallback.FallbackStorage'
EMAIL_SUBJECT_PREFIX	
'[Django] '
SEND_BROKEN_LINK_EMAILS	
False
EXPORT_MODE	
True
API_CACHE_LENGTH	
u'********************'
ENV_NAME	
'hubtest'
SESSION_COOKIE_DOMAIN	
None
ES_PREFIX	
'hubtest'
ADMIN_FOR	
()
TIME_INPUT_FORMATS	
('%H:%M:%S', '%H:%M:%S.%f', '%H:%M')
DATABASES	
{'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.postgresql_psycopg2',
             'HOST': '/home/chembiohub/anaconda2/envs/hubtest/var/postgressocket',
             'NAME': 'hubtest_db',
             'OPTIONS': {},
             'PASSWORD': u'********************',
             'PORT': '',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': 'UTC',
             'USER': 'chembiohub'}}
FILE_UPLOAD_DIRECTORY_PERMISSIONS	
None
STATIC_URL	
'/hubtest/static/'
FILE_UPLOAD_PERMISSIONS	
None
FILE_UPLOAD_HANDLERS	
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
DEFAULT_CONTENT_TYPE	
'text/html'
TEST_RUNNER	
'django.test.runner.DiscoverRunner'
APPEND_SLASH	
True
FIRST_DAY_OF_WEEK	
0
DATABASE_ROUTERS	
[]
DEFAULT_TABLESPACE	
''
YEAR_MONTH_FORMAT	
'F Y'
STATICFILES_STORAGE	
'django.contrib.staticfiles.storage.StaticFilesStorage'
CACHES	
{'default': {'BACKEND': 'django_redis.cache.RedisCache',
             'LOCATION': 'redis://127.0.0.1:6379/1',
             'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'}},
 'hubtest': {'BACKEND': 'django_redis.cache.RedisCache',
             'LOCATION': 'redis://127.0.0.1:6379/1',
             'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                         u'COMPRESS_COMPRESSOR': <built-in function compress>,
                         u'COMPRESS_DECOMPRESSOR': <built-in function decompress>,
                         u'COMPRESS_DECOMPRESSOR_ERROR': <class 'zlib.error'>}}}
SERVER_EMAIL	
'no-reply-chemreg@chembiohub.ox.ac.uk'
SESSION_COOKIE_PATH	
'/'
SILENCED_SYSTEM_CHECKS	
[]
ID_PREFIX	
'UOX'
USE_I18N	
True
THOUSAND_SEPARATOR	
','
SECRET_KEY	
u'********************'
LANGUAGE_COOKIE_NAME	
'django_language'
DEFAULT_INDEX_TABLESPACE	
''
SESSION_CACHE_ALIAS	
'hubtest'
TRANSACTIONS_MANAGED	
False
LOGGING_CONFIG	
'logging.config.dictConfig'
TASTYPIE_CANNED_ERROR	
'An internal server error occurred. Please contact ChEMBL help.'
TEMPLATE_LOADERS	
('django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader',
 'django.template.loaders.eggs.Loader')
WSGI_APPLICATION	
'deployment.wsgi.application'
TEMPLATE_DEBUG	
True
X_FRAME_OPTIONS	
'SAMEORIGIN'
CSRF_COOKIE_NAME	
'hubtestcsrftoken'
CTAB_COLUMN	
'ctab'
FORCE_SCRIPT_NAME	
None
USE_X_FORWARDED_HOST	
False
WS_DOCS_TITLE	
'Chem Bio Hub web services based upon ChEMBL web services live documentation'
SIGNING_BACKEND	
'django.core.signing.TimestampSigner'
SESSION_COOKIE_SECURE	
False
CSRF_COOKIE_DOMAIN	
None
FILE_CHARSET	
'utf-8'
DEBUG	
True
LANGUAGE_COOKIE_DOMAIN	
None
DEFAULT_FILE_STORAGE	
'django.core.files.storage.FileSystemStorage'
INSTALLED_APPS	
('tastypie',
 'django_hstore',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'grappelli',
 'django.contrib.admin',
 'deployment',
 'chembl_core_db',
 'chembl_core_model',
 'chembl_business_model',
 'flowjs',
 'cbh_core_model',
 'cbh_core_ws',
 'cbh_datastore_model',
 'cbh_datastore_ws',
 'cbh_chembl_model_extension',
 'cbh_chembl_ws_extension',
 'cbh_chembl_id_generator',
 'solo',
 'django_rq')
LANGUAGES_BIDI	
('he', 'ar', 'fa', 'ur')
COMMENTS_ALLOW_PROFANITIES	
False
FLOWJS_PATH	
'/home/chembiohub/anaconda2/envs/hubtest/var/media/flow'
STATICFILES_DIRS	
('./src/ng-chem', './src/ng-chem/dist')
PREPEND_WWW	
False
SECURE_PROXY_SSL_HEADER	
None
LANGUAGE_COOKIE_AGE	
None
SESSION_COOKIE_HTTPONLY	
False
DEBUG_PROPAGATE_EXCEPTIONS	
False
INTERNAL_IPS	
('127.0.0.1',)
FULL_RESPONSE_LOGGING	
True
MONTH_DAY_FORMAT	
'F j'
LOGIN_URL	
'/hubtest/login'
SESSION_EXPIRE_AT_BROWSER_CLOSE	
False
RAVEN_CONFIG	
{'dsn': 'http://799d9560a5a24a6abc5383e8a4435111:ebc6d747d1654709b812974757213e85@163.1.63.22/2'}
TIME_FORMAT	
'P'
AUTH_USER_MODEL	
'auth.User'
DATE_INPUT_FORMATS	
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
AUTHENTICATION_BACKENDS	
('django.contrib.auth.backends.ModelBackend',)
EMAIL_HOST_PASSWORD	
u'********************'
PASSWORD_RESET_TIMEOUT_DAYS	
u'********************'
SESSION_FILE_PATH	
None
CACHE_MIDDLEWARE_ALIAS	
'default'
SESSION_SAVE_EVERY_REQUEST	
True
NUMBER_GROUPING	
0
CONDA_ENV_PATH	
'/home/chembiohub/anaconda2/envs/hubtest'
FULL_HEADER_LOGGING	
False
SESSION_ENGINE	
'django.contrib.sessions.backends.db'
WEBSERVICES_NAME	
'hubtest/api'
CSRF_FAILURE_VIEW	
'django.views.csrf.csrf_failure'
CSRF_COOKIE_PATH	
'/'
LOGIN_REDIRECT_URL	
'/hubtest/#/projects/list'
PROJECT_ROOT	
'/srv/chembiohub_installs/chembiohub_ws/deployment/settings'
INCHI_BINARIES_LOCATION	
{'1.02': '/home/chembiohub/anaconda2/envs/hubtest/var/INCHI-1-BIN/linux/64bit/inchi-1'}
IGNORABLE_404_URLS	
()
LOCALE_PATHS	
()
TEMPLATE_STRING_IF_INVALID	
''
API_CACHE_ENABLE	
u'********************'
OPEN_SOURCE	
True
LOGOUT_URL	
'/accounts/logout/'
EMAIL_USE_TLS	
False
FIXTURE_DIRS	
()
EMAIL_HOST	
'smtp.ox.ac.uk'
DATE_FORMAT	
'N j, Y'
LOGGING	
{'formatters': {'simple': {'format': '%(levelname)s %(message)s'},
                'verbose': {'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'}},
 'handlers': {'console': {'class': 'logging.StreamHandler',
                          'formatter': 'simple',
                          'level': 'DEBUG'}},
 'loggers': {'cbh_chembl_id_generator': {'handlers': ['console'],
                                         'level': 'DEBUG',
                                         'propagate': True},
             'cbh_chembl_model_extension': {'handlers': ['console'],
                                            'level': 'DEBUG',
                                            'propagate': True},
             'cbh_chembl_ws_extension': {'handlers': ['console'],
                                         'level': 'DEBUG',
                                         'propagate': True},
             'cbh_core_model': {'handlers': ['console'],
                                'level': 'DEBUG',
                                'propagate': True},
             'cbh_core_ws': {'handlers': ['console'],
                             'level': 'DEBUG',
                             'propagate': True},
             'cbh_datastore_model': {'handlers': ['console'],
                                     'level': 'DEBUG',
                                     'propagate': True},
             'cbh_datastore_ws': {'handlers': ['console'],
                                  'level': 'DEBUG',
                                  'propagate': True},
             'chembl_business_model': {'handlers': ['console'],
                                       'level': 'DEBUG',
                                       'propagate': True},
             'chembl_core_db': {'handlers': ['console'],
                                'level': 'DEBUG',
                                'propagate': True},
             'chembl_core_model': {'handlers': ['console'],
                                   'level': 'DEBUG',
                                   'propagate': True},
             'deployment': {'handlers': ['console'],
                            'level': 'DEBUG',
                            'propagate': True},
             'django': {'handlers': ['console'],
                        'level': 'INFO',
                        'propagate': True},
             'django.contrib.admin': {'handlers': ['console'],
                                      'level': 'DEBUG',
                                      'propagate': True},
             'django.contrib.auth': {'handlers': ['console'],
                                     'level': 'DEBUG',
                                     'propagate': True},
             'django.contrib.contenttypes': {'handlers': ['console'],
                                             'level': 'DEBUG',
                                             'propagate': True},
             'django.contrib.messages': {'handlers': ['console'],
                                         'level': 'DEBUG',
                                         'propagate': True},
             'django.contrib.sessions': {'handlers': ['console'],
                                         'level': 'DEBUG',
                                         'propagate': True},
             'django.contrib.sites': {'handlers': ['console'],
                                      'level': 'DEBUG',
                                      'propagate': True},
             'django.contrib.staticfiles': {'handlers': ['console'],
                                            'level': 'DEBUG',
                                            'propagate': True},
             'django_hstore': {'handlers': ['console'],
                               'level': 'DEBUG',
                               'propagate': True},
             'django_rq': {'handlers': ['console'],
                           'level': 'DEBUG',
                           'propagate': True},
             'flowjs': {'handlers': ['console'],
                        'level': 'DEBUG',
                        'propagate': True},
             'grappelli': {'handlers': ['console'],
                           'level': 'DEBUG',
                           'propagate': True},
             'solo': {'handlers': ['console'],
                      'level': 'DEBUG',
                      'propagate': True},
             'tastypie': {'handlers': ['console'],
                          'level': 'DEBUG',
                          'propagate': True}},
 'version': 1}
MEDIA_ROOT	
'/home/chembiohub/anaconda2/envs/hubtest/var/media/'
DEFAULT_EXCEPTION_REPORTER_FILTER	
'django.views.debug.SafeExceptionReporterFilter'
ADMINS	
(('Andrew Stretton', 'andrew.stretton@sgc.ox.ac.uk'),)
WS_BASE_URL	
'/chemblws'
FORMAT_MODULE_PATH	
None
DEFAULT_FROM_EMAIL	
'webmaster@localhost'
TASTYPIE_ALLOW_MISSING_SLASH	
True
MEDIA_URL	
''
DATETIME_FORMAT	
'N j, Y, P'
TEMPLATE_DIRS	
('./src/ng-chem/',)
MIDDLEWARE_CLASSES	
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']
SITE_ID	
1
DISALLOWED_USER_AGENTS	
()
ALLOWED_INCLUDE_ROOTS	
('/home/vagrant/', '/var/www/chembiohub_ws/')
DECIMAL_SEPARATOR	
'.'
SHORT_DATE_FORMAT	
'm/d/Y'
RQ_QUEUES	
{'default': {'USE_REDIS_CACHE': 'hubtest'}}
LOGOUT_REDIRECT_URL	
'/hubtest/login'
STATICFILES_FINDERS	
('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder')
CACHE_MIDDLEWARE_KEY_PREFIX	
u'********************'
TIME_ZONE	
'America/Chicago'
FILE_UPLOAD_MAX_MEMORY_SIZE	
2621440
APP_SPECIFIC_TABLES_MANAGED	
True
EMAIL_BACKEND	
'django.core.mail.backends.smtp.EmailBackend'
CORE_TABLES_MANAGED	
True
EMAIL_USE_SSL	
False
TEMPLATE_CONTEXT_PROCESSORS	
('django.core.context_processors.csrf',
 'django.contrib.auth.context_processors.auth',
 'django.core.context_processors.debug',
 'django.core.context_processors.i18n',
 'django.core.context_processors.media',
 'django.core.context_processors.static',
 'django.core.context_processors.request',
 'django.contrib.messages.context_processors.messages',
 'deployment.context_processors.static_paths')
MIGRATION_MODULES	
{}
SESSION_COOKIE_AGE	
1209600
SETTINGS_MODULE	
'deployment.settings.default'
USE_ETAGS	
False
LANGUAGES	
(('af', 'Afrikaans'),
 ('ar', 'Arabic'),
 ('ast', 'Asturian'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('be', 'Belarusian'),
 ('bn', 'Bengali'),
 ('br', 'Breton'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-au', 'Australian English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('es-ve', 'Venezuelan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('ia', 'Interlingua'),
 ('id', 'Indonesian'),
 ('io', 'Ido'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lb', 'Luxembourgish'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('mr', 'Marathi'),
 ('my', 'Burmese'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('os', 'Ossetic'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('udm', 'Udmurt'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-hans', 'Simplified Chinese'),
 ('zh-hant', 'Traditional Chinese'),
 ('zh-tw', 'Traditional Chinese'))
FILE_UPLOAD_TEMP_DIR	
None
CSRF_COOKIE_AGE	
31449600
SESSION_COOKIE_NAME	
'hubtest_sessionid'
EMAIL_PORT	
25
USE_TZ	
True
SHORT_DATETIME_FORMAT	
'm/d/Y P'
PASSWORD_HASHERS	
u'********************'
ABSOLUTE_URL_OVERRIDES	
{}
LANGUAGE_COOKIE_PATH	
'/'
CACHE_MIDDLEWARE_SECONDS	
3000000
CSRF_COOKIE_HTTPONLY	
False
DATETIME_INPUT_FORMATS	
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
EMAIL_HOST_USER	
''
PROFANITIES_LIST	
u'********************'

**Comment by KarenPorter** [comment]
Still an issue - needs estimating and scheduling

**Comment by strets123** [comment]
Now exports with an empty Excel sheet hubtest

**Comment by KarenPorter** [comment]
it does export (although now I can't export when there actually is data - as noted against issue #800).

Also, exports with the fields in alphabetical order rather than the order of the project configuration which would be irritating to users.

**Comment by strets123** [comment]
Fields are in the project registered order. Uncurated fields then follow the project fields. These are in alphabetical order

**Comment by KarenPorter** [comment]
passed
