### ISSUE TITLE
Tab order when adding single cpd in hubtest is all over the place - no relevance to field order.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#779]
Tab order when adding single cpd in hubtest is all over the place - no relevance to field order.

**Comment by KarenPorter** [comment]
They now tab in order.  I should have recorded the specific project I was testing on at the time but as far as I can tell now (for the projects on hubtest) this is fixed - may have been an artefact of how custom fields were earlier defined?

Closing
