### ISSUE TITLE
In hubtest I'm trying to upload a file to SBM CDT Test - get whirring for 1-2 seconds then nothing, 

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#781]
In hubtest I'm trying to upload a file to SBM CDT Test - get whirring for 1-2 seconds then nothing, no error messages, File isn't uploaded.

**Comment by strets123** [comment]
Should be fixed, smae issue with global variable

**Comment by aekhendry** [comment]
This is now fixed. Hubtest chrome
