### ISSUE TITLE
Project title on project list page is not clickable.


Message says "Click a project title to see mo

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#786]
Project title on project list page is not clickable.

Message says "Click a project title to see more details and add data to that project" but title is not clickable, Info icon similarly implies project title should take user to an overview page.  Either message should be changed or title becomes clickable.

**Comment by PaulBarrett79** [comment]
Message has been changed to "A list of all of the projects you have access to.". The info/help button explains all of the actions available to a user on this page.

Deployed to hubtest

**Comment by aekhendry** [comment]
Fixed hubtest chrome
