### ISSUE TITLE
Re-create chemreg help GIFs with new screens and workflow

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#787]
The old help GIFs for chemreg are obsolete - they need replacing with new ones which show new workflow, redesigned pages and better performance.

**Comment by KarenPorter** [comment]
More work needed to update whole help page (including gifs)

**Comment by KarenPorter** [comment]
check with @PaulBarrett79

**Comment by KarenPorter** [comment]
done - closing
