### ISSUE TITLE
Exported batch details doesn't include AlogP.  

I exported the batch 5043 from Chemical Inventory p

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#789]
Exported batch details doesn't include AlogP.  

I exported the batch 5043 from Chemical Inventory project on hubtest and although there is a heading for alogp it is blank in the spreadsheet. View the project details and it is there.

**Comment by KarenPorter** [comment]
Should the 3 issues 789, 818 and 821 be addressed together?

**Comment by KarenPorter** [comment]
Resolved. Closing.
