### ISSUE TITLE
What should Search Compounds button do when you are on the search page?  Currently is clickable,does

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#790]
What should Search Compounds button do when you are on the search page?  Currently is clickable,does nothing and the URL shows including a project key for a specific project (Plasmid test fields).  Just feels slightly flaky.

**Comment by KarenPorter** [comment]
I think this behaviour might have changed.  Seems more robust now - all just stays as it was.  Can probably close - @strets123 can you confirm if you think there's an issue in this area and if not, close this ticket.

**Comment by KarenPorter** [comment]
resolved. Closed.
