### ISSUE TITLE
Analysis of minimal extension for AssayReg Plus

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#792]
Determine minimum functionality and effort needed to extend AssayReg to add significant added value (AKA ELN-Lite, although this would still be somewhat short of that)

Components to spec and estimate:

rich text data capture
image capture and annotation
field selection and deposition

For comparison purposes - very basic analysis of existing utilities - EverNote, SciNote and ELN utility developed by Luc Patigny(if we can get hold of it) for fit, effort to integrate and functional benefits, plus any major deficiencies or drawbacks.

Producing - recommendation and estimate, prerequisites, scope and out of scope statement, testing requirements, success criteria.

**Comment by PaulBarrett79** [comment]
Also I will attempt to identify people we should ask for further advice on this - the "college tutor" mentioned in our meeting this morning.

**Comment by strets123** [comment]
Bottom level of the assay item should use vertical tabs
A given "level" in a data form config could have the option of enabling / disabling the following features not currently supported by assayreg directly:

Generic File uploads
Image uploads
"Sample uploads" - would link to Chemreg
Data tables (using the current quick data upload function)

Would probably be easier to implement these things outside of angular schema form as the data can then more easily be used for other things

**Comment by PaulBarrett79** [comment]
Document is at S:\OxChemBioDB\Project Documents\Requirements Capturing\AssayReg\AssayReg ELNification.docx

**Comment by strets123** [comment]
Further task was the addition of export functionality to assareg which allows multiple levels to be downloaded at once.
Estimate 2 days to create a dot net script that can do this with high fidelity

**Comment by PaulBarrett79** [comment]
This analysis has been completed and resulted in a number of other subtasks
