### ISSUE TITLE
SciNote evaluation

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#793]
Test SciNote and provide feedback on:

- potential bugs, 
- parts of the software that are not intuitive (including the position of buttons,...), 
- features that you don't like and 
- new features that you believe should be implemented).

**Comment by strets123** [comment]
Gap analysis of ChemBio Hub and how that might be fulfilled by scinote

|   |   |   |   |   |
|---|---|---|---|---|
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |
|   |   |   |   |   |

**Comment by strets123** [comment]
Feedback on Scinote:

Slow web service calls (may be a latency issue due tio location of server hosting it)
Delayed change of page for example click on user profile in the top right and you can then do something else while you are waiting - it should change page then run the code for the page.
No loading icons to indicate an update is being made to something

**Comment by PaulBarrett79** [comment]
I've added a report on this to the S drive at S:\OxChemBioDB\Reports\SciNote Feedback PB.docx

**Comment by PaulBarrett79** [comment]
Feedback gathered and given back to SciNote by Karen
