### ISSUE TITLE
Custom field config and simple project admin

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#795]
Item|Estimate|Date|Done ?|Tested by
---|:-:|:-:|:-:|:-:
Owners of an project can change the name of it|3|11/01/16|on time|
need to also fix the issue with names etc. against the permission codes which prevents django upgrade|3|12/01/16|on time|
1:1 relationship between project and custom field config so that this doesn't affect other projects - deal with legacy data|5|12/01/16|ahead|
Create new project|4|13/01/16|on time|
Add custom fields to project|4|14/01/16|on time|
Hide custom fields either from all users or from viewers|1|14/01/16|just viewers|
Change order of custom fields in table and other views|1|14/01/16|on time|
Deploy for test ~ 2pm|2|15/01/16|done|

**Comment by strets123** [comment]
Adding an archive feature and changing what the close button does in the front end is slightly tricky. Therefore I am going to do htis on the back end and have a separate section for archived fields. The archived fields can then just have a button for restore.

**Comment by strets123** [comment]
- [ ]	If the user is an “owner” of a given project then the “edit configuration” link can be seen in the project list by the title
- [ ]	If the project name is updated to one longer than 100 characters then a warnng message appears and the update and close button does not work
- [ ]	The associated permission names for a given project are updated in the user admin
- [ ]	The Custom field config name for the given project also gets updated
- [ ]	If a user is not an owner then the edit configuration link is disabled
- [ ]	After adding or updating a project the whole window reloads
- [ ]	If the project name has non alphanumeric characters there is an error message and you cant submit
- [ ]	If a field name has commas, slashes, dots or quotes you can't submit
- [ ]	If a field name is repeated you cant submit
- [ ]	If you add a required value then you are able to set a default for it
- [ ]	If you add a choice field then you are able to set the possible values for it
- [ ]	If you edit an existing project then you cant delete the fields except where they are just being added
- [ ]	If you mouse over a field then you get a cursor to show it can be dragged and dropped
- [ ]	If you edit an existing project then you cant change the names of the fields
- [ ]	Known bugs that are not serious but hard to fix – if you add a field with the same name as a previous field that is readonly, both become readonly. If you don't put a name in on the second field item in the list then the error message “Required” does not show up properly
- [ ]	You cannot yet hide a field from all users but can move it to the end

**Comment by KarenPorter** [comment]
@strets123 is this ready for testing now?  Still in under investigation column.

**Comment by strets123** [comment]
Yes, there is another bug that has only arisen this morning, not sure where from

**Comment by aekhendry** [comment]
Close and disregard in edit config mode is not working.
No error message provided for item two in list. Will not let you save as intended however.
Item 8 will submit for /. Also, for others, error message appears when you enter it, but if you click save, it does not save but error message dissapears.
I got the IE10 doodle warning when using chrome.
It is not saving default value/ description/ choice field value in edit config mode
I think despite some indication it could be clearer that they can be dragged and dropped. Also, is there anything to indicate what the relevance of being able to do this is?
I'm not sure I understand Item 3 and 4 in the list

**Comment by strets123** [comment]
Close and disregard in edit config mode is not working.
>> Now working
No error message provided for item two in list. Will not let you save as intended however.
>> Now working
Item 8 will submit for /. Also, for others, error message appears when you enter it, but if you click save, it does not save but error message dissapears.
>> Now not doing this, stops if error
I got the IE10 doodle warning when using chrome.
>> Not reproduced
It is not saving default value/ description/ choice field value in edit config mode
>> Please try again havent tested this yet
I think despite some indication it could be clearer that they can be dragged and dropped. 
>> Done
Also, is there anything to indicate what the relevance of being able to do this is?
>> Done
I'm not sure I understand Item 3 and 4 in the list
>> These are backend items to avoid things becoming duplicates


>> Final thing is need to deal with server errors if project name used before not yet done

**Comment by aekhendry** [comment]
Not working -

No error message provided for item two in list. Will not let you save (as intended ) however.

****
When searching all, I'm seeing items from the CDT project, even though that project (or the data) does not appear to exist on the system.

Custom field creation of choice and tag fields now saves, however this function is broken when i try to add data to the project. Drop downs are not working, and it is possible to enter in data directly into the table via edit mode when you should not be able to (I.e. for choice fields)

**Comment by aekhendry** [comment]
A clearer indication is required on each project as to what your permissions are. MAybe something the says either viewer, editor or owner. There is plenty of space for it

**Comment by aekhendry** [comment]
Odd behaviour now when creating a project with multiple tagged / choice custom fields. The default values are modified for ALL custom fields of this type. this means you cannot have two of these field types with different field types.

**Comment by aekhendry** [comment]
Above issues are all fixed. An old issue however:

It is still possible to enter values directly into the handsontable for the choice only field.

Edit table -> Enter value into a cell of the choice only field type -> Click save -> Value is saved even though it wasn't an option in the original choice.

Maybe the ability to freeze any cells of a particular field type is necessary?

**Comment by strets123** [comment]
OK, well marking as ready for deployment, I will add this issue to the edit mode issue
