### ISSUE TITLE
Basic editing of project permissions

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#796]
Item|Estimate|Date|Done ?|Tested by
---|:-:|:-:|:-:|:-:
Add user to project as editor or viewer if you are the owner|5|15/01/16|done|
Rename admin permission to owner via migration|1|18/01/16|done|
Remove user from project if you own the project|3|18/01/16|done|
Add and remove other owners|1|19/01/16|done|
Also needs a flag on the user model to say that user is from outside and make new users invitable|1|19/01/16|done|
On addition of a project, creator becomes the owner|1|19/01/16|done|
Deploy for test ~ 4pm|2|19/01/16| done|

**Comment by strets123** [comment]
Now ensured that validation is in both the back end and the front end

**Comment by aekhendry** [comment]
Having trouble finding this permission in admin. It doesn't seem to exist as described here?

**Comment by strets123** [comment]
Once we are on the production system you can just add it to the "member" group
That way only Oxford login people will be able to add projects

**Comment by strets123** [comment]
Scan through the perpissions dropdown, you will find cbh_core_model__add_project

**Comment by aekhendry** [comment]
Apologies, found it. Working nicely. hubtest chrome
