### ISSUE TITLE
Easier adding of project fields and permissions via clones

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#797]
Item|Estimate|Date|Done ?|Tested by
---|:-:|:-:|:-:|:-:
Add fields to project from file|3|20/01/16|not done|
Clone fields from existing project|3|20/01/16|done|
Clone permissions from existing project |3|done ahead of time||
Deploy for test ~ 2pm|2|21/01/16||
Deploy for production ~ 12pm|3|22/01/16||
Adam will need to assign owners in the admin for existing projects|1|22/01/16||

**Comment by strets123** [comment]
Please test and close if done

**Comment by aekhendry** [comment]
'Copy Project Definition' button in project creation is not clear. Change to 'Clone Project Fields'?

**Comment by aekhendry** [comment]
Otherwise works well. hubtest chrome

**Comment by strets123** [comment]
OK, agreed on terminology with Adam
