### ISSUE TITLE
2 weeks work for 1 person on organisations, to be split further...

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#798]
Item	Estimate	Date	Done ?	Tested by
---	:-:	:-:	:-:	:-:
New API for organization, subclass of group, fields that are in the "group" part are disguised	8			
organisations Admin integrated	2			
Ownership is persisted as permissions eg org1_owner	1			
Organisation will also have a name which will mirror the group name for research groups	1			
Owners list is added to API as an attribute for the given organisation and db changes are dealt with on the backend by overriding default tastypie methods	2			
Also a simple attribute like we have for project to say user is an owner	1			
Owners can add people to an organisation which sends an appropriate invite email	8			
Invitation emails will be updated to include the organisation added and permissions of that organisation	3			
Permissions updated emails need to be verified to contain all of the user's permissions as a summary after the change	2			
Owners can remove people from the organisation.	1			
Owners cannot leave the organisation - they have to ask some other owner to remove them having the effect that an organisation must have an owner	1			
Based on the department affiliations, organizations will be created but they won't have owners until we assign them in the admin - they don't need owners	adam task			
Outside users cannot be added to an organisation - this needs a change to the skinningconfig so that it is not a default behaviour	2			
Add group to project as editor or viewer if you are the owner but dont allow add a group as an owner	5			
When selecting groups to add to a project from the dropdown,the default dropdown before they type should contain the organisations they are a member of	3			
On sign up the new user would see the organisations list and would click a mailto link in order to ask to join an organisation or would start an organisation	1			
They can add their own project and would get a "looks like you need to page"	1			
No email required if user removed from a project or group	0.5			
No email required if user changes themselves	0.5			
Oxford users can be invited - needs work on webauth	5			
New user is added as a member to any organisations that were in the invitation	5			
Archive projects if project owner - show archived projects button available at the bottom, info box on the archive button to say that the show archived button is at the bottom	2			
Leave system - just a mailto link	0.5			
Current frontend functionality for invitations will be removed in favour of an organisation by organisation, project by project approach - effort to remove current feature	1			
Tidy up info boxes on the project list page	2			
Organisations list on front end	4

**Comment by KarenPorter** [comment]
@strets123 I think this is now off the table?  Certainly as originally envisioned?  Can you please amend proposed scope or close.

**Comment by KarenPorter** [comment]
closing
