### ISSUE TITLE
Rich Text Editor field within AssayReg

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#799]
Item|Estimate|Date|Done ?|Tested by
---|:-:|:-:|:-:|:-:
Evaluate available RTEs for suitability|3|11/01/16|yes | |
Set up Rich Text field in django schema form|3|12/01/16|yes| |
Set up rich text field display in front end|3|12/01/16|yes| |
Save a draft|3|13/01/16| | |
autosave using save draft mechanism|5|14/01/16| | |
testing|3|15/01/16| | |

**Comment by PaulBarrett79** [comment]
I have put an assesssment of RTEs on the S drive 

S:/OxChemBioDB/Project Documents/Requirements Capturing/AssayReg/AssayReg RTE comparison.docx

**Comment by PaulBarrett79** [comment]
I have implemented ckEditor to be used wherever there is a textarea field (large text block) as a form element within AssayReg.

Create a form for a level which contains a "Full Text" field
Create a new level object using that form
The Full Text field will use the rich text editor
Add some text with formatting
Save the object
In the AssayReg data overview, view the field details
In the modal popup, the field will be displayed with any formatting applied to the text entered.

**Comment by PaulBarrett79** [comment]
Deployed to hubtest

**Comment by aekhendry** [comment]
Can't test I'm afraid. Assay reg appears to be broken. I cant edit or create a new subproject in a new assay reg project.

**Comment by strets123** [comment]
Please test again, working now I think

**Comment by aekhendry** [comment]
Not working I'm afraid, I get no text box in any level when I set it to full text. The text box is not appearing where it should be. Short text working fine.

**Comment by PaulBarrett79** [comment]
Are you changing an existing project fields?

Have you tried adding a new level and setting one of the fields to be fulltext?

**Comment by PaulBarrett79** [comment]
I've changed the way we use ckeditor - we were using a CDN (hosted elsewhere) but I've added this as a bower dependency now. This means it *should* work on hubtest now (was working fine on Andy's machine and my machine locally).

Andy needs to test that it installs correctly from bower on his machine.

Pushed to github, awaiting deployment

**Comment by PaulBarrett79** [comment]
Had to modify the bower file again becuase it required user input to decide between ckeditor versions (not suitable for automated deployment).

Pushed for review by AS.

**Comment by PaulBarrett79** [comment]
More bower issues - now fixed.

Deployed to hubtest

**Comment by aekhendry** [comment]
Works well. Table and add image does not work though as I expected. Can we disable these buttons?

**Comment by PaulBarrett79** [comment]
I can try disabling these.

**Comment by PaulBarrett79** [comment]
This is possible by defining explicitly which elements to include (and leaving out those which are not required).

**Comment by PaulBarrett79** [comment]
I have added configuration to the back end so that the editor has limited functionality (nothing HTML or table related - just formatting is allowed)

Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to hubtest

**Comment by aekhendry** [comment]
Working, hubtest chrome
