### ISSUE TITLE
File attachment field in AssayReg

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#800]
Item|Estimate |Date |Done? |Tested by
---|:-:|:-:|:-:|:-:
Set up image fields and storage location provision within AssayReg|8|19/01/16|yes | |
Configure image fields in django schema form|3|20/01/16|yes | |
FlowFile integration (our existing file upload service) and configuring for upload progress|5|21/01/16| | |

**Comment by PaulBarrett79** [comment]
- [ ] datastore_model models.py create a dictionary of image and non image file extensions and mimetypes
- [ ] cbh_datastore_ws resources.py need to replace BaseAttachmentResource authorization with a custom one to check user can access the file via DPC

**Comment by PaulBarrett79** [comment]
File attachment - as defined as being able to add images to assayreg data levels, not within any ChemiReg components - should now be ready to test.

**Comment by PaulBarrett79** [comment]
If this functionality should be replicated within ChemiReg elements, to move AssayReg parts into ChemiReg, then this should receive a new issue ticket.

**Comment by aekhendry** [comment]
I upload the image, it previews. But clicking save results in a 400 error. What should we do with this, as the application is no longer relevant but the functionality is?

**Comment by KarenPorter** [comment]
This should work - at least as a demonstration of principle.

I found:
500 error when I duplicate an existing activity (independent of whether there's an image associated

404 error when I attach a file (non-image)
400 error on submit

Please investigate @PaulBarrett79  - if no resolution within a short period of time, record findings and proposed further investigations / actions so they can be incorporated into ChemiReg solution development

**Comment by PaulBarrett79** [comment]
I know for a fact that this is currently only accepting images. So the first action to fix this is have validation that the file uploaded is an image file (not allowing upload if file is not an image). Then moving on to how to handle different file types, for example Excel.

**Comment by KarenPorter** [comment]
I don't think we need to handle different file types specifically - just ensure that we only accept images and have the right notification when the file isn't an image.  

The core issue to address here is the 400 error - we have tested uploading an image and it doesn't work.

**Comment by PaulBarrett79** [comment]
The 400 errors are reproducible on my machine.

I removed the elasticsearch index for assayreg datapoints, reindexed and was able to add data with (and without) a file correctly.

Since the elasticsearch index for hubtest is on the same box as hub, I can't do this fix inside of working hours in case it stops someone else's upload.

For future reference, I will raise with @strets123  that if a particular fix or release needs an elasticsearch re-index, it should be tagged as such wither in the code or on here. It's easy to do, the time is taken working out that reindexing is what is needed.

**Comment by PaulBarrett79** [comment]
I have reindexed hubtest - this is now available for testing once again.

**Comment by aekhendry** [comment]
So I believe this is working. I upload a file, and in the table it is listed as something like {"attachments":[{"mimeType":"image/jpeg","printName":"sign-racoonrat.jpg","url":"/hubtest/api/datastore/cbh_base_attachments/19"}]}

However a limitation of assay reg is that there is no single molecule view for an assay result, and so i have no way of actually seeing the image currently.  If I click duplicate, the image is shwon to me in the single activity submission form, indicating that the image has been stored.

I understand that this issue may lie outside the remit of the card, and may be covered by the future changes to ChemiReg. If this is the case, then please move to awaiting deployment.

Hubtest chrome

**Comment by KarenPorter** [comment]
Accepted with constraint that this is AssayReg only and needs to be applied to ChemiReg.  Push to awaiting deployment.
