### ISSUE TITLE
Update data point may change the created by name on assayreg

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#802]
This would explain the issue we have seen with this, need to explore further

**Comment by strets123** [comment]
I have put a fix in place for this across assayreg and chemreg

**Comment by strets123** [comment]
Please test this by:

On hub - create a datapoint, log in as different user, edit the datapoint

Do same on hubtest.

Using assayreg search look for the datapoints.

On hubtest the datapoint will belong to the creating user

On hub it will belong to the updating user

**Comment by aekhendry** [comment]
Can't test on hub, I'm getting a 500 error whenever I click save. I've tried this with a few projects and it seems that the save function is broken at all levels in the project.

**Comment by strets123** [comment]
This bug only happens when you add the first ever thing in. I have tested by automated tests and it works now, closing
