### ISSUE TITLE
Rebrand ChemReg as ChemiReg

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#803]
determine what changes need to happen - 
technical (code and commentary) - schedule effort
publicity (user community comms)
behavioural (effect change).

**Comment by strets123** [comment]
Technical - 2 hours for general code base
2 hours for file names and blog post and web page names

**Comment by PaulBarrett79** [comment]
Performed this ChemReg to ChemiReg for the CBH main site. I have deployed this to staging.chembiohub.ox.ac.uk for checking.

Modified all text
Modified images

**Comment by PaulBarrett79** [comment]
Performed ChemReg to ChemiReg for email text, help text, message parameters and front-end file names within the ChemBio Hub platform.

Pushed to github

**Comment by PaulBarrett79** [comment]
Provided that we are happy for low-risk only changes (no class names, DB names or anything that needs any kind of data migration) I will push this to hubtest for testing.

**Comment by KarenPorter** [comment]
@aekhendry I think you have signed off - please confirm and move to deployment list.

**Comment by aekhendry** [comment]
Tested the website changes and working fine, happy for it to be deployed

**Comment by PaulBarrett79** [comment]
Deployed CBH main site to chembiohub.ox.ac.uk

**Comment by PaulBarrett79** [comment]
Deployed ChemBio Hub platform changes to hubtest. 

ChemiReg text displayed in hubtest.

**Comment by aekhendry** [comment]
Seems to be all good, only changes i could really see were in the Help FAQ. hubtest chrome

**Comment by strets123** [comment]
@PaulBarrett79 There is a load of changes that were made at the time we were working on the AssayReg front end alone which need to be rolled back and converted in ChemiReg e.g. see messagefactory.js and other mentions of AssayReg that should be platform or chemireg

**Comment by KarenPorter** [comment]
@strets123 caveat accepted - but this issue concerns visible branding only (to satisfy requirements of ChemRegs) - therefore signing off on this issue and pushing to awaiting deployment
