### ISSUE TITLE
When adding the first datapoint to an  AssayReg instance there is a reproducible error

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#805]
Need to change the initial migration so that the id sequence updates properly - see 0011_auto_20150810_1258.py

**Comment by strets123** [comment]
I have changed the code to allow this to work properly. New test framework proves this is fixed

**Comment by KarenPorter** [comment]
@strets123 Not sure why this is in code review?  From comments looks like it is ready to test?  

How does AN other confirm fix though?  steps to produce original error / steps to demo it no longer happens - can we sign off on test framework run?

**Comment by strets123** [comment]
Sign off as tested
