### ISSUE TITLE
Improve auto-mapping of fields

### ISSUE THREAD

**Issue by ddamerell53** [thesgc/chembiohub_helpdesk#811]
The SGC installation of ChemReg includes the two custom fields: RequestedGlobalID and RequestedLocalID.  For some reason when we batch upload an SDF file the RequestedGlobalID field gets mapped to RequestedLocalID.

We use these columns to determine which compound series the user is requesting that the compounds get registered for.

**Comment by strets123** [comment]
I have committed something and believe this is now fixed but I have not had time to add a test. Please pull and see if this now works.

**Comment by strets123** [comment]
confirmed as working by @ddamerell53
