### ISSUE TITLE
Structure image in Excel export

### ISSUE THREAD

**Issue by ddamerell53** [thesgc/chembiohub_helpdesk#813]
As part of the SGC compound registration process we are required to export an SDF and Excel document for audit purposes.  Our custom ChemReg plugin uses the generic ChemReg SDF/Excel exporters to generate these audit files.  At the moment the Excel export is missing an image of the structure.  Whilst perhaps not 100% essential I think it's something everybody would expect of the Excel export functionality in the GUI anyway.

I've marked this as a "Showstopper" as I want to as closely as possible replicate our existing audit file formats.

**Comment by strets123** [comment]
I have now added the structure image functionality - please pull all repositories to see it.

**Comment by strets123** [comment]
Confirmed as working by @ddamerell53
