### ISSUE TITLE
Using saved searches for assayregging

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#820]
Instead of having assayreg as a separate tool, there is another way.,..

**Comment by strets123** [comment]
All data is stored in the current ChemReg Schema

Project type can either be:

Saved search project
Inventory Project
Novel Compound Project
Experiment Results Project


Saved searches are made into a "field" of AssayReg
Any saved search project the user has access to will have its saved searches listed in the saved search list but it will also be possible to browse them in greater detail by 
Extra information can then be added to a saved search which would in effect be an experimental report.
Individual items can also be "picked" and added to an existing saved search

**Comment by KarenPorter** [comment]
@strets123 

Needs an approach and estimate for planning purposes.

**Comment by KarenPorter** [comment]
redundant.  Closing.
