### ISSUE TITLE
Excel export is exporting system generating fields that it shouldn't

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#821]
See feedback from Colin:

There are some extra columns – Std InChi, alogp, Known Drug and MedChem Friendly – which were not on my headings and I have no idea what they are, and some duplicates – Mol Formula and Formula, Mol Weight and Mol Wt.

Can we please correct this?

**Comment by KarenPorter** [comment]
@strets123 for review

@aekhendry  - please label bugs for review so that Andy / Paul are aware (as well as contacting them directly if needed to explain more fully or discuss).

**Comment by KarenPorter** [comment]
Should the 3 issues 789, 818 and 821 be addressed together?

**Comment by KarenPorter** [comment]
Resolved. Closing.
