### ISSUE TITLE
Chemireg back end - making ready for handover

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#822]
API consistency is required:

Make the created by field work properly

Make changes to the data as it passes through functions and testable

Document and test the API

Add one elasticsearch type or index per project to keep mappings from possibility of interferance

Tidy up the way that sorting is done

Get rid of the inconsistencies with the rest of the system

Get  rid of the camelCase converter thing

Make the elasticsearch API consistent with tastypie

Consider abandoning resource URIs as we will not have enough separate resources to warrant them

Make the calls to the API more REST like

Use an appropriate way to serialize elasticsearch queries

Get rid of the need for partial deserialization of the HStore fields by simply moving to django JSON on v1.9

Remove the dependency on Chembl

Make elasticsearch indexing happen in one call

Support a saved searches as field

Support the feature "Saved searches that this item appears in"

Support adding the first item singly and creating the ES index properly in the process

Use the elasticsearch GET api so we need to do minimal reformatting of the request object

Use the django rdkit module for simpler structure search

**Comment by KarenPorter** [comment]
First off - needs an analysis effort to estimate effort @strets123

**Comment by KarenPorter** [comment]
@strets123 assume done as part of refactoring?
