### ISSUE TITLE
Clone a compound analysis

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#825]

**Comment by strets123** [comment]
The cloning of a compound will work be removing the relevant IDs from the existing value and then saving it.

Following the save, the redirect will change to be a UOX id in query which shows the compound cloned AND the new compound in edit mode.

The message will be changed to tell the user that they can archive their previous compound should they wish.

**Comment by strets123** [comment]
Deployed, hubtest

**Comment by aekhendry** [comment]
Working, hubtest chrome
