### ISSUE TITLE
No indication that a structure search was an invalid structure

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#832]
There is an alert box that comes up if the structure search is invalid from the custom fields system but no proper alert to save the structure entered was incorrect.

**Comment by KarenPorter** [comment]
awainting deployment , then can be tested

**Comment by KarenPorter** [comment]
User is notified via greying out of apply and close button, and a message - passed.

I think I've captured this elsewhere, but the message when there are no matching results needs improving - 0 results    -    No Compounds Found. To add compounds use the link above. - there is no link above.

**Comment by PaulBarrett79** [comment]
1 hour job to get wording right and/or add any other visual cues

**Comment by PaulBarrett79** [comment]
We already had a new message for the 0 compounds found but it was only being employed for the "old" search page. Now used for the new one as well.

**Comment by PaulBarrett79** [comment]
Changed message to To add result click the Add Single or Add Multiple links below. This is only shown when one project is selected so links will be present.

Pushed to github

**Comment by PaulBarrett79** [comment]
Available for testing on staging/staging

**Comment by KarenPorter** [comment]
Can't test - structure query times out on /staging so always get 0 results.

**Comment by strets123** [comment]
Yes, staging structure search not available. This is the sole feature to be
tested on demo.

**Comment by KarenPorter** [comment]
Tested on demo and passed
