### ISSUE TITLE
hubtest throws a an error when exporting as excel

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#835]
https://chembiohub.ox.ac.uk/hubtest/api/cbh_compound_batches/?project__project_key__in=christy-example-project&archived=false&format=xlsx&limit=10000

nasty looking error page when exporting from hubtest

**Comment by strets123** [comment]
Now fixed

**Comment by aekhendry** [comment]
Fixed, hubtest chrome
