### ISSUE TITLE
Excel export on hub is exporting strange fields

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#836]
I exported the Demo ChemReg Project and some weird fields came out that are not present in the project.
e.g. : cxcnxzkcjxz	cxcnxzkcjxz__2	cxcnxzkcjxz__3	cxcnxzkcjxz__4	date

**Comment by KarenPorter** [comment]
@strets123 assume this is done?  We have no reproduction steps on this, so my testing is a bit ad hoc.
