### ISSUE TITLE
Can accidentally set table as archived compound view

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#837]
I'm don't think this is intended behaviour. 

Edit handsontable -> sort table by archived compounds (archived compounds are shown) -> click edit and the table reverts to original state, but now only displaying archived compounds.

I believe clicking save should revert the table back to the non-archived compound view

**Comment by aekhendry** [comment]
Edge case bug

**Comment by strets123** [comment]
Hmm, I think something may be going wrong with the new way of archiving stuff via clone.

**Comment by strets123** [comment]
Should be fixed by search page refactor

**Comment by KarenPorter** [comment]
fixed awaiting testing

**Comment by KarenPorter** [comment]
Can no longer view archived entries within standard search, so this is no longer an issue.  Closing - done.
