### ISSUE TITLE
Project types are defined and can be managed separately

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#845]
This is a subtask of #823

This work is to enable project types to be used for holding assay related data - similar to the approach used for saved search functionality - and for parent/child relationships of these projects to be planned and visualised.

**Comment by PaulBarrett79** [comment]
Further breakdown of tasks
- [ ] Use case / user story of project type to hold simple assay data
- [ ] UX of project management for storing assay data
- [ ] wireframes of UX
- [ ] technical analysis of implementation
- [ ] build the functionality

**Comment by KarenPorter** [comment]
No longer relevant - close.
