### ISSUE TITLE
New SSL cert for chembiohub.ox.ac.uk

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#848]
We need to replace our cert with a SHA-256 cert, signed through the official university channels.

**Comment by PaulBarrett79** [comment]
There are a number of options outlined by the JANET service for obtaining SHA-256 certificates for academic domains, outlined here:

https://www.jisc.ac.uk/certificate-service

Since this would technically be for a SGC server, we should discuss with Brian the best way to go about this.

**Comment by KarenPorter** [comment]
email sent to Brian for approval.

**Comment by nroam** [comment]
Please talk to Chris Sluman, who can work with IT Services to renew the cert.

**Comment by KarenPorter** [comment]
@strets123 I think there is progress on this?  Please update issue with latest status.

**Comment by KarenPorter** [comment]
certificate ready - awainting confidence that deployment is robust and next scheduled deployment.

**Comment by KarenPorter** [comment]
can go in next deployment

**Comment by strets123** [comment]
done
