### ISSUE TITLE
ChemiReg: Export of a different registration request

### ISSUE THREAD

**Issue by ddamerell53** [thesgc/chembiohub_helpdesk#850]
When I click the export button before clicking "Save these records", the exported Excel file includes a set of compounds I'd previously registered.  I do have an image but I can't post it to Git Hub

**Comment by ddamerell53** [comment]
OK - worked it out.  Here's how I caused it.

#1 Click "Add multiple compounds"
#2 Select a file and click "Upload"
#2 Save to database
#3 Click "Add more items via file"
#4 Select a file and click "Upload"

Note how the "Export" button has appeared on the preview page.  If you click it you will see the previous set of registered compounds.

**Comment by KarenPorter** [comment]
Refactoring has addressed. Closing.
