### ISSUE TITLE
ChemiReg: Horizontal scrolling causes row height to change

### ISSUE THREAD

**Issue by ddamerell53** [thesgc/chembiohub_helpdesk#851]
When I scroll the compound preview panel (just before clicking "Save these records") the row height changes.  It appears as though the rows are sized to the structure image height but as that vanishes the rows size resets based on the text.  You have to scroll more than to just no longer see the structure image though.  It's quite noticeable on the SGC set-up if you want a demo

**Comment by KarenPorter** [comment]
Can no longer reproduce - assume resolved by refactoring. Closing.
