### ISSUE TITLE
Mapped data fields wrongly associated

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#852]
We have noticed something very strange with our deployment of ChemiReg.  After our code has inserted the compounds into our databases it writes back an updated version of the SDF for ChemiReg to parse.  It appears as though the supplementary fields get associated with the correct compound but that the mapped fields get associated with the wrong compound.  So for us this means fields like “SGCOxfordID” are incorrect but those not mapped like “MatchingSGCGlobalIDs” are correct.  I’ve manually checked the SDF are code writes and all appears OK.

**Comment by PaulBarrett79** [comment]
There is was sort order problem where the project fields were being retrieved in the wrong order. A local change to David's system seems to fix this issue.

This is not reproducible on my local system - exports are in the correct order.

So while David's issue is fixed, I think this may need to be investigated further.

I also fixed a another issue for David's deployment which was an elasticsearch indexing problem.

**Comment by PaulBarrett79** [comment]
I have given David instructions for how to perform the replacement elasticsearch indexing when he has the chance (which does not seem that often at the moment).

**Comment by PaulBarrett79** [comment]
David has reported this issue is now fixed. Moving to Closed.
