### ISSUE TITLE
Saved search is not working correctly

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#853]

**Comment by aekhendry** [comment]
I add a new saved search on hub, featuring two projects. I refresh and reset search page. I use my new saved search. Saved search is now only showing one of the two projects worth of compounds. This remains the case even if I change the project manually, even removing the project for which the data is showing. 

Hub Chrome

**Comment by PaulBarrett79** [comment]
Duplicate of #896 - closing
