### ISSUE TITLE
upload of 8 sided rings can cause entire system crash

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#854]

**Comment by aekhendry** [comment]
I uploaded a file containing an 8 sided ring. This behaviour (previously documented) causes a 502/503 error on clicking save. I keep tyring to put the file in (uploading file and clicking save multiple times etc).  Eventually the system gets stuck, and refreshing the page completely shuts down the server, preventing access for all users. After around 30 seconds, the system appears to reset and it is possible to access the cbh again.

I appreciate this is a very specific use case, but there really should be no bug that results in the lock down of the system for everyone.

**Comment by aekhendry** [comment]
File containing example compounds has been sent to andy and paul, subject: issue 854

**Comment by strets123** [comment]
I have fixed and tested this on bot hubtest and hub

see file uploaded via this URL

https://chembiohub.ox.ac.uk/hub/#/search?projectFrom=hendry&project__project_key__in=hendry&multiple_batch_id=2213

**Comment by aekhendry** [comment]
fixed, hub chrome
