### ISSUE TITLE
If I upload a file with no headers, it just lists them as unnamed. I'm not sure what the appropriate behaviour is here?

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#857]
‘Appropriate message for headers not retrieved’ : If I upload a file with no headers (a blank space where the header should be with data underneath), it lists them in the system as 'unnamed_01'. I'm not sure what the appropriate behaviour is here?

**Comment by KarenPorter** [comment]
I think this behaviour is perfectly valid - the column needs a label  and this is fine. Closing.
