### ISSUE TITLE
Backups can be done to keep an up to date record of each project in SDF and XLSX format each hour

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#86]
This would cover simple integration requirements and also disaster recovery.

**Comment by KarenPorter** [comment]
@strets123 please comment and move to backlog if still appropriate.  Do you have an estimate of effort needed?

**Comment by strets123** [comment]
Yes, there are some types of production incident for which we are not prepared - for example if the server goes down in an unrecoverable way we would lose some data and would not be able to spin up quickly enough

**Comment by strets123** [comment]
Effort required is only 2 hours

**Comment by KarenPorter** [comment]
@strets123 is this implemented?

**Comment by strets123** [comment]
No but we have the code to archive a project

**Comment by KarenPorter** [comment]
done (in a repeatable way by script). Closing.
