### ISSUE TITLE
Improvements to invite external user may be possible - inconsistency in emails copy

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#862]
‘a user can be invited, see the 4 scenarios outlined here: #679’  : This process is a bit messy and I think could be a lot simpler. We just need one copy that invites an external user to a project. It doesn’t matter if it’s a reminder, it is just the same email. They follow the link to the sign up page. If they have already logged in (I.e. their user name already exists) then give them the opportunity to change their password. I think that is good enough. The messages that appear when inviting someone in the popup box can also be simplified correspondingly to – You have invited XXX to this/these project(s).

**Comment by KarenPorter** [comment]
testing this - I get' there was a problem sending your invitation, please contact the ChemBio Hub team' message.  I'm inviting existing users or sending reminders.  SO there is a live bug. @strets123

**Comment by KarenPorter** [comment]
I understand this has been resolved.  @strets123 please provide an update and suggested means/ location for testing and signing off.

**Comment by aekhendry** [comment]
On staging it is not sending an email so i cannot test this

**Comment by strets123** [comment]
This functionality works on Hub. Did you actually want me to change the copy?

**Comment by KarenPorter** [comment]
Adam reports no email delivered in testing

**Comment by strets123** [comment]
But that was testing on staging/staging - hub is working now.

**Comment by aekhendry** [comment]
Hi Andy, I've just tested this again and it is now sending the email. it definitely wasn't before and this was on hub. Is there anyway when inviting external to a project to automatically asign them viewing rights? Currently this is not happening i dont think

**Comment by KarenPorter** [comment]
Fixed in hub. Closing
