### ISSUE TITLE
Password reset email is currently a place holder featuring 'example.com' etc

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#863]
‘password reset – if the password entered by a user is incorrect, the user gets a link to the password reset form, which works’: Currently the email you receive is a place holder, and the link it sends to change your password is not correct. This needs to be updated

**Comment by KarenPorter** [comment]
@strets123 outstanding defect.  URL of linked page is -  https://example.com/hub/api/reset/MTQ0/4br-8685ee34771fab9d6cc3

**Comment by PaulBarrett79** [comment]
This is a configuration issue - should now be fixed.

**Comment by KarenPorter** [comment]
Tested on staging and I didn't get any email notification at all.  Should it be another instance?  Should work on staging in any case.

**Comment by aekhendry** [comment]
This was deployed to hub not staging. Fixed. Chomre Hub
