### ISSUE TITLE
substructure or SMARTS search is not currently highlighted in retrieved images

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#866]
‘substructure or smarts search is highlighted in the images’ This is not working for substructure or SMARTS

**Comment by KarenPorter** [comment]
@aekhendry is this still an issue?  i don't understand the context - you want the scaffold to be shown (as a different colour?) in the image returned from search results?

**Comment by aekhendry** [comment]
No longer relevant. It was to do with the help text giving incorrect information but has been removed due to search page re-factoring.
