### ISSUE TITLE
Draw single compound custom field bug

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#872]
In draw single: if I validate a structure I have drawn - enter new custom field information - click save  custom field information is not saved but structure is. If I enter the Custom field information before validating, works fine.

**Comment by strets123** [comment]
Delayed pending new add compounds interface

**Comment by KarenPorter** [comment]
done - awaiting testing

**Comment by KarenPorter** [comment]
tested and signed off - behaviour has now changed to prevent this
