### ISSUE TITLE
InChI submission needs re-evaluating. I don’t think it’s even working.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#880]
InChI submission needs re-evaluating. I don’t think it’s even working.

**Comment by strets123** [comment]
Now fixed hubtest

**Comment by KarenPorter** [comment]
Hubtest -I tried to export records to excel so i could then load the InChis to test - got the exception:

ImmediateHttpResponse at /hubtest/api/cbh_compound_batches/
No exception message supplied

for both Hendyii and Adam shouldnt have this projects

**Comment by strets123** [comment]
Should now be fixed

**Comment by KarenPorter** [comment]
I put the 5 std inchis from project 'Adam shouldnt have this' back into that project and got all of them not-processable.

**Comment by strets123** [comment]
OK, now fixed the strings were not being stripped of whitespace

**Comment by KarenPorter** [comment]
passed
