### ISSUE TITLE
Excel and SDF export only provides the first 1000 rows.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#882]
Excel and SDF export only provides the first 1000 rows. The button states ‘export ALL’. As such, it really needs to be the whole project.

**Comment by strets123** [comment]
Up to 10000 items per project can now be exported

**Comment by KarenPorter** [comment]
awaiting data volumes to test

**Comment by PaulBarrett79** [comment]
Data volumes - for Andy to estimate

**Comment by strets123** [comment]
This limit has now been bumped up but the Excel and SDF exports are not currently working

**Comment by strets123** [comment]
2 -3 hours left on this to fix SDF export

**Comment by strets123** [comment]
SDF export is now done

**Comment by strets123** [comment]
SDF export now deployed to demo

**Comment by KarenPorter** [comment]
error - 

TypeError at /demo/api/cbh_compound_batches_v2
string indices must be integers
Request Method:	GET
Request URL:	http://staging.chembiohub.ox.ac.uk/demo/api/cbh_compound_batches_v2?pids=3&limit=50&offset=0&encoded_query=W10%3D&format=sdf
Django Version:	1.7.10
Exception Type:	TypeError
Exception Value:	
string indices must be integers
Exception Location:	./cbh_chem_api/new_serializers.py in to_sdf, line 216
Python Executable:	/srv/chembiohub/anaconda2/envs/demo/bin/uwsgi
Python Version:	2.7.10
Python Path:	
['/srv/chembiohub/anaconda2/envs/demo/lib/python2.7/site-packages/django_q',
 './src/django-flowjs/',
 './src/chembl_extras/',
 './src/chembl_core_model/',
 './src/chembl_core_db/',
 './src/chembl_business_model/',
 './src/cbh_core_model/',
 './src/cbh_chembl_id_generator/',
 './src/cbh_chembl_model_extension/',
 '.',
 '',
 '/srv/chembiohub/anaconda2/envs/demo/lib/python27.zip',
 '/srv/chembiohub/anaconda2/envs/demo/lib/python2.7',
 '/srv/chembiohub/anaconda2/envs/demo/lib/python2.7/plat-linux2',
 '/srv/chembiohub/anaconda2/envs/demo/lib/python2.7/lib-tk',
 '/srv/chembiohub/anaconda2/envs/demo/lib/python2.7/lib-old',
 '/srv/chembiohub/anaconda2/envs/demo/lib/python2.7/lib-dynload',
 '/srv/chembiohub/anaconda2/envs/demo/lib/python2.7/site-packages/cairocffi-0.6-py2.7.egg',
 '/srv/chembiohub/anaconda2/envs/demo/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg',
 '/srv/chembiohub/anaconda2/envs/demo/lib/python2.7/site-packages']
Server time:	Mon, 25 Apr 2016 03:35:41 -0500

**Comment by strets123** [comment]
Fix now deployed to /demo

**Comment by KarenPorter** [comment]
passed testing.
