### ISSUE TITLE
In custom field config popup, field names are obstructed over a certain length

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#894]
When editing a project config, I cannot see the full name in a given field text box if the text is too long. This is quite irritating as I need to see this to know which fields I am editing. Also note that the Field type drop down looks messy as it is chopping the words up in awkward places.

**Comment by KarenPorter** [comment]
less editing possible following the refactoring but full name visibility is still an issue.  Could be addressed with a hover over to show field name?  Messy field type issue is fixed.

Ultral low priority though.
