### ISSUE TITLE
Search Page - project field selection from URL not shown

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#895]
If using a saved search, for example, and that search URL contained a custom field lookup, the search is performed correctly but the selection is not shown in the Project Data Values box.

**Comment by PaulBarrett79** [comment]
I have added code to force a redraw after the custom fields have been looked up asynchronously. I tried a number of locations for this and all the logical places got into an infinite looop of triggering redraws.

Added as a timeout function in the controller which runs once.

Search form now shows custom field search selections from URL.

**Comment by PaulBarrett79** [comment]
Pushed to github, awaiting deployment to hubtest

**Comment by PaulBarrett79** [comment]
Deployed to hubtest

**Comment by aekhendry** [comment]
Not sure how to test this, will ask tomorrow

**Comment by aekhendry** [comment]
Fixed, hubtest chrome
