### ISSUE TITLE
projectFrom is no longer used in search page but exists in links to search page

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#896]
projectFrom is no longer used in search page but exists in links to search page. Leads to search results containing projects constraints not defined in the form.

**Comment by strets123** [comment]
This variable is used to navigate back to see the whole project. I guess we could just have a simple Boolean to say this is a preview then you can show the messages based on that and assume 1 project will be selected.

**Comment by PaulBarrett79** [comment]
I've done just that - added a "justAdded" variable in its place, set by examining project__project_key__in. All seems to work correctly when adding compounds and searching.

**Comment by PaulBarrett79** [comment]
Pushed to github

**Comment by PaulBarrett79** [comment]
Deployed to hubtest

**Comment by aekhendry** [comment]
I'm not sure how to test this, will ask tomorrow.

**Comment by aekhendry** [comment]
Fixed, hubtest chrome
