### ISSUE TITLE
Move the upload and validator methods to their own API based on multiplebatch

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#898]

**Comment by strets123** [comment]
Currently the upload functionality is mixed too much with the compound search functionality. Instead we need to separate into different modules. This way the API will document itself as the fields will be validated properly.

**Comment by strets123** [comment]
There is a set of "fields" that are added to the data as it comes back when uploading a file and previewing it - see the   validate_multi_batch function here : https://github.com/thesgc/cbh_chembl_ws_extension/blob/master/cbh_chembl_ws_extension/compounds.py#L541

By making these fiellds class based we can better document the API as each endpoint will declare all of its fields

**Comment by KarenPorter** [comment]
@strets123 assume addressed as part of refactor?

**Comment by KarenPorter** [comment]
to be incorporated into performance effort.
