### ISSUE TITLE
Validate the search GET request properly and reduce amount of business logic

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#899]

**Comment by strets123** [comment]
Currently the parameters used for filtering are not validated correctly and the standard apply_filters workflow is not used for the get_list_elasticsearch function in compounds.py in cbh_chembl_ws_extension

This does have some advantages but would be best to standardise

**Comment by strets123** [comment]
By doing all of the searches we need to do on the custom_fields_list field and using some templating tricks we can have and appropriate object model for a search which will be validated by elasticsearch itself.

For example, to do a nested query we would do...

    {
  "query": {
    "bool": {
      "must": [
       For field in field_queries
        {
          "nested": {
            "path": "custom_fields_list", 
            "query": {
              "bool": {
                "must": [ 
                  { "match": { "custom_fields_list.name": name_of_field }},
		  template_dictionary
                ]
        }}}}
      ]
    }}}

where template_dictionary is a boolean query that does
numeric_range
equals
contains
starts_with
ends_with
date_range
in this list (line separated)

**Comment by KarenPorter** [comment]
technically signed off - search page working proves fix
