### ISSUE TITLE
Make elasticsearch indexing happen in one call

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#902]

**Comment by strets123** [comment]
Current update API needs elasticsearch to be indexed separately, remove this requirement.

**Comment by strets123** [comment]
Also Support adding the first item singly and creating the ES index properly in the process

**Comment by strets123** [comment]
This can be done via the create_response method as was done in AssayReg hence short estimate

**Comment by KarenPorter** [comment]
complete. Closing
