### ISSUE TITLE
Broken date fields for elasticsearch

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#906]
Add one elasticsearch type or index per project to keep mappings from possibility of interferance

A production incident was caused by issues with the data type mapping in elasticsearch.

This problem can be fixed by moving to and explicit set of type mappings, we have nearly done this but just need to fix the way sort works and disable the indexing of the  customFields field entirely.

The reason that we cannot index the customFields field like this is that if a particular named field changes its data type between projects then elasticsearch will throw an error.

The list-like project_data_fields field gives us the ability to index the different fields like this:

    [{"name": "ny field name", "stringvalue" : "", "numvalue": 22, "datevalue": "value if date"}]

This will then be sorted by a script as discussed in #741

**Comment by strets123** [comment]
This will require code changes in the create_temporary_index function of elasticsearch_client.py in the cbh_chembl_ws_extension module. The customFields and uncuratedFields fields will be added to the ignore pattern.

The indexing code will also be changed to include datevalue, stringvalue and numvalue

**Comment by strets123** [comment]
Now fixed by using explicit string mapping for the relevant date field

**Comment by KarenPorter** [comment]
Bug found using added before value:
total recs 695.  Search for added after 17/2/16 - 251 recs returned.  clear added after field then search for added before 17/2/16 - 694 recs returned.

I don't think it's directly related to the code fix above - but manifest when testing it.

**Comment by strets123** [comment]
I cannot reproduce this issue.

**Comment by KarenPorter** [comment]
resolved - prob reindexing fixed it
