### ISSUE TITLE
UTF8 issue with file upload

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#908]

**Comment by strets123** [comment]
30% of the test SDFs provided by Adam did not upload properly, need to fix this and then continue the testing of file uploads

**Comment by strets123** [comment]
There is a unix utility to clean and convert these badly encoded files so we can do this for all SDFs following upload.

**Comment by strets123** [comment]
fixed by assuming the input data is utf8 and ignoring any none utf8 characters

**Comment by aekhendry** [comment]
Fixed, hub test chrome
