### ISSUE TITLE
Multiple batch upload id should be labelled with a timestamp instead of the id value on the search form

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#912]
Multiple batch upload id should be labelled with a timestamp instead of the id value on the search form.Searching by upload batch could be really useful if it was more user friendly - people won't remember the ID for a file they uploaded but they will remember when they uploaded it (roughly)

**Comment by strets123** [comment]
I am not so sure of this. Christy seemed to perfectly well understand that there was a sequential ID for the upload.

If searching for a date you have the date search. ID is more precise, this is an informatics system 

See the Zen of python

In the face of ambiguity resist the temptation to guess

**Comment by PaulBarrett79** [comment]
She probably did understand the principle but the practicality of searching on an ID that you might never have even noted is, I think, different.

I'm thinking more of the search page for the average scientist.

Even if there was some sort of subsetting of the dropdown that would be better. 
One week ago:
1
2
3
Two weeks ago:
4
5
6

Something like that.

**Comment by KarenPorter** [comment]
this is a low priority given no use feedback . closing for now
