### ISSUE TITLE
indexing of all items within elasticsearch in some way

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#916]

**Comment by strets123** [comment]
Indexing of embedded objects in elasticsearch should now work more or less properly as I have stopped the json field contents being indexed raw and removed the dynamic mapping

**Comment by strets123** [comment]
The global columns configuration helps to index the fields more carefully

**Comment by strets123** [comment]
This should now work for file uploads in the new indexer but it is not possible to test as the updates and add singles do not yet work in search v2

**Comment by KarenPorter** [comment]
add single works so this can now be tested - via all adding interfaces

**Comment by KarenPorter** [comment]
Is it a valid test to search for values associated with recently added / updated records and have them found?

**Comment by strets123** [comment]
Yes, this is now working but I think the original task may have referred to hierarchical data structure

**Comment by KarenPorter** [comment]
Recently added and changed data fields are found as part of search.  Passed testing
