### ISSUE TITLE
better project dashboard - showing all collections etc

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#922]

**Comment by KarenPorter** [comment]
deployed to /demo

all UX on project list page to be reviewed

**Comment by KarenPorter** [comment]
info messages both out of date:
filter project list - results do not narrow by project type
a list of all the projects you have access to - this is fairly explicit and the current info mentions assay type - it's too long and tautological.  Maybe: "If you believe you should have access to projects not shown or the functions available for each are not what you expect, contact your administrator"?

**Comment by KarenPorter** [comment]
Project list heading is clickable - i assume it takes the user to the page and location where they are currently.  Ideally would be non-clickable.

**Comment by PaulBarrett79** [comment]
Small fix ~ 1 hour

**Comment by PaulBarrett79** [comment]
Messages corrected and Project List header is no longer clickable.

Pushed to github

**Comment by PaulBarrett79** [comment]
Available for testing on staging/staging

**Comment by KarenPorter** [comment]
Info message for filter project list says the results are based on project name.  When I search on the word 'special', expecting to see just the 'special name test' project, I get some filtering happening - but I can't figure out on what basis.  Similarly i filter on _ (underscore) and it does some filtering but not what I expect based on the info message.

I'd remove the first sentence in the project list info box- the meaning is repeated in the second sentence.

**Comment by PaulBarrett79** [comment]
Modified the project filter to specify explicitly that it should just filter on name. This should produce more consistent behaviour.

Altered message to specify that the filter applies to any part of the title, not just the start, to try and avoid any confusion.

Pushed to github.

**Comment by PaulBarrett79** [comment]
available to test on staging/staging

**Comment by KarenPorter** [comment]
passed
