### ISSUE TITLE
saved search saves a snapshot and parameters to redo search later

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#923]

**Comment by PaulBarrett79** [comment]
So far added:
method to fetch a set of capped URL parameters. This is done by retrieving the last (most recent) item and capping the ID search at this value, and appending to the current search filter
code within search controller's save search mechanism to generate a new url with this capped parameter
changed the saved search list temp[late to include a link to this capped url.

Because the APIs are currently all broken on the build, I cannot verify that this works yet...

**Comment by PaulBarrett79** [comment]
I've pushed progress so far to github

**Comment by KarenPorter** [comment]
Deployed to /demo for testing

**Comment by KarenPorter** [comment]
Not working on /demo

**Comment by PaulBarrett79** [comment]
This works for me on demo - please retest

**Comment by KarenPorter** [comment]
Doesn't work when you have an empty search - no error message.

**Comment by PaulBarrett79** [comment]
User can now save an empty (no parameter) search as a saved search.

Pushed to github

**Comment by PaulBarrett79** [comment]
Available for testing on staging/staging

**Comment by KarenPorter** [comment]
Can't test on /staging - search results are timing out.

**Comment by strets123** [comment]
Now working on demo, including structure search

**Comment by KarenPorter** [comment]
From earlier last week.  I created 2 new saved searches but they didn't show up in My Saved Searches.  They're there now - so was this something to do with indexing?

**Comment by PaulBarrett79** [comment]
Yes. Saved searches are a batch so are affected by indexing. Indexing now works so they will show up.

**Comment by KarenPorter** [comment]
My saved searches modal window doesn't close when I view original results (although results are retrieved and populated behind the modal window.

**Comment by strets123** [comment]
Also, due to the way chemical searches work, I can only retrieve a chemical search when I am logged in in the same session as I was when the search was done

**Comment by KarenPorter** [comment]
Saved a search again and I still can't see it in saved search list.  I've logged out and back in again - still doesn't show up.  How long should I expect it to be before it shows up?  Needs to be fast.

**Comment by PaulBarrett79** [comment]
added ng-click=cancel() to all of the search links in the modal

Saved searches show up instantly  on my development machine - performance related on testing server?

**Comment by KarenPorter** [comment]
still not visible, so not a performance thing idt

**Comment by PaulBarrett79** [comment]
This would appear to be an indexing problem on the demo server instance. I cannot now replicate the behaviour of newly created saved searches not showing up on my local machine.

I fixed an edge case issue with these - if a search had no results, no filters but was restricted by a project, the capped search could not be generated because there are no results (reliant on results[0]) so was stopping the saving process - now fixed.

**Comment by strets123** [comment]
Yes,  there was previously an indexing issue for these. Now should be fixed.

**Comment by KarenPorter** [comment]
tested and can no longer replicate the issue.  Passed

**Comment by PaulBarrett79** [comment]
"Also, due to the way chemical searches work, I can only retrieve a chemical search when I am logged in in the same session as I was when the search was done"

This is a pretty big issue considering that most users with chemical projects will want to use this functionality to keep sketched searches.

Parameter needs to be added to chemical searches so that when they are run again (not using the capped search) the structural query from before is referenced.

**Comment by PaulBarrett79** [comment]
Fresh usage  of a saved chemical search now implemented.

**Comment by PaulBarrett79** [comment]
Now deployed to testing on demo

**Comment by KarenPorter** [comment]
yebut I can't test substructure search on demo @strets123

**Comment by aekhendry** [comment]
Also i found a bug on demo. 

Searched Hendry 10 project by 'ww' text search. Two compounds returned. Saved search. Reset page and clicked on new saved search link. Three compounds returned, two as expected and one from another project. I believe it returned due to the 'ww' in the third compounds inchi key.

**Comment by KarenPorter** [comment]
further to Adam's new bug:  the 3 results returned are only returned the first time you run it (either original results or use the search again.  The second time - only 2 records are returned)

**Comment by strets123** [comment]
see issue #1019

**Comment by KarenPorter** [comment]
KarenPorter commented 2 days ago collaborator
yebut I can't test substructure search on demo @strets123  

I can test substructure search in Staging, but can't save and retrieve searches.
I can save and retrieve searches in Demo, but can't run substructure searches.

Need an environment where i can comprehensively test this.
