### ISSUE TITLE
Project objects or compounds have URI + tidy up resource URI structure

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#924]

**Comment by strets123** [comment]
I have completely overhauled the way that the compound search URIs work

**Comment by KarenPorter** [comment]
how do I test this?

**Comment by KarenPorter** [comment]
demonstated by saved search - saving URIs

**Comment by KarenPorter** [comment]
I can't test saved search - any i save are not retrieved.

**Comment by PaulBarrett79** [comment]
Dependent on #923 for testing

**Comment by PaulBarrett79** [comment]
#923 is up for retesting so this may now be testable

**Comment by KarenPorter** [comment]
scenario:

I created 2 searches  -in demo as user demo, called 25g and twenty five grams, neither were available in the list of saved searches, although they did appear later (> 1 day later).

I created a search - in demo as user demo, called Hendry .....  it is not available in the list of saved searches .

I created a search - in demo as user demo, called Hendry and Anna with sort.  It includes  sort direction selected (asc) - it is immediately available in list of saved searches.

**Comment by strets123** [comment]
I believe that this was tested during redeployments of the system which is why the saving of searches was not working. However, we should probably handle the success and failure better.

**Comment by strets123** [comment]
Paul adding an alert / error handling

**Comment by KarenPorter** [comment]
accepted remaining issue as backlog item and passed remainder
