### ISSUE TITLE
Tagging function in custom fields is case sensitive, I'm not sure this is necess

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#93]
Tagging function in custom fields is case sensitive, I'm not sure this is necessary especially if this inhibits cross linking when searching for a particular tag. For example when tagging, the word "Cold" and "cold" can both be entered under the same field heading.

date recorded in spreadsheet: 13/04/2015 16:05:28

**Comment by strets123** [comment]
Would we be happy for all data to be lower cased?

**Comment by KarenPorter** [comment]
When saved?  Or making case-agnostic searching?  If the former, I'd say no - there are abbreviations that all users would expect to see in capitals for instance that would look weird if rendered in lower case - but they should be retrieved.  So I'd say - save both Cold and cold (as shown), and retrieve both when user searches for 'cold' that would be the Google way.

**Comment by aekhendry** [comment]
Agree with Karen here

**Comment by aekhendry** [comment]
Tested, seems to be working. Tag new chrome. This will need improving the the future however as I'm concerned about the prospect of it not picking everything up in a search. Could you indicate what kind of searches it might fall down on Andy?

**Comment by strets123** [comment]
if searching for PhD you would have to use the correct case

**Comment by aekhendry** [comment]
Thanks, moving across
