### ISSUE TITLE
File attachments for single record in ChemiReg

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#930]
Refactor file upload model to include a project id somewhere - perhaps in the identifier

This will give a way of creating a URL which uses the project id to retrieve an attachment and is therefore secure.

ID can also include timestamp

How many file upload "sections" will be allowed?

**Comment by strets123** [comment]
Needs to cover at least... txt, ttf, .dat, .csv, .zip. pdf etc.

**Comment by PaulBarrett79** [comment]
- [ ] migrate flowjs into cbh_core_api and cbh_core_model
- [ ] allow projectid to be passed as part of file upload
- [ ] assign projectID into the unique identifier of file
- [ ] allow projectID to be retrieved for checking as part of file download process

**Comment by PaulBarrett79** [comment]
API changes have broken this functionality - needed to adjust the model used

**Comment by KarenPorter** [comment]
awainting testing

**Comment by KarenPorter** [comment]
What can I test in this?  Checking of mandatory fields not implemented, so what can i sign off?

**Comment by PaulBarrett79** [comment]
This ticket is for adding an Attachment to an individual record in the system. (via a file upload field.

To test:
Search for items which are known to have a file upload field configured (for example Hendry test 10)
Pick a record and open the detail popup (click the structure image)
Enter edit mode
Click the + icon on the file upload field
Choose a file
File will be shown. If it is an image-  thumbnail shown. If it is a document - placeholder thumbnail shown.
Click "update and close".
Table should now indicate files uploaded to that field.
Re-open modal window - thumbnail(s) displayed in file field.

To test removal:
Enter edit mode
Click x ixon top right of the thumbnail
Click "update and close"
Thumbnail removed

Available on /demo

**Comment by PaulBarrett79** [comment]
I am altering the title of this ticket becuase there is now confusion between file attachments and multiple record upload.

**Comment by KarenPorter** [comment]
tested - passed
