### ISSUE TITLE
A-Z sorts not working correctly in table

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#932]
They reorganise the data but not in anyway that makes sense.

**Comment by strets123** [comment]
Now fixed by using zero padding

**Comment by KarenPorter** [comment]
pretty much there, but:

in project yolo, field yolo - all records initially contained value of 2010.  I updated 2 at random to fred and george and they stayed at the bottom of the sorted list, whether the field was sorted asc or desc.  I then updated 3 more (to 2009, 2011, 2014) - and now all records behave as they should when sorted - ie desc order is 'george, fred, 2014, 2011 .......

**Comment by strets123** [comment]
I propose that we close this as neither of us can reproduce.
