### ISSUE TITLE
Ability to search for names when assigning permissions on the front end not working

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#933]
You type in a name and nothing happens, you have to search for the name from the list manually. 

Also, the list should be in alphabetical order

**Comment by strets123** [comment]
You can now search for either the name or the user name (for users without first and last names) - you will need to create a user with first and last names to confirm this)

**Comment by KarenPorter** [comment]
no change in behaviour to previously.  What is supposed to be different?

**Comment by strets123** [comment]
Now working, you can now search for a person's name or username and they are in alphabetical order

**Comment by KarenPorter** [comment]
works in Firefox but not Chrome - is there anything that can be done to address this?

**Comment by strets123** [comment]
I have bumped the caching of this file by renaming it. Please test again.

**Comment by KarenPorter** [comment]
passed.  What is the rationale behind some of the names being not selectable for some roles (I'm sure it is by design but I can't figure out what it's doing)

**Comment by strets123** [comment]
It is just that if you are already an owner then you are by definition an editor so I thought it was less confusing to stop people selecting themselves

**Comment by KarenPorter** [comment]
I can't pick edward either though @strets123

**Comment by strets123** [comment]
Yes, you cannot add edward as an owner because he does not have the add_projects permission or is not an administrator. All members on webauth have the add_project permission

**Comment by KarenPorter** [comment]
passed
