### ISSUE TITLE
Increment field required

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#934]
I have been asked for a field type in which a new entry is automatically given an incrementing number. 

for example, I add two new items and their respective fields display 1 and 2. subsquent entries will show 3, 4 ,5 etc. It must also be possible to set the start number, as often these system are already in place in the lab and they want to continue

**Comment by KarenPorter** [comment]
@strets123 @aekhendry please liaise and determine what, if anything, needs to be captured for any outstanding increment field requirement.

**Comment by aekhendry** [comment]
I'll come back to this following my meeting with Hide today

**Comment by aekhendry** [comment]
I'm marking as done, Hide is using it with no problems
