### ISSUE TITLE
Regex search required for text based searching in ChemiReg search

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#935]
As we do not want the search for matches in the middle of words, we should use the whitespace analyzer and search for a phrase prefix. On reflextion, regexp querying is not reccomended as it is slow and there are a lot of characters which need to be escaped.

**Comment by strets123** [comment]
The logic now works for phrases and is case independent but captures ALL characters to you can do things like chemical names with square brackets etc.

**Comment by KarenPorter** [comment]
text search failing to update between searches in hubtest:
search for 'asda' returns 8 values (correct), search for xxxx returns 695 (all - inclorrect), search foe awd returns 0 (should be 2)

**Comment by strets123** [comment]
Fixed, this was due to HTML tags in the field data Adam had added

**Comment by KarenPorter** [comment]
fixed
