### ISSUE TITLE
export was not respecting archived compounds

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#940]
Previous behaviour was that when exporting data the archived compounds came out too.

Now fixed, should also cover custom field searches too.

**Comment by KarenPorter** [comment]
I'm getting the archived compounds along with the others (Adam shouldnt have this project)

**Comment by strets123** [comment]
Please test again now that the caching issue is fixed

**Comment by KarenPorter** [comment]
passed

**Comment by strets123** [comment]
closed as fixed
