### ISSUE TITLE
Caching of templates on the front end causing "old" versions to remain active on chrome under windows

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#941]
If the user never reboots their PC and just puts it on standby, under certain conditions the chrome process is never rebooted. Therefore caching via javascript under the angular framework takes effect meaning that some templates are held in memory as javascript objects even if the server side version has been changed.

In order to get around this issue I have added templatecaching as part of the front end build workflow.

Fixed hubtest chrome

**Comment by KarenPorter** [comment]
how can I test this?  Older addcompounds page was shown when i navigated to it on hubtest - then updated when i refreshed.  Is this the expected new behaviour (ie still having to refresh to update the page)? @strets123

**Comment by strets123** [comment]
OK, I have now added a further step to the deployment workflow which logs all users out. Thus a reload of the page is enforced. You will have been logged out of hubtest.

**Comment by KarenPorter** [comment]
Still - how do I test this? is it possible to simulate what we're trying to test -ie:

current - 
user on Chrome navigates to page - views existing format.
user on Firefox navigates to page - views existing format.
developer deploys new page as previously
user on Chrome navigates to page - views existing format
user on Firefox navigates to page - views revised format.

new functionality -
user on Chrome navigates to page - views existing format.
user on Firefox navigates to page - views existing format.
developer deploys new page with updated workflow
user on Chrome navigates to page - views revised format
user on Firefox navigates to page - views revised format.

**Comment by KarenPorter** [comment]
explained sufficiently - passed.
