### ISSUE TITLE
Hands on table breaks when screen resolution changes

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#946]
If i have the window at half the screen size and scroll across a table, the fields headings detach from the data. This causes the data to be out of order with the field headings. Making full screen fixes the problem. This is much like what used to happen in the system.

**Comment by strets123** [comment]
Need to re test with the new hands on table interface

**Comment by aekhendry** [comment]
Seem to be fixed. hub test chrome
