### ISSUE TITLE
caching and editing of global column configuration

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#947]

**Comment by strets123** [comment]
As part of the refactoring of the search interface and improving the app performance, a bottleneck was identified in the columns configuration.

**Comment by strets123** [comment]
The current columns configuration is project by project but actually what is needed is:

1) a whole app columns configuration which is simpler than the current one and just used for the table view but which included sorting and filtering
2) a columns configuration for when working on the add compounds page
3) the current columns config on a single-project basis for when working on editing a compound

**Comment by strets123** [comment]
In order to provide this flexibility, a new resource was added for 1)

**Comment by strets123** [comment]
- [ ] create column config service
- [ ] combine with skinningconfig
- [ ] integrate with handsontable js
- [ ] add a generic summary renderer
- [ ] add  the form for search in the directive
- [ ] make the url work
- [ ] make sure logic is correct for hiding and reselecting a filter wherever on the interface this is done (should be same object with a dotted path so this should work nicely)
- [ ] integrate the back end for search
- [ ] integrate the indexing on save of a compound batch


-

**Comment by strets123** [comment]
I have written up more about this decision here

https://github.com/thesgc/chembiohub_helpdesk/wiki/Schemata-in-ChemiReg

**Comment by KarenPorter** [comment]
Done.
