### ISSUE TITLE
Structural images in single molecule view are not making best use of available space

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#949]
Sstructural images need to fit the size of the window, in some cases they are comically small e.g. UOXKS11BRP

**Comment by strets123** [comment]
I have managed to fix the big images. There were some parameters which needed changing

**Comment by aekhendry** [comment]
Is this on hubtest only im assuming? I'm still finding the smaller molecule on hubtest are not taking up a great deal of the available space (although they are a bit bigger)

**Comment by strets123** [comment]
Now testable - structure image fixed

**Comment by KarenPorter** [comment]
1.  I have no means that I can see of filtering by compounds which have a structure (or don't have a structure).

Viewing Hendry Compound entries, the top 6 entries have structure, when I launch each one in modal, there is a structure (and project data fields) for items 1, 4 and 5, no data shows for the other 3.  whether this is related to the image fix or a separate defect, I can't say.

**Comment by strets123** [comment]
This issue was caused by a string field having been at some point changed to be a decimal field.

We will need to do more testing to do with data types and validation and stop the ability  to change the type of fields.

**Comment by strets123** [comment]
1) Issue can be raised as a backlog item but is not related to this.

**Comment by PaulBarrett79** [comment]
Available for testing on hubtest

**Comment by aekhendry** [comment]
Marking as fixed

**Comment by aekhendry** [comment]
demo, chrome
