### ISSUE TITLE
Restricted fields

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#953]
Work needs to be done to make the v2 API work correctly with all of the following features of the system. Progress through the checklist is expected to be pretty much linear over time.

I will un-strikethrough the tasks as they get deployed so they can be tested.

I will also need to work on the projects/fields sidebar in order to make it possible to hide the fields that do not have data in them.

###Compound Search 

- [ ]  List display for chemreg shows 4 columns for project , user, structure uox etc and then shows project data fields and then date, batch and upload
- [x] User can search by keyword
- [x]  User can search by anything else in the search form
- [ ]  Added by datesearch  is and inclusive data
- [ ] Can view  data that the user has access to
- [x] Can filter the project
- [x] Can hide fields
- [x] Can sort fields
- [x] Can open the field options via a menu button on the left
- [x] Can reset all parameters with the Reset Search Page button
- [ ]  Links can be rendered appropriately if labelled as a link field

- [x] Page responds appropriately to resizing
- [ ] ~~There is no way to "break" the page by resizing constantly~~
- [x]  Page, all search terms, archive mode, list or gallery choice, items per page are all retained when the page is reloaded by pressing ctrl f5
- [ ]  Add multiple compound link from project page if >1 project selected should be disabled
- [x]  Add multiple if single inventory project selected should lead to add compounds page (adding compounds not yet working)
- [x]  Add single if single invetory project selected should happen inline
- [x]  Add single should lead to the add single compound page if single compound project selected
- [ ]  ~~edit mode edit a single field by click - not yet~~
- [x] Project owner can archive/restore items via the project list page link in the admin section
- [ ]  can fill down on archive/restore
- [x]  can fill  down with other fields when in edit mode
- [x]  after fill down a message appears and it is possible to undo the changes just made on both the standard page and the archive/restore pages
- [x]  Custom fields in the handsontable consist of a unique list of the fields in the projects which have at that time been selected
- [x]  User can pick from a list to search and can filter the pick from list including for values with semicolons and other special characters

- [ ]  ~~substructure or smarts search is highlighted in the images~~
- [x]  User can page through the results. If they then perform another action which changes the view then they get taken back to page 1. Likewise if they add an item

- [x]  Export gives the same number of results as the number in the data preview
- [ ]  ~~values from restricted fields should not be shown in the search dropdown~~
- [ ] ~~Restricted fields are not shown to viewers of a project~~

###Draw a compound
- [ ]  Draw compound allows the user to draw and then validate a compound. If validation successful then a save button is available
- [x]  Draw compound allows the user to draw and then validate a compound. If validation unsuccessful then relevant message is shown
- [x]  Draw compound allows the user save a compound and a relevant message is shown
- [ ]  ~~Custom fields can be added to the compound and are validated~~

###Add single inventory item feature 
- [ ]  Custom fields should be validated and required fields respected
- [ ]  ~~Should be possible to add uncurated fields~~

- [ ]  Existing values from that project are shown to the user as they add to an existing dropdown field
- [x]  Uncurated fields can be added individually but currently only on the pre validate stage

###Addcompounds 
- [ ]  Add compounds info box
- [ ]  Uploaded records info box
- [ ]  With structures info box
- [ ]  Without structures info box
- [ ]  Overlaps info box
- [ ]  What do the statuses mean?
- [x]  Appropriate message for unprocessable file
- [ ]  ~~Approriate message if saving the compounds fails~~
- [ ]  Messages against individual compounds when uploaded correspond to appropriate error type
- [x]  Ability to sort the preview of compounds
- [ ]  Ability to remove those sorts
- [ ]  Ability to filter the preview of compounds by the different statuses
- [ ]  Ability to remove those filters
- [x]  Ability to map a column to something in the custom fields
- [x]  Disabled mapping of a column if it doesn't fit in that datatype and message
- [ ]  ~~Ignoring data works by changing the dropdown. Message where saving the data changes to reflect this~~
- [ ]  ~~Ignored items are not saved~~
- [ ]  ~~Errors ignore by default but can be saved as new items if from xlsx~~
- [ ]  ~~Errors ignore by default but can be saved as new items if from sdf~~
- [ ]  ~~Errors ignore by default but CANNOT be saved as new items if from sdf~~
- [x]  Specific and different handling of SMILES mapping, not available if the file is an SDF
- [x]  Ability to do any of the above sorts and filters and then reload the page and get the same thing
- [ ]  ~~Custom fields are validated and required fields are respected in this process~~

##Compound saved confirmation
- [ ]  Compound preview after adding an upload
- [ ]  Friendly title to the page + filter indicates success
- [ ]  Inuitive to remove the filter if you wish and the title goes back to search

**Comment by KarenPorter** [comment]
minor comments:
hidden/shown icons are quiet similar, could be made more distinct with use of colour (red=hidden?)
Project drop down - style not applied to select all/ deselect all text
Sort buttons - if use no sort / asc /desc they'd fit on one line and be similar overall length as hide/show below
no export search results button (prob in todo list but I can't see it)

**Comment by KarenPorter** [comment]
on staging - this saved search should also return 2 records from the xx inventory project (ie total of 4 records)  ONly returns 2 records with blank project name.

http://staging.chembiohub.ox.ac.uk/staging/#/searchv2?limit=100&offset=0&encoded_query=%5B%7B%22query_type%22:%22greater_than%22,%22greater_than%22:%227%22,%22field_path%22:%22multiple_batch_id%22%7D%5D&encoded_sorts=%5B%7B%22field_path%22:%22id%22,%22sort_direction%22:%22asc%22%7D%5D&encoded_hides=%5B%22custom_fields.Alias%22%5D

**Comment by strets123** [comment]
All comments have been addressed and fixed

**Comment by KarenPorter** [comment]
###Add single inventory item feature 

 Custom fields should be validated and required fields respected
   Made Year ordered required in Barret project on demo but no error message when i leave it blank and te new record writes.
 
 Draw compound allows the user to draw and then validate a compound. If validation successful then a save button is available
Passed - my comment though, when validated and save button appears, the Validate button could be disabled or removed(to reappear / enable when structure changes)

 Draw compound allows the user to draw and then validate a compound. If validation unsuccessful then relevant message is shown
 Passed
 Draw compound allows the user save a compound and a relevant message is shown
  Passed

**Comment by KarenPorter** [comment]
##Compound saved confirmation 

 (is this when adding multiple from the search results page?)

 Compound preview after adding an upload
 assuming the answer to the above is yes - passed
 Friendly title to the page + filter indicates success
  not sure what is meant by filter indicates success
 Inuitive to remove the filter if you wish and the title goes back to search
 non-intuitive - i think I'm in the
 wrong area of the app?

**Comment by KarenPorter** [comment]
Upload file message -  94 new batcheswill be saved to the database and6 new batcheswill be ignored.
 - message needs tidying - add a gap in batcheswill (x2) and after and

**Comment by KarenPorter** [comment]
###Compound Search 

 List display for chemreg shows 4 columns for project , user, structure uox etc and then shows project data fields and then date, batch and upload
I think I understand what is implied here - ensure date, batch and upload id columns are at the end, ensure project data fields are in the middle and start with agreed generic columns.  These are structure, ID and project (not user as listed).  The column order is correct, therefore passed.

 Added by datesearch is and inclusive data
    not sure what is meant by this?
search on date field - it isn't defined as a date field (I don't think), dates are not pickable as dates (from calendar picker as might be usual)

 Can view data that the user has access to
  I can't test - can't add new users to make viewers so I can see what ddata restrictions they have.

 Links can be rendered appropriately if labelled as a link field
  I've defined a link field and it doesn't seem to mandate a link format.  Also, when it is a valid link, it isn't clickable

Add multiple compound link from project page if >1 project selected should be disabled
I don't know how to select more than 1 project on the project page.  As soon as i click one project i go to the addcompounds page.  From te Search page, if I have >1 project, the add multiple button is greyed out, as expected.

can fill down on archive/restore
  - I can't edit, not sure what is meant by this

**Comment by KarenPorter** [comment]
###Addcompounds
Appropriate message for headers not retrieved
  not sure how to replicate

 Ability to filter the preview of compounds by the different statuses
 Ability to remove those filters
   What is meant by status?  There isn't a status column.   I can sort, but not filter on action

 Ignoring data works by changing the dropdown. Message where saving the data changes to reflect this
  don't know what this means


Ignored items are not saved
  I checked a record to ignore and it was written (without a CBH_ID though)

**Comment by KarenPorter** [comment]
Add single compound:

I defined a set of values for a field (Supplier in Hendry Compounds project).  In add single, I get a bunch of values shown in the drop down for this field, including those I've defined but a whole bunch of others too.

the message "If you make any changes to these fields after clicking Validate, you will have to click Validate again for these changes to be submitted." is untrue, all custom fields saved whether added before or after validation.

Chemical search

The Apply and Close button remains greyed out - how do I actually run a structure search?

ChemDoodle erase behaving erratically.  wont let me remove the last additional carbon attached to a benzene ring.  I can demo.

ChemDoodle really not stable - I'm on Chrome and I haven't had this experience previously.  I'm clicking a doodle button and it is highlighting, but is still applying the previous button action type.






Archived items - 

restore/view archived items where there are zero items, the message says "0 results    -    No Compounds Found. To add compounds use the link above." - there is no link above and in any case this message doesn't apply here.

**Comment by strets123** [comment]
All points from the previous comment have now been fixed I believe
1) Expected behaviour
2) Message removed
3) Bug fixed
4 and 5, not reproduced as yet

**Comment by strets123** [comment]
Data volumne - 10 hrs
restricted fields - 4 hrs

**Comment by strets123** [comment]
Restricted fields remains to be fixed - 2 hours left

**Comment by strets123** [comment]
OK, heere are the test scenarios

Feature: Restricted Fields

        Scenario: Data removed from output when field restricted
            Given superuser
            And testuser
            And I create a project as before
            And I add a restricted field
            And some compounds exist in the project with this restricted field
            When I give testuser read permissions on the project
            Then the output data from search does not contain the restricted field


        Scenario: Two projects with same field one of them restricted to the testuser
            Given 2 projects exist 
            And 1 has a restricted field 
            And the other has an unrestricted field of the same type
            And there are compounds in both projects with values in that field
            When I give a user viewer permissions to both
            Users can see all data from both
            And if they search against the part restricted field
            Then they only see the project with the unrestricteed field



        Scenario: Two projects with same field one of them restricted to the testuser
            Given 2 projects exist 
            And 1 has a restricted field 
            And the other has an unrestricted field of the same type
            And there are compounds in both projects with values in that field
            When I give a user viewer permissions to both
            Users can see all data from both
            And if they look at the pick from list from the part restricted field
            Then they only see the pick from list values from the project with the unrestricteed field

**Comment by strets123** [comment]
Now implemented as described above

**Comment by KarenPorter** [comment]
scenario one failed - restricted field is available in the Excel export so not secure.

**Comment by KarenPorter** [comment]
scenario 2.  I added user karen to 2 projects as viewer - hendry test 9 and hendry test 10.  both share a field 'awd' although it is restricted in 9 but not in 10.  All results are as expected, except separate issue;

searching on field 'awd for not-blank - i get no results, when i should get 2 records (relating to project 10 records).  If I search for specific value in the field, I get the 2 records shown.

**Comment by KarenPorter** [comment]
scenario 3 - passed

**Comment by strets123** [comment]
Excel export fail + not blank filter

**Comment by strets123** [comment]
Fix to this is now deployed on to staging

**Comment by KarenPorter** [comment]
Scenario 1 passed

**Comment by KarenPorter** [comment]
Scenario 2 peripheral issue passed
