### ISSUE TITLE
Single molecule modal needs an associated URL or angular route

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#955]
Single molecule/record modals currently do not have an associated route or URL, they are ophan processes. They also break the back button - expected behaviour should be that Back closes the modal and reverts to the search page (as is the behaviour on waffle for example)

This also provides users with a URL to link to a specific compound/inventory record.

Navigating directly to a single record modal should use the unfiltered search page as "backdrop", again the same as Waffle.

As part of this process, we will be fixing the broken link in the search results table to the modal.

**Comment by PaulBarrett79** [comment]
Added a modalStateProvider and connfigured a modal state to be invoked by URL instead of opening a modal within the search controller.

Closing the modal returns to the base search state without losing search parameters.

Edit mode within the modal is still handled in the same way.

We can now repeat this process for other modals should we wish.

**Comment by PaulBarrett79** [comment]
This has now been completed.

Go to search page
Click the detail link on a table record
Modal will open and URL will have the ID in the URL
Pressing back in the browser will close the modal and redisplay the search page

Pushed to github, deployed to staging

**Comment by KarenPorter** [comment]
passed testing
