### ISSUE TITLE
Svgify function breaks on use of the search bar

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#956]
The function to colour in the SVGs on the project list page breaks if the user uses the search bar to search for a project - needs to be a directive.

**Comment by PaulBarrett79** [comment]
Just needed to add a watch on the generated scope variable which the search bar uses to narrow down the list. There may be a more performant way but this seems ok for now.

Pushed to github

**Comment by PaulBarrett79** [comment]
I have moved the svgify function into the projectlist directive itself as it was intermittently not called (semi-reproducible). Pushed to github.

**Comment by strets123** [comment]
completed - test by searching on project page and by going backwards and forwards to project page

**Comment by KarenPorter** [comment]
What would the previous behaviour have been specifically?  (The one I'm now trying to not see).

**Comment by strets123** [comment]
The icons on the project list page were turning black on use of the project search bar or if there had been an error elsewhere in the app and you returned to the project page

**Comment by PaulBarrett79** [comment]
Available for test/verification on hubtest

**Comment by aekhendry** [comment]
I can't replicate described behaviour, marking as fixed
