### ISSUE TITLE
additional specialist group required - Andy

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#957]
To make a the chemistry dept joint inventory work, we need a group simialr to member, In which all chemistry email addresses are automatically added to it. Particiapting projects are then added to that group, Granting viewing permissions to all members. This needs to be done as soon as we have finished refactoring the ELN (as discussed with Karen)

**Comment by KarenPorter** [comment]
@strets123 @aekhendry discussion needed

**Comment by aekhendry** [comment]
I don't think this relevant any more. We are consolidating the users we have rather then pushing ahead with this.
