### ISSUE TITLE
Cleanup of data processing APIs

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#958]

**Comment by strets123** [comment]
Following further assessment of the data processing APIs, there was no real alternative but to restructure the way the calls themselves in order to allow the data to be processed in parallel.

The functionality will be delivered in this order

1) End to end workflow of the upload inventory items
2) Process SMILES list
3) SDF processing
4) Logical hooks to add in scarab functionality

In order to do task 1) then there are 5 separate API calls

1) Upload data and split into segments
2) Present those segment ids to the front end
3) Make n further calls from the front end to process the segments in turn or retrieve the result of processing
4) Make another call from the front end at 100% processed to get the full status of all of the columns
5) Present the data to the front end
6) Harmonise the currently available filters on the data with the new "way" of filtering

**Comment by strets123** [comment]
Propose that this work is delivered by working in Parallel with Paul where Paul is working on the rendering of embedded tables

**Comment by KarenPorter** [comment]
@strets123 is this done as part of refactoring?

**Comment by KarenPorter** [comment]
closed - remaining task covered by #994
