### ISSUE TITLE
If starting from empty install, new projects overwrite previous custom field config

### ISSUE THREAD

**Issue by PaulBarrett79** [thesgc/chembiohub_helpdesk#961]
User adds their first project and adds fields. Saves project. User adds  new project, with different fields. These new fields are then used as the custom field config for all previous projects.

**Comment by PaulBarrett79** [comment]
This issue has been addressed in that a new install does not exhibit this behaviour.

**Comment by aekhendry** [comment]
Tried to test but not possible for me to do:
[15:54:38] Paul Barrett: I'm not sure you'll be able to test 961
[15:55:22] Paul Barrett: It was an initialisation problem on an empty system - since demo and hubtest aren't empty you won't be able to replicate
Flagged for Devs

**Comment by KarenPorter** [comment]
Accepted as not user-testable. Closing
