### ISSUE TITLE
Bug when using the "copy fields from another project" feature

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#965]
This feature appears to copy too many things across - projects lose their custom field config and end up being reverted to all having the same one

**Comment by strets123** [comment]
We believe we have found the source of this issue. The complex assay reg models and their default values were meant that the default config was getting updated rather than new ones added.

Therefore I am proceeding with the depreciation of the ass.ay reg. We can also merge out django migrations.

**Comment by KarenPorter** [comment]
@strets123 assume this is resolved.  Some basic testing appears to show it is.  please confirm and close.
