### ISSUE TITLE
Minor change to schemata was proposed

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#968]
It has become apparent that 
1)
There is too much repetition in project schemata
2)
The fields of different data type may need to be split up in the table view

In order to deal with this it was proposed that the deduplication criteria are changed for global fields schema.

**Comment by strets123** [comment]
Currently, search is possible across all field types but for things like attachements, some processing is needed to get filenames into an array format where pick from list can work.

**Comment by strets123** [comment]
Integer and string fields can be safely mixed as this tends to be what the users of the inventory system have in their input data and there is not great need to change that.

**Comment by strets123** [comment]
Date ranges can be searched for but the user has to enter the date in the format

2001-01-01

**Comment by strets123** [comment]
The only "type" of search that needs a special form would be chemical search and this is for the whole batch anyway so is not related to the fields in the batch

**Comment by KarenPorter** [comment]
@strets123 think this is resolved as part of refactoring?
