### ISSUE TITLE
test results from #953

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#970]
Add single:
Hendry compounds - i defined a field as required, then added a single molecule.  it pre-populated with te default, then i deleted that value and it saved with a blank value in that field.

**Comment by strets123** [comment]
but that is not marked as done

**Comment by KarenPorter** [comment]
###Add single inventory item feature 

 Custom fields should be validated and required fields respected

**Comment by KarenPorter** [comment]
Sorry  -fix is only applied in the case of an inventory project.

**Comment by KarenPorter** [comment]
But I get the same behaviour in the inventory project i i can delete the default value and save it.

**Comment by KarenPorter** [comment]
Let's close this issue - I'll go back to adding comments within 953 - makes more sense
