### ISSUE TITLE
Not explicit how to commit and get out of edit mode

### ISSUE THREAD

**Issue by KarenPorter** [thesgc/chembiohub_helpdesk#971]
Clicked on edit in search results and made various changes - each change results in a message saying 1 item has been updated - although there are more cumulative changes than that.  Undo removes all uncommitted changes - which makes sense but with the update message the implication is that it will only undo the single previous update.

Users may feel uncomfortable coming out of edit mode in order to commit their changes  - non intuitive.  I think they'll be searching for a commit button or a note that says if they leave their changes will be saved.

**Comment by strets123** [comment]
OK, following discussion we decided:

1) Editing a cell should be through a modal only.
2) Edits should add to an undo counter for the page you are on.
3) Fills should also add to this edit counter.
4) Copy should read:

4 changes saved... undo

**Comment by KarenPorter** [comment]
completed. Closing.
