### ISSUE TITLE
Pressing enter when typing in a field with an invalid value clears the chemdoodle drawing for no reason

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#981]
I draw a new compound in add single.

I add additional information to available fields. 

One of the fields is marked as 'Required'. 

I hit enter when selected on this field without submitting any further information.

the chemdoodle clipboard is cleared.

This would be extremely frustrating if I have spent time drawing a large compound. This behaviour is not seen if I hit enter when the 'required' is not selected.

staging demo

**Comment by KarenPorter** [comment]
resolved. Closing.
