### ISSUE TITLE
Stereochemistry not saving as drawn in draw single

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#983]
I'm drawing stereochemical bonds in draw single and they are not being saved as drawn. Andy is better experienced with this, could you please double check this with a few examples and see what you think.

Demo staging

**Comment by strets123** [comment]
I have added a fix to this, issue was due to code not being called correctly back when draw single was added back in to the system

**Comment by KarenPorter** [comment]
resolved. awaiting testing on hub

**Comment by aekhendry** [comment]
Fixed. Hub Chrome
