### ISSUE TITLE
http://chemreg.sgc.ox.ac.uk/0/login?next=/0/

The above link doesn't work for me.

### ISSUE THREAD

**Issue by strets123** [thesgc/chembiohub_helpdesk#984]
http://chemreg.sgc.ox.ac.uk/0/login?next=/0/

The above link doesn't work for me.

**Comment by KarenPorter** [comment]
@strets123 @aekhendry High priority - please look at this asap

**Comment by strets123** [comment]
This was resolved, there was an email chain about this. It was not a ChemBio Hub issue hence why it was not discussed on this board.

It was an SGC DNS issue.
