### ISSUE TITLE
archiving needs some sort of confirmation

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#985]
It is my feeling that the archiving function requires more definite confirmation. 

Currently we click 'Archive compounds' on the project page - click 'archive' on the items we wish to remove and that's it.

My concern is that most users would consider the action of selecting 'archive' for each compound is merely selecting the compounds to be archived, rather then actually performing the action there and then.

I propose for each compound archived a message appears above saying 'X items have be archived from this project'. This ensures the user understands exactly what the action of clicking the archive button is doing.

**Comment by KarenPorter** [comment]
addressed in a more definitive way, so closing.
