### ISSUE TITLE
sequential project names cause new chemical project not to be saved.

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#989]
I add a new project Hendry test 1 (Chemical). I attempt to add another new chemical project Hendry test 2. It will not let me save the new project. Hendry test 3 will save. This behaviour is not seen when saving plate map projects wit sequential names.

**Comment by KarenPorter** [comment]
@aekhendry is this still happening on hub?  Can't reproduce.

**Comment by aekhendry** [comment]
fixed. closing. Hub chrome
