### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#994]
The system is far to slow in both previewing and uploading a file of only 500 compounds. If it is impossible to improve this quickly, it is well worth looking into.

**Comment by KarenPorter** [comment]
High priority

**Comment by strets123** [comment]
Now expectations are managed when the upload is large and the user is told how many compounds are loading or saving dependent on the step.

If an error occurs then the loading icon will go away and a message is shown whether at the first stage or at the commit stage.

We will need to simulate an error to prove this next one...

If there is an error when saving data then the data that had been saved either to the database or to the index will be cleaned up and removed. The user will still be shown the preview but will be asked to click start again and wont get another chance to save.

Large files should now be processable

**Comment by strets123** [comment]
Now bugfixes added:

1) Files less than 100 compounds process synchronously
2) spaces and long filenames are now processed

**Comment by aekhendry** [comment]
As far as i can tell both these things are working. staging/staging chrome
