### ISSUE TITLE
The file upload field feature is not working

### ISSUE THREAD

**Issue by aekhendry** [thesgc/chembiohub_helpdesk#995]
Each time I try and add any file type < 1mb nothing happens and i get a 404 error

**Comment by strets123** [comment]
There are some bugs in the flow of file uploading itself - the POST request gets called multiple times or not at all. I do not know how to fix this so it is going to take some investigation to get it right.

**Comment by strets123** [comment]
UploadSize - this can be tested for on the front end and passed back as a validation error before the upload actually commences

**Comment by KarenPorter** [comment]
Additional bugs / missing functionality:

1. where user attempts to upload a file containing files, they need to be warned and that file not uploaded (or the embedded files ignored if that's equally simple)

2. where user downloads project data to Excel, and that project includes files, the Excel file contains a link to download the embedded files (or the file field is ignored if that isn't possible / simple.  In which case the user is warned that embedded files need to be downloaded separately.

3. where user has uploaded files to a project, they need a way to retrieve those files (even if one at a time).  May be covered by 2.

4. where user uploads a file of size greater than 20mb, they need to be warned.  Assume simplest action is to block upload of any file > defined maximum.  Can the maximum be easily defined at installation / project level (of so, include, if not, set hard stop)?  Alternatively they can be warned that upload will take some time and to come back.  

5. where a project storage maximum is reached (by configured or hard-coded maximum defined), users are prevented (and warned) from uploading any further files until they have cleared space.
1, 2 and 4 are required minimum functionality for current release.  Remaining effort can be documented and put in a new backlog issue.  Based on these min requirements, what is the outstanding remaining effort on this issue?

**Comment by strets123** [comment]
1 - the mapping interface simply needs to exclude file fields from the drop down
2. Yes
3. This is already possible from the hidden link in the preview image
4. Yes, as stated above

**Comment by strets123** [comment]
OK so so far I have been looking for bugs and found and fixed the following that trelate to the feeling of this not working.

Viewing data in the modal - removed debug info from page
Ensured reload of the page after the file had been uploaded and the update button pressed for the custom fields
After adding of a file upload field to a project, ensured that the renderers.js file does not break due to the file upload being undefined (this was recorded as a different bug)

**Comment by strets123** [comment]
Now added a check to the mapping of fields so it is impossible to map a field if it is a file field

**Comment by PaulBarrett79** [comment]
Added a click event to cancel the uploaded file within the schema form file upload directive when it is removed from the model.

**Comment by PaulBarrett79** [comment]
Added placeholders for a function to check file size. This needs to be added as a parameter in the uploadOptions setup in cbh_core_model/models.py (line 773). I tried this but any newly added methods here are not being added to the object which emerges at the front end - tried removing @cached_property, restarting, checking there were no migrations to run but couldn't force this to update at all.

**Comment by PaulBarrett79** [comment]
I've pushed progress so far

**Comment by PaulBarrett79** [comment]
Got functionality which checks file size on initial upload. User is notified by a (basic) popup. I can come up with something a bit better looking though - just needed to get the functionality there.

**Comment by KarenPorter** [comment]
I can still upload a file of >20Mb

**Comment by KarenPorter** [comment]
passed - preventing file in file uploading.

**Comment by strets123** [comment]
Fix deployed to staging and demo

**Comment by KarenPorter** [comment]
Passed.  Although - can we have some simple styling consistent with the rest of the application and location of pop-up more vertically centred?

**Comment by strets123** [comment]
see #1021
